
(* ::Subsection::Closed:: *)
(* 3.2.1 (f+g x)^m (A+B log(e ((a+b x) over (c+d x))^n))^p *)
Int[(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_., x_Symbol, _:RubiNotebookReference["99dcd533"]] := (a + b*x)*(A + B*Log[e*((a + b*x)/(c + d*x))^n])^p/ b - B*n*p*(b*c - a*d)/b* Int[(A + B*Log[e*((a + b*x)/(c + d*x))^n])^(p - 1)/(c + d*x), x] /; FreeQ[{a, b, c, d, e, A, B, n}, x] && NeQ[b*c - a*d, 0] && IGtQ[p, 0]
Int[(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^p_., x_Symbol, _:RubiNotebookReference["9b9a6b6a"]] := (a + b*x)*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])^p/ b - B*n*p*(b*c - a*d)/b* Int[(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])^(p - 1)/(c + d*x), x] /; FreeQ[{a, b, c, d, e, A, B, n}, x] && EqQ[n + mn, 0] && NeQ[b*c - a*d, 0] && IGtQ[p, 0]
(* Int[(A_.+B_.*Log[e_.*((a_.+b_.*x_)^n1_.*(c_.+d_.*x_)^n2_)^n_.])^p_. ,x_Symbol] := (a+b*x)*(A+B*Log[e*((a+b*x)^n1/(c+d*x)^n1)^n])^p/b - B*n*p*(b*c-a*d)/b*Int[(A+B*Log[e*((a+b*x)^n1/(c+d*x)^n1)^n])^(p-1)/( c+d*x),x] /; FreeQ[{a,b,c,d,e,A,B,n},x] && EqQ[n1+n2,0] && GtQ[n1,0] &&  (EqQ[n1,1] || EqQ[n,1]) && NeQ[b*c-a*d,0] && IGtQ[p,0] *)
Int[(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_, x_Symbol, _:RubiNotebookReference["9f1717d8"]] := Unintegrable[(A + B*Log[e*((a + b*x)/(c + d*x))^n])^p, x] /; FreeQ[{a, b, c, d, e, A, B, n, p}, x]
Int[(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^p_, x_Symbol, _:RubiNotebookReference["9ed57def"]] := Unintegrable[(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])^p, x] /; FreeQ[{a, b, c, d, e, A, B, n, p}, x] && EqQ[n + mn, 0]
Int[(A_. + B_.*Log[e_.*(u_/v_)^n_.])^p_., x_Symbol, _:RubiNotebookReference["9c93c3b6"]] := Int[(A + B*Log[e*(ExpandToSum[u, x]/ExpandToSum[v, x])^n])^p, x] /; FreeQ[{e, A, B, n, p}, x] && LinearQ[{u, v}, x] && Not[LinearMatchQ[{u, v}, x]]
Int[(A_. + B_.*Log[e_.*u_^n_.*v_^mn_])^p_., x_Symbol, _:RubiNotebookReference["9d51a981"]] := Int[(A + B*Log[e*ExpandToSum[u, x]^n/ExpandToSum[v, x]^n])^p, x] /; FreeQ[{e, A, B, n, p}, x] && EqQ[n + mn, 0] && IGtQ[n, 0] && LinearQ[{u, v}, x] && Not[LinearMatchQ[{u, v}, x]]
Int[(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["960deebc"]] := -Log[-(b*c - a*d)/(d*(a + b*x))]*(A + B*Log[e*((a + b*x)/(c + d*x))^n])/g + B*n*(b*c - a*d)/g* Int[Log[-(b*c - a*d)/(d*(a + b*x))]/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0] && EqQ[b*f - a*g, 0]
Int[(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["97cf848b"]] := -Log[-(b*c - a*d)/(d*(a + b*x))]*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])/g + B*n*(b*c - a*d)/g* Int[Log[-(b*c - a*d)/(d*(a + b*x))]/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && NeQ[b*c - a*d, 0] && EqQ[b*f - a*g, 0]
Int[(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["389e2774"]] := -Log[(b*c - a*d)/(b*(c + d*x))]*(A + B*Log[e*((a + b*x)/(c + d*x))^n])/g + B*n*(b*c - a*d)/g* Int[Log[(b*c - a*d)/(b*(c + d*x))]/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0] && EqQ[d*f - c*g, 0]
Int[(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["395c4d43"]] := -Log[(b*c - a*d)/(b*(c + d*x))]*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])/g + B*n*(b*c - a*d)/g* Int[Log[(b*c - a*d)/(b*(c + d*x))]/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && NeQ[b*c - a*d, 0] && EqQ[d*f - c*g, 0]
Int[(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["3b1af31a"]] := Log[f + g*x]*(A + B*Log[e*((a + b*x)/(c + d*x))^n])/g - b*B*n/g*Int[Log[f + g*x]/(a + b*x), x] + B*d*n/g*Int[Log[f + g*x]/(c + d*x), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0]
Int[(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["3ad8992d"]] := Log[f + g*x]*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])/g - b*B*n/g*Int[Log[f + g*x]/(a + b*x), x] + B*d*n/g*Int[Log[f + g*x]/(c + d*x), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && NeQ[b*c - a*d, 0]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.]), x_Symbol, _:RubiNotebookReference["3f978fa8"]] := (f + g*x)^(m + 1)*(A + B*Log[e*((a + b*x)/(c + d*x))^n])/(g*(m + 1)) - B*n*(b*c - a*d)/(g*(m + 1))* Int[(f + g*x)^(m + 1)/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, m, n}, x] && NeQ[b*c - a*d, 0] && NeQ[m, -1] && NeQ[m, -2]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_]), x_Symbol, _:RubiNotebookReference["3e55e59f"]] := (f + g*x)^(m + 1)*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])/(g*(m + 1)) - B*n*(b*c - a*d)/(g*(m + 1))* Int[(f + g*x)^(m + 1)/((a + b*x)*(c + d*x)), x] /; FreeQ[{a, b, c, d, e, f, g, A, B, m, n}, x] && EqQ[n + mn, 0] && NeQ[b*c - a*d, 0] && NeQ[m, -1] && Not[EqQ[m, -2] && IntegerQ[n]]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_., x_Symbol, _:RubiNotebookReference["3c135bc6"]] := (b*c - a*d)^(m + 1)*(g/b)^m* Subst[Int[x^m*(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0] && IntegersQ[m, p] && EqQ[b*f - a*g, 0] && (GtQ[p, 0] || LtQ[m, -1])
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^ p_., x_Symbol, _:RubiNotebookReference["3dd131f1"]] := (b*c - a*d)^(m + 1)*(g/b)^m* Subst[Int[x^m*(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && IGtQ[n, 0] && NeQ[b*c - a*d, 0] && IntegersQ[m, p] && EqQ[b*f - a*g, 0] && (GtQ[p, 0] || LtQ[m, -1])
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_., x_Symbol, _:RubiNotebookReference["368d76cc"]] := (b*c - a*d)^(m + 1)*(g/d)^m* Subst[Int[(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0] && IntegersQ[m, p] && EqQ[d*f - c*g, 0] && (GtQ[p, 0] || LtQ[m, -1])
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^ p_., x_Symbol, _:RubiNotebookReference["374f1cfb"]] := (b*c - a*d)^(m + 1)*(g/d)^m* Subst[Int[(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && IGtQ[n, 0] && NeQ[b*c - a*d, 0] && IntegersQ[m, p] && EqQ[d*f - c*g, 0] && (GtQ[p, 0] || LtQ[m, -1])
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_., x_Symbol, _:RubiNotebookReference["2a2b889a"]] := (b*c - a*d)* Subst[Int[(b*f - a*g - (d*f - c*g)*x)^ m*(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && NeQ[b*c - a*d, 0] && IntegerQ[m] && IGtQ[p, 0]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^ p_., x_Symbol, _:RubiNotebookReference["2be9e2ad"]] := (b*c - a*d)* Subst[Int[(b*f - a*g - (d*f - c*g)*x)^ m*(A + B*Log[e*x^n])^p/(b - d*x)^(m + 2), x], x, (a + b*x)/(c + d*x)] /; FreeQ[{a, b, c, d, e, f, g, A, B, n}, x] && EqQ[n + mn, 0] && IGtQ[n, 0] && NeQ[b*c - a*d, 0] && IntegerQ[m] && IGtQ[p, 0]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*((a_. + b_.*x_)/(c_. + d_.*x_))^n_.])^p_., x_Symbol, _:RubiNotebookReference["29af5cf4"]] := Unintegrable[(f + g*x)^m*(A + B*Log[e*((a + b*x)/(c + d*x))^n])^p, x] /; FreeQ[{a, b, c, d, e, f, g, A, B, m, n, p}, x]
Int[(f_. + g_.*x_)^ m_.*(A_. + B_.*Log[e_.*(a_. + b_.*x_)^n_.*(c_. + d_.*x_)^mn_])^ p_., x_Symbol, _:RubiNotebookReference["286d36c3"]] := Unintegrable[(f + g*x)^m*(A + B*Log[e*(a + b*x)^n/(c + d*x)^n])^p, x] /; FreeQ[{a, b, c, d, e, f, g, A, B, m, n, p}, x] && EqQ[n + mn, 0] && IntegerQ[n]
Int[w_^m_.*(A_. + B_.*Log[e_.*(u_/v_)^n_.])^p_., x_Symbol, _:RubiNotebookReference["2d222046"]] := Int[ExpandToSum[w, x]^ m*(A + B*Log[e*(ExpandToSum[u, x]/ExpandToSum[v, x])^n])^p, x] /; FreeQ[{e, A, B, m, n, p}, x] && LinearQ[{u, v, w}, x] && Not[LinearMatchQ[{u, v, w}, x]]
Int[w_^m_.*(A_. + B_.*Log[e_.*u_^n_.*v_^mn_])^p_., x_Symbol, _:RubiNotebookReference["2ce04a71"]] := Int[ExpandToSum[w, x]^ m*(A + B*Log[e*ExpandToSum[u, x]^n/ExpandToSum[v, x]^n])^p, x] /; FreeQ[{e, A, B, m, n, p}, x] && EqQ[n + mn, 0] && IGtQ[n, 0] && LinearQ[{u, v, w}, x] && Not[LinearMatchQ[{u, v, w}, x]]
