
(* ::Subsection::Closed:: *)
(* 3.4 u (a+b log(c (d+e x^m)^n))^p *)
Int[Pq_^m_.*Log[u_], x_Symbol, _:RubiNotebookReference["aa89f964"]] := With[{C = FullSimplify[Pq^m*(1 - u)/D[u, x]]}, C*PolyLog[2, 1 - u] /; FreeQ[C, x]] /; IntegerQ[m] && PolyQ[Pq, x] && RationalFunctionQ[u, x] && LeQ[RationalFunctionExponents[u, x][[2]], Expon[Pq, x]]
Int[Log[c_.*(d_ + e_.*x_^n_)^p_.], x_Symbol, _:RubiNotebookReference["a8cf473d"]] := x*Log[c*(d + e*x^n)^p] - e*n*p*Int[x^n/(d + e*x^n), x] /; FreeQ[{c, d, e, n, p}, x]
Int[(a_. + b_.*Log[c_.*(d_ + e_./x_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["a90d2d0a"]] := (e + d*x)*(a + b*Log[c*(d + e/x)^p])^q/d + b*e*p*q/d*Int[(a + b*Log[c*(d + e/x)^p])^(q - 1)/x, x] /; FreeQ[{a, b, c, d, e, p}, x] && IGtQ[q, 0]
Int[(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["ac423b8f"]] := x*(a + b*Log[c*(d + e*x^n)^p])^q - b*e*n*p*q* Int[x^n*(a + b*Log[c*(d + e*x^n)^p])^(q - 1)/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, n, p}, x] && IGtQ[q, 0] && (EqQ[q, 1] || IntegerQ[n])
(* Int[(a_.+b_.*Log[c_.*(d_+e_.*x_^n_)^p_.])^q_,x_Symbol] :=  With[{k=Denominator[n]}, k*Subst[Int[x^(k-1)*(a+b*Log[c*(d+e*x^(k*n))^p])^q,x],x,x^(1/k)]] /;  FreeQ[{a,b,c,d,e,p,q},x] && LtQ[-1,n,1] && (GtQ[n,0] || IGtQ[q,0]) *)
Int[(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["afc6efe1"]] := With[{k = Denominator[n]}, k*Subst[Int[x^(k - 1)*(a + b*Log[c*(d + e*x^(k*n))^p])^q, x], x, x^(1/k)]] /; FreeQ[{a, b, c, d, e, p, q}, x] && FractionQ[n]
Int[(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["ae0485d6"]] := Unintegrable[(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, n, p, q}, x]
Int[(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["a558c2eb"]] := Int[(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, p, q}, x] && BinomialQ[v, x] && Not[BinomialMatchQ[v, x]]
Int[x_^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["a49aa8dc"]] := 1/n*Subst[ Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*Log[c*(d + e*x)^p])^q, x], x, x^n] /; FreeQ[{a, b, c, d, e, m, n, p, q}, x] && IntegerQ[ Simplify[(m + 1)/n]] && (GtQ[(m + 1)/n, 0] || IGtQ[q, 0]) && Not[EqQ[q, 1] && ILtQ[n, 0] && IGtQ[m, 0]]
Int[(f_.*x_)^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.]), x_Symbol, _:RubiNotebookReference["cda2b60f"]] := (f*x)^(m + 1)*(a + b*Log[c*(d + e*x^n)^p])/(f*(m + 1)) - b*e*n*p/(f*(m + 1))*Int[x^(n - 1)*(f*x)^(m + 1)/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && NeQ[m, -1]
Int[(f_*x_)^m_*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["cc60dc38"]] := (f*x)^m/x^m* Int[x^m*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, m, n, p, q}, x] && IntegerQ[Simplify[(m + 1)/n]] && (GtQ[(m + 1)/n, 0] || IGtQ[q, 0])
Int[(f_.*x_)^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["ce266261"]] := (f*x)^(m + 1)*(a + b*Log[c*(d + e*x^n)^p])^ q/(f*(m + 1)) - b*e*n*p*q/(f^n*(m + 1))* Int[(f*x)^(m + n)*(a + b*Log[c*(d + e*x^n)^p])^(q - 1)/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && IGtQ[q, 1] && IntegerQ[n] && NeQ[m, -1]
Int[x_^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_, x_Symbol, _:RubiNotebookReference["cfe40856"]] := With[{k = Denominator[n]}, k*Subst[ Int[x^(k*(m + 1) - 1)*(a + b*Log[c*(d + e*x^(k*n))^p])^q, x], x, x^(1/k)]] /; FreeQ[{a, b, c, d, e, m, p, q}, x] && FractionQ[n]
Int[(f_*x_)^m_*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["caab1ed3"]] := (f*x)^m/x^m* Int[x^m*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, m, p, q}, x] && FractionQ[n]
Int[(f_.*x_)^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["cb6974e4"]] := Unintegrable[(f*x)^m*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, m, n, p, q}, x]
Int[(f_.*x_)^m_.*(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["c92fcabd"]] := Int[(f*x)^m*(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, f, m, p, q}, x] && BinomialQ[v, x] && Not[BinomialMatchQ[v, x]]
Int[(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])/(f_. + g_.*x_), x_Symbol, _:RubiNotebookReference["c8eda08a"]] := Log[f + g*x]*(a + b*Log[c*(d + e*x^n)^p])/g - b*e*n*p/g*Int[x^(n - 1)*Log[f + g*x]/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, f, g, n, p}, x] && RationalQ[n]
Int[(f_. + g_.*x_)^r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.]), x_Symbol, _:RubiNotebookReference["c3b1e7b7"]] := (f + g*x)^(r + 1)*(a + b*Log[c*(d + e*x^n)^p])/(g*(r + 1)) - b*e*n*p/(g*(r + 1))* Int[x^(n - 1)*(f + g*x)^(r + 1)/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, f, g, n, p, r}, x] && (IGtQ[r, 0] || RationalQ[n]) && NeQ[r, -1]
Int[(f_. + g_.*x_)^r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["c2738d80"]] := Unintegrable[(f + g*x)^r*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, g, n, p, q, r}, x]
Int[u_^r_.*(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["df1719e1"]] := Int[ExpandToSum[u, x]^r*(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, p, q, r}, x] && LinearQ[u, x] && BinomialQ[v, x] && Not[LinearMatchQ[u, x] && BinomialMatchQ[v, x]]
Int[x_^m_.*(f_. + g_.*x_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["ded573d6"]] := Int[ExpandIntegrand[(a + b*Log[c*(d + e*x^n)^p])^q, x^m*(f + g*x)^r, x], x] /; FreeQ[{a, b, c, d, e, f, g, n, p, q}, x] && IntegerQ[m] && IntegerQ[r]
Int[(h_.*x_)^m_*(f_. + g_.*x_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_.)^p_.])^q_., x_Symbol, _:RubiNotebookReference["dc93cd8f"]] := With[{k = Denominator[m]}, k/h*Subst[ Int[x^(k*(m + 1) - 1)*(f + g*x^k/h)^ r*(a + b*Log[c*(d + e*x^(k*n)/h^n)^p])^q, x], x, (h*x)^(1/k)]] /; FreeQ[{a, b, c, d, e, f, g, h, p, r}, x] && FractionQ[m] && IntegerQ[n] && IntegerQ[r]
Int[(h_.*x_)^m_.*(f_. + g_.*x_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["dd51a7b8"]] := Unintegrable[(h*x)^m*(f + g*x)^r*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n, p, q, r}, x]
Int[(h_.*x_)^m_.*u_^r_.*(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["d81eb13d"]] := Int[(h*x)^m*ExpandToSum[u, x]^r*(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, h, m, p, q, r}, x] && LinearQ[u, x] && BinomialQ[v, x] && Not[LinearMatchQ[u, x] && BinomialMatchQ[v, x]]
Int[(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])/(f_ + g_.*x_^2), x_Symbol, _:RubiNotebookReference["d9dcdb0a"]] := With[{u = IntHide[1/(f + g*x^2), x]}, u*(a + b*Log[c*(d + e*x^n)^p]) - b*e*n*p*Int[u*x^(n - 1)/(d + e*x^n), x]] /; FreeQ[{a, b, c, d, e, f, g, n, p}, x] && IntegerQ[n]
Int[(f_ + g_.*x_^s_)^r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^ q_., x_Symbol, _:RubiNotebookReference["db9a6553"]] := With[{t = ExpandIntegrand[(a + b*Log[c*(d + e*x^n)^p])^q, (f + g*x^s)^r, x]}, Int[t, x] /; SumQ[t]] /; FreeQ[{a, b, c, d, e, f, g, n, p, q, r, s}, x] && IntegerQ[n] && IGtQ[q, 0] && IntegerQ[r] && IntegerQ[s] && (EqQ[q, 1] || GtQ[r, 0] && GtQ[s, 1] || LtQ[s, 0] && LtQ[r, 0])
Int[(f_ + g_.*x_^s_)^r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^ q_., x_Symbol, _:RubiNotebookReference["da580f64"]] := With[{k = Denominator[n]}, k*Subst[ Int[x^(k - 1)*(f + g*x^(k*s))^ r*(a + b*Log[c*(d + e*x^(k*n))^p])^q, x], x, x^(1/k)] /; IntegerQ[k*s]] /; FreeQ[{a, b, c, d, e, f, g, n, p, q, r, s}, x] && FractionQ[n]
Int[(f_ + g_.*x_^s_)^r_. (a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^ q_., x_Symbol, _:RubiNotebookReference["d1044859"]] := Unintegrable[(f + g*x^s)^r*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, g, n, p, q, r, s}, x]
Int[u_^r_.*(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["d0c6226e"]] := Int[ExpandToSum[u, x]^r*(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, p, q, r}, x] && BinomialQ[{u, v}, x] && Not[BinomialMatchQ[{u, v}, x]]
Int[x_^m_.*(f_ + g_.*x_^s_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["67ab7e84"]] := 1/n*Subst[ Int[x^(Simplify[(m + 1)/n] - 1)*(f + g*x^(s/n))^ r*(a + b*Log[c*(d + e*x)^p])^q, x], x, x^n] /; FreeQ[{a, b, c, d, e, f, g, m, n, p, q, r, s}, x] && IntegerQ[r] && IntegerQ[s/n] && IntegerQ[Simplify[(m + 1)/n]] && (GtQ[(m + 1)/n, 0] || IGtQ[q, 0])
Int[x_^m_.*(f_ + g_.*x_^s_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["666914b3"]] := Int[ExpandIntegrand[(a + b*Log[c*(d + e*x^n)^p])^q, x^m*(f + g*x^s)^r, x], x] /; FreeQ[{a, b, c, d, e, f, g, m, n, p, q, r, s}, x] && IGtQ[q, 0] && IntegerQ[m] && IntegerQ[r] && IntegerQ[s]
Int[(f_ + g_.*x_^s_)^r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^ q_., x_Symbol, _:RubiNotebookReference["642faaea"]] := With[{k = Denominator[n]}, k*Subst[ Int[x^(k - 1)*(f + g*x^(k*s))^ r*(a + b*Log[c*(d + e*x^(k*n))^p])^q, x], x, x^(1/k)] /; IntegerQ[k*s]] /; FreeQ[{a, b, c, d, e, f, g, n, p, q, r, s}, x] && FractionQ[n]
Int[x_^m_.*(f_ + g_.*x_^s_)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["65edc0dd"]] := 1/n*Subst[ Int[x^(m + 1/n - 1)*(f + g*x^(s/n))^r*(a + b*Log[c*(d + e*x)^p])^ q, x], x, x^n] /; FreeQ[{a, b, c, d, e, f, g, m, n, p, q, r, s}, x] && FractionQ[n] && IntegerQ[1/n] && IntegerQ[s/n]
Int[(h_.*x_)^m_*(f_. + g_.*x_^s_.)^ r_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_.)^p_.])^q_., x_Symbol, _:RubiNotebookReference["60a2d658"]] := With[{k = Denominator[m]}, k/h*Subst[ Int[x^(k*(m + 1) - 1)*(f + g*x^(k*s)/h^s)^ r*(a + b*Log[c*(d + e*x^(k*n)/h^n)^p])^q, x], x, (h*x)^(1/k)]] /; FreeQ[{a, b, c, d, e, f, g, h, p, r}, x] && FractionQ[m] && IntegerQ[n] && IntegerQ[s]
Int[(h_.*x_)^m_.*(f_ + g_.*x_^s_)^ r_. (a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["6160bc6f"]] := Unintegrable[(h*x)^m*(f + g*x^s)^r*(a + b*Log[c*(d + e*x^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n, p, q, r, s}, x]
Int[(h_.*x_)^m_.*u_^r_.*(a_. + b_.*Log[c_.*v_^p_.])^q_., x_Symbol, _:RubiNotebookReference["63260236"]] := Int[(h*x)^m*ExpandToSum[u, x]^r*(a + b*Log[c*ExpandToSum[v, x]^p])^q, x] /; FreeQ[{a, b, c, h, m, p, q, r}, x] && BinomialQ[{u, v}, x] && Not[BinomialMatchQ[{u, v}, x]]
Int[Log[f_.*x_^q_.]^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.])/x_, x_Symbol, _:RubiNotebookReference["62e46801"]] := Log[f*x^q]^(m + 1)*(a + b*Log[c*(d + e*x^n)^p])/(q*(m + 1)) - b*e*n*p/(q*(m + 1))* Int[x^(n - 1)*Log[f*x^q]^(m + 1)/(d + e*x^n), x] /; FreeQ[{a, b, c, d, e, f, m, n, p, q}, x] && NeQ[m, -1]
Int[F_[f_.*x_]^m_.*(a_. + b_.*Log[c_.*(d_ + e_.*x_^n_)^p_.]), x_Symbol, _:RubiNotebookReference["69b82f3c"]] := With[{u = IntHide[F[f*x]^m, x]}, Dist[a + b*Log[c*(d + e*x^n)^p], u, x] - b*e*n*p*Int[SimplifyIntegrand[u*x^(n - 1)/(d + e*x^n), x], x]] /; FreeQ[{a, b, c, d, e, f, p}, x] && MemberQ[{ArcSin, ArcCos, ArcSinh, ArcCosh}, F] && IGtQ[m, 0] && IGtQ[n, 1]
Int[(a_. + b_.*Log[c_.*(d_ + e_.*(f_. + g_.*x_)^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["687a450b"]] := 1/g*Subst[Int[(a + b*Log[c*(d + e*x^n)^p])^q, x], x, f + g*x] /; FreeQ[{a, b, c, d, e, f, g, n, p}, x] && IGtQ[q, 0] && (EqQ[q, 1] || IntegerQ[n])
Int[(a_. + b_.*Log[c_.*(d_ + e_.*(f_. + g_.*x_)^n_)^p_.])^q_., x_Symbol, _:RubiNotebookReference["fa7c463d"]] := Unintegrable[(a + b*Log[c*(d + e*(f + g*x)^n)^p])^q, x] /; FreeQ[{a, b, c, d, e, f, g, n, p, q}, x]
