(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_.,x_Symbol] :=
  1/c^p \[Star] Int[(b/2+c*x)^(2*p),x] /;
FreeQ[{a,b,c},x] && EqQ[b^2-4*a*c,0] && IntegerQ[p]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  2*(a+b*x+c*x^2)^(p+1)/((2*p+1)*(b+2*c*x)) /;
FreeQ[{a,b,c,p},x] && EqQ[b^2-4*a*c,0] && LtQ[p,-1]


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (a+b*x+c*x^2)^FracPart[p]/(c^IntPart[p]*(b/2+c*x)^(2*FracPart[p])) \[Star] Int[(b/2+c*x)^(2*p),x] /;
FreeQ[{a,b,c,p},x] && EqQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[x^p*(b+c*x)^p,x],x] /;
FreeQ[{b,c},x] && IntegerQ[p]


(* ::Code:: *)
(* Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, -c \[Star] Int[ExpandIntegrand[1/((-q/2-b/2-c*x)*(-q/2+b/2+c*x)),x],x]] /;
FreeQ[{a,b,c},x] && NiceSqrtQ[b^2-4*a*c] && PosQ[c] *)


(* ::Code:: *)
(* Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, -c \[Star] Int[ExpandIntegrand[1/((q/2-b/2-c*x)*(q/2+b/2+c*x)),x],x]] /;
FreeQ[{a,b,c},x] && NiceSqrtQ[b^2-4*a*c] && NegQ[c] *)


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, c \[Star] Int[ExpandIntegrand[1/((b/2-q/2+c*x)*(b/2+q/2+c*x)),x],x]] /;
FreeQ[{a,b,c},x] && NiceSqrtQ[b^2-4*a*c]


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  With[{q=1-4*Simplify[a*c/b^2]},
  -2/b \[Star] Subst[Int[1/(q-x^2),x],x,1+2*c*x/b] /;
 RationalQ[q] && (EqQ[q^2,1] || Not[RationalQ[b^2-4*a*c]])] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
Int[1/(a_+b_.*x_+c_.*x_^2),x_Symbol] :=
  -2 \[Star] Subst[Int[1/Simp[b^2-4*a*c-x^2,x],x],x,b+2*c*x] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
(* Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, 1/(-c)^p \[Star] Int[ExpandIntegrand[(-q/2-b/2-c*x)^p*(-q/2+b/2+c*x)^p,x],x] /;
 Not[FractionalPowerFactorQ[q]]] /;
FreeQ[{a,b,c},x] && IntegerQ[p] && NiceSqrtQ[b^2-4*a*c] && PosQ[c] *)


(* ::Code:: *)
(* Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, 1/(-c)^p \[Star] Int[ExpandIntegrand[(q/2-b/2-c*x)^p*(q/2+b/2+c*x)^p,x],x] /;
 Not[FractionalPowerFactorQ[q]]] /;
FreeQ[{a,b,c},x] && IntegerQ[p] && NiceSqrtQ[b^2-4*a*c] && NegQ[c] *)


(* ::Code:: *)
Int[(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]}, 1/c^p \[Star] Int[ExpandIntegrand[(b/2-q/2+c*x)^p*(b/2+q/2+c*x)^p,x],x] /;
 Not[FractionalPowerFactorQ[q]]] /;
FreeQ[{a,b,c},x] && IntegerQ[p] && NiceSqrtQ[b^2-4*a*c]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x+c*x^2)^p,x],x] /;
FreeQ[{a,b,c},x] && IntegerQ[p] && (GtQ[p,0] || EqQ[a,0])


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^(p+1)/((p+1)*(b^2-4*a*c)) -
  2*c*(2*p+3)/((p+1)*(b^2-4*a*c)) \[Star] Int[(a+b*x+c*x^2)^(p+1),x] /;
FreeQ[{a,b,c},x] && ILtQ[p,-1]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^p/(2*c*(2*p+1)) -
  p*(b^2-4*a*c)/(2*c*(2*p+1)) \[Star] Int[(a+b*x+c*x^2)^(p-1),x] /;
FreeQ[{a,b,c},x] && GtQ[p,0] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[1/(a_.+b_.*x_+c_.*x_^2)^(3/2),x_Symbol] :=
  -2*(b+2*c*x)/((b^2-4*a*c)*Sqrt[a+b*x+c*x^2]) /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b+2*c*x)*(a+b*x+c*x^2)^(p+1)/((p+1)*(b^2-4*a*c)) -
  2*c*(2*p+3)/((p+1)*(b^2-4*a*c)) \[Star] Int[(a+b*x+c*x^2)^(p+1),x] /;
FreeQ[{a,b,c},x] && LtQ[p,-1] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  1/(2*c*(-4*c/(b^2-4*a*c))^p) \[Star] Subst[Int[Simp[1-x^2/(b^2-4*a*c),x]^p,x],x,b+2*c*x] /;
FreeQ[{a,b,c,p},x] && GtQ[4*a-b^2/c,0]


(* ::Code:: *)
Int[1/Sqrt[b_.*x_+c_.*x_^2],x_Symbol] :=
  2 \[Star] Subst[Int[1/(1-c*x^2),x],x,x/Sqrt[b*x+c*x^2]] /;
FreeQ[{b,c},x]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_+c_.*x_^2],x_Symbol] :=
  2 \[Star] Subst[Int[1/(4*c-x^2),x],x,(b+2*c*x)/Sqrt[a+b*x+c*x^2]] /;
FreeQ[{a,b,c},x]


(* ::Code:: *)
Int[(b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  (b*x+c*x^2)^p/(-c*(b*x+c*x^2)/(b^2))^p \[Star] Int[(-c*x/b-c^2*x^2/b^2)^p,x] /;
FreeQ[{b,c},x] && (IntegerQ[4*p] || IntegerQ[3*p])


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  4*Sqrt[(b+2*c*x)^2]/(b+2*c*x) \[Star] Subst[Int[x^(4*(p+1)-1)/Sqrt[b^2-4*a*c+4*c*x^4],x],x,(a+b*x+c*x^2)^(1/4)] /;
FreeQ[{a,b,c},x] && IntegerQ[4*p]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  3*Sqrt[(b+2*c*x)^2]/(b+2*c*x) \[Star] Subst[Int[x^(3*(p+1)-1)/Sqrt[b^2-4*a*c+4*c*x^3],x],x,(a+b*x+c*x^2)^(1/3)] /;
FreeQ[{a,b,c},x] && IntegerQ[3*p]


(* ::Code:: *)
Int[(a_.+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  -(a+b*x+c*x^2)^(p+1)/(q*(p+1)*((q-b-2*c*x)/(2*q))^(p+1))*Hypergeometric2F1[-p,p+1,p+2,(b+q+2*c*x)/(2*q)]] /;
FreeQ[{a,b,c,p},x] && Not[IntegerQ[4*p]] && Not[IntegerQ[3*p]]


(* ::Code:: *)
Int[(a_.+b_.*u_+c_.*u_^2)^p_,x_Symbol] :=
  1/Coefficient[u,x,1] \[Star] Subst[Int[(a+b*x+c*x^2)^p,x],x,u] /;
FreeQ[{a,b,c,p},x] && LinearQ[u,x] && NeQ[u,x]



