
(* ::Subsection::Closed:: *)
(* 7.3.2 (d x)^m (a+b arctanh(c x^n))^p *)
Int[(a_. + b_.*ArcTanh[c_.*x_])/x_, x_Symbol, _:RubiNotebookReference["cbeafdce"]] := a*Log[x] - b/2*PolyLog[2, -c*x] + b/2*PolyLog[2, c*x] /; FreeQ[{a, b, c}, x]
Int[(a_. + b_.*ArcCoth[c_.*x_])/x_, x_Symbol, _:RubiNotebookReference["c9ac4397"]] := a*Log[x] + b/2*PolyLog[2, -1/(c*x)] - b/2*PolyLog[2, 1/(c*x)] /; FreeQ[{a, b, c}, x]
Int[(a_. + b_.*ArcTanh[c_.*x_])^p_/x_, x_Symbol, _:RubiNotebookReference["c86e29a0"]] := 2*(a + b*ArcTanh[c*x])^p*ArcTanh[1 - 2/(1 - c*x)] - 2*b*c*p* Int[(a + b*ArcTanh[c*x])^(p - 1)* ArcTanh[1 - 2/(1 - c*x)]/(1 - c^2*x^2), x] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1]
Int[(a_. + b_.*ArcCoth[c_.*x_])^p_/x_, x_Symbol, _:RubiNotebookReference["cd213f25"]] := 2*(a + b*ArcCoth[c*x])^p*ArcCoth[1 - 2/(1 - c*x)] - 2*b*c*p* Int[(a + b*ArcCoth[c*x])^(p - 1)* ArcCoth[1 - 2/(1 - c*x)]/(1 - c^2*x^2), x] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1]
Int[(a_. + b_.*ArcTanh[c_.*x_^n_])^p_./x_, x_Symbol, _:RubiNotebookReference["cce35512"]] := 1/n*Subst[Int[(a + b*ArcTanh[c*x])^p/x, x], x, x^n] /; FreeQ[{a, b, c, n}, x] && IGtQ[p, 0]
Int[(a_. + b_.*ArcCoth[c_.*x_^n_])^p_./x_, x_Symbol, _:RubiNotebookReference["cea5eb4b"]] := 1/n*Subst[Int[(a + b*ArcCoth[c*x])^p/x, x], x, x^n] /; FreeQ[{a, b, c, n}, x] && IGtQ[p, 0]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["cf67817c"]] := x^(m + 1)*(a + b*ArcTanh[c*x^n])^p/(m + 1) - b*c*n*p/(m + 1)* Int[x^(m + n)*(a + b*ArcTanh[c*x^n])^(p - 1)/(1 - c^2*x^(2*n)), x] /; FreeQ[{a, b, c, m, n}, x] && IGtQ[p, 0] && (EqQ[p, 1] || EqQ[n, 1] && IntegerQ[m]) && NeQ[m, -1]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["c43bc641"]] := x^(m + 1)*(a + b*ArcCoth[c*x^n])^p/(m + 1) - b*c*n*p/(m + 1)* Int[x^(m + n)*(a + b*ArcCoth[c*x^n])^(p - 1)/(1 - c^2*x^(2*n)), x] /; FreeQ[{a, b, c, m, n}, x] && IGtQ[p, 0] && (EqQ[p, 1] || EqQ[n, 1] && IntegerQ[m]) && NeQ[m, -1]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["c5f9ac76"]] := 1/n*Subst[Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*ArcTanh[c*x])^p, x], x, x^n] /; FreeQ[{a, b, c, m, n}, x] && IGtQ[p, 1] && IntegerQ[Simplify[(m + 1)/n]]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["fbc09ffd"]] := 1/n*Subst[Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*ArcCoth[c*x])^p, x], x, x^n] /; FreeQ[{a, b, c, m, n}, x] && IGtQ[p, 1] && IntegerQ[Simplify[(m + 1)/n]]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["fa02f5ca"]] := Int[ExpandIntegrand[ x^m*(a + b*Log[1 + c*x^n]/2 - b*Log[1 - c*x^n]/2)^p, x], x] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1] && IGtQ[n, 0] && IntegerQ[m]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["f8444b93"]] := Int[ExpandIntegrand[ x^m*(a + b*Log[1 + x^(-n)/c]/2 - b*Log[1 - x^(-n)/c]/2)^p, x], x] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1] && IGtQ[n, 0] && IntegerQ[m]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["f98621a4"]] := With[{k = Denominator[m]}, k*Subst[Int[x^(k*(m + 1) - 1)*(a + b*ArcTanh[c*x^(k*n)])^p, x], x, x^(1/k)]] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1] && IGtQ[n, 0] && FractionQ[m]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["fcc93721"]] := With[{k = Denominator[m]}, k*Subst[Int[x^(k*(m + 1) - 1)*(a + b*ArcCoth[c*x^(k*n)])^p, x], x, x^(1/k)]] /; FreeQ[{a, b, c}, x] && IGtQ[p, 1] && IGtQ[n, 0] && FractionQ[m]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["fd0b5d16"]] := Int[x^m*(a + b*ArcCoth[x^(-n)/c])^p, x] /; FreeQ[{a, b, c, m}, x] && IGtQ[p, 1] && ILtQ[n, 0]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["ff4de34f"]] := Int[x^m*(a + b*ArcTanh[x^(-n)/c])^p, x] /; FreeQ[{a, b, c, m}, x] && IGtQ[p, 1] && ILtQ[n, 0]
Int[x_^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["fe8f8978"]] := With[{k = Denominator[n]}, k*Subst[Int[x^(k*(m + 1) - 1)*(a + b*ArcTanh[c*x^(k*n)])^p, x], x, x^(1/k)]] /; FreeQ[{a, b, c, m}, x] && IGtQ[p, 1] && FractionQ[n]
Int[x_^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_])^p_, x_Symbol, _:RubiNotebookReference["f5d3ce45"]] := With[{k = Denominator[n]}, k*Subst[Int[x^(k*(m + 1) - 1)*(a + b*ArcCoth[c*x^(k*n)])^p, x], x, x^(1/k)]] /; FreeQ[{a, b, c, m}, x] && IGtQ[p, 1] && FractionQ[n]
Int[(d_*x_)^m_*(a_. + b_.*ArcTanh[c_.*x_^n_.]), x_Symbol, _:RubiNotebookReference["f411a472"]] := (d*x)^(m + 1)*(a + b*ArcTanh[c*x^n])/(d*(m + 1)) - b*c*n/(d^n*(m + 1))*Int[(d*x)^(m + n)/(1 - c^2*x^(2*n)), x] /; FreeQ[{a, b, c, d, m, n}, x] && IntegerQ[n] && NeQ[m, -1]
Int[(d_*x_)^m_*(a_. + b_.*ArcCoth[c_.*x_^n_.]), x_Symbol, _:RubiNotebookReference["e9753013"]] := (d*x)^(m + 1)*(a + b*ArcCoth[c*x^n])/(d*(m + 1)) - b*c*n/(d^n*(m + 1))*Int[(d*x)^(m + n)/(1 - c^2*x^(2*n)), x] /; FreeQ[{a, b, c, d, m, n}, x] && IntegerQ[n] && NeQ[m, -1]
Int[(d_*x_)^m_*(a_. + b_.*ArcTanh[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["e8b75a24"]] := d^IntPart[m]*(d*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*ArcTanh[c*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n}, x] && IGtQ[p, 0] && (EqQ[p, 1] || RationalQ[m, n])
Int[(d_*x_)^m_*(a_. + b_.*ArcCoth[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["eaf1e47d"]] := d^IntPart[m]*(d*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*ArcCoth[c*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n}, x] && IGtQ[p, 0] && (EqQ[p, 1] || RationalQ[m, n])
Int[(d_.*x_)^m_.*(a_. + b_.*ArcTanh[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["eb338e4a"]] := Unintegrable[(d*x)^m*(a + b*ArcTanh[c*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
Int[(d_.*x_)^m_.*(a_. + b_.*ArcCoth[c_.*x_^n_.])^p_., x_Symbol, _:RubiNotebookReference["ee7c98cf"]] := Unintegrable[(d*x)^m*(a + b*ArcCoth[c*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
