
(* ::Subsection::Closed:: *)
(* 4.3.4.1 (a+b tan)^m (A+B tan+C tan^2) *)
Int[(a_. + b_.*tan[e_. + f_.*x_])^m_.*(A_ + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := A/(b*f)*Subst[Int[(a + x)^m, x], x, b*Tan[e + f*x]] /; FreeQ[{a, b, e, f, A, C, m}, x] && EqQ[A, C]
Int[(a_. + b_.*cot[e_. + f_.*x_])^m_.*(A_ + C_.*cot[e_. + f_.*x_]^2), x_Symbol] := -A/(b*f)* Subst[Int[(a + x)^m, x], x, b*Cot[e + f*x]] /; FreeQ[{a, b, e, f, A, C, m}, x] && EqQ[A, C]
Int[(a_. + b_.*tan[e_. + f_.*x_])^ m_.*(A_. + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := 1/b^2*Int[(a + b*Tan[e + f*x])^(m + 1)* Simp[b*B - a*C + b*C*Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, B, C, m}, x] && EqQ[A*b^2 - a*b*B + a^2*C, 0]
Int[(a_. + b_.*tan[e_. + f_.*x_])^m_.*(A_. + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := -C/b^2* Int[(a + b*Tan[e + f*x])^(m + 1)*(a - b*Tan[e + f*x]), x] /; FreeQ[{a, b, e, f, A, C, m}, x] && EqQ[A*b^2 + a^2*C, 0]
Int[(a_. + b_.*tan[e_. + f_.*x_])^ m_.*(A_. + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := -(a*A + b*B - a*C)* Tan[e + f*x]*(a + b*Tan[e + f*x])^m/(2*a*f*m) + 1/(2*a^2*m)* Int[(a + b*Tan[e + f*x])^(m + 1)* Simp[(b*B - a*C) + a*A*(2*m + 1) - (b*C*(m - 1) + (A*b - a*B)*(m + 1))* Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, B, C}, x] && NeQ[A*b^2 - a*b*B + a^2*C, 0] && LeQ[m, -1] && EqQ[a^2 + b^2, 0]
Int[(a_. + b_.*tan[e_. + f_.*x_])^m_.*(A_. + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := -(a*A - a*C)* Tan[e + f*x]*(a + b*Tan[e + f*x])^m/(2*a*f*m) + 1/(2*a^2*m)* Int[(a + b*Tan[e + f*x])^(m + 1)* Simp[-a*C + a*A*(2*m + 1) - (b*C*(m - 1) + A*b*(m + 1))*Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, C}, x] && NeQ[A*b^2 + a^2*C, 0] && LeQ[m, -1] && EqQ[a^2 + b^2, 0]
Int[(A_ + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2)/(a_. + b_.*tan[e_. + f_.*x_]), x_Symbol] := (a*A + b*B - a*C)*x/(a^2 + b^2) + (A*b^2 - a*b*B + a^2*C)/(a^2 + b^2)* Int[(1 + Tan[e + f*x]^2)/(a + b*Tan[e + f*x]), x] /; FreeQ[{a, b, e, f, A, B, C}, x] && NeQ[a^2 + b^2, 0] && EqQ[A*b - a*B - b*C, 0]
Int[(A_ + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2)/ tan[e_. + f_.*x_], x_Symbol] := B*x + A*Int[1/Tan[e + f*x], x] + C*Int[Tan[e + f*x], x] /; FreeQ[{e, f, A, B, C}, x] && NeQ[A, C]
Int[(A_ + C_.*tan[e_. + f_.*x_]^2)/tan[e_. + f_.*x_], x_Symbol] := A*Int[1/Tan[e + f*x], x] + C*Int[Tan[e + f*x], x] /; FreeQ[{e, f, A, C}, x] && NeQ[A, C]
Int[(A_ + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2)/(a_. + b_.*tan[e_. + f_.*x_]), x_Symbol] := (a*A + b*B - a*C)*x/(a^2 + b^2) - (A*b - a*B - b*C)/(a^2 + b^2)*Int[Tan[e + f*x], x] + (A*b^2 - a*b*B + a^2*C)/(a^2 + b^2)* Int[(1 + Tan[e + f*x]^2)/(a + b*Tan[e + f*x]), x] /; FreeQ[{a, b, e, f, A, B, C}, x] && NeQ[A*b^2 - a*b*B + a^2*C, 0] && NeQ[a^2 + b^2, 0] && NeQ[A*b - a*B - b*C, 0]
Int[(A_ + C_.*tan[e_. + f_.*x_]^2)/(a_ + b_.*tan[e_. + f_.*x_]), x_Symbol] := a*(A - C)*x/(a^2 + b^2) - b*(A - C)/(a^2 + b^2)*Int[Tan[e + f*x], x] + (a^2*C + A*b^2)/(a^2 + b^2)* Int[(1 + Tan[e + f*x]^2)/(a + b*Tan[e + f*x]), x] /; FreeQ[{a, b, e, f, A, C}, x] && NeQ[a^2*C + A*b^2, 0] && NeQ[a^2 + b^2, 0] && NeQ[A, C]
Int[(a_. + b_.*tan[e_. + f_.*x_])^ m_*(A_. + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := (A*b^2 - a*b*B + a^2*C)*(a + b*Tan[e + f*x])^(m + 1)/(b* f*(m + 1)*(a^2 + b^2)) + 1/(a^2 + b^2)* Int[(a + b*Tan[e + f*x])^(m + 1)* Simp[b*B + a*(A - C) - (A*b - a*B - b*C)*Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, B, C}, x] && NeQ[A*b^2 - a*b*B + a^2*C, 0] && LtQ[m, -1] && NeQ[a^2 + b^2, 0]
Int[(a_. + b_.*tan[e_. + f_.*x_])^m_*(A_. + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := (A*b^2 + a^2*C)*(a + b*Tan[e + f*x])^(m + 1)/(b* f*(m + 1)*(a^2 + b^2)) + 1/(a^2 + b^2)* Int[(a + b*Tan[e + f*x])^(m + 1)* Simp[a*(A - C) - (A*b - b*C)*Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, C}, x] && NeQ[A*b^2 + a^2*C, 0] && LtQ[m, -1] && NeQ[a^2 + b^2, 0]
Int[(a_. + b_.*tan[e_. + f_.*x_])^ m_.*(A_. + B_.*tan[e_. + f_.*x_] + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := C*(a + b*Tan[e + f*x])^(m + 1)/(b*f*(m + 1)) + Int[(a + b*Tan[e + f*x])^m*Simp[A - C + B*Tan[e + f*x], x], x] /; FreeQ[{a, b, e, f, A, B, C, m}, x] && NeQ[A*b^2 - a*b*B + a^2*C, 0] && Not[LeQ[m, -1]]
Int[(a_. + b_.*tan[e_. + f_.*x_])^m_.*(A_. + C_.*tan[e_. + f_.*x_]^2), x_Symbol] := C*(a + b*Tan[e + f*x])^(m + 1)/(b*f*(m + 1)) + (A - C)* Int[(a + b*Tan[e + f*x])^m, x] /; FreeQ[{a, b, e, f, A, C, m}, x] && NeQ[A*b^2 + a^2*C, 0] && Not[LeQ[m, -1]]
