
(* ::Subsection::Closed:: *)
(* 4.3.7 (d trig)^m (a+b (c tan)^n)^p *)
Int[u_.*(a_ + b_.*tan[e_. + f_.*x_]^2)^p_, x_Symbol, _:RubiNotebookReference["b663834b"]] := Int[ActivateTrig[u*(a*sec[e + f*x]^2)^p], x] /; FreeQ[{a, b, e, f, p}, x] && EqQ[a, b]
Int[u_.*(b_.*tan[e_. + f_.*x_]^n_)^p_, x_Symbol, _:RubiNotebookReference["b4253d12"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, (b*ff^n)^ IntPart[p]*(b*Tan[e + f*x]^n)^ FracPart[p]/(Tan[e + f*x]/ff)^(n*FracPart[p])* Int[ActivateTrig[u]*(Tan[e + f*x]/ff)^(n*p), x]] /; FreeQ[{b, e, f, n, p}, x] && Not[IntegerQ[p]] && IntegerQ[n] && (EqQ[u, 1] || MatchQ[u, (d_.*trig_[e + f*x])^m_. /; FreeQ[{d, m}, x] && MemberQ[{sin, cos, tan, cot, sec, csc}, trig]])
Int[u_.*(b_.*(c_.*tan[e_. + f_.*x_])^n_)^p_, x_Symbol, _:RubiNotebookReference["b5e75725"]] := b^IntPart[p]*(b*(c*Tan[e + f*x])^n)^ FracPart[p]/(c*Tan[e + f*x])^(n*FracPart[p])* Int[ActivateTrig[u]*(c*Tan[e + f*x])^(n*p), x] /; FreeQ[{b, c, e, f, n, p}, x] && Not[IntegerQ[p]] && Not[IntegerQ[n]] && (EqQ[u, 1] || MatchQ[u, (d_.*trig_[e + f*x])^m_. /; FreeQ[{d, m}, x] && MemberQ[{sin, cos, tan, cot, sec, csc}, trig]])
Int[1/(a_ + b_.*tan[e_. + f_.*x_]^2), x_Symbol, _:RubiNotebookReference["b0a841a0"]] := x/(a - b) - b/(a - b)*Int[Sec[e + f*x]^2/(a + b*Tan[e + f*x]^2), x] /; FreeQ[{a, b, e, f}, x] && NeQ[a, b]
Int[(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^p_, x_Symbol, _:RubiNotebookReference["b16a2b97"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, c*ff/f* Subst[Int[(a + b*(ff*x)^n)^p/(c^2 + ff^2*x^2), x], x, c*Tan[e + f*x]/ff]] /; FreeQ[{a, b, c, e, f, n, p}, x] && (IntegersQ[n, p] || IGtQ[p, 0] || EqQ[n^2, 4] || EqQ[n^2, 16])
Int[(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^p_., x_Symbol, _:RubiNotebookReference["b32c95ce"]] := Unintegrable[(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, e, f, n, p}, x]
Int[sin[e_. + f_.*x_]^m_*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^p_., x_Symbol, _:RubiNotebookReference["b2eefff9"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, c*ff^(m + 1)/f* Subst[Int[x^m*(a + b*(ff*x)^n)^p/(c^2 + ff^2*x^2)^(m/2 + 1), x], x, c*Tan[e + f*x]/ff]] /; FreeQ[{a, b, c, e, f, n, p}, x] && IntegerQ[m/2]
Int[sin[e_. + f_.*x_]^m_.*(a_ + b_.*tan[e_. + f_.*x_]^2)^p_., x_Symbol, _:RubiNotebookReference["b9b2b8c4"]] := With[{ff = FreeFactors[Sec[e + f*x], x]}, 1/(f*ff^m)* Subst[Int[(-1 + ff^2*x^2)^((m - 1)/2)*(a - b + b*ff^2*x^2)^p/ x^(m + 1), x], x, Sec[e + f*x]/ff]] /; FreeQ[{a, b, e, f, p}, x] && IntegerQ[(m - 1)/2]
Int[sin[e_. + f_.*x_]^m_.*(a_ + b_.*tan[e_. + f_.*x_]^n_)^p_., x_Symbol, _:RubiNotebookReference["b870d2f3"]] := With[{ff = FreeFactors[Sec[e + f*x], x]}, 1/(f*ff^m)* Subst[Int[(-1 + ff^2*x^2)^((m - 1)/ 2)*(a + b*(-1 + ff^2*x^2)^(n/2))^p/x^(m + 1), x], x, Sec[e + f*x]/ff]] /; FreeQ[{a, b, e, f, p}, x] && IntegerQ[(m - 1)/2] && IntegerQ[n/2]
Int[(d_.*sin[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["666f612c"]] := Int[ExpandTrig[(d*sin[e + f*x])^m*(a + b*(c*tan[e + f*x])^n)^p, x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && IGtQ[p, 0]
Int[(d_.*sin[e_. + f_.*x_])^m_*(a_ + b_.*tan[e_. + f_.*x_]^2)^p_, x_Symbol, _:RubiNotebookReference["67ad0b1b"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, ff*(d*Sin[e + f*x])^m*(Sec[e + f*x]^2)^(m/2)/(f*Tan[e + f*x]^m)* Subst[ Int[(ff*x)^m*(a + b*ff^2*x^2)^p/(1 + ff^2*x^2)^(m/2 + 1), x], x, Tan[e + f*x]/ff]] /; FreeQ[{a, b, d, e, f, m, p}, x] && Not[IntegerQ[m]]
Int[(d_.*sin[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["65ebb542"]] := Unintegrable[(d*Sin[e + f*x])^m*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(d_.*cos[e_. + f_.*x_])^m_*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_, x_Symbol, _:RubiNotebookReference["6429df75"]] := (d*Cos[e + f*x])^FracPart[m]*(Sec[e + f*x]/d)^ FracPart[m]* Int[(Sec[e + f*x]/d)^(-m)*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && Not[IntegerQ[m]]
Int[(d_.*tan[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["6166c9f0"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, c*ff/f* Subst[Int[(d*ff*x/c)^m*(a + b*(ff*x)^n)^p/(c^2 + ff^2*x^2), x], x, c*Tan[e + f*x]/ff]] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && (IGtQ[p, 0] || EqQ[n, 2] || EqQ[n, 4] || IntegerQ[p] && RationalQ[n])
Int[(d_.*tan[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["60a4a3c7"]] := Int[ExpandTrig[(d*tan[e + f*x])^m*(a + b*(c*tan[e + f*x])^n)^p, x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && IGtQ[p, 0]
Int[(d_.*tan[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["62e21d9e"]] := Unintegrable[(d*Tan[e + f*x])^m*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(d_.*cot[e_. + f_.*x_])^m_*(a_ + b_.*tan[e_. + f_.*x_]^n_.)^p_., x_Symbol, _:RubiNotebookReference["632077a9"]] := d^(n*p)*Int[(d*Cot[e + f*x])^(m - n*p)*(b + a*Cot[e + f*x]^n)^p, x] /; FreeQ[{a, b, d, e, f, m, n, p}, x] && Not[IntegerQ[m]] && IntegersQ[n, p]
Int[(d_.*cot[e_. + f_.*x_])^m_*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_, x_Symbol, _:RubiNotebookReference["687c3094"]] := (d*Cot[e + f*x])^FracPart[m]*(Tan[e + f*x]/d)^ FracPart[m]* Int[(Tan[e + f*x]/d)^(-m)*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && Not[IntegerQ[m]]
Int[sec[e_. + f_.*x_]^m_*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^p_., x_Symbol, _:RubiNotebookReference["69be5aa3"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, ff/(c^(m - 1)*f)* Subst[Int[(c^2 + ff^2*x^2)^(m/2 - 1)*(a + b*(ff*x)^n)^p, x], x, c*Tan[e + f*x]/ff]] /; FreeQ[{a, b, c, e, f, n, p}, x] && IntegerQ[ m/2] && (IntegersQ[n, p] || IGtQ[m, 0] || IGtQ[p, 0] || EqQ[n^2, 4] || EqQ[n^2, 16])
Int[sec[e_. + f_.*x_]^m_.*(a_ + b_.*tan[e_. + f_.*x_]^n_)^p_., x_Symbol, _:RubiNotebookReference["74dacec2"]] := With[{ff = FreeFactors[Sin[e + f*x], x]}, ff/f* Subst[Int[ ExpandToSum[b*(ff*x)^n + a*(1 - ff^2*x^2)^(n/2), x]^ p/(1 - ff^2*x^2)^((m + n*p + 1)/2), x], x, Sin[e + f*x]/ff]] /; FreeQ[{a, b, e, f}, x] && IntegerQ[(m - 1)/2] && IntegerQ[n/2] && IntegerQ[p]
Int[sec[e_. + f_.*x_]^m_.*(a_ + b_.*tan[e_. + f_.*x_]^n_)^p_., x_Symbol, _:RubiNotebookReference["7518a4f5"]] := With[{ff = FreeFactors[Sin[e + f*x], x]}, ff/f* Subst[Int[ 1/(1 - ff^2*x^2)^((m + 1)/ 2)*((b*(ff*x)^n + a*(1 - ff^2*x^2)^(n/2))/(1 - ff^2*x^2)^(n/2))^p, x], x, Sin[e + f*x]/ff]] /; FreeQ[{a, b, e, f, p}, x] && IntegerQ[(m - 1)/2] && IntegerQ[n/2] && Not[IntegerQ[p]]
Int[(d_.*sec[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["775e1aac"]] := Int[ExpandTrig[(d*sec[e + f*x])^m*(a + b*(c*tan[e + f*x])^n)^p, x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && IGtQ[p, 0]
Int[(d_.*sec[e_. + f_.*x_])^m_*(a_ + b_.*tan[e_. + f_.*x_]^2)^p_, x_Symbol, _:RubiNotebookReference["769c709b"]] := With[{ff = FreeFactors[Tan[e + f*x], x]}, ff*(d*Sec[e + f*x])^m/(f*(Sec[e + f*x]^2)^(m/2))* Subst[Int[(1 + ff^2*x^2)^(m/2 - 1)*(a + b*ff^2*x^2)^p, x], x, Tan[e + f*x]/ff]] /; FreeQ[{a, b, d, e, f, m, p}, x] && Not[IntegerQ[m]]
Int[(d_.*sec[e_. + f_.*x_])^m_.*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_., x_Symbol, _:RubiNotebookReference["73d3661e"]] := Unintegrable[(d*Sec[e + f*x])^m*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(d_.*csc[e_. + f_.*x_])^m_*(a_ + b_.*(c_.*tan[e_. + f_.*x_])^n_)^ p_, x_Symbol, _:RubiNotebookReference["72110c29"]] := (d*Csc[e + f*x])^FracPart[m]*(Sin[e + f*x]/d)^ FracPart[m]* Int[(Sin[e + f*x]/d)^(-m)*(a + b*(c*Tan[e + f*x])^n)^p, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && Not[IntegerQ[m]]
