
(* ::Subsection::Closed:: *)
(* 6.1.11 (e x)^m (a+b x^n)^p sinh *)
Int[(a_ + b_.*x_^n_)^p_.*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e1ecad31"]] := Int[ExpandIntegrand[Sinh[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, n}, x] && IGtQ[p, 0]
Int[(a_ + b_.*x_^n_)^p_.*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e3aa1368"]] := Int[ExpandIntegrand[Cosh[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, n}, x] && IGtQ[p, 0]
Int[(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e268795f"]] := x^(-n + 1)*(a + b*x^n)^(p + 1)*Sinh[c + d*x]/(b*n*(p + 1)) - (-n + 1)/(b*n*(p + 1))* Int[x^(-n)*(a + b*x^n)^(p + 1)*Sinh[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(-n + 1)*(a + b*x^n)^(p + 1)*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && IntegerQ[p] && IGtQ[n, 0] && LtQ[p, -1] && GtQ[n, 2]
Int[(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e7276fda"]] := x^(-n + 1)*(a + b*x^n)^(p + 1)*Cosh[c + d*x]/(b*n*(p + 1)) - (-n + 1)/(b*n*(p + 1))* Int[x^(-n)*(a + b*x^n)^(p + 1)*Cosh[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(-n + 1)*(a + b*x^n)^(p + 1)*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && IntegerQ[p] && IGtQ[n, 0] && LtQ[p, -1] && GtQ[n, 2]
Int[(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e6e505ed"]] := Int[ExpandIntegrand[Sinh[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e4a3bbb4"]] := Int[ExpandIntegrand[Cosh[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["e561d183"]] := Int[x^(n*p)*(b + a*x^(-n))^p*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["ee3d96be"]] := Int[x^(n*p)*(b + a*x^(-n))^p*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["effffc89"]] := Unintegrable[(a + b*x^n)^p*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d6e87620"]] := Unintegrable[(a + b*x^n)^p*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d72a1c17"]] := Int[ExpandIntegrand[Sinh[c + d*x], (e*x)^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IGtQ[p, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d56ca24e"]] := Int[ExpandIntegrand[Cosh[c + d*x], (e*x)^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IGtQ[p, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d4aec879"]] := e^m*(a + b*x^n)^(p + 1)*Sinh[c + d*x]/(b*n*(p + 1)) - d*e^m/(b*n*(p + 1))*Int[(a + b*x^n)^(p + 1)*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IntegerQ[p] && EqQ[m - n + 1, 0] && LtQ[p, -1] && (IntegerQ[n] || GtQ[e, 0])
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d1e1defc"]] := e^m*(a + b*x^n)^(p + 1)*Cosh[c + d*x]/(b*n*(p + 1)) - d*e^m/(b*n*(p + 1))*Int[(a + b*x^n)^(p + 1)*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IntegerQ[p] && EqQ[m - n + 1, 0] && LtQ[p, -1] && (IntegerQ[n] || GtQ[e, 0])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d023b4cb"]] := x^(m - n + 1)*(a + b*x^n)^(p + 1)*Sinh[c + d*x]/(b*n*(p + 1)) - (m - n + 1)/(b*n*(p + 1))* Int[x^(m - n)*(a + b*x^n)^(p + 1)*Sinh[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(m - n + 1)*(a + b*x^n)^(p + 1)*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, -1] && IGtQ[n, 0] && RationalQ[m] && (GtQ[m - n + 1, 0] || GtQ[n, 2])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d2650a92"]] := x^(m - n + 1)*(a + b*x^n)^(p + 1)*Cosh[c + d*x]/(b*n*(p + 1)) - (m - n + 1)/(b*n*(p + 1))* Int[x^(m - n)*(a + b*x^n)^(p + 1)*Cosh[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(m - n + 1)*(a + b*x^n)^(p + 1)*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, -1] && IGtQ[n, 0] && RationalQ[m] && (GtQ[m - n + 1, 0] || GtQ[n, 2])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d3a760a5"]] := Int[ExpandIntegrand[Sinh[c + d*x], x^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IntegerQ[m] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d8fb2798"]] := Int[ExpandIntegrand[Cosh[c + d*x], x^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IntegerQ[m] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["d9394daf"]] := Int[x^(m + n*p)*(b + a*x^(-n))^p*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["c45dd9ce"]] := Int[x^(m + n*p)*(b + a*x^(-n))^p*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Sinh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["c59fb3f9"]] := Unintegrable[(e*x)^m*(a + b*x^n)^p*Sinh[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Cosh[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["c7d90da0"]] := Unintegrable[(e*x)^m*(a + b*x^n)^p*Cosh[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
