
(* ::Subsection::Closed:: *)
(* 5.1.4 (f x)^m (d+e x^2)^p (a+b arcsin(c x))^n *)
Int[x_*(a_. + b_.*ArcSin[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol, _:RubiNotebookReference["60ccca5f"]] := -1/e* Subst[Int[(a + b*x)^n*Tan[x], x], x, ArcSin[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
Int[x_*(a_. + b_.*ArcCos[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol, _:RubiNotebookReference["628a7406"]] := 1/e*Subst[Int[(a + b*x)^n*Cot[x], x], x, ArcCos[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["63481e31"]] := (d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^ n/(2*e*(p + 1)) + b*n/(2*c*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && NeQ[p, -1]
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["660708b4"]] := (d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^ n/(2*e*(p + 1)) - b*n/(2*c*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && NeQ[p, -1]
Int[(a_. + b_.*ArcSin[c_.*x_])^n_./(x_*(d_ + e_.*x_^2)), x_Symbol, _:RubiNotebookReference["67c56283"]] := 1/d*Subst[Int[(a + b*x)^n/(Cos[x]*Sin[x]), x], x, ArcSin[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
Int[(a_. + b_.*ArcCos[c_.*x_])^n_./(x_*(d_ + e_.*x_^2)), x_Symbol, _:RubiNotebookReference["6583dcda"]] := -1/d* Subst[Int[(a + b*x)^n/(Cos[x]*Sin[x]), x], x, ArcCos[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6441b6ed"]] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n/(d*f*(m + 1)) - b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6f1df1d0"]] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n/(d*f*(m + 1)) + b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])/x_, x_Symbol, _:RubiNotebookReference["6edf9be7"]] := (d + e*x^2)^p*(a + b*ArcSin[c*x])/(2*p) - b*c*d^p/(2*p)*Int[(1 - c^2*x^2)^(p - 1/2), x] + d*Int[(d + e*x^2)^(p - 1)*(a + b*ArcSin[c*x])/x, x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])/x_, x_Symbol, _:RubiNotebookReference["7c631a18"]] := (d + e*x^2)^p*(a + b*ArcCos[c*x])/(2*p) + b*c*d^p/(2*p)*Int[(1 - c^2*x^2)^(p - 1/2), x] + d*Int[(d + e*x^2)^(p - 1)*(a + b*ArcCos[c*x])/x, x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol, _:RubiNotebookReference["7da1702f"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSin[c*x])/(f*(m + 1)) - b*c*d^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2), x] - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcSin[c*x]), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0] && ILtQ[(m + 1)/2, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol, _:RubiNotebookReference["7fe7ce76"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCos[c*x])/(f*(m + 1)) + b*c*d^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2), x] - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcCos[c*x]), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0] && ILtQ[(m + 1)/2, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol, _:RubiNotebookReference["7e25a441"]] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcSin[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol, _:RubiNotebookReference["7b6ab2c4"]] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcCos[c*x], u, x] + b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[x_^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol, _:RubiNotebookReference["7aa8d8f3"]] := With[{u = IntHide[x^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcSin[c*x], u, x] - b*c*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[SimplifyIntegrand[u/Sqrt[d + e*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IntegerQ[p - 1/2] && NeQ[p, -1/2] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0])
Int[x_^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol, _:RubiNotebookReference["78ee66aa"]] := With[{u = IntHide[x^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcCos[c*x], u, x] + b*c*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[SimplifyIntegrand[u/Sqrt[d + e*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IntegerQ[p - 1/2] && NeQ[p, -1/2] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0])
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["792c0c9d"]] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^n/(f*(m + 1)) - b*c*n/(f*(m + 1))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 1)*(a + b*ArcSin[c*x])^(n - 1), x] + c^2/(f^2*(m + 1))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 2)*(a + b*ArcSin[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["72704ba0"]] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcCos[c*x])^n/(f*(m + 1)) + b*c*n/(f*(m + 1))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 1)*(a + b*ArcCos[c*x])^(n - 1), x] + c^2/(f^2*(m + 1))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 2)*(a + b*ArcCos[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["73b22197"]] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^n/(f*(m + 2)) - b*c*n/(f*(m + 2))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 1)*(a + b*ArcSin[c*x])^(n - 1), x] + 1/(m + 2)*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^m*(a + b*ArcSin[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && (IGtQ[m, -2] || EqQ[n, 1])
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6ed6b5f6"]] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcCos[c*x])^n/(f*(m + 2)) + b*c*n/(f*(m + 2))*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^(m + 1)*(a + b*ArcCos[c*x])^(n - 1), x] + 1/(m + 2)*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(f*x)^m*(a + b*ArcCos[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && (IGtQ[m, -2] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6f14dfc1"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSin[c*x])^n/(f*(m + 1)) - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcSin[c*x])^n, x] - b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6d526198"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCos[c*x])^n/(f*(m + 1)) - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcCos[c*x])^n, x] + b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6c900baf"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSin[c*x])^n/(f*(m + 2*p + 1)) + 2*d*p/(m + 2*p + 1)* Int[(f*x)^m*(d + e*x^2)^(p - 1)*(a + b*ArcSin[c*x])^n, x] - b*c*n/(f*(m + 2*p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && Not[LtQ[m, -1]]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["69df1d2a"]] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCos[c*x])^n/(f*(m + 2*p + 1)) + 2*d*p/(m + 2*p + 1)* Int[(f*x)^m*(d + e*x^2)^(p - 1)*(a + b*ArcCos[c*x])^n, x] + b*c*n/(f*(m + 2*p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && Not[LtQ[m, -1]]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["681d771d"]] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n/(d*f*(m + 1)) + c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^p*(a + b*ArcSin[c*x])^n, x] - b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && ILtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6a5bc944"]] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n/(d*f*(m + 1)) + c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^p*(a + b*ArcCos[c*x])^n, x] + b*c*n/(f*(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && ILtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["6b99a373"]] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^ n/(2*e*(p + 1)) - f^2*(m - 1)/(2*e*(p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n, x] + b*f*n/(2*c*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && IGtQ[m, 1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["60c5e44e"]] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^ n/(2*e*(p + 1)) - f^2*(m - 1)/(2*e*(p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n, x] - b*f*n/(2*c*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && IGtQ[m, 1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["61078e79"]] := -(f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n/(2*d*f*(p + 1)) + (m + 2*p + 3)/(2*d*(p + 1))* Int[(f*x)^m*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n, x] + b*c*n/(2*f*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && (IntegerQ[m] || IntegerQ[p] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["d66ad293"]] := -(f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n/(2*d*f*(p + 1)) + (m + 2*p + 3)/(2*d*(p + 1))* Int[(f*x)^m*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n, x] - b*c*n/(2*f*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && (IntegerQ[m] || IntegerQ[p] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["d7a8b8a4"]] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^ n/(e*(m + 2*p + 1)) + f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^p*(a + b*ArcSin[c*x])^n, x] + b*f*n/(c*(m + 2*p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && IGtQ[m, 1] && NeQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["d5ee06fd"]] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^ n/(e*(m + 2*p + 1)) + f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^p*(a + b*ArcCos[c*x])^n, x] - b*f*n/(c*(m + 2*p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && IGtQ[m, 1] && NeQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_, x_Symbol, _:RubiNotebookReference["d42c6cca"]] := (f*x)^m* Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcSin[c*x])^(n + 1)/(b*c*(n + 1)) - f*m/(b*c*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_, x_Symbol, _:RubiNotebookReference["d1637a4f"]] := -(f*x)^m* Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcCos[c*x])^(n + 1)/(b*c*(n + 1)) + f*m/(b*c*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_, x_Symbol, _:RubiNotebookReference["d0a11078"]] := (f*x)^m* Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcSin[c*x])^(n + 1)/(b*c*(n + 1)) - f*m/(b*c*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n + 1), x] + c*(m + 2*p + 1)/(b*f*(n + 1))* Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && IGtQ[2*p, 0] && NeQ[m + 2*p + 1, 0] && IGtQ[m, -3]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_, x_Symbol, _:RubiNotebookReference["d2e7ae21"]] := -(f*x)^m* Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcCos[c*x])^(n + 1)/(b*c*(n + 1)) + f*m/(b*c*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m - 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n + 1), x] - c*(m + 2*p + 1)/(b*f*(n + 1))* Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[(f*x)^(m + 1)*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && IGtQ[2*p, 0] && NeQ[m + 2*p + 1, 0] && IGtQ[m, -3]
(* Int[(f_.*x_)^m_.*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSin[c_.*x_])^n_,x_ Symbol] :=  (f*x)^m*Sqrt[1-c^2*x^2]*(d+e*x^2)^p*(a+b*ArcSin[c*x])^(n+1)/(b*c*(n+1) ) - f*m/(b*c*(n+1))*Simp[(d+e*x^2)^p/(1-c^2*x^2)^p]*Int[(f*x)^(m-1)*(1- c^2*x^2)^(p+1/2)*(a+b*ArcSin[c*x])^(n+1),x] + c*(2*p+1)/(b*f*(n+1))*Simp[(d+e*x^2)^p/(1-c^2*x^2)^p]*Int[(f*x)^(m+ 1)*(1-c^2*x^2)^(p-1/2)*(a+b*ArcSin[c*x])^(n+1),x] /;  FreeQ[{a,b,c,d,e,f},x] && EqQ[c^2*d+e,0] && LtQ[n,-1] &&  IntegerQ[2*p] && NeQ[p,-1/2] && IGtQ[m,-3] *)
(* Int[(f_.*x_)^m_.*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcCos[c_.*x_])^n_,x_ Symbol] :=  -(f*x)^m*Sqrt[1-c^2*x^2]*(d+e*x^2)^p*(a+b*ArcCos[c*x])^(n+1)/(b*c*(n+ 1)) + f*m/(b*c*(n+1))*Simp[(d+e*x^2)^p/(1-c^2*x^2)^p]*Int[(f*x)^(m-1)*(1- c^2*x^2)^(p+1/2)*(a+b*ArcCos[c*x])^(n+1),x] - c*(2*p+1)/(b*f*(n+1))*Simp[(d+e*x^2)^p/(1-c^2*x^2)^p]*Int[(f*x)^(m+ 1)*(1-c^2*x^2)^(p-1/2)*(a+b*ArcCos[c*x])^(n+1),x] /;  FreeQ[{a,b,c,d,e,f},x] && EqQ[c^2*d+e,0] && LtQ[n,-1] &&  IntegerQ[2*p] && NeQ[p,-1/2] && IGtQ[m,-3] *)
Int[(f_.*x_)^m_*(a_. + b_.*ArcSin[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["d9bbe91c"]] := f*(f*x)^(m - 1)*Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^n/(e*m) + b*f*n/(c*m)*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[(f*x)^(m - 1)*(a + b*ArcSin[c*x])^(n - 1), x] + f^2*(m - 1)/(c^2*m)* Int[((f*x)^(m - 2)*(a + b*ArcSin[c*x])^n)/Sqrt[d + e*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && IGtQ[m, 1]
Int[(f_.*x_)^m_*(a_. + b_.*ArcCos[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["4bbdea2a"]] := f*(f*x)^(m - 1)*Sqrt[d + e*x^2]*(a + b*ArcCos[c*x])^n/(e*m) - b*f*n/(c*m)*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[(f*x)^(m - 1)*(a + b*ArcCos[c*x])^(n - 1), x] + f^2*(m - 1)/(c^2*m)* Int[((f*x)^(m - 2)*(a + b*ArcCos[c*x])^n)/Sqrt[d + e*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && IGtQ[m, 1]
Int[x_^m_*(a_. + b_.*ArcSin[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["4a7f801d"]] := 1/c^(m + 1)*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Subst[Int[(a + b*x)^n*Sin[x]^m, x], x, ArcSin[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0] && IntegerQ[m]
Int[x_^m_*(a_. + b_.*ArcCos[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["48393e44"]] := -1/c^(m + 1)* Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Subst[Int[(a + b*x)^n*Cos[x]^m, x], x, ArcCos[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0] && IntegerQ[m]
Int[(f_.*x_)^m_*(a_. + b_.*ArcSin[c_.*x_])/Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["49fb5473"]] := (f*x)^(m + 1)/(f*(m + 1))* Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]*(a + b*ArcSin[c*x])* Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2] - b*c*(f*x)^(m + 2)/(f^2*(m + 1)*(m + 2))* Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* HypergeometricPFQ[{1, 1 + m/2, 1 + m/2}, {3/2 + m/2, 2 + m/2}, c^2*x^2] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_*(a_. + b_.*ArcCos[c_.*x_])/Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["4cb442f6"]] := (f*x)^(m + 1)/(f*(m + 1))*(a + b*ArcCos[c*x])* Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2] + b*c*(f*x)^(m + 2)/(f^2*(m + 1)*(m + 2))* Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* HypergeometricPFQ[{1, 1 + m/2, 1 + m/2}, {3/2 + m/2, 2 + m/2}, c^2*x^2] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_.*(a_. + b_.*ArcSin[c_.*x_])^n_/Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["4d7628c1"]] := (f*x)^m/(b*c*(n + 1))* Simp[Sqrt[1 - c^2*x^2]/ Sqrt[d + e*x^2]]*(a + b*ArcSin[c*x])^(n + 1) - f*m/(b*c*(n + 1))*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[(f*x)^(m - 1)*(a + b*ArcSin[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1]
Int[(f_.*x_)^m_.*(a_. + b_.*ArcCos[c_.*x_])^n_/Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["4f309698"]] := -(f*x)^m/(b*c*(n + 1))* Simp[Sqrt[1 - c^2*x^2]/ Sqrt[d + e*x^2]]*(a + b*ArcCos[c*x])^(n + 1) + f*m/(b*c*(n + 1))*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[(f*x)^(m - 1)*(a + b*ArcCos[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1]
Int[x_^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["4ef2fcaf"]] := 1/(b*c^(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Subst[Int[x^n*Sin[-a/b + x/b]^m*Cos[-a/b + x/b]^(2*p + 1), x], x, a + b*ArcSin[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[2*p + 2, 0] && IGtQ[m, 0]
Int[x_^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["45aebb92"]] := -1/(b*c^(m + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Subst[Int[x^n*Cos[-a/b + x/b]^m*Sin[-a/b + x/b]^(2*p + 1), x], x, a + b*ArcCos[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[2*p + 2, 0] && IGtQ[m, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["446cd1a5"]] := Int[ExpandIntegrand[(a + b*ArcSin[c*x])^n/ Sqrt[d + e*x^2], (f*x)^m*(d + e*x^2)^(p + 1/2), x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[p + 1/2, 0] && Not[IGtQ[(m + 1)/2, 0]] && (EqQ[m, -1] || EqQ[m, -2])
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["f3018d4f"]] := Int[ExpandIntegrand[(a + b*ArcCos[c*x])^n/ Sqrt[d + e*x^2], (f*x)^m*(d + e*x^2)^(p + 1/2), x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[p + 1/2, 0] && Not[IGtQ[(m + 1)/2, 0]] && (EqQ[m, -1] || EqQ[m, -2])
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol, _:RubiNotebookReference["f2c3e778"]] := (d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])/(2* e*(p + 1)) - b*c/(2*e*(p + 1))*Int[(d + e*x^2)^(p + 1)/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[c^2*d + e, 0] && NeQ[p, -1]
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol, _:RubiNotebookReference["f0855921"]] := (d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])/(2* e*(p + 1)) + b*c/(2*e*(p + 1))*Int[(d + e*x^2)^(p + 1)/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[c^2*d + e, 0] && NeQ[p, -1]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol, _:RubiNotebookReference["f1473316"]] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcSin[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[c^2*d + e, 0] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[(m - 1)/2, 0] && LeQ[m + p, 0])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol, _:RubiNotebookReference["f4082593"]] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcCos[c*x], u, x] + b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[c^2*d + e, 0] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[(m - 1)/2, 0] && LeQ[m + p, 0])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["f5ca4fa4"]] := Int[ExpandIntegrand[(a + b*ArcSin[c*x])^n, (f*x)^m*(d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[c^2*d + e, 0] && IGtQ[n, 0] && IntegerQ[p] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["f78cf1fd"]] := Int[ExpandIntegrand[(a + b*ArcCos[c*x])^n, (f*x)^m*(d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[c^2*d + e, 0] && IGtQ[n, 0] && IntegerQ[p] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["f64e9bca"]] := Unintegrable[(f*x)^m*(d + e*x^2)^p*(a + b*ArcSin[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["fd12dcf7"]] := Unintegrable[(f*x)^m*(d + e*x^2)^p*(a + b*ArcCos[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["fcd0b6c0"]] := (-d^2*g/e)^q* Int[(h*x)^m*(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcSin[c*x])^ n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["e1b422a1"]] := (-d^2*g/e)^q* Int[(h*x)^m*(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcCos[c*x])^ n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["e0764896"]] := (-d^2*g/e)^IntPart[q]*(d + e*x)^ FracPart[q]*(f + g*x)^FracPart[q]/(1 - c^2*x^2)^FracPart[q]* Int[(h*x)^m*(d + e*x)^(p - q)*(1 - c^2*x^2)^ q*(a + b*ArcSin[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["e230f6cf"]] := (-d^2*g/e)^IntPart[q]*(d + e*x)^ FracPart[q]*(f + g*x)^FracPart[q]/(1 - c^2*x^2)^FracPart[q]* Int[(h*x)^m*(d + e*x)^(p - q)*(1 - c^2*x^2)^ q*(a + b*ArcCos[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
