
(* ::Subsection::Closed:: *)
(* 5.1.3 (d+e x^2)^p (a+b arcsin(c x))^n *)
(* Int[(a_.+b_.*ArcSin[c_.*x_])^n_./Sqrt[d_+e_.*x_^2],x_Symbol] :=  1/c*Simp[Sqrt[1-c^2*x^2]/Sqrt[d+e*x^2]]*Subst[Int[(a+b*x)^n,x],x, ArcSin[c*x]] /; FreeQ[{a,b,c,d,e,n},x] && EqQ[c^2*d+e,0] *)
(* Int[(a_.+b_.*ArcCos[c_.*x_])^n_./Sqrt[d_+e_.*x_^2],x_Symbol] :=  -1/c*Simp[Sqrt[1-c^2*x^2]/Sqrt[d+e*x^2]]*Subst[Int[(a+b*x)^n,x],x, ArcCos[c*x]] /; FreeQ[{a,b,c,d,e,n},x] && EqQ[c^2*d+e,0] *)
Int[1/(Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSin[c_.*x_])), x_Symbol] := 1/(b*c)*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Log[a + b*ArcSin[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0]
Int[1/(Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcCos[c_.*x_])), x_Symbol] := -1/(b*c)*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Log[a + b*ArcCos[c*x]]/(b*c*Sqrt[d]) /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0]
Int[(a_. + b_.*ArcSin[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol] := 1/(b*c*(n + 1))* Simp[Sqrt[1 - c^2*x^2]/ Sqrt[d + e*x^2]]*(a + b*ArcSin[c*x])^(n + 1) /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && NeQ[n, -1]
Int[(a_. + b_.*ArcCos[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol] := -1/(b*c*(n + 1))* Simp[Sqrt[1 - c^2*x^2]/ Sqrt[d + e*x^2]]*(a + b*ArcCos[c*x])^(n + 1) /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && NeQ[n, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcSin[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcCos[c*x], u, x] + b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := x*Sqrt[d + e*x^2]*(a + b*ArcSin[c*x])^n/2 - b*c*n/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[x*(a + b*ArcSin[c*x])^(n - 1), x] + 1/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(a + b*ArcSin[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0]
Int[Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := x*Sqrt[d + e*x^2]*(a + b*ArcCos[c*x])^n/2 + b*c*n/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[x*(a + b*ArcCos[c*x])^(n - 1), x] + 1/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 - c^2*x^2]]* Int[(a + b*ArcCos[c*x])^n/Sqrt[1 - c^2*x^2], x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := x*(d + e*x^2)^p*(a + b*ArcSin[c*x])^n/(2*p + 1) + 2*d*p/(2*p + 1)* Int[(d + e*x^2)^(p - 1)*(a + b*ArcSin[c*x])^n, x] - b*c*n/(2*p + 1)*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := x*(d + e*x^2)^p*(a + b*ArcCos[c*x])^n/(2*p + 1) + 2*d*p/(2*p + 1)* Int[(d + e*x^2)^(p - 1)*(a + b*ArcCos[c*x])^n, x] + b*c*n/(2*p + 1)*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0]
Int[(a_. + b_.*ArcSin[c_.*x_])^n_./(d_ + e_.*x_^2)^(3/2), x_Symbol] := x*(a + b*ArcSin[c*x])^n/(d*Sqrt[d + e*x^2]) - b*c*n/d*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[x*(a + b*ArcSin[c*x])^(n - 1)/(1 - c^2*x^2), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0]
Int[(a_. + b_.*ArcCos[c_.*x_])^n_./(d_ + e_.*x_^2)^(3/2), x_Symbol] := x*(a + b*ArcCos[c*x])^n/(d*Sqrt[d + e*x^2]) + b*c*n/d*Simp[Sqrt[1 - c^2*x^2]/Sqrt[d + e*x^2]]* Int[x*(a + b*ArcCos[c*x])^(n - 1)/(1 - c^2*x^2), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0]
Int[(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := -x*(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^ n/(2*d*(p + 1)) + (2*p + 3)/(2*d*(p + 1))* Int[(d + e*x^2)^(p + 1)*(a + b*ArcSin[c*x])^n, x] + b*c*n/(2*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcSin[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && NeQ[p, -3/2]
Int[(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := -x*(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^ n/(2*d*(p + 1)) + (2*p + 3)/(2*d*(p + 1))* Int[(d + e*x^2)^(p + 1)*(a + b*ArcCos[c*x])^n, x] - b*c*n/(2*(p + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p + 1/2)*(a + b*ArcCos[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && NeQ[p, -3/2]
Int[(a_. + b_.*ArcSin[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol] := 1/(c*d)*Subst[Int[(a + b*x)^n*Sec[x], x], x, ArcSin[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
Int[(a_. + b_.*ArcCos[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol] := -1/(c*d)* Subst[Int[(a + b*x)^n*Csc[x], x], x, ArcCos[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
(* Int[(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSin[c_.*x_])^n_,x_Symbol] :=  d^p*(1-c^2*x^2)^(p+1/2)*(a+b*ArcSin[c*x])^(n+1)/(b*c*(n+1)) + c*d^p*(2*p+1)/(b*(n+1))*Int[x*(1-c^2*x^2)^(p-1/2)*(a+b*ArcSin[c*x])^ (n+1),x] /; FreeQ[{a,b,c,d,e,p},x] && EqQ[c^2*d+e,0] && LtQ[n,-1] &&  (IntegerQ[p] || GtQ[d,0]) *)
(* Int[(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcCos[c_.*x_])^n_,x_Symbol] :=  -d^p*(1-c^2*x^2)^(p+1/2)*(a+b*ArcCos[c*x])^(n+1)/(b*c*(n+1)) - c*d^p*(2*p+1)/(b*(n+1))*Int[x*(1-c^2*x^2)^(p-1/2)*(a+b*ArcCos[c*x])^ (n+1),x] /; FreeQ[{a,b,c,d,e,p},x] && EqQ[c^2*d+e,0] && LtQ[n,-1] &&  (IntegerQ[p] || GtQ[d,0]) *)
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_, x_Symbol] := Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcSin[c*x])^(n + 1)/(b*c*(n + 1)) + c*(2*p + 1)/(b*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcSin[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_, x_Symbol] := -Sqrt[1 - c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcCos[c*x])^(n + 1)/(b*c*(n + 1)) - c*(2*p + 1)/(b*(n + 1))*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Int[x*(1 - c^2*x^2)^(p - 1/2)*(a + b*ArcCos[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := 1/(b*c)*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Subst[Int[x^n*Cos[-a/b + x/b]^(2*p + 1), x], x, a + b*ArcSin[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[2*p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := -1/(b*c)*Simp[(d + e*x^2)^p/(1 - c^2*x^2)^p]* Subst[Int[x^n*Sin[-a/b + x/b]^(2*p + 1), x], x, a + b*ArcCos[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[2*p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcSin[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[c^2*d + e, 0] && (IGtQ[p, 0] || ILtQ[p + 1/2, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcCos[c*x], u, x] + b*c*Int[SimplifyIntegrand[u/Sqrt[1 - c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[c^2*d + e, 0] && (IGtQ[p, 0] || ILtQ[p + 1/2, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcSin[c*x])^n, (d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, n}, x] && NeQ[c^2*d + e, 0] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[n, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcCos[c*x])^n, (d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, n}, x] && NeQ[c^2*d + e, 0] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[n, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := Unintegrable[(d + e*x^2)^p*(a + b*ArcSin[c*x])^n, x] /; FreeQ[{a, b, c, d, e, n, p}, x]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := Unintegrable[(d + e*x^2)^p*(a + b*ArcCos[c*x])^n, x] /; FreeQ[{a, b, c, d, e, n, p}, x]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := (-d^2*g/e)^q* Int[(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcSin[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := (-d^2*g/e)^q* Int[(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcCos[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcSin[c_.*x_])^n_., x_Symbol] := (d + e*x)^q*(f + g*x)^q/(1 - c^2*x^2)^q* Int[(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcSin[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcCos[c_.*x_])^n_., x_Symbol] := (d + e*x)^q*(f + g*x)^q/(1 - c^2*x^2)^q* Int[(d + e*x)^(p - q)*(1 - c^2*x^2)^q*(a + b*ArcCos[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 - e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
