(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(c_+d_.*x_)/(a_+b_.*x_^2),x_Symbol] :=
  c^2/a \[Star] Int[1/(c-d*x),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)/(a_+b_.*x_^2),x_Symbol] :=
  c \[Star] Int[1/(a+b*x^2),x] + d \[Star] Int[x/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)/(a_+b_.*x_^2)^(3/2),x_Symbol] :=
  -(a*d-b*c*x)/(a*b*Sqrt[a+b*x^2]) /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a*d-b*c*x)/(2*a*b*(p+1))*(a+b*x^2)^(p+1) + 
  c*(2*p+3)/(2*a*(p+1)) \[Star] Int[(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d},x] && LtQ[p,-1] && NeQ[p,-3/2]


(* ::Code:: *)
Int[(c_+d_.*x_)*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  d*(a+b*x^2)^(p+1)/(2*b*(p+1)) + c \[Star] Int[(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,p},x] && Not[LeQ[p,-1]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[(c+d*x)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[c,0] && Not[IntegerQ[n]])


(* ::Code:: *)
Int[(c_+d_.*x_)^2*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)*(a+b*x^2)^(p+1)/(b*(p+1)) - d^2*(p+2)/(b*(p+1)) \[Star] Int[(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c^2+a*d^2,0] && LtQ[p,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(p+1)) /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(n+2*p+1)) + 
  2*c*Simplify[n+p]/(n+2*p+1) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[Simplify[n+p],0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -d*(c+d*x)^n*(a+b*x^2)^(p+1)/(b*c*n) /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+2*p+2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -d*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*b*c*(n+p+1)) + 
  Simplify[n+2*p+2]/(2*c*(n+p+1)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[Simplify[n+2*p+2],0] && (LtQ[n,-1] || GtQ[n+p,0])


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2)^(3/2),x_Symbol] :=
  -2^(n-1)*d*c^(n-2)*(c+d*x)/(b*Sqrt[a+b*x^2]) + 
  d^2/b \[Star] Int[1/Sqrt[a+b*x^2]*ExpandToSum[(2^(n-1)*c^(n-1)-(c+d*x)^(n-1))/(c-d*x),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[n,2]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(-c)^(-n-2)*d^(2*n+3)*Sqrt[a+b*x^2]/(2^(n+1)*b^(n+2)*(c+d*x)) - 
  d^(2*n+2)/b^(n+1) \[Star] Int[1/Sqrt[a+b*x^2]*ExpandToSum[(2^(-n-1)*(-c)^(-n-1)-(-c+d*x)^(-n-1))/(c+d*x),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[n,0] && EqQ[n+p,-3/2]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
(* c^(2*n)/a^n \[Star] Int[(a+b*x^2)^(n+p)/(c-d*x)^n,x] /; *)
  Int[(a+b*x^2)^(n+p)/(a/c+b*x/d)^n,x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IntegerQ[n] && RationalQ[p] && (LtQ[0,-n,p] || LtQ[p,-n,0]) && NeQ[n,2] && NeQ[n,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(a+b*x^2)^p/(d*(n+p+1)) - 
  b*p/(d^2*(n+p+1)) \[Star] Int[(c+d*x)^(n+2)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && GtQ[p,0] && (LtQ[n,-2] || EqQ[n+2*p+1,0]) && NeQ[n+p+1,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(a+b*x^2)^p/(d*(n+2*p+1)) - 
  2*b*c*p/(d^2*(n+2*p+1)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && GtQ[p,0] && (LeQ[-2,n,0] || EqQ[n+p+1,0]) && NeQ[n+2*p+1,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -c*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*a*d*(p+1)) + 
  c*(n+2*p+2)/(2*a*(p+1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && LtQ[p,-1] && LtQ[0,n,1] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(p+1)) - 
  d^2*(n+p)/(b*(p+1)) \[Star] Int[(c+d*x)^(n-2)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && LtQ[p,-1] && GtQ[n,1] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(n+2*p+1)) + 
  2*c*(n+p)/(n+2*p+1) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c^2+a*d^2,0] && GtQ[n,0] && NeQ[n+2*p+1,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -d*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*b*c*(n+p+1)) + 
  (n+2*p+2)/(2*c*(n+p+1)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c^2+a*d^2,0] && LtQ[n,0] && NeQ[n+p+1,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[1/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  2*d \[Star] Subst[Int[1/(2*b*c+d^2*x^2),x],x,Sqrt[a+b*x^2]/Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^(p+1)*c^(n-1)*((c-d*x)/c)^(p+1)/(a/c+b*x/d)^(p+1) \[Star] Int[(1+d*x/c)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,n},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[n] || GtQ[c,0]) && GtQ[a,0] && 
  Not[IntegerQ[n] && (IntegerQ[3*p] || IntegerQ[4*p])]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^(n-1)*(a+b*x^2)^(p+1)/((1+d*x/c)^(p+1)*(a/c+(b*x)/d)^(p+1)) \[Star] Int[(1+d*x/c)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,n},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[n] || GtQ[c,0]) && Not[GtQ[a,0]] && 
  Not[IntegerQ[n] && (IntegerQ[3*p] || IntegerQ[4*p])]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^IntPart[n]*(c+d*x)^FracPart[n]/(1+d*x/c)^FracPart[n] \[Star] Int[(1+d*x/c)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n},x] && EqQ[b*c^2+a*d^2,0] && Not[IntegerQ[n] || GtQ[c,0]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  d*n*c^(n-1)*(a+b*x^2)^(p+1)/(2*b*(p+1)) + 
  Int[ExpandIntegrand[((c+d*x)^n-d*n*c^(n-1)*x)*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[p,0] && IGtQ[n,0] && LeQ[n,p]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[(c+d*x)^n*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,d,n},x] && IGtQ[p,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^p \[Star] Int[ExpandIntegrand[(c+d*x)^n*(1-Rt[-b/a,2]*x)^p*(1+Rt[-b/a,2]*x)^p,x],x] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[n] && NiceSqrtQ[-b/a] && Not[FractionalPowerFactorQ[Rt[-b/a,2]]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[(c+d*x)^n/(a+b*x^2),x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,1]


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)),x_Symbol] :=
  d*Log[RemoveContent[c+d*x,x]]/(b*c^2+a*d^2) + 
  b/(b*c^2+a*d^2) \[Star] Int[(c-d*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  d*(c+d*x)^(n+1)/((n+1)*(b*c^2+a*d^2)) + 
  b/(b*c^2+a*d^2) \[Star] Int[(c+d*x)^(n+1)*(c-d*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && ILtQ[n,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  d*(c+d*x)^(n-1)/(b*(n-1)) + 
  1/b \[Star] Int[(c+d*x)^(n-2)*Simp[b*c^2-a*d^2+2*b*c*d*x,x]/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && GtQ[n,1]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  d*(c+d*x)^(n+1)/((n+1)*(b*c^2+a*d^2)) + 
  b/(b*c^2+a*d^2) \[Star] Int[(c+d*x)^(n+1)*(c-d*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,n},x] && LtQ[n,-1]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/(a_+b_.*x_^2),x_Symbol] :=
  2*d \[Star] Subst[Int[x^2/(b*c^2+a*d^2-2*b*c*x^2+b*x^4),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[1/(Sqrt[c_+d_.*x_]*(a_+b_.*x_^2)),x_Symbol] :=
  2*d \[Star] Subst[Int[1/(b*c^2+a*d^2-2*b*c*x^2+b*x^4),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[(c+d*x)^n,1/(a+b*x^2),x],x] /;
FreeQ[{a,b,c,d,n},x] && Not[IntegerQ[2*n]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(a*d-b*c*x)*(a+b*x^2)^p/((n+1)*(b*c^2+a*d^2)) - 
  2*a*b*p/((n+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^(n+2)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[n+2*p+2,0] && GtQ[p,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n-1)*(a*d-b*c*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) + 
  (2*p+3)*(b*c^2+a*d^2)/(2*a*b*(p+1)) \[Star] Int[(c+d*x)^(n-2)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[n+2*p+2,0] && LtQ[p,-1]


(* ::Code:: *)
Int[1/((c_+d_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -Subst[Int[1/(b*c^2+a*d^2-x^2),x],x,(a*d-b*c*x)/Sqrt[a+b*x^2]] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[-a*b,2]},
  (q-b*x)*(c+d*x)^(n+1)*(a+b*x^2)^p/((n+1)*(b*c+d*q)*((b*c+d*q)*(q+b*x)/((b*c-d*q)*(-q+b*x)))^p)*
    Hypergeometric2F1[n+1,-p,n+2,2*b*q*(c+d*x)/((b*c-d*q)*(q-b*x))]] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n+2*p+2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -x*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*a*(p+1)) - 
  c*n/(2*a*(p+1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n+2*p+3,0] && LtQ[p,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/((n+1)*(b*c^2+a*d^2)) + 
  b*c/(b*c^2+a*d^2) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n+2*p+3,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(a+b*x^2)^p/(d*(n+1)) - 
  2*b*p/(d*(n+1)) \[Star] Int[x*(c+d*x)^(n+1)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,n},x] && GtQ[p,0] && (IntegerQ[p] || LtQ[n,-1]) && NeQ[n,-1] && Not[ILtQ[n+2*p+1,0]] && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(a+b*x^2)^p/(d*(n+2*p+1)) + 
  2*p/(d*(n+2*p+1)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^(p-1)*(a*d-b*c*x),x] /;
FreeQ[{a,b,c,d,n},x] && GtQ[p,0] && NeQ[n+2*p+1,0] && (Not[RationalQ[n]] || LtQ[n,1]) && Not[ILtQ[n+2*p,0]] && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -x*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*a*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1)*(c*(2*p+3)+d*(n+2*p+3)*x),x] /;
FreeQ[{a,b,c,d},x] && LtQ[p,-1] && GtQ[n,0] && (LtQ[n,1] || ILtQ[n+2*p+3,0] && NeQ[n,2]) && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a*d-b*c*x)*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) - 
  1/(2*a*b*(p+1)) \[Star] Int[(c+d*x)^(n-2)*(a+b*x^2)^(p+1)*Simp[a*d^2*(n-1)-b*c^2*(2*p+3)-b*c*d*(n+2*p+2)*x,x],x] /;
FreeQ[{a,b,c,d},x] && LtQ[p,-1] && GtQ[n,1] && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(a*d+b*c*x)*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/(2*a*(p+1)*(b*c^2+a*d^2)) + 
  1/(2*a*(p+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^(p+1)*Simp[b*c^2*(2*p+3)+a*d^2*(n+2*p+3)+b*c*d*(n+2*p+4)*x,x],x] /;
FreeQ[{a,b,c,d,n},x] && LtQ[p,-1] && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(n+2*p+1)) + 
  1/(b*(n+2*p+1)) \[Star] Int[(c+d*x)^(n-2)*(a+b*x^2)^p*Simp[b*c^2*(n+2*p+1)-a*d^2*(n-1)+2*b*c*d*(n+p)*x,x],x] /;
FreeQ[{a,b,c,d,n,p},x] && If[RationalQ[n], GtQ[n,1], SumSimplerQ[n,-2]] && NeQ[n+2*p+1,0] && IntQuadraticQ[a,0,b,c,d,n,p,x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/((n+1)*(b*c^2+a*d^2)) + 
  b/((n+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p*(c*(n+1)-d*(n+2*p+3)*x),x] /;
FreeQ[{a,b,c,d,n,p},x] && NeQ[n,-1] && (LtQ[n,-1] && IntQuadraticQ[a,0,b,c,d,n,p,x] || SumSimplerQ[n,1] && IntegerQ[p] || ILtQ[Simplify[n+2*p+3],0])


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/4)),x_Symbol] :=
  With[{q=Rt[-a,4]},
  1/(2*d*q)*ArcTan[c*q*(a+b*x^2)^(1/4)/(q^2*(c+d*x)-c*Sqrt[a+b*x^2])] - 
  1/(2*d*q)*ArcTanh[c*q*(a+b*x^2)^(1/4)/(q^2*(c+d*x)+c*Sqrt[a+b*x^2])]] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+2*a*d^2,0] && NegQ[a]


(* ::Code:: *)
(* Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/4)),x_Symbol] :=
  With[{q=Rt[-a,4]},
  1/(2*d*q)*ArcTan[c*q*(a+b*x^2)^(1/4)/(q^2*(c+d*x)-c*Sqrt[a+b*x^2])] - 
  1/(4*q*d)*Log[(q^2*(c+d*x)+c*Sqrt[a+b*x^2]+c*q*(a+b*x^2)^(1/4))/(q^2*(c+d*x)+c*Sqrt[a+b*x^2]-c*q*(a+b*x^2)^(1/4))]] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+2*a*d^2,0] && NegQ[a] *)


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/4)),x_Symbol] :=
  (-a-b*x^2)^(1/4)/(a+b*x^2)^(1/4) \[Star] Int[1/((c+d*x)*(-a-b*x^2)^(1/4)),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+2*a*d^2,0] && PosQ[a]


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/3)),x_Symbol] :=
  With[{q=Rt[6*b^2*d^2/c^2,3]},
  -Sqrt[3]*b*d*ArcTan[1/Sqrt[3]+2*b*(c-d*x)/(Sqrt[3]*c*q*(a+b*x^2)^(1/3))]/(c^2*q^2) - 
  3*b*d*Log[c+d*x]/(2*c^2*q^2) + 
  3*b*d*Log[b*c-b*d*x-c*q*(a+b*x^2)^(1/3)]/(2*c^2*q^2)] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2-3*a*d^2,0]


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/3)),x_Symbol] :=
  a^(1/3) \[Star] Int[1/((c+d*x)*(1-3*d*x/c)^(1/3)*(1+3*d*x/c)^(1/3)),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+9*a*d^2,0] && GtQ[a,0]


(* ::Code:: *)
Int[1/((c_+d_.*x_)*(a_+b_.*x_^2)^(1/3)),x_Symbol] :=
  (1+b*x^2/a)^(1/3)/(a+b*x^2)^(1/3) \[Star] Int[1/((c+d*x)*(1+b*x^2/a)^(1/3)),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+9*a*d^2,0] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  c \[Star] Int[(a+b*x^2)^p/(c^2-d^2*x^2),x] - d \[Star] Int[x*(a+b*x^2)^p/(c^2-d^2*x^2),x] /;
FreeQ[{a,b,c,d,p},x]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x^2)^p,(c/(c^2-d^2*x^2)-d*x/(c^2-d^2*x^2))^(-n),x],x] /;
FreeQ[{a,b,c,d,p},x] && ILtQ[n,-1] && PosQ[a/b]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[-a/b,2]},
  -(a+b*x^2)^p*(1/(c+d*x))^(2*p)/(d*(1-(c-d*q)/(c+d*x))^p*(1-(c+d*q)/(c+d*x))^p) \[Star] 
    Subst[Int[(1-(c-d*q)*x)^p*(1-(c+d*q)*x)^p/x^(n+2*p+2),x],x,1/(c+d*x)]] /;
FreeQ[{a,b,c,d,p},x] && ILtQ[n,-1] && NegQ[a/b]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  2/d \[Star] Subst[Int[x^2/Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2],x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && PosQ[b/a]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  With[{q=Rt[-b/a,2]},
  -2*Sqrt[c+d*x]/(Sqrt[a]*q*Sqrt[q*(c+d*x)/(d+c*q)]) \[Star] 
    Subst[Int[Sqrt[1-2*d*x^2/(d+c*q)]/Sqrt[1-x^2],x],x,Sqrt[(1-q*x)/2]]] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && GtQ[a,0]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[Sqrt[c+d*x]/Sqrt[1+b*x^2/a],x] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[1/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  2/d \[Star] Subst[Int[1/Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2],x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && PosQ[b/a]


(* ::Code:: *)
Int[1/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[-b/a,2]},
  -2*Sqrt[q*(c+d*x)/(d+c*q)]/(Sqrt[a]*q*Sqrt[c+d*x]) \[Star] 
    Subst[Int[1/(Sqrt[1-2*d*x^2/(d+c*q)]*Sqrt[1-x^2]),x],x,Sqrt[(1-q*x)/2]]] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && GtQ[a,0]


(* ::Code:: *)
Int[1/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[1/(Sqrt[c+d*x]*Sqrt[1+b*x^2/a]),x] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^p \[Star] Int[(c+d*x)^n*(1+Rt[-b/a,2]*x)^p*(1-Rt[-b/a,2]*x)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && GtQ[a,0] && NegQ[b/a]


(* ::Code:: *)
(* Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a+b*x^2)^p/(1+b/a*x^2)^p \[Star] Int[(c+d*x)^n*(1+b/a*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && Not[GtQ[a,0]] *)


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{q=Rt[-a/b,2]},
  (a+b*x^2)^p/(d*(1-(c+d*x)/(c-d*q))^p*(1-(c+d*x)/(c+d*q))^p) \[Star] 
    Subst[Int[x^n*Simp[1-x/(c+d*q),x]^p*Simp[1-x/(c-d*q),x]^p,x],x,c+d*x]] /;
FreeQ[{a,b,c,d,n,p},x] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[(c_+d_.*u_)^n_.*(a_+b_.*u_^2)^p_.,x_Symbol] :=
  1/Coefficient[u,x,1] \[Star] Subst[Int[(c+d*x)^n*(a+b*x^2)^p,x],x,u] /;
FreeQ[{a,b,c,d,n,p},x] && LinearQ[u,x] && NeQ[u,x]



