(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2)^p_.,x_Symbol] :=
  Int[(e*x)^m*(a*c+b*d*x^4)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[b*c+a*d,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[c,0])


(* ::Code:: *)
Int[x_^3*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  (a+b*x^2)^(p+1)*(c+d*x^2)^(p+1)/(4*b*d*(p+1)) /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c+a*d,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  -(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1)/(4*a*c*e*(p+1)) /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[b*c+a*d,0] && EqQ[m+4*p+5,0]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  1/2 \[Star] Subst[Int[x^((m-1)/2)*(a+b*x)^p*(c+d*x)^p,x],x,x^2] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c+a*d,0] && IntegerQ[(m-1)/2]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^p*(c+d*x^2)^p/(e*(m+1)) - 
  4*b*d*p/(e^4*(m+1)) \[Star] Int[(e*x)^(m+4)*(a+b*x^2)^(p-1)*(c+d*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c+a*d,0] && GtQ[p,0] && LtQ[m,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^p*(c+d*x^2)^p/(e*(m+4*p+1)) + 
  4*a*c*p/(m+4*p+1) \[Star] Int[(e*x)^m*(a+b*x^2)^(p-1)*(c+d*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c+a*d,0] && GtQ[p,0] && NeQ[m+4*p+1,0] && IntegerQ[2*m]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  e^3*(e*x)^(m-3)*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1)/(4*b*d*(p+1)) - 
  e^4*(m-3)/(4*b*d*(p+1)) \[Star] Int[(e*x)^(m-4)*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c+a*d,0] && LtQ[p,-1] && GtQ[m,3]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  -(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1)/(4*a*c*e*(p+1)) + 
  (m+4*p+5)/(4*a*c*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c+a*d,0] && LtQ[p,-1] && IntegerQ[2*m]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(p+1)/(a*c*e*(m+1)) - 
  b*d*(m+4*p+5)/(a*c*e^4*(m+1)) \[Star] Int[(e*x)^(m+4)*(a+b*x^2)^p*(c+d*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,p},x] && EqQ[b*c+a*d,0] && LtQ[m,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^p_,x_Symbol] :=
  (a+b*x^2)^FracPart[p]*(c+d*x^2)^FracPart[p]/(a*c+b*d*x^4)^FracPart[p] \[Star] Int[(e*x)^m*(a*c+b*d*x^4)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[b*c+a*d,0] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[x_^m_.*(b_.*x_^2)^p_*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  1/(2*b^((m-1)/2)) \[Star] Subst[Int[(b*x)^(p+(m-1)/2)*(c+d*x)^q,x],x,x^2] /;
FreeQ[{b,c,d,m,p,q},x] && IntegerQ[(m-1)/2]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(b_.*x_^2.)^p_*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  e^m*b^IntPart[p]*(b*x^2)^FracPart[p]/x^(2*FracPart[p]) \[Star] Int[x^(m+2*p)*(c+d*x^2)^q,x] /;
FreeQ[{b,c,d,e,m,p,q},x] && (IntegerQ[m] || GtQ[e,0])


(* ::Code:: *)
Int[(e_*x_)^m_*(b_.*x_^2.)^p_*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  e^IntPart[m]*(e*x)^FracPart[m]/x^FracPart[m] \[Star] Int[x^m*(b*x^2)^p*(c+d*x^2)^q,x] /;
FreeQ[{b,c,d,e,m,p,q},x] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[x_/((a_+b_.*x_^2)^(1/4)*(c_+d_.*x_^2)),x_Symbol] :=
  -1/(Sqrt[2]*Rt[a,4]*d)*ArcTan[(Rt[a,4]^2-Sqrt[a+b*x^2])/(Sqrt[2]*Rt[a,4]*(a+b*x^2)^(1/4))] - 
  1/(Sqrt[2]*Rt[a,4]*d)*ArcTanh[(Rt[a,4]^2+Sqrt[a+b*x^2])/(Sqrt[2]*Rt[a,4]*(a+b*x^2)^(1/4))] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c-2*a*d,0] && PosQ[a]


(* ::Code:: *)
Int[x_^m_/((a_+b_.*x_^2)^(1/4)*(c_+d_.*x_^2)),x_Symbol] :=
  Int[ExpandIntegrand[x^m/((a+b*x^2)^(1/4)*(c+d*x^2)),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c-2*a*d,0] && IntegerQ[m] && (PosQ[a] || IntegerQ[m/2])


(* ::Code:: *)
Int[x_^2/((a_+b_.*x_^2)^(3/4)*(c_+d_.*x_^2)),x_Symbol] :=
  -b/(a*d*Rt[b^2/a,4]^3)*ArcTan[(b+Rt[b^2/a,4]^2*Sqrt[a+b*x^2])/(Rt[b^2/a,4]^3*x*(a+b*x^2)^(1/4))] + 
  b/(a*d*Rt[b^2/a,4]^3)*ArcTanh[(b-Rt[b^2/a,4]^2*Sqrt[a+b*x^2])/(Rt[b^2/a,4]^3*x*(a+b*x^2)^(1/4))] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c-2*a*d,0] && PosQ[b^2/a]


(* ::Code:: *)
Int[x_^2/((a_+b_.*x_^2)^(3/4)*(c_+d_.*x_^2)),x_Symbol] :=
  -b/(Sqrt[2]*a*d*Rt[-b^2/a,4]^3)*ArcTan[(Rt[-b^2/a,4]*x)/(Sqrt[2]*(a+b*x^2)^(1/4))] + 
  b/(Sqrt[2]*a*d*Rt[-b^2/a,4]^3)*ArcTanh[(Rt[-b^2/a,4]*x)/(Sqrt[2]*(a+b*x^2)^(1/4))] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c-2*a*d,0] && NegQ[b^2/a]


(* ::Code:: *)
Int[x_^m_/((a_+b_.*x_^2)^(3/4)*(c_+d_.*x_^2)),x_Symbol] :=
  Int[ExpandIntegrand[x^m/((a+b*x^2)^(3/4)*(c+d*x^2)),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c-2*a*d,0] && IntegerQ[m] && (PosQ[a] || IntegerQ[m/2])


(* ::Code:: *)
Int[x_*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  1/2 \[Star] Subst[Int[(a+b*x)^p*(c+d*x)^q,x],x,x^2] /;
FreeQ[{a,b,c,d,p,q},x] && NeQ[b*c-a*d,0]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  1/2 \[Star] Subst[Int[x^((m-1)/2)*(a+b*x)^p*(c+d*x)^q,x],x,x^2] /;
FreeQ[{a,b,c,d,p,q},x] && NeQ[b*c-a*d,0] && IntegerQ[(m-1)/2]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  Int[ExpandIntegrand[(e*x)^m*(a+b*x^2)^p*(c+d*x^2)^q,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && IGtQ[p,0] && IGtQ[q,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2),x_Symbol] :=
  c*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*e*(m+1)) /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && EqQ[a*d*(m+1)-b*c*(m+2*p+3),0] && NeQ[m,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2),x_Symbol] :=
  (b*c-a*d)*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*b*e*(m+1)) + d/b \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e},x] && NeQ[b*c-a*d,0] && EqQ[m+2*p+3,0] && LtQ[p,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2),x_Symbol] :=
  c*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*e*(m+1)) + d/e^2 \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && EqQ[Simplify[m+2*p+3],0] && NeQ[m,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2),x_Symbol] :=
  c*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*e*(m+1)) + 
  (a*d*(m+1)-b*c*(m+2*p+3))/(a*e^2*(m+1)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,p},x] && NeQ[b*c-a*d,0] && LtQ[m,-1] && Not[ILtQ[p,-1]]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2),x_Symbol] :=
  (-a)^(m/2-1)*(b*c-a*d)*x*(a+b*x^2)^(p+1)/(2*b^(m/2+1)*(p+1)) + 
  1/(2*b^(m/2+1)*(p+1)) \[Star] Int[(a+b*x^2)^(p+1)*
    ExpandToSum[2*b*(p+1)*x^2*Together[(b^(m/2)*x^(m-2)*(c+d*x^2)-(-a)^(m/2-1)*(b*c-a*d))/(a+b*x^2)]-(-a)^(m/2-1)*(b*c-a*d),x],x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && IGtQ[m/2,0] && (IntegerQ[p] || EqQ[m+2*p+1,0])


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2),x_Symbol] :=
  (-a)^(m/2-1)*(b*c-a*d)*x*(a+b*x^2)^(p+1)/(2*b^(m/2+1)*(p+1)) + 
  1/(2*b^(m/2+1)*(p+1)) \[Star] Int[x^m*(a+b*x^2)^(p+1)*
    ExpandToSum[2*b*(p+1)*Together[(b^(m/2)*(c+d*x^2)-(-a)^(m/2-1)*(b*c-a*d)*x^(-m+2))/(a+b*x^2)]-
      (-a)^(m/2-1)*(b*c-a*d)*x^(-m),x],x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && ILtQ[m/2,0] && (IntegerQ[p] || EqQ[m+2*p+1,0])


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2),x_Symbol] :=
  -(b*c-a*d)*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(2*a*b*e*(p+1)) - 
  (a*d*(m+1)-b*c*(m+2*p+3))/(2*a*b*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && 
  (Not[IntegerQ[p+1/2]] && NeQ[p,-5/4] || Not[RationalQ[m]] || ILtQ[p+1/2,0] && LeQ[-1,m,-2*(p+1)])


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2),x_Symbol] :=
  d*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(b*e*(m+2*p+3)) - 
  (a*d*(m+1)-b*c*(m+2*p+3))/(b*(m+2*p+3)) \[Star] Int[(e*x)^m*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && NeQ[m+2*p+3,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_/(c_+d_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[(e*x)^m*(a+b*x^2)^p/(c+d*x^2),x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && IGtQ[p,0] && (IntegerQ[m] || IGtQ[2*(m+1),0] || Not[RationalQ[m]])


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^2,x_Symbol] :=
  c^2*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*e*(m+1)) - 
  1/(a*e^2*(m+1)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^p*Simp[2*b*c^2*(p+1)+c*(b*c-2*a*d)*(m+1)-a*d^2*(m+1)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p},x] && NeQ[b*c-a*d,0] && LtQ[m,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^2,x_Symbol] :=
  -(b*c-a*d)^2*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(2*a*b^2*e*(p+1)) + 
  1/(2*a*b^2*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*Simp[(b*c-a*d)^2*(m+1)+2*b^2*c^2*(p+1)+2*a*b*d^2*(p+1)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^2,x_Symbol] :=
  d^2*(e*x)^(m+3)*(a+b*x^2)^(p+1)/(b*e^3*(m+2*p+5)) + 
  1/(b*(m+2*p+5)) \[Star] Int[(e*x)^m*(a+b*x^2)^p*Simp[b*c^2*(m+2*p+5)-d*(a*d*(m+3)-2*b*c*(m+2*p+5))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && NeQ[m+2*p+5,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  With[{k=Denominator[m]},
  k/e \[Star] Subst[Int[x^(k*(m+1)-1)*(a+b*x^(k*2)/e^2)^p*(c+d*x^(k*2)/e^2)^q,x],x,(e*x)^(1/k)]] /;
FreeQ[{a,b,c,d,e,p,q},x] && NeQ[b*c-a*d,0] && FractionQ[m] && IntegerQ[p]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  e*(e*x)^(m-1)*(a+b*x^2)^(p+1)*(c+d*x^2)^q/(2*b*(p+1)) - 
  e^2/(2*b*(p+1)) \[Star] Int[(e*x)^(m-2)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)*Simp[c*(m-1)+d*(m+2*q-1)*x^2,x],x] /;
FreeQ[{a,b,c,d,e},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && GtQ[q,0] && GtQ[m,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -(b*c-a*d)*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)/(2*a*b*e*(p+1)) + 
  1/(2*a*b*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-2)*
    Simp[c*(2*b*c*(p+1)+(b*c-a*d)*(m+1))+d*(2*b*c*(p+1)+(b*c-a*d)*(m+2*q-1))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && GtQ[q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^q/(2*a*e*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)*Simp[c*(m+2*p+3)+d*(m+2*p+2*q+3)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && LtQ[0,q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -a*e^3*(e*x)^(m-3)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(2*b*(b*c-a*d)*(p+1)) + 
  e^4/(2*b*(b*c-a*d)*(p+1)) \[Star] Int[(e*x)^(m-4)*(a+b*x^2)^(p+1)*(c+d*x^2)^q*
    Simp[a*c*(m-3)+(a*d*(m+2*q-1)+2*b*c*(p+1))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,q},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && GtQ[m,3] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  e*(e*x)^(m-1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(2*(b*c-a*d)*(p+1)) - 
  e^2/(2*(b*c-a*d)*(p+1)) \[Star] Int[(e*x)^(m-2)*(a+b*x^2)^(p+1)*(c+d*x^2)^q*Simp[c*(m-1)+d*(m+2*p+2*q+3)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,q},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && GtQ[m,1] && LeQ[m,3] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -b*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(2*a*e*(b*c-a*d)*(p+1)) + 
  1/(2*a*(b*c-a*d)*(p+1)) \[Star] 
    Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^q*Simp[b*c*(m+1)+2*(b*c-a*d)*(p+1)+b*d*(m+2*p+2*q+5)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m,q},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^p*(c+d*x^2)^q/(e*(m+1)) - 
  2/(e^2*(m+1)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^(p-1)*(c+d*x^2)^(q-1)*Simp[b*c*p+a*d*q+b*d*(p+q)*x^2,x],x] /;
FreeQ[{a,b,c,d,e},x] && NeQ[b*c-a*d,0] && GtQ[q,0] && LtQ[m,-1] && GtQ[p,0] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  c*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)/(a*e*(m+1)) - 
  1/(a*e^2*(m+1)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^p*(c+d*x^2)^(q-2)*
    Simp[c*(b*c-a*d)*(m+1)+2*c*(b*c*(p+1)+a*d*(q-1))+d*((b*c-a*d)*(m+1)+2*b*c*(p+q))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p},x] && NeQ[b*c-a*d,0] && GtQ[q,1] && LtQ[m,-1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^q/(a*e*(m+1)) - 
  1/(a*e^2*(m+1)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^p*(c+d*x^2)^(q-1)*
    Simp[b*c*(m+1)+2*(b*c*(p+1)+a*d*q)+d*(b*(m+1)+2*b*(p+q+1))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p},x] && NeQ[b*c-a*d,0] && LtQ[0,q,1] && LtQ[m,-1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^p*(c+d*x^2)^q/(e*(m+2*(p+q)+1)) + 
  2/(m+2*(p+q)+1) \[Star] Int[(e*x)^m*(a+b*x^2)^(p-1)*(c+d*x^2)^(q-1)*Simp[a*c*(p+q)+(q*(b*c-a*d)+a*d*(p+q))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && GtQ[q,0] && GtQ[p,0] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  d*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)/(b*e*(m+2*(p+q)+1)) + 
  1/(b*(m+2*(p+q)+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^p*(c+d*x^2)^(q-2)*
    Simp[c*((b*c-a*d)*(m+1)+2*b*c*(p+q))+(d*(b*c-a*d)*(m+1)+2*d*(q-1)*(b*c-a*d)+2*b*c*d*(p+q))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && GtQ[q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  e*(e*x)^(m-1)*(a+b*x^2)^(p+1)*(c+d*x^2)^q/(b*(m+2*(p+q)+1)) - 
  e^2/(b*(m+2*(p+q)+1)) \[Star] 
    Int[(e*x)^(m-2)*(a+b*x^2)^p*(c+d*x^2)^(q-1)*Simp[a*c*(m-1)+(a*d*(m-1)-2*q*(b*c-a*d))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p},x] && NeQ[b*c-a*d,0] && GtQ[q,0] && GtQ[m,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  e^3*(e*x)^(m-3)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(b*d*(m+2*(p+q)+1)) - 
  e^4/(b*d*(m+2*(p+q)+1)) \[Star] 
    Int[(e*x)^(m-4)*(a+b*x^2)^p*(c+d*x^2)^q*Simp[a*c*(m-3)+(a*d*(m+2*q-1)+b*c*(m+2*p-1))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p,q},x] && NeQ[b*c-a*d,0] && GtQ[m,3] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(a*c*e*(m+1)) - 
  1/(a*c*e^2*(m+1)) \[Star] 
    Int[(e*x)^(m+2)*(a+b*x^2)^p*(c+d*x^2)^q*Simp[(b*c+a*d)*(m+3)+2*(b*c*p+a*d*q)+b*d*(m+2*p+2*q+5)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,p,q},x] && NeQ[b*c-a*d,0] && LtQ[m,-1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_./((a_+b_.*x_^2)*(c_+d_.*x_^2)),x_Symbol] :=
  -a*e^2/(b*c-a*d) \[Star] Int[(e*x)^(m-2)/(a+b*x^2),x] + c*e^2/(b*c-a*d) \[Star] Int[(e*x)^(m-2)/(c+d*x^2),x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LeQ[2,m,3]


(* ::Code:: *)
Int[(e_.*x_)^m_./((a_+b_.*x_^2)*(c_+d_.*x_^2)),x_Symbol] :=
  b/(b*c-a*d) \[Star] Int[(e*x)^m/(a+b*x^2),x] - d/(b*c-a*d) \[Star] Int[(e*x)^m/(c+d*x^2),x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_^2)^q_./(a_+b_.*x_^2),x_Symbol] :=
  e^2/b \[Star] Int[(e*x)^(m-2)*(c+d*x^2)^q,x] - a*e^2/b \[Star] Int[(e*x)^(m-2)*(c+d*x^2)^q/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e,m,q},x] && NeQ[b*c-a*d,0] && LeQ[2,m,3] && IntBinomialQ[a,b,c,d,e,m,2,-1,q,x]


(* ::Code:: *)
Int[x_*(a_+b_.*x_^2)^p_/(c_+d_.*x_^2),x_Symbol] :=
  b/d \[Star] Int[x*(a+b*x^2)^(p-1),x] - (b*c-a*d)/d \[Star] Int[x*(a+b*x^2)^(p-1)/(c+d*x^2),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && GtQ[p,0] && IntBinomialQ[a,b,c,d,1,1,2,p,-1,x]


(* ::Code:: *)
Int[x_*(a_+b_.*x_^2)^p_/(c_+d_.*x_^2),x_Symbol] :=
  b/(b*c-a*d) \[Star] Int[x*(a+b*x^2)^(p-1),x] - d/(b*c-a*d) \[Star] Int[x*(a+b*x^2)^(p+1)/(c+d*x^2),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && IntBinomialQ[a,b,c,d,1,1,2,p,-1,x]


(* ::Code:: *)
Int[x_^2/(Sqrt[a_+b_.*x_^2]*Sqrt[c_+d_.*x_^2]),x_Symbol] :=
  x*Sqrt[a+b*x^2]/(b*Sqrt[c+d*x^2]) - c/b \[Star] Int[Sqrt[a+b*x^2]/(c+d*x^2)^(3/2),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && PosQ[b/a] && PosQ[d/c] && Not[SimplerSqrtQ[b/a,d/c]]


(* ::Code:: *)
Int[x_^2/(Sqrt[a_+b_.*x_^2]*Sqrt[c_+d_.*x_^2]),x_Symbol] :=
  1/b \[Star] Int[Sqrt[a+b*x^2]/Sqrt[c+d*x^2],x] - a/b \[Star] Int[1/(Sqrt[a+b*x^2]*Sqrt[c+d*x^2]),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c-a*d,0] && Not[SimplerSqrtQ[-b/a,-d/c]]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  With[{k=Denominator[p]},
  k*a^(p+(m+1)/2)/2 \[Star] 
    Subst[Int[x^(k*(m+1)/2-1)*(c-(b*c-a*d)*x^k)^q/(1-b*x^k)^(p+q+(m+1)/2+1),x],x,x^(2/k)/(a+b*x^2)^(1/k)]] /;
FreeQ[{a,b,c,d},x] && RationalQ[m,p] && IntegersQ[p+(m+1)/2,q] && LtQ[-1,p,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -(b*c-a*d)*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)/(a*b*e*2*(p+1)) + 
  1/(a*b*2*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-2)*
    Simp[c*(b*c*2*(p+1)+(b*c-a*d)*(m+1))+d*(b*c*2*(p+1)+(b*c-a*d)*(m+2*(q-1)+1))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && GtQ[q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^q/(a*e*2*(p+1)) + 
  1/(a*2*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)*Simp[c*(m+2*(p+1)+1)+d*(m+2*(p+q+1)+1)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && LtQ[0,q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  -b*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q+1)/(a*e*2*(b*c-a*d)*(p+1)) + 
  1/(a*2*(b*c-a*d)*(p+1)) \[Star] 
    Int[(e*x)^m*(a+b*x^2)^(p+1)*(c+d*x^2)^q*Simp[b*c*(m+1)+2*(b*c-a*d)*(p+1)+d*b*(m+2*(p+q+2)+1)*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m,q},x] && NeQ[b*c-a*d,0] && LtQ[p,-1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  (e*x)^(m+1)*(a+b*x^2)^p*(c+d*x^2)^q/(e*(m+2*(p+q)+1)) + 
  2/(m+2*(p+q)+1) \[Star] Int[(e*x)^m*(a+b*x^2)^(p-1)*(c+d*x^2)^(q-1)*Simp[a*c*(p+q)+(q*(b*c-a*d)+a*d*(p+q))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && GtQ[q,0] && GtQ[p,0] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  d*(e*x)^(m+1)*(a+b*x^2)^(p+1)*(c+d*x^2)^(q-1)/(b*e*(m+2*(p+q)+1)) + 
  1/(b*(m+2*(p+q)+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^p*(c+d*x^2)^(q-2)*
    Simp[c*((b*c-a*d)*(m+1)+b*c*2*(p+q))+(d*(b*c-a*d)*(m+1)+d*2*(q-1)*(b*c-a*d)+b*c*d*2*(p+q))*x^2,x],x] /;
FreeQ[{a,b,c,d,e,m,p},x] && NeQ[b*c-a*d,0] && GtQ[q,1] && IntBinomialQ[a,b,c,d,e,m,2,p,q,x]


(* ::Code:: *)
Int[x_^m_/((a_+b_.*x_^2)*(c_+d_.*x_^2)),x_Symbol] :=
  -a/(b*c-a*d) \[Star] Int[x^(m-2)/(a+b*x^2),x] + c/(b*c-a*d) \[Star] Int[x^(m-2)/(c+d*x^2),x] /;
FreeQ[{a,b,c,d,m},x] && NeQ[b*c-a*d,0] && (EqQ[m,2] || EqQ[m,3])


(* ::Code:: *)
Int[(e_.*x_)^m_./((a_+b_.*x_^2)*(c_+d_.*x_^2)),x_Symbol] :=
  b/(b*c-a*d) \[Star] Int[(e*x)^m/(a+b*x^2),x] - d/(b*c-a*d) \[Star] Int[(e*x)^m/(c+d*x^2),x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  Int[ExpandIntegrand[(e*x)^m*(a+b*x^2)^p*(c+d*x^2)^q,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && NeQ[b*c-a*d,0] && IGtQ[p,-2] && (IGtQ[q,-2] || EqQ[q,-3] && IntegerQ[(m-1)/2])


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_.*(c_+d_.*x_^2)^q_.,x_Symbol] :=
  (e*x)^m/(2*x*(x^2)^(Simplify[(m+1)/2]-1)) \[Star] Subst[Int[x^(Simplify[(m+1)/2]-1)*(a+b*x)^p*(c+d*x)^q,x],x,x^2] /;
FreeQ[{a,b,c,d,e,m,p,q},x] && NeQ[b*c-a*d,0] && IntegerQ[Simplify[m+2*p]] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  a^p*c^q*(e*x)^(m+1)/(e*(m+1))*AppellF1[(m+1)/2,-p,-q,1+(m+1)/2,-b*x^2/a,-d*x^2/c] /;
FreeQ[{a,b,c,d,e,m,p,q},x] && NeQ[b*c-a*d,0] && NeQ[m,-1] && NeQ[m,1] && (IntegerQ[p] || GtQ[a,0]) && (IntegerQ[q] || GtQ[c,0])


(* ::Code:: *)
Int[(e_.*x_)^m_.*(a_+b_.*x_^2)^p_*(c_+d_.*x_^2)^q_,x_Symbol] :=
  a^IntPart[p]*(a+b*x^2)^FracPart[p]/(1+b*x^2/a)^FracPart[p] \[Star] Int[(e*x)^m*(1+b*x^2/a)^p*(c+d*x^2)^q,x] /;
FreeQ[{a,b,c,d,e,m,p,q},x] && NeQ[b*c-a*d,0] && NeQ[m,-1] && NeQ[m,1] && Not[IntegerQ[p] || GtQ[a,0]]



