(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[(c+d*x)^(m+p)*(e+f*x)^n*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,e,f,m,n,p},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[c,0] && Not[IntegerQ[m]])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (g/e)^n \[Star] Int[(d+e*x)^(m+n)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[e*f-d*g,0] && IntegerQ[n] && Not[IntegerQ[m] && SimplerQ[f+g*x,d+e*x]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (e/g)^m \[Star] Int[(f+g*x)^(m+n)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[e*f-d*g,0] && GtQ[e/g,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (d+e*x)^m/(f+g*x)^m \[Star] Int[(f+g*x)^(m+n)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[e*f-d*g,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_.+b_.*x_^2)^p_.,x_Symbol] :=
  Int[(c*e+d*f*x^2)^m*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,f,m,n,p},x] && EqQ[m,n] && EqQ[d*e+c*f,0] && (IntegerQ[m] || GtQ[c,0] && GtQ[e,0])


(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_.+b_.*x_^2),x_Symbol] :=
  a*x*(c+d*x)^(m+1)*(e+f*x)^(n+1)/(c*e) /;
FreeQ[{a,b,c,d,e,f,m,n},x] && EqQ[m,n] && EqQ[d*e+c*f,0] && EqQ[b*c*e-a*d*f*(2*m+3),0]


(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_.+b_.*x_^2),x_Symbol] :=
  (b*c*e-a*d*f)*x*(c+d*x)^(m+1)*(e+f*x)^(n+1)/(2*c*d*e*f*(m+1)) - 
  (b*c*e-a*d*f*(2*m+3))/(2*c*d*e*f*(m+1)) \[Star] Int[(c+d*x)^(m+1)*(e+f*x)^(n+1),x] /;
FreeQ[{a,b,c,d,e,f,m,n},x] && EqQ[m,n] && EqQ[d*e+c*f,0] && LtQ[m,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_.+b_.*x_^2),x_Symbol] :=
  b*x*(c+d*x)^(m+1)*(e+f*x)^(n+1)/(d*f*(2*m+3)) - 
  (b*c*e-a*d*f*(2*m+3))/(d*f*(2*m+3)) \[Star] Int[(c+d*x)^m*(e+f*x)^n,x] /;
FreeQ[{a,b,c,d,e,f,m,n},x] && EqQ[m,n] && EqQ[d*e+c*f,0] && Not[LtQ[m,-1]]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]*Sqrt[e_+f_.*x_]/(a_.+b_.*x_^2),x_Symbol] :=
  d*f/b \[Star] Int[1/(Sqrt[c+d*x]*Sqrt[e+f*x]),x] + 
  1/b \[Star] Int[(b*c*e-a*d*f)/(Sqrt[c+d*x]*Sqrt[e+f*x]*(a+b*x^2)),x] /;
FreeQ[{a,b,c,d,e,f},x] && EqQ[d*e+c*f,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^m_.*(e_+f_.*x_)^n_.*(a_.+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^FracPart[m]*(e+f*x)^FracPart[m]/(c*e+d*f*x^2)^FracPart[m] \[Star] Int[(c*e+d*f*x^2)^m*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,f,m,n,p},x] && EqQ[m,n] && EqQ[d*e+c*f,0] && Not[EqQ[p,2] && LtQ[m,-1]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  2/e^(n+2*p+1) \[Star] Subst[Int[x^(2*m+1)*(e*f-d*g+g*x^2)^n*(c*d^2+a*e^2-2*c*d*x^2+c*x^4)^p,x],x,Sqrt[d+e*x]] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[p,0] && ILtQ[n,0] && IntegerQ[m+1/2]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(a+c*x^2)^p,d+e*x,x],R=PolynomialRemainder[(a+c*x^2)^p,d+e*x,x]},
  R*(d+e*x)^(m+1)*(f+g*x)^(n+1)/((m+1)*(e*f-d*g)) + 
  1/((m+1)*(e*f-d*g)) \[Star] Int[(d+e*x)^(m+1)*(f+g*x)^n*ExpandToSum[(m+1)*(e*f-d*g)*Qx-g*R*(m+n+2),x],x]] /;
FreeQ[{a,c,d,e,f,g,n},x] && IGtQ[p,0] && ILtQ[2*m,-2] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  c^p*(d+e*x)^(m+2*p)*(f+g*x)^(n+1)/(g*e^(2*p)*(m+n+2*p+1)) + 
  1/(g*e^(2*p)*(m+n+2*p+1)) \[Star] Int[(d+e*x)^m*(f+g*x)^n*
    ExpandToSum[g*(m+n+2*p+1)*(e^(2*p)*(a+c*x^2)^p-c^p*(d+e*x)^(2*p))-c^p*(e*f-d*g)*(m+2*p)*(d+e*x)^(2*p-1),x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[p,0] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && NeQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^p,x],x] /;
FreeQ[{a,c,d,e,f,g,m,n},x] && IGtQ[p,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)/(a_+c_.*x_^2),x_Symbol] :=
  g*(d+e*x)^m/(c*m) + 
  1/c \[Star] Int[(d+e*x)^(m-1)*Simp[c*d*f-a*e*g+(g*c*d+c*e*f)*x,x]/(a+c*x^2),x] /;
FreeQ[{a,c,d,e,f,g},x] && FractionQ[m] && GtQ[m,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)/(Sqrt[d_.+e_.*x_]*(a_+c_.*x_^2)),x_Symbol] :=
  2 \[Star] Subst[Int[(e*f-d*g+g*x^2)/(c*d^2+a*e^2-2*c*d*x^2+c*x^4),x],x,Sqrt[d+e*x]] /;
FreeQ[{a,c,d,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)/(a_+c_.*x_^2),x_Symbol] :=
  (e*f-d*g)*(d+e*x)^(m+1)/((m+1)*(c*d^2+a*e^2)) + 
  1/(c*d^2+a*e^2) \[Star] Int[(d+e*x)^(m+1)*Simp[c*d*f+a*e*g-c*(e*f-d*g)*x,x]/(a+c*x^2),x] /;
FreeQ[{a,c,d,e,f,g},x] && FractionQ[m] && LtQ[m,-1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_/(a_+c_.*x_^2),x_Symbol] :=
  With[{q=Denominator[m]},
  q/e \[Star] Subst[Int[ExpandIntegrand[x^(q*(m+1)-1)*((e*f-d*g)/e+g*x^q/e)^n/((c*d^2+a*e^2)/e^2-2*c*d*x^q/e^2+c*x^(2*q)/e^2),x],x],x,(d+e*x)^(1/q)]] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[n] && FractionQ[m]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_./(a_+c_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n/(a+c*x^2),x],x] /;
FreeQ[{a,c,d,e,f,g,m},x] && IntegersQ[n]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_/(a_+c_.*x_^2),x_Symbol] :=
  g/c \[Star] Int[Simp[2*e*f+d*g+e*g*x,x]*(d+e*x)^(m-1)*(f+g*x)^(n-2),x] + 
  1/c \[Star] Int[Simp[c*d*f^2-2*a*e*f*g-a*d*g^2+(c*e*f^2+2*c*d*f*g-a*e*g^2)*x,x]*(d+e*x)^(m-1)*(f+g*x)^(n-2)/(a+c*x^2),x] /;
FreeQ[{a,c,d,e,f,g},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && GtQ[m,0] && GtQ[n,1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_/(a_+c_.*x_^2),x_Symbol] :=
  e*g/c \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^(n-1),x] + 
  1/c \[Star] Int[Simp[c*d*f-a*e*g+(c*e*f+c*d*g)*x,x]*(d+e*x)^(m-1)*(f+g*x)^(n-1)/(a+c*x^2),x] /;
FreeQ[{a,c,d,e,f,g},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && GtQ[m,0] && GtQ[n,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_/(a_+c_.*x_^2),x_Symbol] :=
  -g*(e*f-d*g)/(c*f^2+a*g^2) \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^n,x] + 
  1/(c*f^2+a*g^2) \[Star] 
    Int[Simp[c*d*f+a*e*g+c*(e*f-d*g)*x,x]*(d+e*x)^(m-1)*(f+g*x)^(n+1)/(a+c*x^2),x] /;
FreeQ[{a,c,d,e,f,g},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && GtQ[m,0] && LtQ[n,-1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_/(Sqrt[f_.+g_.*x_]*(a_.+c_.*x_^2)),x_Symbol] :=
  Int[ExpandIntegrand[1/(Sqrt[d+e*x]*Sqrt[f+g*x]),(d+e*x)^(m+1/2)/(a+c*x^2),x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[m+1/2,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_/(a_+c_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n,1/(a+c*x^2),x],x] /;
FreeQ[{a,c,d,e,f,g,m,n},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  With[{q=Rt[-a*c,2]},
    1/c^p \[Star] Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n*(-q+c*x)^p*(q+c*x)^p,x],x] /;
 Not[FractionalPowerFactorQ[q]]] /;
FreeQ[{a,c,d,e,f,g},x] && ILtQ[p,-1] && IntegersQ[m,n] && NiceSqrtQ[-a*c]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^2*(a_.+c_.*x_^2)^p_.,x_Symbol] :=
  g^2*(d+e*x)^(m+1)*(a+c*x^2)^(p+1)/(c*e*(m+2*p+3)) /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[d*g*(p+1)-e*f*(m+2*p+3),0] && 
  EqQ[e*(c*f^2+a*g^2)*(m+1)+2*c*f*(e*f-d*g)*(p+1),0] && NeQ[m+2*p+3,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_./(a_+c_.*x_^2)^(3/2),x_Symbol] :=
  -2^(m-1)*d^(m-2)*(e*f+d*g)^n*(d+e*x)/(c*e^(n-1)*Sqrt[a+c*x^2]) + 
  1/(c*e^(n-2)) \[Star] Int[ExpandToSum[(2^(m-1)*d^(m-1)*(e*f+d*g)^n-e^n*(d+e*x)^(m-1)*(f+g*x)^n)/(d-e*x),x]/Sqrt[a+c*x^2],x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && IGtQ[m,0] && IGtQ[n,0]


(* ::Code:: *)
Int[x_^n_.*(d_.+e_.*x_)^m_./(a_+c_.*x_^2)^(3/2),x_Symbol] :=
  -2^(m-1)*d^(m+n-2)*(d+e*x)/(c*e^(n-1)*Sqrt[a+c*x^2]) + 
  d^2/a \[Star] Int[ExpandToSum[((d+e*x)^(m-1)-2^(m-1)*d^(m+n-1)*e^(-n)*x^(-n))/(d-e*x),x]/(x^(-n)*Sqrt[a+c*x^2]),x] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && IGtQ[m,0] && ILtQ[n,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_/(d_+e_.*x_),x_Symbol] :=
  Int[(a/d+c*x/e)*(f+g*x)^n*(a+c*x^2)^(p-1),x] /;
FreeQ[{a,c,d,e,f,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && GtQ[p,0]


(* ::Code:: *)
(* Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_.*Sqrt[a_+c_.*x_^2],x_Symbol] :=
  d^(2*m)/a^m \[Star] Int[(d-e*x)^(-m)*(f+g*x)^n*(a+c*x^2)^(m+1/2),x] /;
FreeQ[{a,c,d,e,f,g,n},x] && EqQ[c*d^2+a*e^2,0] && ILtQ[m,0] && IntegerQ[n] *)


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  g*(d+e*x)^m*(a+c*x^2)^(p+1)/(c*(m+2*p+2)) /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[c*e*f*(m+2*p+2)+c*d*g*m,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d*g+e*f)*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*c*d*(p+1)) - 
  e*(m*(d*g+e*f)+2*e*f*(p+1))/(2*c*d*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && LtQ[p,-1] && GtQ[m,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d*g+e*f)*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*c*d*(p+1)) - 
  e*(m*(d*g+e*f)+2*e*f*(p+1))/(2*c*d*(p+1)) \[Star] Int[(d+e*x)^Simplify[m-1]*(a+c*x^2)^Simplify[p+1],x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && SumSimplerQ[p,1] && SumSimplerQ[m,-1] && NeQ[p,-1] && Not[IGtQ[m,0]]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d*g-e*f)*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*c*d*(m+p+1)) + 
  (m*(g*c*d+c*e*f)+2*e*c*f*(p+1))/(e*(2*c*d)*(m+p+1)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && 
  (LtQ[m,-1] && Not[IGtQ[m+p+1,0]] || LtQ[m,0] && LtQ[p,-1] || EqQ[m+2*p+2,0]) && NeQ[m+p+1,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  g*(d+e*x)^m*(a+c*x^2)^(p+1)/(c*(m+2*p+2)) + 
  (m*(d*g+e*f)+2*e*f*(p+1))/(e*(m+2*p+2)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && NeQ[m+2*p+2,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  ((e*f+d*g)*(2*p+3)+2*e*g*(p+1)*x)*(a+c*x^2)^(p+1)/(2*c*(p+1)*(2*p+3)) /;
FreeQ[{a,c,d,e,f,g,p},x] && EqQ[a*e*g-c*d*f*(2*p+3),0] && NeQ[p,-1]


(* ::Code:: *)
Int[x_*(d_+e_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d+e*x)*(a+c*x^2)^(p+1)/(2*c*(p+1)) - 
  e/(2*c*(p+1)) \[Star] Int[(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e},x] && LtQ[p,-1] && Not[IntegerQ[p] && NiceSqrtQ[-a*c]]


(* ::Code:: *)
Int[(d_+e_.*x_)*(f_+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  a*(e*f+d*g)*(a+c*x^2)^(p+1)/(2*a*c*(p+1)) - 
  (c*d*f-a*e*g)*x*(a+c*x^2)^(p+1)/(2*a*c*(p+1)) - 
  (a*e*g-c*d*f*(2*p+3))/(2*a*c*(p+1)) \[Star] Int[(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e,f,g},x] && LtQ[p,-1] && Not[IntegerQ[p] && NiceSqrtQ[-a*c]]


(* ::Code:: *)
Int[(d_.+e_.*x_)*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (e*f+d*g)*(a+c*x^2)^(p+1)/(2*c*(p+1)) + 
  e*g*x*(a+c*x^2)^(p+1)/(c*(2*p+3)) - 
  (a*e*g-c*d*f*(2*p+3))/(c*(2*p+3)) \[Star] Int[(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,p},x] && Not[LeQ[p,-1]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  -(e*f-d*g)*(d+e*x)^(m+1)*(a+c*x^2)^(p+1)/(2*(p+1)*(c*d^2+a*e^2)) /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[Simplify[m+2*p+3],0] && EqQ[c*d*f+a*e*g,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d+e*x)^m*(a+c*x^2)^(p+1)*(a*g-c*f*x)/(2*a*c*(p+1)) - 
  m*(c*d*f+a*e*g)/(2*a*c*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[Simplify[m+2*p+3],0] && LtQ[p,-1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  -(e*f-d*g)*(d+e*x)^(m+1)*(a+c*x^2)^(p+1)/(2*(p+1)*(c*d^2+a*e^2)) + 
  (c*d*f+a*e*g)/(c*d^2+a*e^2) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[Simplify[m+2*p+3],0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  -(d+e*x)^(m+1)*(a+c*x^2)^p/(e^2*(m+1)*(m+2)*(c*d^2+a*e^2))*
    ((d*g-e*f*(m+2))*(c*d^2+a*e^2)-2*c*d^2*p*(e*f-d*g)-e*(g*(m+1)*(c*d^2+a*e^2)+2*c*d*p*(e*f-d*g))*x) - 
  p/(e^2*(m+1)*(m+2)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+2)*(a+c*x^2)^(p-1)*
    Simp[2*a*c*e*(e*f-d*g)*(m+2)-c*(2*c*d*(d*g*(2*p+1)-e*f*(m+2*p+2))-2*a*e^2*g*(m+1))*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && GtQ[p,0] && LtQ[m,-2] && LtQ[m+2*p,0] && Not[ILtQ[m+2*p+3,0]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (d+e*x)^(m+1)*(e*f*(m+2*p+2)-d*g*(2*p+1)+e*g*(m+1)*x)*(a+c*x^2)^p/(e^2*(m+1)*(m+2*p+2)) + 
  p/(e^2*(m+1)*(m+2*p+2)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^(p-1)*
    Simp[g*(2*a*e+2*a*e*m)+(g*(2*c*d+4*c*d*p)-2*c*e*f*(m+2*p+2))*x,x],x] /;
FreeQ[{a,c,d,e,f,g,m},x] && GtQ[p,0] && 
  (LtQ[m,-1] || EqQ[p,1] || IntegerQ[p] && Not[RationalQ[m]]) && NeQ[m,-1] && Not[ILtQ[m+2*p+1,0]] && 
  (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (d+e*x)^(m+1)*(c*e*f*(m+2*p+2)-g*c*d*(2*p+1)+g*c*e*(m+2*p+1)*x)*(a+c*x^2)^p/
    (c*e^2*(m+2*p+1)*(m+2*p+2)) + 
  2*p/(c*e^2*(m+2*p+1)*(m+2*p+2)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^(p-1)*
    Simp[f*a*c*e^2*(m+2*p+2)+a*c*d*e*g*m-(c^2*f*d*e*(m+2*p+2)-g*(c^2*d^2*(2*p+1)+a*c*e^2*(m+2*p+1)))*x,x],x] /;
FreeQ[{a,c,d,e,f,g,m},x] && 
  GtQ[p,0] && (IntegerQ[p] || Not[RationalQ[m]] || GeQ[m,-1] && LtQ[m,0]) && Not[ILtQ[m+2*p,0]] && 
  (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Int[(a+c*x^2)^p*ExpandIntegrand[(d+e*x)^m*(f+g*x),x],x] /;
FreeQ[{a,c,d,e,f,g},x] && ILtQ[p,-1] && IGtQ[m,0] && RationalQ[a,c,d,e,f,g]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (d+e*x)^(m-1)*(a+c*x^2)^(p+1)*(a*(e*f+d*g)-(c*d*f-a*e*g)*x)/(2*a*c*(p+1)) - 
  1/(2*a*c*(p+1)) \[Star] Int[(d+e*x)^(m-2)*(a+c*x^2)^(p+1)*
    Simp[a*e*(e*f*(m-1)+d*g*m)-c*d^2*f*(2*p+3)+e*(a*e*g*m-c*d*f*(m+2*p+2))*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && LtQ[p,-1] && GtQ[m,1] && 
  (EqQ[d,0] || EqQ[m,2] && EqQ[p,-3] && RationalQ[a,c,d,e,f,g] || Not[ILtQ[m+2*p+3,0]])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d+e*x)^m*(a+c*x^2)^(p+1)*(a*g-c*f*x)/(2*a*c*(p+1)) - 
  1/(2*a*c*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1)*Simp[a*e*g*m-c*d*f*(2*p+3)-c*e*f*(m+2*p+3)*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && LtQ[p,-1] && GtQ[m,0] && (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -(d+e*x)^(m+1)*(f*a*c*e-a*g*c*d+c*(c*d*f+a*e*g)*x)*(a+c*x^2)^(p+1)/(2*a*c*(p+1)*(c*d^2+a*e^2)) + 
  1/(2*a*c*(p+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^(p+1)*
    Simp[f*(c^2*d^2*(2*p+3)+a*c*e^2*(m+2*p+3))-a*c*d*e*g*m+c*e*(c*d*f+a*e*g)*(m+2*p+4)*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && LtQ[p,-1] && (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  g*(d+e*x)^m*(a+c*x^2)^(p+1)/(c*(m+2*p+2)) + 
  1/(c*(m+2*p+2)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^p*
    Simp[c*d*f*(m+2*p+2)-a*e*g*m+c*(e*f*(m+2*p+2)+d*g*m)*x,x],x] /;
FreeQ[{a,c,d,e,f,g,p},x] && GtQ[m,0] && NeQ[m+2*p+2,0] && 
  (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p]) && Not[IGtQ[m,0] && EqQ[f,0]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (e*f-d*g)*(d+e*x)^(m+1)*(a+c*x^2)^(p+1)/((m+1)*(c*d^2+a*e^2)) + 
  1/((m+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p*Simp[(c*d*f+a*e*g)*(m+1)-c*(e*f-d*g)*(m+2*p+3)*x,x],x] /;
FreeQ[{a,c,d,e,f,g,p},x] && LtQ[m,-1] && (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  (e*f-d*g)*(d+e*x)^(m+1)*(a+c*x^2)^(p+1)/((m+1)*(c*d^2+a*e^2)) + 
  1/((m+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p*Simp[(c*d*f+a*e*g)*(m+1)-c*(e*f-d*g)*(m+2*p+3)*x,x],x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && ILtQ[Simplify[m+2*p+3],0] && NeQ[m,-1]


(* ::Code:: *)
Int[(f_+g_.*x_)/(Sqrt[x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  2 \[Star] Subst[Int[(f+g*x^2)/Sqrt[a+c*x^4],x],x,Sqrt[x]] /;
FreeQ[{a,c,f,g},x]


(* ::Code:: *)
Int[(f_+g_.*x_)/(Sqrt[e_*x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  Sqrt[x]/Sqrt[e*x] \[Star] Int[(f+g*x)/(Sqrt[x]*Sqrt[a+c*x^2]),x] /;
FreeQ[{a,c,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,a*e+c*d*x,x], R=PolynomialRemainder[(f+g*x)^n,a*e+c*d*x,x]},
  -d*R*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*a*e*(p+1)) + 
  d/(2*a*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1)*ExpandToSum[2*a*e*(p+1)*Q+R*(m+2*p+2),x],x]] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && IGtQ[m,0] && LtQ[p,-1] && EqQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_.*(a_.+c_.*x_^2)^p_/(d_+e_.*x_),x_Symbol] :=
  d*(f+g*x)^n*(a+c*x^2)^(p+1)/(2*a*e*p*(d+e*x)) - 
  n*(e*f+d*g)/(2*d*e*p) \[Star] Int[(f+g*x)^(n-1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && IGtQ[n,1] && LtQ[p,-1] && EqQ[n+2*p+1,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_/(d_+e_.*x_),x_Symbol] :=
  -(e*f-d*g)*(f+g*x)^(n-1)*(a+c*x^2)^(p+1)/(2*c*d*p*(d+e*x)) + 
  1/(2*d*e^2*p) \[Star] Int[(f+g*x)^(n-2)*(a+c*x^2)^p*Simp[(e*f-d*g)*(e*f+d*g-d*g*n)+2*e^2*f^2*p+e*g*((e*f-d*g)*n+2*e*f*p)*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && LtQ[p,-1] && EqQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_*(d_+e_.*x_)^m_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -(e*f-d*g)^n*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*c*d*e^(n-1)*(m+p+1)) + 
  1/(2*d*e^n*(m+p+1)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p*
    ExpandToSum[(2*d*e^n*(m+p+1)*(f+g*x)^n-(e*f-d*g)^n*(d*m-e*(m+2*p+2)*x))/(d+e*x),x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && ILtQ[m,-1] && LtQ[p,-1] && EqQ[c*d^2+a*e^2,0]


(* ::Code:: *)
(* Int[(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_/(d_+e_.*x_),x_Symbol] :=
  d*(f+g*x)^n*(a+c*x^2)^(p+1)/(2*a*e*p*(d+e*x)) - 
  1/(2*d*e*p) \[Star] Int[(f+g*x)^(n-1)*(a+c*x^2)^p*Simp[d*g*n-e*f*(2*p+1)-e*g*(n+2*p+1)*x,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && LtQ[p,-1] && EqQ[c*d^2+a*e^2,0] *)


(* ::Code:: *)
(* Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  d^(2*m)/a^m \[Star] Int[(f+g*x)^n*(a+c*x^2)^(m+p)/(d-e*x)^m,x] /;
FreeQ[{a,c,d,e,f,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[f,0] && ILtQ[m,-1] && Not[IGtQ[n,0] && ILtQ[m+n,0] && Not[GtQ[p,1]]] *)


(* ::Code:: *)
(* Int[(d_+e_.*x_)^m_*(f_+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  d^(2*m)/a^m \[Star] Int[(f+g*x)^n*(a+c*x^2)^(m+p)/(d-e*x)^m,x] /;
FreeQ[{a,c,d,e,f,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && ILtQ[m,0] && IntegerQ[n] *)


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_/(d_+e_.*x_),x_Symbol] :=
  d*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(2*a*p*(e*f-d*g)*(d+e*x)) + 
  1/(p*(2*c*d)*(e*f-d*g)) \[Star] Int[(f+g*x)^n*(a+c*x^2)^p*(c*e*f*(2*p+1)-c*d*g*(n+2*p+1)+c*e*g*(n+2*p+2)*x),x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && ILtQ[n,0] && ILtQ[n+2*p,0] && Not[IGtQ[n,0]]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -e*(d+e*x)^(m-1)*(f+g*x)^n*(a+c*x^2)^(p+1)/(c*(m-n-1)) /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && EqQ[e*f+d*g,0] && NeQ[m-n-1,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -e^2*(d+e*x)^(m-1)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(c*(n+1)*(e*f+d*g)) /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && EqQ[m-n-2,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (d+e*x)^m*(f+g*x)^(n+1)*(a+c*x^2)^p/(g*(n+1)) + 
  c*m/(e*g*(n+1)) \[Star] Int[(d+e*x)^(m+1)*(f+g*x)^(n+1)*(a+c*x^2)^(p-1),x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && GtQ[p,0] && LtQ[n,-1] && Not[IntegerQ[n+p] && LeQ[n+p+2,0]]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -(d+e*x)^m*(f+g*x)^(n+1)*(a+c*x^2)^p/(g*(m-n-1)) - 
  c*m*(e*f+d*g)/(e^2*g*(m-n-1)) \[Star] Int[(d+e*x)^(m+1)*(f+g*x)^n*(a+c*x^2)^(p-1),x] /;
FreeQ[{a,c,d,e,f,g,n},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && GtQ[p,0] && NeQ[m-n-1,0] && Not[IGtQ[n,0]] && Not[IntegerQ[n+p] && LtQ[n+p+2,0]] && RationalQ[n]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  e*(d+e*x)^(m-1)*(f+g*x)^n*(a+c*x^2)^(p+1)/(c*(p+1)) - 
  e*g*n/(c*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^(n-1)*(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && LtQ[p,-1] && GtQ[n,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  e^2*(d+e*x)^(m-1)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(c*(p+1)*(e*f+d*g)) + 
  e^2*g*(m-n-2)/(c*(p+1)*(e*f+d*g)) \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^n*(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,d,e,f,g,n},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && LtQ[p,-1] && RationalQ[n]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -e*(d+e*x)^(m-1)*(f+g*x)^n*(a+c*x^2)^(p+1)/(c*(m-n-1)) - 
  n*(e*f+d*g)/(e*(m-n-1)) \[Star] Int[(d+e*x)^m*(f+g*x)^(n-1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && GtQ[n,0] && NeQ[m-n-1,0] && (IntegerQ[2*p] || IntegerQ[n])


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  -e^2*(d+e*x)^(m-1)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/((n+1)*(c*e*f+c*d*g)) - 
  e*(m-n-2)/((n+1)*(e*f+d*g)) \[Star] Int[(d+e*x)^m*(f+g*x)^(n+1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p,0] && LtQ[n,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[Sqrt[d_+e_.*x_]/((f_.+g_.*x_)*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  2*e^2 \[Star] Subst[Int[1/(c*(e*f+d*g)+e^2*g*x^2),x],x,Sqrt[a+c*x^2]/Sqrt[d+e*x]] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  e^2*(d+e*x)^(m-2)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(c*g*(n+p+2)) /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p-1,0] && EqQ[e*f*(p+1)-d*g*(2*n+p+3),0] && NeQ[n+p+2,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  e^2*(e*f-d*g)*(d+e*x)^(m-2)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(c*g*(n+1)*(e*f+d*g)) - 
  e*(e*f*(p+1)-d*g*(2*n+p+3))/(g*(n+1)*(e*f+d*g)) \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^(n+1)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p-1,0] && LtQ[n,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  e^2*(d+e*x)^(m-2)*(f+g*x)^(n+1)*(a+c*x^2)^(p+1)/(c*g*(n+p+2)) - 
  (e*f*(p+1)-d*g*(2*n+p+3))/(g*(n+p+2)) \[Star] Int[(d+e*x)^(m-1)*(f+g*x)^n*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+p-1,0] && Not[LtQ[n,-1]] && IntegerQ[2*p]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[1/Sqrt[a+c*x^2],(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^(p+1/2),x],x] /;
FreeQ[{a,c,d,e,f,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && IntegerQ[p-1/2] && ILtQ[m,0] && ILtQ[n,0] && Not[IGtQ[n,0]]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^p,x],x] /;
FreeQ[{a,c,d,e,f,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && ILtQ[m,0] && (ILtQ[n,0] || IGtQ[n,0] && ILtQ[p+1/2,0]) && Not[IGtQ[n,0]]


(* ::Code:: *)
(* Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,a*e+c*d*x,x], R=PolynomialRemainder[(f+g*x)^n,a*e+c*d*x,x]},
  -d*R*(d+e*x)^m*(a+c*x^2)^(p+1)/(2*a*e*(p+1)) + 
  d/(2*a*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1)*ExpandToSum[2*a*e*(p+1)*Q+R*(m+2*p+2),x],x]] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && ILtQ[p+1/2,0] && IGtQ[m,0] && IGtQ[n,0] *)


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+c*x^2)^p,(d+e*x)^m*(f+g*x)^n,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[c*d^2+a*e^2,0] && EqQ[m+n+2*p+1,0] && ILtQ[m,0] && ILtQ[n,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_+g_.*x_)^n_.*(a_.+c_.*x_^2)^p_,x_Symbol] :=
  g^n*(d+e*x)^(m+n-1)*(a+c*x^2)^(p+1)/(c*e^(n-1)*(m+n+2*p+1)) + 
  1/(c*e^n*(m+n+2*p+1)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^p*
    ExpandToSum[c*e^n*(m+n+2*p+1)*(f+g*x)^n-c*g^n*(m+n+2*p+1)*(d+e*x)^n-2*e*g^n*(m+p+n)*(d+e*x)^(n-2)*(a*e-c*d*x),x],x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && EqQ[c*d^2+a*e^2,0] && IGtQ[n,0] && NeQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,a+c*x^2,x],
        R=Coeff[PolynomialRemainder[(f+g*x)^n,a+c*x^2,x],x,0],
        S=Coeff[PolynomialRemainder[(f+g*x)^n,a+c*x^2,x],x,1]},
  (d+e*x)^m*(a+c*x^2)^(p+1)*(a*S-c*R*x)/(2*a*c*(p+1)) + 
  1/(2*a*c*(p+1)) \[Star] Int[(d+e*x)^(m-1)*(a+c*x^2)^(p+1)*
    ExpandToSum[2*a*c*(p+1)*(d+e*x)*Q-a*e*S*m+c*d*R*(2*p+3)+c*e*R*(m+2*p+3)*x,x],x]] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && LtQ[p,-1] && GtQ[m,0] && NeQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(d+e*x)^m*(f+g*x)^n,a+c*x^2,x],
        R=Coeff[PolynomialRemainder[(d+e*x)^m*(f+g*x)^n,a+c*x^2,x],x,0],
        S=Coeff[PolynomialRemainder[(d+e*x)^m*(f+g*x)^n,a+c*x^2,x],x,1]},
  (a*S-c*R*x)*(a+c*x^2)^(p+1)/(2*a*c*(p+1)) + 
  1/(2*a*c*(p+1)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^(p+1)*
    ExpandToSum[2*a*c*(p+1)*(d+e*x)^(-m)*Q+c*R*(2*p+3)*(d+e*x)^(-m),x],x]] /;
FreeQ[{a,c,d,e,f,g},x] && IGtQ[n,1] && LtQ[p,-1] && ILtQ[m,0] && NeQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,a+c*x^2,x],
        R=Coeff[PolynomialRemainder[(f+g*x)^n,a+c*x^2,x],x,0],
        S=Coeff[PolynomialRemainder[(f+g*x)^n,a+c*x^2,x],x,1]},
  -(d+e*x)^(m+1)*(a+c*x^2)^(p+1)*(a*(e*R-d*S)+(c*d*R+a*e*S)*x)/(2*a*(p+1)*(c*d^2+a*e^2)) + 
  1/(2*a*(p+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^(p+1)*
   ExpandToSum[2*a*(p+1)*(c*d^2+a*e^2)*Q+c*d^2*R*(2*p+3)-a*e*(d*S*m-e*R*(m+2*p+3))+e*(c*d*R+a*e*S)*(m+2*p+4)*x,x],x]] /;
FreeQ[{a,c,d,e,f,g,m},x] && IGtQ[n,1] && LtQ[p,-1] && NeQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,d+e*x,x], R=PolynomialRemainder[(f+g*x)^n,d+e*x,x]},
  (e*R*(d+e*x)^(m+1)*(a+c*x^2)^(p+1))/((m+1)*(c*d^2+a*e^2)) + 
  1/((m+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p*
     ExpandToSum[(m+1)*(c*d^2+a*e^2)*Q+c*d*R*(m+1)-c*e*R*(m+2*p+3)*x,x],x]] /;
FreeQ[{a,c,d,e,f,g,p},x] && IGtQ[n,1] && ILtQ[m,-1] && NeQ[c*d^2+a*e^2,0] && (NeQ[m+n,0] || EqQ[p,-1/2])


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  g^n*(d+e*x)^(m+n-1)*(a+c*x^2)^(p+1)/(c*e^(n-1)*(m+n+2*p+1)) + 
  1/(c*e^n*(m+n+2*p+1)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^p*ExpandToSum[c*e^n*(m+n+2*p+1)*(f+g*x)^n-c*g^n*(m+n+2*p+1)*(d+e*x)^n-
    g^n*(d+e*x)^(n-2)*(a*e^2*(m+n-1)-c*d^2*(m+n+2*p+1)-2*c*d*e*(m+n+p)*x),x],x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && IGtQ[n,1] && IntegerQ[m] && NeQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Int[(d+e*x)^(m+p)*(f+g*x)^n*(a/d+c/e*x)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n},x] && EqQ[c*d^2+a*e^2,0] && GtQ[a,0] && GtQ[d,0]


(* ::Code:: *)
Int[(d_+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_,x_Symbol] :=
  (a+c*x^2)^FracPart[p]/((d+e*x)^FracPart[p]*(a/d+(c*x)/e)^FracPart[p]) \[Star] Int[(d+e*x)^(m+p)*(f+g*x)^n*(a/d+c/e*x)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n},x] && EqQ[c*d^2+a*e^2,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  g/e \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p,x] + (e*f-d*g)/e \[Star] Int[(d+e*x)^m*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && Not[IGtQ[m,0]]


(* ::Code:: *)
Int[(a_+c_.*x_^2)^p_/((d_.+e_.*x_)*(f_.+g_.*x_)),x_Symbol] :=
  (c*d^2+a*e^2)/(e*(e*f-d*g)) \[Star] Int[(a+c*x^2)^(p-1)/(d+e*x),x] - 
  1/(e*(e*f-d*g)) \[Star] Int[Simp[c*d*f+a*e*g-c*(e*f-d*g)*x,x]*(a+c*x^2)^(p-1)/(f+g*x),x] /;
FreeQ[{a,c,d,e,f,g},x] && FractionQ[p] && GtQ[p,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2],x_Symbol] :=
  (d+e*x)^(m+1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/(e*(m+1)) - 
  1/(2*e*(m+1)) \[Star] Int[(d+e*x)^(m+1)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*Simp[a*g+2*c*f*x+3*c*g*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && LtQ[m,-1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2],x_Symbol] :=
  2*(d+e*x)^(m+1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/(e*(2*m+5)) + 
  1/(e*(2*m+5)) \[Star] Int[(d+e*x)^m/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[3*a*e*f-a*d*g-2*(c*d*f-a*e*g)*x+(c*e*f-3*c*d*g)*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g,m},x] && IntegerQ[2*m] && Not[LtQ[m,-1]]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*Sqrt[a_+c_.*x_^2]/Sqrt[f_.+g_.*x_],x_Symbol] :=
  2*(d+e*x)^m*Sqrt[f+g*x]*Sqrt[a+c*x^2]/(g*(2*m+3)) - 
  1/(g*(2*m+3)) \[Star] Int[(d+e*x)^(m-1)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[2*a*(e*f*m-d*g*(m+1))+(2*c*d*f-2*a*e*g)*x-(2*c*(d*g*m-e*f*(m+1)))*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && GtQ[m,0]


(* ::Code:: *)
Int[Sqrt[a_+c_.*x_^2]/((d_.+e_.*x_)*Sqrt[f_.+g_.*x_]),x_Symbol] :=
  (c*d^2+a*e^2)/e^2 \[Star] Int[1/((d+e*x)*Sqrt[f+g*x]*Sqrt[a+c*x^2]),x] - 
  1/e^2 \[Star] Int[(c*d-c*e*x)/(Sqrt[f+g*x]*Sqrt[a+c*x^2]),x] /;
FreeQ[{a,c,d,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*Sqrt[a_+c_.*x_^2]/Sqrt[f_.+g_.*x_],x_Symbol] :=
  (d+e*x)^(m+1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/((m+1)*(e*f-d*g)) - 
  1/(2*(m+1)*(e*f-d*g)) \[Star] Int[(d+e*x)^(m+1)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[a*g*(2*m+3)+2*(c*f)*x+c*g*(2*m+5)*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && LtQ[m,-1]


(* ::Code:: *)
Int[Sqrt[d_.+e_.*x_]/(Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  With[{q=Rt[-4*a*c,2]},
  Sqrt[2]*Sqrt[2*c*f-g*q]*Sqrt[-q+2*c*x]*(d+e*x)*
    Sqrt[(e*f-d*g)*(q+2*c*x)/((2*c*f-g*q)*(d+e*x))]*
    Sqrt[(e*f-d*g)*(2*a+q*x)/((q*f-2*a*g)*(d+e*x))]/
   (g*Sqrt[2*c*d-e*q]*Sqrt[2*a*c/q+c*x]*Sqrt[a+c*x^2])*
    EllipticPi[e*(2*c*f-g*q)/(g*(2*c*d-e*q)),
      ArcSin[Sqrt[2*c*d-e*q]*Sqrt[f+g*x]/(Sqrt[2*c*f-g*q]*Sqrt[d+e*x])],
      (q*d-2*a*e)*(2*c*f-g*q)/((q*f-2*a*g)*(2*c*d-e*q))]] /;
FreeQ[{a,c,d,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^(3/2)/(Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  e/g \[Star] Int[Sqrt[d+e*x]*Sqrt[f+g*x]/Sqrt[a+c*x^2],x] - 
  (e*f-d*g)/g \[Star] Int[Sqrt[d+e*x]/(Sqrt[f+g*x]*Sqrt[a+c*x^2]),x] /;
FreeQ[{a,c,d,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_/(Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  2*e^2*(d+e*x)^(m-2)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/(c*g*(2*m-1)) - 
  1/(c*g*(2*m-1)) \[Star] Int[(d+e*x)^(m-3)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[a*e^2*(d*g+2*e*f*(m-2))-c*d^3*g*(2*m-1)+e*(e*(a*e*g*(2*m-3))+c*d*(2*e*f-3*d*g*(2*m-1)))*x+2*e^2*(c*e*f-3*c*d*g)*(m-1)*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && GeQ[m,2]


(* ::Code:: *)
(* Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[c^2+a*d^2/b,4],r=Rt[(b*e^2+a*f^2)/(f*(d*e-c*f)),2]},
  ArcTan[r*(Sqrt[c+d*x]/Sqrt[a+b*x^2])]/(r*(d*e-c*f)) - 
  b*(q^2*f+d*e-c*f)*(c+q^2+d*x)*Sqrt[d^2*(a+b*x^2)/(b*(c+q^2+d*x)^2)]/(d*q*(a*d*f^2-b*e*(d*e-2*c*f))*Sqrt[a+b*x^2])*
    EllipticF[2*ArcTan[Sqrt[c+d*x]/q],(1+c/q^2)/2] + 
  b*(q^2*f+d*e-c*f)^2*(c+q^2+d*x)*Sqrt[d^2*(a+b*x^2)/(b*(c+q^2+d*x)^2)]/(2*d*q*(d*e-c*f)*(a*d*f^2-b*e*(d*e-2*c*f))*Sqrt[a+b*x^2])*
    EllipticPi[-(q^2*f-d*e+c*f)^2/(4*q^2*f*(d*e-c*f)),2*ArcTan[Sqrt[c+d*x]/q],(1+c/q^2)/2]] /;
FreeQ[{a,b,c,d,e,f},x] && PosQ[b/a] && PosQ[(b*e^2+a*f^2)/(f*(d*e-c*f))] && NeQ[a*d*f^2-b*e*(d*e-2*c*f),0] *)


(* ::Code:: *)
(* Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[c^2+a*d^2/b,4],r=Rt[-(b*e^2+a*f^2)/(f*(d*e-c*f)),2]},
  ArcTanh[r*(Sqrt[c+d*x]/Sqrt[a+b*x^2])]/(r*(d*e-c*f)) - 
  b*(q^2*f+d*e-c*f)*(c+q^2+d*x)*Sqrt[d^2*(a+b*x^2)/(b*(c+q^2+d*x)^2)]/(d*q*(a*d*f^2-b*e*(d*e-2*c*f))*Sqrt[a+b*x^2])*
    EllipticF[2*ArcTan[Sqrt[c+d*x]/q],(1+c/q^2)/2] + 
  b*(q^2*f+d*e-c*f)^2*(c+q^2+d*x)*Sqrt[d^2*(a+b*x^2)/(b*(c+q^2+d*x)^2)]/(2*d*q*(d*e-c*f)*(a*d*f^2-b*e*(d*e-2*c*f))*Sqrt[a+b*x^2])*
    EllipticPi[-(q^2*f-d*e+c*f)^2/(4*q^2*f*(d*e-c*f)),2*ArcTan[Sqrt[c+d*x]/q],(1+c/q^2)/2]] /;
FreeQ[{a,b,c,d,e,f},x] && PosQ[b/a] && NegQ[(b*e^2+a*f^2)/(f*(d*e-c*f))] && NeQ[a*d*f^2-b*e*(d*e-2*c*f),0] *)


(* ::Code:: *)
Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  2 \[Star] Subst[Int[1/((d*e-c*f+f*x^2)*Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2]),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d,e,f},x] && PosQ[b/a]


(* ::Code:: *)
Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[-b/a,2]},
  1/Sqrt[a] \[Star] Int[1/((e+f*x)*Sqrt[c+d*x]*Sqrt[1-q*x]*Sqrt[1+q*x]),x]] /;
FreeQ[{a,b,c,d,e,f},x] && NegQ[b/a] && GtQ[a,0]


(* ::Code:: *)
Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[-b/a,2]},
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[1/((e+f*x)*Sqrt[c+d*x]*Sqrt[1-q*x]*Sqrt[1+q*x]),x]] /;
FreeQ[{a,b,c,d,e,f},x] && NegQ[b/a] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[1/(Sqrt[c_.+d_.*x_]*Sqrt[e_.+f_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -2*(c+d*x)*Sqrt[(d*e-c*f)^2*(a+b*x^2)/((b*e^2+a*f^2)*(c+d*x)^2)]/((d*e-c*f)*Sqrt[a+b*x^2]) \[Star] 
  Subst[Int[1/Sqrt[Simp[1-(2*b*c*e+2*a*d*f)*x^2/(b*e^2+a*f^2)+(b*c^2+a*d^2)*x^4/(b*e^2+a*f^2),x]],x],x,Sqrt[e+f*x]/Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d,e,f},x]


(* ::Code:: *)
Int[1/(Sqrt[c_.+d_.*x_]*(e_.+f_.*x_)^(3/2)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  d/(d*e-c*f) \[Star] Int[1/(Sqrt[c+d*x]*Sqrt[e+f*x]*Sqrt[a+b*x^2]),x] - 
  f/(d*e-c*f) \[Star] Int[Sqrt[c+d*x]/((e+f*x)^(3/2)*Sqrt[a+b*x^2]),x] /;
FreeQ[{a,b,c,d,e,f},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_/(Sqrt[f_.+g_.*x_]*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  e^2*(d+e*x)^(m+1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/((m+1)*(e*f-d*g)*(c*d^2+a*e^2)) + 
  1/(2*(m+1)*(e*f-d*g)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[2*c*d*(e*f-d*g)*(m+1)-a*e^2*g*(2*m+3)+2*c*e*(d*g*(m+1)-e*f*(m+2))*x-c*e^2*g*(2*m+5)*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && LeQ[m,-2]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*Sqrt[f_.+g_.*x_]/Sqrt[a_+c_.*x_^2],x_Symbol] :=
  2*e*(d+e*x)^(m-1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/(c*(2*m+1)) - 
  1/(c*(2*m+1)) \[Star] Int[(d+e*x)^(m-2)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[a*e*(d*g+2*e*f*(m-1))-c*d^2*f*(2*m+1)+(a*e^2*g*(2*m-1)-c*d*(4*e*f*m+d*g*(2*m+1)))*x-c*e*(e*f+d*g*(4*m-1))*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && GtQ[m,1]


(* ::Code:: *)
Int[Sqrt[f_.+g_.*x_]/((d_.+e_.*x_)*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  g/e \[Star] Int[1/(Sqrt[f+g*x]*Sqrt[a+c*x^2]),x] + 
  (e*f-d*g)/e \[Star] Int[1/((d+e*x)*Sqrt[f+g*x]*Sqrt[a+c*x^2]),x] /;
FreeQ[{a,c,d,e,f,g},x]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_*Sqrt[f_.+g_.*x_]/Sqrt[a_+c_.*x_^2],x_Symbol] :=
  e*(d+e*x)^(m+1)*Sqrt[f+g*x]*Sqrt[a+c*x^2]/((m+1)*(c*d^2+a*e^2)) + 
  1/(2*(m+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)/(Sqrt[f+g*x]*Sqrt[a+c*x^2])*
    Simp[2*c*d*f*(m+1)-e*(a*g)+2*c*(d*g*(m+1)-e*f*(m+2))*x-c*e*g*(2*m+5)*x^2,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[2*m] && LeQ[m,-2]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_/(d_.+e_.*x_),x_Symbol] :=
  (c*d^2+a*e^2)/(e*(e*f-d*g)) \[Star] Int[(f+g*x)^(n+1)*(a+c*x^2)^(p-1)/(d+e*x),x] - 
  1/(e*(e*f-d*g)) \[Star] Int[(f+g*x)^n*(c*d*f+a*e*g-c*(e*f-d*g)*x)*(a+c*x^2)^(p-1),x] /;
FreeQ[{a,c,d,e,f,g},x] && Not[IntegerQ[n]] && Not[IntegerQ[p]] && GtQ[p,0] && LtQ[n,-1]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_/(d_.+e_.*x_),x_Symbol] :=
  e*(e*f-d*g)/(c*d^2+a*e^2) \[Star] Int[(f+g*x)^(n-1)*(a+c*x^2)^(p+1)/(d+e*x),x] + 
  1/(c*d^2+a*e^2) \[Star] Int[(f+g*x)^(n-1)*(c*d*f+a*e*g-c*(e*f-d*g)*x)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g},x] && 
  Not[IntegerQ[n]] && Not[IntegerQ[p]] && LtQ[p,-1] && GtQ[n,0]


(* ::Code:: *)
Int[(f_.+g_.*x_)^n_/((d_.+e_.*x_)*Sqrt[a_+c_.*x_^2]),x_Symbol] :=
  Int[ExpandIntegrand[1/(Sqrt[f+g*x]*Sqrt[a+c*x^2]),(f+g*x)^(n+1/2)/(d+e*x),x],x] /;
FreeQ[{a,c,d,e,f,g},x] && IntegerQ[n+1/2]


(* ::Code:: *)
(* Int[(d_.+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  With[{q=Denominator[m]},
  q/e \[Star] Subst[Int[x^(q*(m+1)-1)*((e*f-d*g)/e+g*x^q/e)^n*((c*d^2+a*e^2)/e^2-2*c*d*x^q/e^2+c*x^(2*q)/e^2)^p,x],x,(d+e*x)^(1/q)]] /;
FreeQ[{a,c,d,e,f,g},x] && IntegersQ[n,p] && FractionQ[m] *)


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^p,x],x] /;
FreeQ[{a,c,d,e,f,g},x] && (IntegerQ[p] || ILtQ[m,0] && ILtQ[n,0])


(* ::Code:: *)
Int[(d_+e_.*x_)^m_*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Q=PolynomialQuotient[(f+g*x)^n,d+e*x,x], R=PolynomialRemainder[(f+g*x)^n,d+e*x,x]},
  (e*R*(d+e*x)^(m+1)*(a+c*x^2)^(p+1))/((m+1)*(c*d^2+a*e^2)) + 
  1/((m+1)*(c*d^2+a*e^2)) \[Star] Int[(d+e*x)^(m+1)*(a+c*x^2)^p*
     ExpandToSum[(m+1)*(c*d^2+a*e^2)*Q+c*d*R*(m+1)-c*e*R*(m+2*p+3)*x,x],x]] /;
FreeQ[{a,c,d,e,f,g,p},x] && IGtQ[n,1] && LtQ[m,-1]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_*(a_+c_.*x_^2)^p_,x_Symbol] :=
  g^n*(d+e*x)^(m+n-1)*(a+c*x^2)^(p+1)/(c*e^(n-1)*(m+n+2*p+1)) + 
  1/(c*e^n*(m+n+2*p+1)) \[Star] Int[(d+e*x)^m*(a+c*x^2)^p*ExpandToSum[c*e^n*(m+n+2*p+1)*(f+g*x)^n-c*g^n*(m+n+2*p+1)*(d+e*x)^n-
    g^n*(d+e*x)^(n-2)*(a*e^2*(m+n-1)-c*d^2*(m+n+2*p+1)-2*c*d*e*(m+n+p)*x),x],x] /;
FreeQ[{a,c,d,e,f,g,m,p},x] && IGtQ[n,1] && NeQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[(d_.+e_.*x_)^m_.*(f_.+g_.*x_)^n_.*(a_+c_.*x_^2)^p_,x_Symbol] :=
  Unintegrable[(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^p,x] /;
FreeQ[{a,c,d,e,f,g,m,n,p},x]


(* ::Code:: *)
Int[(d_.+e_.*u_)^m_.*(f_.+g_.*u_)^n_.*(a_+c_.*u_^2)^p_.,x_Symbol] :=
  1/Coefficient[u,x,1] \[Star] Subst[Int[(d+e*x)^m*(f+g*x)^n*(a+c*x^2)^p,x],x,u] /;
FreeQ[{a,c,d,e,f,g,m,n,p},x] && LinearQ[u,x] && NeQ[u,x]



