(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[(e*x)^m*(c+d*x)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[c,0] && Not[IntegerQ[n]])


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  2*e^m/d^(m+2*p+1) \[Star] Subst[Int[x^(2*n+1)*(-c+x^2)^m*(b*c^2+a*d^2-2*b*c*x^2+b*x^4)^p,x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[p,0] && ILtQ[m,0] && IntegerQ[n+1/2]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  2/e^(n+2*p+1) \[Star] Subst[Int[x^(2*m+1)*(e*c+d*x^2)^n*(a*e^2+b*x^4)^p,x],x,Sqrt[e*x]] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[p,0] && ILtQ[n,0] && IntegerQ[m+1/2]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(a+b*x^2)^p,c+d*x,x],R=PolynomialRemainder[(a+b*x^2)^p,c+d*x,x]},
  -R*(e*x)^(m+1)*(c+d*x)^(n+1)/(c*e*(n+1)) + 
  1/(c*(n+1)) \[Star] Int[(e*x)^m*(c+d*x)^(n+1)*ExpandToSum[c*(n+1)*Qx+R*(m+n+2),x],x]] /;
FreeQ[{a,b,c,d,e,m},x] && IGtQ[p,0] && LtQ[n,-1] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(a+b*x^2)^p,e*x,x],R=PolynomialRemainder[(a+b*x^2)^p,e*x,x]},
  R*(e*x)^(m+1)*(c+d*x)^(n+1)/((m+1)*(e*c)) + 
  1/((m+1)*(e*c)) \[Star] Int[(e*x)^(m+1)*(c+d*x)^n*ExpandToSum[(m+1)*(e*c)*Qx-d*R*(m+n+2),x],x]] /;
FreeQ[{a,b,c,d,e,n},x] && IGtQ[p,0] && LtQ[m,-1] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  b^p*(e*x)^(m+2*p)*(c+d*x)^(n+1)/(d*e^(2*p)*(m+n+2*p+1)) + 
  1/(d*e^(2*p)*(m+n+2*p+1)) \[Star] Int[(e*x)^m*(c+d*x)^n*
    ExpandToSum[d*(m+n+2*p+1)*(e^(2*p)*(a+b*x^2)^p-b^p*(e*x)^(2*p))-b^p*(e*c)*(m+2*p)*(e*x)^(2*p-1),x],x] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[p,0] && NeQ[m+n+2*p+1,0] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[(e*x)^m*(c+d*x)^n*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,d,e,m,n},x] && IGtQ[p,0]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)/(a_+b_.*x_^2),x_Symbol] :=
  Int[ExpandIntegrand[x^m*(c+d*x)/(a+b*x^2),x],x] /;
FreeQ[{a,b,c,d},x] && IntegerQ[m]


(* ::Code:: *)
Int[(c_+d_.*x_)^2/(x_*(a_+b_.*x_^2)),x_Symbol] :=
  c^2/a*Log[x] + 2*c*d \[Star] Int[1/(a+b*x^2),x] - (b*c^2-a*d^2)/a \[Star] Int[x/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  d^n*x^(m+n-1)/(b*(m+n-1)) + 
  1/b \[Star] Int[x^m*ExpandToSum[b*(c+d*x)^n-b*d^n*x^n-a*d^n*x^(n-2),x]/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,1] && IGtQ[m,-2] && NeQ[m+n-1,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  With[{Qx=PolynomialQuotient[(c+d*x)^n,x,x], R=PolynomialRemainder[(c+d*x)^n,x,x]},
  R*x^(m+1)/(a*(m+1)) + 
  1/a \[Star] Int[x^(m+1)*ExpandToSum[a*Qx-b*R*x,x]/(a+b*x^2),x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,1] && ILtQ[m,-1]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_./(a_+b_.*x_^2)^(3/2),x_Symbol] :=
  -2^(n-1)*c^(m+n-2)*(c+d*x)/(b*d^(m-1)*Sqrt[a+b*x^2]) + 
  1/(b*d^(m-2)) \[Star] Int[(1/Sqrt[a+b*x^2])*ExpandToSum[(2^(n-1)*c^(m+n-1)-d^m*x^m*(c+d*x)^(n-1))/(c-d*x),x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && IGtQ[m,0] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_./(a_+b_.*x_^2)^(3/2),x_Symbol] :=
  -2^(n-1)*c^(m+n-2)*(c+d*x)/(b*d^(m-1)*Sqrt[a+b*x^2]) + 
  c^2/a \[Star] Int[x^m/Sqrt[a+b*x^2]*ExpandToSum[((c+d*x)^(n-1)-2^(n-1)*c^(m+n-1)*d^(-m)*x^(-m))/(c-d*x),x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && ILtQ[m,0] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m,a*d+b*c*x,x], R=PolynomialRemainder[x^m,a*d+b*c*x,x]},
  -c*R*(c+d*x)^n*(a+b*x^2)^(p+1)/(2*a*d*(p+1)) + 
  c/(2*a*(p+1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1)*ExpandToSum[2*a*d*(p+1)*Qx+R*(n+2*p+2),x],x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && IGtQ[m,1] && LtQ[p,-1] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m*(c+d*x)^n,a+b*x^2,x],
        e=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,0],
        f=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,1]},
  (a*f-b*e*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(a+b*x^2)^(p+1)*ExpandToSum[2*a*(p+1)*Qx+e*(2*p+3),x],x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && IGtQ[m,0] && LtQ[p,-1] && EqQ[n,1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m,a+b*x^2,x],
        e=Coeff[PolynomialRemainder[x^m,a+b*x^2,x],x,0],
        f=Coeff[PolynomialRemainder[x^m,a+b*x^2,x],x,1]},
  (c+d*x)^n*(a*f-b*e*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) + 
  1/(2*a*b*(p +1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1)*
    ExpandToSum[2*a*b*(p+1)*(c+d*x)*Qx-a*d*f*n+b*c*e*(2*p+3)+b*d*e*(n+2*p+3)*x,x],x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && IGtQ[m,0] && LtQ[p,-1] && GtQ[n,1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m*(c+d*x)^n,a+b*x^2,x],
        e=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,0],
        f=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,1]},
  (a*f-b*e*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[x^m*(a+b*x^2)^(p+1)*ExpandToSum[2*a*(p+1)*Qx/x^m+e*(2*p+3)/x^m,x],x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[n,0] && ILtQ[m,0] && LtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*x^m*(a+b*x^2)^(p+1)/(b*(m+2*p+2)) - 
  1/(b*(m+2*p+2)) \[Star] Int[x^(m-1)*(a+b*x^2)^p*Simp[a*d*m-b*c*(m+2*p+2)*x,x],x] /;
FreeQ[{a,b,c,d,p},x] && IGtQ[m,0] && GtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -c*x^(m+1)*(a+b*x^2)^(p+1)/(2*a*(p+1)) + d \[Star] Int[x^(m+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,m,p},x] && ILtQ[m,0] && GtQ[p,-1] && EqQ[m+2*p+3,0]


(* ::Code:: *)
Int[(c_+d_.*x_)*(a_+b_.*x_^2)^p_/x_,x_Symbol] :=
  (c*(2*p+1)+2*d*p*x)*(a+b*x^2)^p/(2*p*(2*p+1)) + 
  a/(2*p+1) \[Star] Int[(c*(2*p+1)+2*d*p*x)*(a+b*x^2)^(p-1)/x,x] /;
FreeQ[{a,b,c,d},x] && GtQ[p,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)*(a_+b_.*x_^2)^p_/x_^2,x_Symbol] :=
  -(2*c*p-d*x)*(a+b*x^2)^p/(2*p*x) + Int[(a*d+2*b*c*p*x)*(a+b*x^2)^(p-1)/x,x] /;
FreeQ[{a,b,c,d},x] && GtQ[p,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  x^(m+1)*(c*(m+2)+d*(m+1)*x)*(a+b*x^2)^p/((m+1)*(m+2)) - 
  2*b*p/((m+1)*(m+2)) \[Star] Int[x^(m+2)*(c*(m+2)+d*(m+1)*x)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && ILtQ[m,-2] && GtQ[p,0] && Not[ILtQ[m+2*p+3,0]] && IntegerQ[2*p]


(* ::Code:: *)
Int[(c_+d_.*x_)/(x_*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  c \[Star] Int[1/(x*Sqrt[a+b*x^2]),x] + d \[Star] Int[1/Sqrt[a+b*x^2],x] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*x^(m+1)*(a+b*x^2)^(p+1)/(a*(m+1)) + 
  1/(a*(m+1))\[Star]Int[x^(m+1)*(a+b*x^2)^p*(a*d*(m+1)-b*c*(m+2*p+3)*x),x] /;
FreeQ[{a,b,c,d,p},x] && ILtQ[m,-1] && GtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(c+d*x)^n,x,x], R=PolynomialRemainder[(c+d*x)^n,x,x]},
  R*x^(m+1)*(a+b*x^2)^(p+1)/(a*(m+1)) + 
  1/(a*(m+1)) \[Star] Int[x^(m+1)*(a+b*x^2)^p*ExpandToSum[a*(m+1)*Qx-b*R*(m+2*p+3)*x,x],x]] /;
FreeQ[{a,b,c,d,p},x] && IGtQ[n,1] && ILtQ[m,-1] && GtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d^n*x^(m+n-1)*(a+b*x^2)^(p+1)/(b*(m+n+2*p+1)) + 
  1/(b*(m+n+2*p+1)) \[Star] Int[x^m*(a+b*x^2)^p*
    ExpandToSum[b*(m+n+2*p+1)*(c+d*x)^n-b*d^n*(m+n+2*p+1)*x^n-a*d^n*(m+n-1)*x^(n-2),x],x] /;
FreeQ[{a,b,c,d,m,p},x] && IGtQ[n,1] && IGtQ[m,-2] && GtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c \[Star] Int[x^m*(a+b*x^2)^p,x] + d \[Star] Int[x^(m+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,p},x] && IntegerQ[m] && Not[IntegerQ[2*p]]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Module[{k},
  Int[x^m*Sum[Binomial[n,2*k]*c^(n-2*k)*d^(2*k)*x^(2*k),{k,0,n/2}]*(a+b*x^2)^p,x] + 
  Int[x^(m+1)*Sum[Binomial[n,2*k+1]*c^(n-2*k-1)*d^(2*k+1)*x^(2*k),{k,0,(n-1)/2}]*(a+b*x^2)^p,x]] /;
FreeQ[{a,b,c,d,p},x] && IGtQ[n,1] && IntegerQ[m] && Not[IntegerQ[2*p]] && Not[EqQ[m,1] && EqQ[b*c^2+a*d^2,0]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^m*(a*d-b*c*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) - 
  e*d*m/(2*b*(p+1))*Int[(e*x)^(m-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[Simplify[m+2*p+3],0] && LtQ[p,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -c*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(2*a*e*(p+1)) + 
  d/e \[Star] Int[(e*x)^(m+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[Simplify[m+2*p+3],0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(c*(m+2)+d*(m+1)*x)*(a+b*x^2)^p/(e*(m+1)*(m+2)) - 
  2*b*p/(e^2*(m+1)*(m+2)) \[Star] Int[(e*x)^(m+2)*(a+b*x^2)^(p-1)*(c*(m+2)+d*(m+1)*x),x] /;
FreeQ[{a,b,c,d,e},x] && GtQ[p,0] && LtQ[m,-2] && Not[ILtQ[m+2*p+3,0]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(c*(m+2*p+2)+d*(m+1)*x)*(a+b*x^2)^p/(e*(m+1)*(m+2*p+2)) + 
  2*p/(e*(m+1)*(m+2*p+2)) \[Star] Int[(e*x)^(m+1)*(a*d*(m+1)-b*c*(m+2*p+2)*x)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,e},x] && GtQ[p,0] && LtQ[m,-1] && Not[ILtQ[m+2*p+1,0]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(c*(m+2*p+2)+d*(m+2*p+1)*x)*(a+b*x^2)^p/(e*(m+2*p+1)*(m+2*p+2)) + 
  2*a*p/((m+2*p+1)*(m+2*p+2)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p-1)*(c*(m+2*p+2)+d*(m+2*p+1)*x),x] /;
FreeQ[{a,b,c,d,e,m},x] && GtQ[p,0] && (IntegerQ[p] || Not[RationalQ[m]] || GeQ[m,-1] && LtQ[m,0]) && Not[ILtQ[m+2*p,0]] && 
  (IntegerQ[m] || IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  e*(e*x)^(m-1)*(c+d*x)*(a+b*x^2)^(p+1)/(2*b*(p+1)) - 
  e^2/(2*b*(p+1)) \[Star] Int[(e*x)^(m-2)*(c*(m-1)+d*m*x)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e},x] && LtQ[p,-1] && GtQ[m,1]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^m*(a*d-b*c*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) - 
  e/(2*a*b*(p+1)) \[Star] Int[(e*x)^(m-1)*(a*d*m-b*c*(m+2*p+3)*x)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e},x] && LtQ[p,-1] && LtQ[0,m,1]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(e*x)^(m+1)*(c+d*x)*(a+b*x^2)^(p+1)/(2*a*e*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(e*x)^m*(c*(m+2*p+3)+d*(m+2*p+4)*x)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && LtQ[p,-1] && LtQ[m,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(e*x)^m*(a+b*x^2)^(p+1)/(b*(m+2*p+2)) - 
  e/(b*(m+2*p+2)) \[Star] Int[(e*x)^(m-1)*(a+b*x^2)^p*Simp[a*d*m-b*c*(m+2*p+2)*x,x],x] /;
FreeQ[{a,b,c,d,e,p},x] && GtQ[m,0] && NeQ[m+2*p+2,0] && (IntegerQ[p] || IntegersQ[2*m,2*p])


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*(e*x)^(m+1)*(a+b*x^2)^(p+1)/(a*e*(m+1)) + 
  1/(a*e*(m+1))\[Star]Int[(e*x)^(m+1)*(a+b*x^2)^p*(a*d*(m+1)-b*c*(m+2*p+3)*x),x] /;
FreeQ[{a,b,c,d,e,p},x] && LtQ[m,-1]


(* ::Code:: *)
Int[(c_+d_.*x_)/(Sqrt[e_.*x_]*(a_+b_.*x_^2)),x_Symbol] :=
  2 \[Star] Subst[Int[(e*c+d*x^2)/(a*e^2+b*x^4),x],x,Sqrt[e*x]] /;
FreeQ[{a,b,c,d,e},x]


(* ::Code:: *)
(* Int[(e_.*x_)^m_*(c_+d_.*x_)/(a_+b_.*x_^2),x_Symbol] :=
  c*(e*x)^(m+1)/(a*e*(m+1)) + 
  1/(a*e) \[Star] Int[(e*x)^(m+1)*Simp[a*d-b*c*x,x]/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && FractionQ[m] && LtQ[m,-1] *)


(* ::Code:: *)
Int[(c_+d_.*x_)/(Sqrt[x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  2 \[Star] Subst[Int[(c+d*x^2)/Sqrt[a+b*x^4],x],x,Sqrt[x]] /;
FreeQ[{a,b,c,d},x]


(* ::Code:: *)
Int[(c_+d_.*x_)/(Sqrt[e_*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  Sqrt[x]/Sqrt[e*x] \[Star] Int[(c+d*x)/(Sqrt[x]*Sqrt[a+b*x^2]),x] /;
FreeQ[{a,b,c,d,e},x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c \[Star] Int[(e*x)^m*(a+b*x^2)^p,x] + d/e \[Star] Int[(e*x)^(m+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(c+d*x)^n,a+b*x^2,x],
        f=Coeff[PolynomialRemainder[(c+d*x)^n,a+b*x^2,x],x,0],
        g=Coeff[PolynomialRemainder[(c+d*x)^n,a+b*x^2,x],x,1]},
  -(e*x)^(m+1)*(f+g*x)*(a+b*x^2)^(p+1)/(2*a*e*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^(p+1)*ExpandToSum[2*a*(p+1)*Qx+f*(m+2*p+3)+g*(m+2*p+4)*x,x],x]] /;
FreeQ[{a,b,c,d,e,m},x] && IGtQ[n,1] && Not[IntegerQ[m]] && LtQ[p,-1]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d^n*(e*x)^(m+n-1)*(a+b*x^2)^(p+1)/(b*e^(n-1)*(m+n+2*p+1)) + 
  1/(b*(m+n+2*p+1)) \[Star] Int[(e*x)^m*(a+b*x^2)^p*
    ExpandToSum[b*(m+n+2*p+1)*(c+d*x)^n-b*d^n*(m+n+2*p+1)*x^n-a*d^n*(m+n-1)*x^(n-2),x],x] /;
FreeQ[{a,b,c,d,e,m,p},x] && IGtQ[n,1] && Not[IntegerQ[m]] && NeQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Module[{k},
  Int[(e*x)^m*Sum[Binomial[n,2*k]*c^(n-2*k)*d^(2*k)*x^(2*k),{k,0,n/2}]*(a+b*x^2)^p,x] + 
  1/e \[Star] Int[(e*x)^(m+1)*Sum[Binomial[n,2*k+1]*c^(n-2*k-1)*d^(2*k+1)*x^(2*k),{k,0,(n-1)/2}]*(a+b*x^2)^p,x]] /;
FreeQ[{a,b,c,d,e,p},x] && IGtQ[n,1] && Not[IntegerQ[m]] && EqQ[m+n+2*p+1,0]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{k=Denominator[n]},
  k/d \[Star] Subst[Int[x^(k*(n+1)-1)*(-c/d+x^k/d)^m*Simp[(b*c^2+a*d^2)/d^2-2*b*c*x^k/d^2+b*x^(2*k)/d^2,x]^p,x],x,(c+d*x)^(1/k)]] /;
FreeQ[{a,b,c,d,m,p},x] && FractionQ[n] && IntegerQ[p] && IntegerQ[m]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^(2*n)/a^n \[Star] Int[x^m*(a+b*x^2)^(n+p)/(c-d*x)^n,x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[m,0] && ILtQ[n,0] && IGtQ[n+p+1/2,0]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(-c)^(m-n-2)*d^(2*n-m+3)*Sqrt[a+b*x^2]/(2^(n+1)*b^(n+2)*(c+d*x)) - 
  d^(2*n-m+2)/b^(n+1) \[Star] Int[1/Sqrt[a+b*x^2]*ExpandToSum[(2^(-n-1)*(-c)^(m-n-1)-d^m*x^m*(-c+d*x)^(-n-1))/(c+d*x),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[m,0] && ILtQ[n,0] && EqQ[n+p,-3/2]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(-c)^(m-n-2)*d^(2*n-m+3)*Sqrt[a+b*x^2]/(2^(n+1)*b^(n+2)*(c+d*x)) - 
  d^(2*n+2)/b^(n+1) \[Star] Int[x^m/Sqrt[a+b*x^2]*ExpandToSum[(2^(-n-1)*(-c)^(m-n-1)*d^(-m)*x^(-m)-(-c+d*x)^(-n-1))/(c+d*x),x],x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[m,0] && ILtQ[n,0] && EqQ[n+p,-3/2]


(* ::Code:: *)
Int[x_*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  a*(a+b*x^2)^p/(2*b*c*p) + b/d \[Star] Int[x^2*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  Int[x^m*(a/c+b*x/d)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && GtQ[p,0]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  c*x^m*(a+b*x^2)^(p+1)/(2*a*d*p*(c+d*x)) - 
  m/(2*d*p) \[Star] Int[x^(m-1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[m,1] && LtQ[p,-1] && EqQ[m+2*p+1,0]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  x^(m-1)*(a+b*x^2)^(p+1)/(2*b*p*(c+d*x)) + 
  1/(2*d^2*p) \[Star] Int[x^(m-2)*(a+b*x^2)^p*(c*(m-1)-d*m*x),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[m,1] && LtQ[p,-1]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  -x^(m+1)*(a+b*x^2)^(p+1)/(2*a*p*(c+d*x)) + 
  1/(2*c^2*p) \[Star] Int[x^m*(a+b*x^2)^p*(c*(m+2*p+1)-d*(m+2*p+2)*x),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[m+2*p,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^(2*n)/a^n \[Star] Int[(e*x)^m*(a+b*x^2)^(n+p)/(c-d*x)^n,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[n,-1] && Not[IGtQ[m,0] && ILtQ[m+n,0] && Not[GtQ[p,1]]]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^n*(a+b*x^2)^(p+1)/(2*b*(n+p+1)) + 
  n/(2*d*(n+p+1)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && (LtQ[n,-1] && Not[IGtQ[n+p+1,0]] || LtQ[n,0] && LtQ[p,-1] || EqQ[n+2*p+2,0]) && NeQ[n+p+1,0]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^n*(a+b*x^2)^(p+1)/(b*(n+2*p+2)) + 
  c*n/(d*(n+2*p+2)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && NeQ[n+2*p+2,0]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/(x_*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -2*c \[Star] Subst[Int[1/(a-c*x^2),x],x,Sqrt[a+b*x^2]/Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[(e_.*x_)^n_*(c_+d_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d^2*(e*x)^(n+1)*(c+d*x)^(m-2)*(a+b*x^2)^(p+1)/(b*e*(n+p+2)) + 
  c*(2*n+p+3)/(n+p+2) \[Star] Int[(e*x)^n*(c+d*x)^(m-1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[m+p-1,0] && Not[LtQ[n,-1]] && IntegerQ[2*p]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^(m+1)*(c+d*x)^n*(a+b*x^2)^p/(e*(m+1)) + 
  b*n/(d*e*(m+1)) \[Star] Int[(e*x)^(m+1)*(c+d*x)^(n+1)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,e},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && GtQ[p,0] && LtQ[m,-1] && Not[IntegerQ[m+p] && LeQ[m+p+2,0]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(e*x)^(m+1)*(c+d*x)^n*(a+b*x^2)^p/(e*(n-m-1)) - 
  b*c*n/(d^2*(n-m-1)) \[Star] Int[(e*x)^m*(c+d*x)^(n+1)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && GtQ[p,0] && NeQ[m-n+1,0] && 
  Not[IGtQ[m,0]] && Not[IntegerQ[m+p] && LtQ[m+p+2,0]] && RationalQ[m]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(e*x)^m*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(p+1)) - 
  d*e*m/(b*(p+1)) \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && LtQ[p,-1] && GtQ[m,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -c*(e*x)^(m+1)*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(a*e*(p+1)) + 
  c*(m-n+2)/(a*(p+1)) \[Star] Int[(e*x)^m*(c+d*x)^(n-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d,e,m},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && LtQ[p,-1] && RationalQ[m]


(* ::Code:: *)
(* Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  d*(e*x)^m*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*(m-n+1)) + 
  c*e*m/(d*(m-n+1)) \[Star] Int[(e*x)^(m-1)*(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && GtQ[m,0] && NeQ[m-n+1,0] && (IntegerQ[2*p] || IntegerQ[m]) *)


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(e_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -d^2*(e*x)^(m+1)*(c+d*x)^(n-1)*(a+b*x^2)^(p+1)/(b*c*e*(m+1)) - 
  d*(n-m-2)/(c*e*(m+1)) \[Star] Int[(e*x)^(m+1)*(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p,0] && LtQ[m,-1] && (IntegerQ[2*p] || IntegerQ[m])


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -d^2*(e*x)^(m+1)*(c+d*x)^(n-2)*(a+b*x^2)^(p+1)/(b*e*(m+1)) + 
  d*(2*m+p+3)/(e*(m+1)) \[Star] Int[(e*x)^(m+1)*(c+d*x)^(n-1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c^2+a*d^2,0] && EqQ[n+p-1,0] && LtQ[m,-1] && IntegerQ[p+1/2]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(m+n-1)*(a+b*x^2)^(p+1)/(b*d^(m-1)*(m+n+2*p+1)) + 
  1/(d^m*(m+n+2*p+1)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^p*
    ExpandToSum[(d^m*(m+n+2*p+1)*x^m-(m+n+2*p+1)*(c+d*x)^m+c*(c+d*x)^(m-2)*(c*(m+n-1)+c*(m+n+2*p+1)+2*d*(m+n+p)*x)),x],x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && IGtQ[m,1] && NeQ[m+n+2*p+1,0] && (IntegerQ[2*p] || ILtQ[m+n,0])


(* ::Code:: *)
(* Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[IncrementalExpand[(a+b*x^2)^p,x^m*(c+d*x)^n,x],x] /;
FreeQ[{a,b,c,d,m,n,p},x] && EqQ[b*c^2+a*d^2,0] && IntegerQ[2*p] && IGtQ[m,0] && ILtQ[n,0] *)


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[x^m*(c+d*x)^n*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,d,p},x] && EqQ[b*c^2+a*d^2,0] && IntegerQ[2*p] && IntegerQ[m] && ILtQ[n,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^(2*n)/a^n \[Star] Int[(e*x)^m*(a+b*x^2)^(n+p)/(c-d*x)^n,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && EqQ[b*c^2+a*d^2,0] && ILtQ[n,0] (* && Not[IGtQ[m,0] && ILtQ[m+n,0] && Not[GtQ[p,1]]] *)


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[(e*x)^m*(c+d*x)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,e,m,n},x] && EqQ[b*c^2+a*d^2,0] && GtQ[a,0] && GtQ[c,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^p*c^IntPart[n]*(c+d*x)^FracPart[n]/(1+d*x/c)^FracPart[n] \[Star] Int[(e*x)^m*(1-d*x/c)^p*(1+d*x/c)^(n+p),x] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && EqQ[b*c^2+a*d^2,0] && GtQ[a,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a+b*x^2)^FracPart[p]/((c+d*x)^FracPart[p]*(a/c+(b*x)/d)^FracPart[p]) \[Star] Int[(e*x)^m*(c+d*x)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && EqQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_./((c_+d_.*x_)*(a_+b_.*x_^2)),x_Symbol] :=
  -c*d/(b*c^2+a*d^2) \[Star] Int[1/(c+d*x),x] + 1/(b*c^2+a*d^2) \[Star] Int[(a*d+b*c*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/(2*(p+1)*(b*c^2+a*d^2)) + 
  a*d/(b*c^2+a*d^2) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[Simplify[n+2*p+3],0] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c+d*x)^(n+1)*(a+b*x^2)^p*(c*(a*d^2+b*c^2*(2*p+1))-d*(a*d^2*(n+1)+b*c^2*(n-2*p+1))*x)/
    (d^2*(n+1)*(n+2)*(b*c^2+a*d^2)) + 
  b*p/(d^2*(n+1)*(n+2)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^(n+2)*(a+b*x^2)^(p-1)*
    Simp[2*a*c*d*(n+2)-(2*a*d^2*(n+1)-2*b*c^2*(2*p+1))*x,x],x] /;
FreeQ[{a,b,c,d},x] && GtQ[p,0] && LtQ[n,-2] && LtQ[n+2*p,0] && Not[ILtQ[n+2*p+3,0]]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c+d*x)^(n+1)*(a+b*x^2)^p*(c*(2*p+1)-d*(n+1)*x)/(d^2*(n+1)*(n+2*p+2)) + 
  2*p/(d^2*(n+1)*(n+2*p+2)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^(p-1)*(a*d*(n+1)+b*c*(2*p+1)*x),x] /;
FreeQ[{a,b,c,d},x] && GtQ[p,0] && LtQ[n,-1] && Not[ILtQ[n+2*p+1,0]]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c+d*x)^(n+1)*(a+b*x^2)^p*(c*(2*p+1)-d*(n+2*p+1)*x)/(d^2*(n+2*p+1)*(n+2*p+2)) + 
  2*p/(d^2*(n+2*p+1)*(n+2*p+2)) \[Star] 
    Int[(c+d*x)^n*(a+b*x^2)^(p-1)*Simp[a*c*d*n+(b*c^2*(2*p+1)+a*d^2*(n+2*p+1))*x,x],x] /;
FreeQ[{a,b,c,d,n},x] && GtQ[p,0] && LeQ[-1,n,0] && Not[ILtQ[n+2*p,0]]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^n*(a+b*x^2)^(p+1)/(2*b*(p+1)) - d*n/(2*b*(p+1)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,d},x] && LtQ[p,-1] && GtQ[n,0] && (IntegerQ[n] || IntegerQ[p] || IntegersQ[2*n,2*p])


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(n+1)*(c-d*x)*(a+b*x^2)^(p+1)/(2*(p+1)*(b*c^2+a*d^2)) - 
  d/(2*(p+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^(p+1)*(c*n-d*(n+2*p+4)*x),x] /;
FreeQ[{a,b,c,d,n},x] && LtQ[p,-1] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -c*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/((n+1)*(b*c^2+a*d^2)) + 
  1/((n+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^p*(a*d*(n+1)+b*c*(n+2*p+3)*x),x] /;
FreeQ[{a,b,c,d,p},x] && LtQ[n,-1] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  (c+d*x)^n/(b*n) - 1/b \[Star] Int[(c+d*x)^(n-1)*(a*d-b*c*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d},x] && GtQ[n,0]


(* ::Code:: *)
Int[x_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^n*(a+b*x^2)^(p+1)/(b*(n+2*p+2)) - 
  n/(b*(n+2*p+2)) \[Star] Int[(c+d*x)^(n-1)*(a+b*x^2)^p*(a*d-b*c*x),x] /;
FreeQ[{a,b,c,d,p},x] && GtQ[n,0] && NeQ[n+2*p+2,0]


(* ::Code:: *)
Int[x_/((c_+d_.*x_)*(a_+b_.*x_^2)^(3/4)),x_Symbol] :=
  With[{q=Rt[-a,4]},
  c/(2*d^2*q^3)*ArcTan[c*q*(a+b*x^2)^(1/4)/(q^2*(c+d*x)-c*Sqrt[a+b*x^2])] + 
  c/(2*d^2*q^3)*ArcTanh[c*q*(a+b*x^2)^(1/4)/(q^2*(c+d*x)+c*Sqrt[a+b*x^2])]] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+2*a*d^2,0] && NegQ[a]


(* ::Code:: *)
Int[x_/((c_+d_.*x_)*(a_+b_.*x_^2)^(3/4)),x_Symbol] :=
  (-a-b*x^2)^(3/4)/(a+b*x^2)^(3/4) \[Star] Int[x/((c+d*x)*(-a-b*x^2)^(3/4)),x] /;
FreeQ[{a,b,c,d},x] && EqQ[b*c^2+2*a*d^2,0] && PosQ[a]


(* ::Code:: *)
Int[(A_.+B_.*x_)/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -2/d^2 \[Star] Subst[Int[(B*c-A*d-B*x^2)/Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2],x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d,A,B},x] && PosQ[b/a]


(* ::Code:: *)
Int[(A_.+B_.*x_)/(Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  B/d \[Star] Int[Sqrt[c+d*x]/Sqrt[a+b*x^2],x] - (B*c-A*d)/d \[Star] Int[1/(Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] /;
FreeQ[{a,b,c,d,A,B},x] && NegQ[b/a]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m*(c+d*x)^n,a+b*x^2,x],
        e=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,0],
        f=Coeff[PolynomialRemainder[x^m*(c+d*x)^n,a+b*x^2,x],x,1]},
  (a*f-b*e*x)*(a+b*x^2)^(p+1)/(2*a*b*(p+1)) + 
  1/(2*a*(p+1)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^(p+1)*ExpandToSum[2*a*(p+1)*(c+d*x)^(-n)*Qx+e*(2*p+3)*(c+d*x)^(-n),x],x]] /;
FreeQ[{a,b,c,d},x] && IGtQ[m,1] && LtQ[p,-1] && ILtQ[n,0] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m,a+b*x^2,x],
        e=Coeff[PolynomialRemainder[x^m,a+b*x^2,x],x,0],
        f=Coeff[PolynomialRemainder[x^m,a+b*x^2,x],x,1]},
  -(c+d*x)^(n+1)*(a+b*x^2)^(p+1)*(a*(d*e-c*f)+(b*c*e+a*d*f)*x)/(2*a*(p+1)*(b*c^2+a*d^2)) + 
  1/(2*a*(p+1)*(b*c^2+a*d^2)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^(p+1)*
    ExpandToSum[2*a*(p+1)*(b*c^2+a*d^2)*Qx+e*(b*c^2*(2*p+3)+a*d^2*(n+2*p+3))-a*c*d*f*n+d*(b*c*e+a*d*f)*(n+2*p+4)*x,x],x]] /;
FreeQ[{a,b,c,d,n},x] && IGtQ[m,1] && LtQ[p,-1] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[x^m,c+d*x,x], R=PolynomialRemainder[x^m,c+d*x,x]},
  d*R*(c+d*x)^(n+1)*(a+b*x^2)^(p+1)/((n+1)*(b*c^2+a*d^2)) + 
  1/((n+1)*(b*c^2+a*d^2)) \[Star] 
    Int[(c+d*x)^(n+1)*(a+b*x^2)^p*ExpandToSum[(n+1)*(b*c^2+a*d^2)*Qx+b*c*R*(n+1)-b*d*R*(n+2*p+3)*x,x],x]] /;
FreeQ[{a,b,c,d,p},x] && IGtQ[m,1] && LtQ[n,-1] && NeQ[b*c^2+a*d^2,0]


(* ::Code:: *)
Int[x_^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c+d*x)^(m+n-1)*(a+b*x^2)^(p+1)/(b*d^(m-1)*(m+n+2*p+1)) + 
  1/(b*d^m*(m+n+2*p+1)) \[Star] Int[(c+d*x)^n*(a+b*x^2)^p*
    ExpandToSum[(b*d^m*(m+n+2*p+1)*x^m-b*(m+n+2*p+1)*(c+d*x)^m-(c+d*x)^(m-2)*(a*d^2*(m+n-1)-b*c^2*(m+n+2*p+1)-2*b*c*d*(m+n+p)*x)),x],x] /;
FreeQ[{a,b,c,d,n,p},x] && IGtQ[m,1] && NeQ[m+n+2*p+1,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  1/d \[Star] Int[x^(m-1)*(a+b*x^2)^p,x] - c/d \[Star] Int[x^(m-1)*(a+b*x^2)^p/(c+d*x),x] /;
FreeQ[{a,b,c,d,p},x] && IGtQ[m,0] && LtQ[-1,p,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_/x_,x_Symbol] :=
  a/c \[Star] Int[(c+d*x)^(n+1)*(a+b*x^2)^(p-1)/x,x] - 
  1/c \[Star] Int[(c+d*x)^n*(a*d-b*c*x)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,d},x] && GtQ[p,0] && ILtQ[n,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  e*d/b \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n-2)*(2*c+d*x),x] - 
  e/b \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n-2)*Simp[2*a*c*d-(b*c^2-a*d^2)*x,x]/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && GtQ[n,1] && GtQ[m,0] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  e^2/b \[Star] Int[(e*x)^(m-2)*(c+d*x)^n,x] - a*e^2/b \[Star] Int[(e*x)^(m-2)*(c+d*x)^n/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && LtQ[0,n,1] && GtQ[m,1] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  d*e/b \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n-1),x] - 
  e/b \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n-1)*(a*d-b*c*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && LtQ[0,n,1] && LtQ[0,m,1] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  e^(m+1/2) \[Star] Int[ExpandIntegrand[1/(Sqrt[e*x]*Sqrt[c+d*x]),x^(m+1/2)*(c+d*x)^(n+1/2)/(a+b*x^2),x],x] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[n+1/2,0] && ILtQ[m-1/2,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  c/a \[Star] Int[(e*x)^m*(c+d*x)^(n-1),x] + 
  1/(a*e) \[Star] Int[((e*x)^(m+1)*(c+d*x)^(n-1)*(a*d-b*c*x))/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && GtQ[n,0] && LtQ[m,-1] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/(a_+b_.*x_^2),x_Symbol] :=
  -e*c*d/(b*c^2+a*d^2) \[Star] Int[(e*x)^(m-1)*(c+d*x)^n,x] + 
  e/(b*c^2+a*d^2) \[Star] Int[(e*x)^(m-1)*(c+d*x)^(n+1)*(a*d+b*c*x)/(a+b*x^2),x] /;
FreeQ[{a,b,c,d,e},x] && LtQ[n,-1] && GtQ[m,0] && Not[IntegerQ[m]] && Not[IntegerQ[n]]


(* ::Code:: *)
Int[Sqrt[e_.*x_]/(Sqrt[c_+d_.*x_]*(a_+b_.*x_^2)),x_Symbol] :=
  e/(2*b) \[Star] Int[1/(Sqrt[e*x]*Sqrt[c+d*x]*(Rt[-a/b,2]+x)),x] - 
  e/(2*b) \[Star] Int[1/(Sqrt[e*x]*Sqrt[c+d*x]*(Rt[-a/b,2]-x)),x] /;
FreeQ[{a,b,c,d,e},x]


(* ::Code:: *)
Int[(e_.*x_)^m_/(Sqrt[c_+d_.*x_]*(a_+b_.*x_^2)),x_Symbol] :=
  e^(m+1/2) \[Star] Int[ExpandIntegrand[1/(Sqrt[e*x]*Sqrt[c+d*x]),x^(m+1/2)/(a+b*x^2),x],x] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[m-1/2,0]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(e*x)^m*(c+d*x)^n*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,d,e,m,n},x] && ILtQ[p,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{k=Denominator[m]},
  k/e \[Star] Subst[Int[x^(k*(m+1)-1)*(c+d*x^k/e)^n*(a+b*x^(2*k)/e^2)^p,x],x,(e*x)^(1/k)]] /;
FreeQ[{a,b,c,d,e,p},x] && ILtQ[n,0] && FractionQ[m]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x^2)^p,x^m*(c+d*x)^n,x],x] /;
FreeQ[{a,b,c,d,p},x] && ILtQ[n,0] && IntegerQ[m] && IntegerQ[2*p]


(* ::Code:: *)
Int[Sqrt[e_.*x_]/((c_+d_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  e/d \[Star] Int[1/(Sqrt[e*x]*Sqrt[a+b*x^2]),x] - 
  c*e/d \[Star] Int[1/(Sqrt[e*x]*(c+d*x)*Sqrt[a+b*x^2]),x] /;
FreeQ[{a,b,c,d,e},x]


(* ::Code:: *)
Int[1/(Sqrt[e_.*x_]*(c_+d_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  1/Sqrt[a] \[Star] Int[1/(Sqrt[e*x]*(c+d*x)*Sqrt[1-Rt[-b/a,2]*x]*Sqrt[1+Rt[-b/a,2]*x]),x] /;
FreeQ[{a,b,c,d,e},x] && GtQ[a,0]


(* ::Code:: *)
Int[1/(Sqrt[e_.*x_]*(c_+d_.*x_)*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[1/(Sqrt[e*x]*(c+d*x)*Sqrt[1+b*x^2/a]),x] /;
FreeQ[{a,b,c,d,e},x] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_/(c_+d_.*x_),x_Symbol] :=
  c \[Star] Int[x^m*(a+b*x^2)^p/(c^2-d^2*x^2),x] - d \[Star] Int[x^(m+1)*(a+b*x^2)^p/(c^2-d^2*x^2),x] /;
FreeQ[{a,b,c,d,m,p},x]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[x^m*(a+b*x^2)^p,(c/(c^2-d^2*x^2)-d*x/(c^2-d^2*x^2))^(-n),x],x] /;
FreeQ[{a,b,c,d,m,p},x] && ILtQ[n,-1]


(* ::Code:: *)
Int[(e_*x_)^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (e*x)^m/x^m \[Star] Int[x^m*(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,p},x] && ILtQ[n,0]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  1/d \[Star] Int[x^(m-1)*(c+d*x)^(n+1)*(a+b*x^2)^p,x] - c/d \[Star] Int[x^(m-1)*(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && IGtQ[m,0]


(* ::Code:: *)
Int[Sqrt[a_+b_.*x_^2]/(x_*Sqrt[c_+d_.*x_]),x_Symbol] :=
  -2 \[Star] Subst[Int[Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2]/(c-x^2),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && PosQ[b/a]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*Sqrt[a_+b_.*x_^2]/x_,x_Symbol] :=
  a*c^(n+1/2) \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] + 
  Int[1/(Sqrt[c+d*x]*Sqrt[a+b*x^2])*ExpandToSum[(-a*c^(n+1/2)+a*(c+d*x)^(n+1/2)+b*x^2*(c+d*x)^(n+1/2))/x,x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n+3/2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_*Sqrt[a_+b_.*x_^2]/x_,x_Symbol] :=
  a*c^(n+1/2) \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] + 
  Int[(c+d*x)^n/Sqrt[a+b*x^2]*ExpandToSum[(a+b*x^2-a*c^(n+1/2)*(c+d*x)^(-n-1/2))/x,x],x] /;
FreeQ[{a,b,c,d},x] && ILtQ[n+1/2,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_*Sqrt[a_+b_.*x_^2],x_Symbol] :=
  c^(n-1/2)*(e*x)^(m+1)*Sqrt[c+d*x]*Sqrt[a+b*x^2]/(e*(m+1)) - 
  1/(2*e*(m+1)) \[Star] Int[(e*x)^(m+1)/(Sqrt[c+d*x]*Sqrt[a+b*x^2])*
    ExpandToSum[(2*a*c^(n+1/2)*(m+1)+a*c^(n-1/2)*d*(2*m+3)*x+2*b*c^(n+1/2)*(m+2)*x^2+b*c^(n-1/2)*d*(2*m+5)*x^3-
      2*a*(m+1)*(c+d*x)^(n+1/2)-2*b*(m+1)*x^2*(c+d*x)^(n+1/2))/x,x],x] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[n+3/2,0] && LtQ[m,-1] && IntegerQ[2*m]


(* ::Code:: *)
Int[(e_.*x_)^m_.*Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2],x_Symbol] :=
  2*(e*x)^(m+1)*Sqrt[c+d*x]*Sqrt[a+b*x^2]/(e*(2*m+5)) + 
  1/(2*m+5) \[Star] Int[(e*x)^m*(3*a*c+2*a*d*x+b*c*x^2)/(Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] /;
FreeQ[{a,b,c,d,e,m},x] && Not[LtQ[m,-1]] && IntegerQ[2*m]


(* ::Code:: *)
Int[Sqrt[c_+d_.*x_]/(x_*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -2 \[Star] Subst[Int[x^2/((c-x^2)*Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2]),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && PosQ[b/a]


(* ::Code:: *)
Int[1/(x_*Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  -2 \[Star] Subst[Int[1/((c-x^2)*Sqrt[(b*c^2+a*d^2)/d^2-2*b*c*x^2/d^2+b*x^4/d^2]),x],x,Sqrt[c+d*x]] /;
FreeQ[{a,b,c,d},x] && PosQ[b/a]


(* ::Code:: *)
Int[1/(x_*Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  With[{q=Rt[-b/a,2]},
  1/Sqrt[a] \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[1-q*x]*Sqrt[1+q*x]),x]] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && GtQ[a,0]


(* ::Code:: *)
Int[1/(x_*Sqrt[c_+d_.*x_]*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[1+b*x^2/a]),x] /;
FreeQ[{a,b,c,d},x] && NegQ[b/a] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(x_*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  c^(n+1/2) \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] - 
  Int[1/(Sqrt[c+d*x]*Sqrt[a+b*x^2])*ExpandToSum[(c^(n+1/2)-(c+d*x)^(n+1/2))/x,x],x] /;
FreeQ[{a,b,c,d},x] && IGtQ[n-1/2,0]


(* ::Code:: *)
Int[(c_+d_.*x_)^n_/(x_*Sqrt[a_+b_.*x_^2]),x_Symbol] :=
  c^(n+1/2) \[Star] Int[1/(x*Sqrt[c+d*x]*Sqrt[a+b*x^2]),x] + 
  Int[(c+d*x)^n/Sqrt[a+b*x^2]*ExpandToSum[(1-c^(n+1/2)*(c+d*x)^(-n-1/2))/x,x],x] /;
FreeQ[{a,b,c,d},x] && ILtQ[n+1/2,0]


(* ::Code:: *)
Int[(e_.*x_)^m_*(c_+d_.*x_)^n_/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  c^(n-1/2)*(e*x)^(m+1)*Sqrt[c+d*x]*Sqrt[a+b*x^2]/(a*e*(m+1)) - 
  1/(2*a*e*(m+1)) \[Star] Int[(e*x)^(m+1)/(Sqrt[c+d*x]*Sqrt[a+b*x^2])*
     ExpandToSum[(2*a*c^(n+1/2)*(m+1)+a*c^(n-1/2)*d*(2*m+3)*x+2*b*c^(n+1/2)*(m+2)*x^2+b*c^(n-1/2)*d*(2*m+5)*x^3-2*a*(m+1)*(c+d*x)^(n+1/2))/x,x],x] /;
FreeQ[{a,b,c,d,e},x] && IGtQ[n+3/2,0] && LtQ[m,-1] && IntegerQ[2*m]


(* ::Code:: *)
Int[x_^m_.*(c_+d_.*x_)^n_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x^2)^p/Sqrt[c+d*x],x^m*(c+d*x)^(n+1/2),x],x] /;
FreeQ[{a,b,c,d,m},x] && IntegerQ[p+1/2] && IntegerQ[n+1/2] && IntegerQ[m]


(* ::Code:: *)
Int[(e_.*x_)^m_.*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Unintegrable[(e*x)^m*(c+d*x)^n*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,d,e,m,n,p},x]


(* ::Code:: *)
(* Int[(g_.*x_)^n_*(d_+e_.*x_)^m_.*(a_+c_.*x_^2)^p_,x_Symbol] :=
  With[{Qx=PolynomialQuotient[(d+e*x)^m,g*x,x], R=PolynomialRemainder[(d+e*x)^m,g*x,x]},
  R*(g*x)^(n+1)*(a+c*x^2)^(p+1)/(a*g*(n+1)) + 
  1/(a*g*(n+1)) \[Star] Int[(g*x)^(n+1)*(a+c*x^2)^p*ExpandToSum[a*g*(n+1)*Qx-c*R*(n+2*p+3)*x,x],x]] /;
FreeQ[{a,c,d,e,g,p},x] && IGtQ[m,0] && LtQ[n,-1] && (IntegerQ[2*p] || NeQ[m,1]) *)


(* ::Code:: *)
(* Int[(g_.*x_)^n_.*(a_+c_.*x_^2)^p_./(d_+e_.*x_),x_Symbol] :=
  a/d \[Star] Int[(g*x)^n*(a+c*x^2)^(p-1),x] + c/(e*g) \[Star] Int[(g*x)^(n+1)*(a+c*x^2)^(p-1),x] /;
FreeQ[{a,c,d,e,g,n,p},x] && EqQ[c*d^2+a*e^2,0] && Not[GtQ[p,0] && IGtQ[n,0]] *)


(* ::Code:: *)
(* Int[x_^2*(f_+g_.*x_)*(a_+c_.*x_^2)^p_,x_Symbol] :=
  f*(f+g*x)*(a+c*x^2)^(p+1)/(2*c*g*(p+1)) - 1/(2*c*(p+1)) \[Star] Int[(f-2*g*(p+1)*x)*(a+c*x^2)^(p+1),x] /;
FreeQ[{a,c,f,g},x] && EqQ[c*f^2+a*g^2,0] && LtQ[p,-1] *)


(* ::Code:: *)
(* Int[x_^2*(f_+g_.*x_)/Sqrt[a_+c_.*x_^2],x_Symbol] :=
  g*(a+c*x^2)^(3/2)/(3*c^2) + f/g \[Star] Int[(x*(f+g*x))/Sqrt[a+c*x^2],x] /;
FreeQ[{a,c,f,g},x] && EqQ[c*f^2+a*g^2,0] *)


(* ::Code:: *)
(* Int[x_^2*(f_+g_.*x_)*(a_+c_.*x_^2)^p_.,x_Symbol] :=
  g*x^2*(a+c*x^2)^(p+1)/(2*c*(p+2)) - 1/(c*(p+2)) \[Star] Int[x*(a*g-c*f*(p+2)*x)*(a+c*x^2)^p,x] /;
FreeQ[{a,c,f,g,p},x] && EqQ[c*f^2+a*g^2,0] *)



