(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[x_/(a_+b_.*x_^2),x_Symbol] :=
  Log[RemoveContent[a+b*x^2,x]]/(2*b) /;
FreeQ[{a,b},x]


(* ::Code:: *)
Int[x_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a+b*x^2)^(p+1)/(2*b*(p+1)) /;
FreeQ[{a,b,p},x] && NeQ[p,-1]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^(p+1)/(a*c*(m+1)) /;
FreeQ[{a,b,c,m,p},x] && EqQ[m+2*p+3,0] && NeQ[m,-1]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  1/2 \[Star] Subst[Int[x^((m-1)/2)*(a+b*x)^p,x],x,x^2] /;
FreeQ[{a,b,m,p},x] && IntegerQ[(m-1)/2]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[(c*x)^m*(a+b*x^2)^p,x],x] /;
FreeQ[{a,b,c,m},x] && IGtQ[p,0]


(* ::Code:: *)
Int[x_^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  x^(m+1)*(a+b*x^2)^(p+1)/(a*(m+1)) - 
  b*(m+2*(p+1)+1)/(a*(m+1)) \[Star] Int[x^(m+2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,m,p},x] && ILtQ[Simplify[(m+1)/2+p+1],0] && NeQ[m,-1]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c*x)^(m+1)*(a+b*x^2)^(p+1)/(a*c*2*(p+1)) +
  (m+2*p+3)/(a*2*(p+1)) \[Star] Int[(c*x)^m*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,m,p},x] && ILtQ[Simplify[(m+1)/2+p+1],0] && NeQ[p,-1]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^p/(c*(m+1)) - 
  2*b*p/(c^2*(m+1)) \[Star] Int[(c*x)^(m+2)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c},x] && GtQ[p,0] && LtQ[m,-1] && Not[ILtQ[(m+2*p+3)/2,0]] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^p/(c*(m+2*p+1)) +
  2*a*p/(m+2*p+1) \[Star] Int[(c*x)^m*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,m},x] && GtQ[p,0] && NeQ[m+2*p+1,0] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[Sqrt[c_.*x_]/(a_+b_.*x_^2)^(5/4),x_Symbol] :=
  Sqrt[c*x]*(1+a/(b*x^2))^(1/4)/(b*(a+b*x^2)^(1/4)) \[Star] Int[1/(x^2*(1+a/(b*x^2))^(5/4)),x] /;
FreeQ[{a,b,c},x] && PosQ[b/a]


(* ::Code:: *)
Int[(c_.*x_)^m_/(a_+b_.*x_^2)^(5/4),x_Symbol] :=
  2*c*(c*x)^(m-1)/(b*(2*m-3)*(a+b*x^2)^(1/4)) - 2*a*c^2*(m-1)/(b*(2*m-3)) \[Star] Int[(c*x)^(m-2)/(a+b*x^2)^(5/4),x] /;
FreeQ[{a,b,c},x] && PosQ[b/a] && IntegerQ[2*m] && GtQ[m,3/2] 


(* ::Code:: *)
Int[(c_.*x_)^m_/(a_+b_.*x_^2)^(5/4),x_Symbol] :=
  (c*x)^(m+1)/(a*c*(m+1)*(a+b*x^2)^(1/4)) - b*(2*m+1)/(2*a*c^2*(m+1)) \[Star] Int[(c*x)^(m+2)/(a+b*x^2)^(5/4),x] /;
FreeQ[{a,b,c},x] && PosQ[b/a] && IntegerQ[2*m] && LtQ[m,-1]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*(c*x)^(m-1)*(a+b*x^2)^(p+1)/(2*b*(p+1)) -
  c^2*(m-1)/(2*b*(p+1)) \[Star] Int[(c*x)^(m-2)*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c},x] && LtQ[p,-1] && GtQ[m,1] && Not[ILtQ[(m+2*p+3)/2,0]] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c*x)^(m+1)*(a+b*x^2)^(p+1)/(2*a*c*(p+1)) +
  (m+2*p+3)/(2*a*(p+1)) \[Star] Int[(c*x)^m*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,m},x] && LtQ[p,-1] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[x_^m_/(a_+b_.*x_^2),x_Symbol] :=
  Int[PolynomialDivide[x^m,(a+b*x^2),x],x] /;
FreeQ[{a,b},x] && IGtQ[m,3]


(* ::Code:: *)
Int[Sqrt[c_*x_]/(a_+b_.*x_^2)^(1/4),x_Symbol] :=
  x*Sqrt[c*x]/(a+b*x^2)^(1/4) - a/2 \[Star] Int[Sqrt[c*x]/(a+b*x^2)^(5/4),x] /;
FreeQ[{a,b,c},x] && PosQ[b/a]


(* ::Code:: *)
Int[Sqrt[c_*x_]/(a_+b_.*x_^2)^(1/4),x_Symbol] :=
  c*(a+b*x^2)^(3/4)/(b*Sqrt[c*x]) + a*c^2/(2*b) \[Star] Int[1/((c*x)^(3/2)*(a+b*x^2)^(1/4)),x] /;
FreeQ[{a,b,c},x] && NegQ[b/a]


(* ::Code:: *)
Int[1/((c_.*x_)^(3/2)*(a_+b_.*x_^2)^(1/4)),x_Symbol] :=
  -2/(c*Sqrt[c*x]*(a+b*x^2)^(1/4)) - b/c^2 \[Star] Int[Sqrt[c*x]/(a+b*x^2)^(5/4),x] /;
FreeQ[{a,b,c},x] && PosQ[b/a]


(* ::Code:: *)
Int[1/((c_.*x_)^(3/2)*(a_+b_.*x_^2)^(1/4)),x_Symbol] :=
  Sqrt[c*x]*(1+a/(b*x^2))^(1/4)/(c^2*(a+b*x^2)^(1/4)) \[Star] Int[1/(x^2*(1+a/(b*x^2))^(1/4)),x] /;
FreeQ[{a,b,c},x] && NegQ[b/a]


(* ::Code:: *)
Int[Sqrt[x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  -2/(Sqrt[a]*(-b/a)^(3/4)) \[Star] Subst[Int[Sqrt[1-2*x^2]/Sqrt[1-x^2],x],x,Sqrt[1-Sqrt[-b/a]*x]/Sqrt[2]] /;
FreeQ[{a,b},x] && GtQ[-b/a,0] && GtQ[a,0]


(* ::Code:: *)
Int[Sqrt[x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  Sqrt[1+b*x^2/a]/Sqrt[a+b*x^2] \[Star] Int[Sqrt[x]/Sqrt[1+b*x^2/a],x] /;
FreeQ[{a,b},x] && GtQ[-b/a,0] && Not[GtQ[a,0]]


(* ::Code:: *)
Int[Sqrt[c_*x_]/Sqrt[a_+b_.*x_^2],x_Symbol] :=
  Sqrt[c*x]/Sqrt[x] \[Star] Int[Sqrt[x]/Sqrt[a+b*x^2],x] /;
FreeQ[{a,b,c},x] && GtQ[-b/a,0]


(* ::Code:: *)
Int[(c_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*(c*x)^(m-1)*(a+b*x^2)^(p+1)/(b*(m+2*p+1)) -
  a*c^2*(m-1)/(b*(m+2*p+1)) \[Star] Int[(c*x)^(m-2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,p},x] && GtQ[m,2-1] && NeQ[m+2*p+1,0] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[(c_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c*(c*x)^(m-1)*(a+b*x^2)^(p+1)/(b*(m+2*p+1)) -
  a*c^2*(m-1)/(b*(m+2*p+1)) \[Star] Int[(c*x)^(m-2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,m,p},x] && SumSimplerQ[m,-2] && NeQ[m+2*p+1,0] && ILtQ[Simplify[(m+1)/2+p],0]


(* ::Code:: *)
Int[(c_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^(p+1)/(a*c*(m+1)) -
  b*(m+2*p+3)/(a*c^2*(m+1)) \[Star] Int[(c*x)^(m+2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,p},x] && LtQ[m,-1] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[(c_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^(p+1)/(a*c*(m+1)) -
  b*(m+2*p+3)/(a*c^2*(m+1)) \[Star] Int[(c*x)^(m+2)*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,m,p},x] && SumSimplerQ[m,2] && ILtQ[Simplify[(m+1)/2+p],0]


(* ::Code:: *)
Int[(c_.*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{k=Denominator[m]},
  k/c \[Star] Subst[Int[x^(k*(m+1)-1)*(a+b*x^(2*k)/c^2)^p,x],x,(c*x)^(1/k)]] /;
FreeQ[{a,b,c,p},x] && FractionQ[m] && IntBinomialQ[a,b,c,2,m,p,x]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^(p+(m+1)/2) \[Star] Subst[Int[x^m/(1-b*x^2)^(p+(m+1)/2+1),x],x,x/(a+b*x^2)^(1/2)] /;
FreeQ[{a,b},x] && LtQ[-1,p,0] && NeQ[p,-1/2] && IntegersQ[m,p+(m+1)/2]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (a/(a+b*x^2))^(p+(m+1)/2)*(a+b*x^2)^(p+(m+1)/2) \[Star] Subst[Int[x^m/(1-b*x^2)^(p+(m+1)/2+1),x],x,x/(a+b*x^2)^(1/2)] /;
FreeQ[{a,b},x] && LtQ[-1,p,0] && NeQ[p,-1/2] && IntegerQ[m] && LtQ[Denominator[p+(m+1)/2],Denominator[p]]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  x^(m+1)*(a+b*x^2)^p/(m+1) - 
  2*b*p/(m+1) \[Star] Int[x^(m+2)*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,m},x] && EqQ[(m+1)/2+p,0] && GtQ[p,0]


(* ::Code:: *)
Int[(c_*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^IntPart[m]*(c*x)^FracPart[m]/x^FracPart[m] \[Star] Int[x^m*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,m},x] && EqQ[(m+1)/2+p,0] && GtQ[p,0]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  (c*x)^(m+1)*(a+b*x^2)^p/(c*(m+2*p+1)) +
  2*a*p/(m+2*p+1) \[Star] Int[(c*x)^m*(a+b*x^2)^(p-1),x] /;
FreeQ[{a,b,c,m},x] && IntegerQ[p+Simplify[(m+1)/2]] && GtQ[p,0] && NeQ[m+2*p+1,0]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  With[{k=Denominator[p]},
  k*a^(p+Simplify[(m+1)/2])/2 \[Star] 
    Subst[Int[x^(k*Simplify[(m+1)/2]-1)/(1-b*x^k)^(p+Simplify[(m+1)/2]+1),x],x,x^(2/k)/(a+b*x^2)^(1/k)]] /;
FreeQ[{a,b,m},x] && IntegerQ[p+Simplify[(m+1)/2]] && LtQ[-1,p,0]


(* ::Code:: *)
Int[(c_*x_)^m_*(a_+b_.*x_^2)^p_,x_Symbol] :=
  c^IntPart[m]*(c*x)^FracPart[m]/x^FracPart[m] \[Star] Int[x^m*(a+b*x^2)^p,x] /;
FreeQ[{a,b,c,m},x] && IntegerQ[p+Simplify[(m+1)/2]] && LtQ[-1,p,0]


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  -(c*x)^(m+1)*(a+b*x^2)^(p+1)/(a*c*2*(p+1)) +
  (m+2*(p+1)+1)/(a*2*(p+1)) \[Star] Int[(c*x)^m*(a+b*x^2)^(p+1),x] /;
FreeQ[{a,b,c,m},x] && IntegerQ[p+Simplify[(m+1)/2]] && LtQ[p,-1]


(* ::Code:: *)
Int[x_^m_./(a_+b_.*x_^2),x_Symbol] :=
  x^(m-1)/(b*(m-1)) -
  a/b \[Star] Int[x^(m-2)/(a+b*x^2),x] /;
FreeQ[{a,b,m},x] && FractionQ[(m+1)/2] && SumSimplerQ[m,-2]


(* ::Code:: *)
Int[x_^m_/(a_+b_.*x_^2),x_Symbol] :=
  x^(m+1)/(a*(m+1)) -
  b/a \[Star] Int[x^Simplify[m+2]/(a+b*x^2),x] /;
FreeQ[{a,b,m},x] && FractionQ[(m+1)/2] && SumSimplerQ[m,2]


(* ::Code:: *)
Int[(c_*x_)^m_/(a_+b_.*x_^2),x_Symbol] :=
  c^IntPart[m]*(c*x)^FracPart[m]/x^FracPart[m] \[Star] Int[x^m/(a+b*x^2),x] /;
FreeQ[{a,b,c,m},x] && FractionQ[(m+1)/2] && (SumSimplerQ[m,2] || SumSimplerQ[m,-2])


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^p*(c*x)^(m+1)/(c*(m+1))*Hypergeometric2F1[-p,(m+1)/2,(m+1)/2+1,-b*x^2/a] /;
FreeQ[{a,b,c,m,p},x] && Not[IGtQ[p,0]] && (ILtQ[p,0] || GtQ[a,0])


(* ::Code:: *)
Int[(c_.*x_)^m_.*(a_+b_.*x_^2)^p_,x_Symbol] :=
  a^IntPart[p]*(a+b*x^2)^FracPart[p]/(1+b*x^2/a)^FracPart[p] \[Star] Int[(c*x)^m*(1+b*x^2/a)^p,x] /;
FreeQ[{a,b,c,m,p},x] && Not[IGtQ[p,0]] && Not[ILtQ[p,0] || GtQ[a,0]]



