
(* ::Subsection::Closed:: *)
(* 5.5.1 u (a+b arcsec(c x))^n *)
Int[ArcSec[c_.*x_], x_Symbol] := x*ArcSec[c*x] - 1/c*Int[1/(x*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[c, x]
Int[ArcCsc[c_.*x_], x_Symbol] := x*ArcCsc[c*x] + 1/c*Int[1/(x*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[c, x]
Int[(a_. + b_.*ArcSec[c_.*x_])^n_, x_Symbol] := 1/c*Subst[Int[(a + b*x)^n*Sec[x]*Tan[x], x], x, ArcSec[c*x]] /; FreeQ[{a, b, c, n}, x] && IGtQ[n, 0]
Int[(a_. + b_.*ArcCsc[c_.*x_])^n_, x_Symbol] := -1/c* Subst[Int[(a + b*x)^n*Csc[x]*Cot[x], x], x, ArcCsc[c*x]] /; FreeQ[{a, b, c, n}, x] && IGtQ[n, 0]
Int[(a_. + b_.*ArcSec[c_.*x_])/x_, x_Symbol] := -Subst[Int[(a + b*ArcCos[x/c])/x, x], x, 1/x] /; FreeQ[{a, b, c}, x]
Int[(a_. + b_.*ArcCsc[c_.*x_])/x_, x_Symbol] := -Subst[Int[(a + b*ArcSin[x/c])/x, x], x, 1/x] /; FreeQ[{a, b, c}, x]
Int[(d_.*x_)^m_.*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := (d*x)^(m + 1)*(a + b*ArcSec[c*x])/(d*(m + 1)) - b*d/(c*(m + 1))*Int[(d*x)^(m - 1)/Sqrt[1 - 1/(c^2*x^2)], x] /; FreeQ[{a, b, c, d, m}, x] && NeQ[m, -1]
Int[(d_.*x_)^m_.*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := (d*x)^(m + 1)*(a + b*ArcCsc[c*x])/(d*(m + 1)) + b*d/(c*(m + 1))*Int[(d*x)^(m - 1)/Sqrt[1 - 1/(c^2*x^2)], x] /; FreeQ[{a, b, c, d, m}, x] && NeQ[m, -1]
Int[x_^m_.*(a_. + b_.*ArcSec[c_.*x_])^n_, x_Symbol] := 1/c^(m + 1)* Subst[Int[(a + b*x)^n*Sec[x]^(m + 1)*Tan[x], x], x, ArcSec[c*x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n] && IntegerQ[m] && (GtQ[n, 0] || LtQ[m, -1])
Int[x_^m_.*(a_. + b_.*ArcCsc[c_.*x_])^n_, x_Symbol] := -1/c^(m + 1)* Subst[Int[(a + b*x)^n*Csc[x]^(m + 1)*Cot[x], x], x, ArcCsc[c*x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n] && IntegerQ[m] && (GtQ[n, 0] || LtQ[m, -1])
Int[(a_. + b_.*ArcSec[c_.*x_])/(d_. + e_.*x_), x_Symbol] := (a + b*ArcSec[c*x])* Log[1 + (e - Sqrt[-c^2*d^2 + e^2])*E^(I*ArcSec[c*x])/(c*d)]/e + (a + b*ArcSec[c*x])* Log[1 + (e + Sqrt[-c^2*d^2 + e^2])*E^(I*ArcSec[c*x])/(c*d)]/e - (a + b*ArcSec[c*x])*Log[1 + E^(2*I*ArcSec[c*x])]/e - b/(c*e)* Int[Log[1 + (e - Sqrt[-c^2*d^2 + e^2])* E^(I*ArcSec[c*x])/(c*d)]/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] - b/(c*e)* Int[Log[1 + (e + Sqrt[-c^2*d^2 + e^2])* E^(I*ArcSec[c*x])/(c*d)]/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] + b/(c*e)* Int[Log[1 + E^(2*I*ArcSec[c*x])]/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[{a, b, c, d, e}, x]
Int[(a_. + b_.*ArcCsc[c_.*x_])/(d_. + e_.*x_), x_Symbol] := (a + b*ArcCsc[c*x])* Log[1 - I*(e - Sqrt[-c^2*d^2 + e^2])*E^(I*ArcCsc[c*x])/(c*d)]/ e + (a + b*ArcCsc[c*x])* Log[1 - I*(e + Sqrt[-c^2*d^2 + e^2])*E^(I*ArcCsc[c*x])/(c*d)]/ e - (a + b*ArcCsc[c*x])*Log[1 - E^(2*I*ArcCsc[c*x])]/e + b/(c*e)* Int[Log[1 - I*(e - Sqrt[-c^2*d^2 + e^2])*E^(I*ArcCsc[c*x])/(c*d)]/(x^2* Sqrt[1 - 1/(c^2*x^2)]), x] + b/(c*e)* Int[Log[1 - I*(e + Sqrt[-c^2*d^2 + e^2])*E^(I*ArcCsc[c*x])/(c*d)]/(x^2* Sqrt[1 - 1/(c^2*x^2)]), x] - b/(c*e)* Int[Log[1 - E^(2*I*ArcCsc[c*x])]/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[{a, b, c, d, e}, x]
Int[(d_. + e_.*x_)^m_.*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := (d + e*x)^(m + 1)*(a + b*ArcSec[c*x])/(e*(m + 1)) - b/(c*e*(m + 1))* Int[(d + e*x)^(m + 1)/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[{a, b, c, d, e, m}, x] && NeQ[m, -1]
Int[(d_. + e_.*x_)^m_.*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := (d + e*x)^(m + 1)*(a + b*ArcCsc[c*x])/(e*(m + 1)) + b/(c*e*(m + 1))* Int[(d + e*x)^(m + 1)/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x] /; FreeQ[{a, b, c, d, e, m}, x] && NeQ[m, -1]
Int[(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[(a + b*ArcSec[c*x]), u, x] - b*c*x/Sqrt[c^2*x^2]* Int[SimplifyIntegrand[u/(x*Sqrt[c^2*x^2 - 1]), x], x]] /; FreeQ[{a, b, c, d, e}, x] && (IGtQ[p, 0] || ILtQ[p + 1/2, 0])
Int[(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[(a + b*ArcCsc[c*x]), u, x] + b*c*x/Sqrt[c^2*x^2]* Int[SimplifyIntegrand[u/(x*Sqrt[c^2*x^2 - 1]), x], x]] /; FreeQ[{a, b, c, d, e}, x] && (IGtQ[p, 0] || ILtQ[p + 1/2, 0])
Int[(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Subst[ Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && IntegerQ[p]
Int[(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Subst[ Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && IntegerQ[p]
Int[(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Sqrt[x^2]/x* Subst[Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[p + 1/2] && GtQ[e, 0] && LtQ[d, 0]
Int[(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Sqrt[x^2]/x* Subst[Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[p + 1/2] && GtQ[e, 0] && LtQ[d, 0]
Int[(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Sqrt[d + e*x^2]/(x*Sqrt[e + d/x^2])* Subst[Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[p + 1/2] && Not[GtQ[e, 0] && LtQ[d, 0]]
Int[(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Sqrt[d + e*x^2]/(x*Sqrt[e + d/x^2])* Subst[Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[p + 1/2] && Not[GtQ[e, 0] && LtQ[d, 0]]
Int[x_*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcSec[c*x])/(2* e*(p + 1)) - b*c*x/(2*e*(p + 1)*Sqrt[c^2*x^2])* Int[(d + e*x^2)^(p + 1)/(x*Sqrt[c^2*x^2 - 1]), x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[p, -1]
Int[x_*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcCsc[c*x])/(2* e*(p + 1)) + b*c*x/(2*e*(p + 1)*Sqrt[c^2*x^2])* Int[(d + e*x^2)^(p + 1)/(x*Sqrt[c^2*x^2 - 1]), x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[p, -1]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[(a + b*ArcSec[c*x]), u, x] - b*c*x/Sqrt[c^2*x^2]* Int[SimplifyIntegrand[u/(x*Sqrt[c^2*x^2 - 1]), x], x]] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && ( IGtQ[p, 0] && Not[ILtQ[(m - 1)/2, 0] && GtQ[m + 2*p + 3, 0]] || IGtQ[(m + 1)/2, 0] && Not[ILtQ[p, 0] && GtQ[m + 2*p + 3, 0]] || ILtQ[(m + 2*p + 1)/2, 0] && Not[ILtQ[(m - 1)/2, 0]])
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[(a + b*ArcCsc[c*x]), u, x] + b*c*x/Sqrt[c^2*x^2]* Int[SimplifyIntegrand[u/(x*Sqrt[c^2*x^2 - 1]), x], x]] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && ( IGtQ[p, 0] && Not[ILtQ[(m - 1)/2, 0] && GtQ[m + 2*p + 3, 0]] || IGtQ[(m + 1)/2, 0] && Not[ILtQ[p, 0] && GtQ[m + 2*p + 3, 0]] || ILtQ[(m + 2*p + 1)/2, 0] && Not[ILtQ[(m - 1)/2, 0]])
Int[x_^m_.*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Subst[ Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && IntegerQ[m] && IntegerQ[p]
Int[x_^m_.*(d_. + e_.*x_^2)^p_.*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Subst[ Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && IntegerQ[m] && IntegerQ[p]
Int[x_^m_.*(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Sqrt[x^2]/x* Subst[Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[m] && IntegerQ[p + 1/2] && GtQ[e, 0] && LtQ[d, 0]
Int[x_^m_.*(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Sqrt[x^2]/x* Subst[Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[m] && IntegerQ[p + 1/2] && GtQ[e, 0] && LtQ[d, 0]
Int[x_^m_.*(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := -Sqrt[d + e*x^2]/(x*Sqrt[e + d/x^2])* Subst[Int[(e + d*x^2)^p*(a + b*ArcCos[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[m] && IntegerQ[p + 1/2] && Not[GtQ[e, 0] && LtQ[d, 0]]
Int[x_^m_.*(d_. + e_.*x_^2)^p_*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := -Sqrt[d + e*x^2]/(x*Sqrt[e + d/x^2])* Subst[Int[(e + d*x^2)^p*(a + b*ArcSin[x/c])^n/x^(m + 2*(p + 1)), x], x, 1/x] /; FreeQ[{a, b, c, d, e, n}, x] && IGtQ[n, 0] && EqQ[c^2*d + e, 0] && IntegerQ[m] && IntegerQ[p + 1/2] && Not[GtQ[e, 0] && LtQ[d, 0]]
Int[u_*(a_. + b_.*ArcSec[c_.*x_]), x_Symbol] := With[{v = IntHide[u, x]}, Dist[(a + b*ArcSec[c*x]), v, x] - b/c* Int[SimplifyIntegrand[v/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x], x] /; InverseFunctionFreeQ[v, x]] /; FreeQ[{a, b, c}, x]
Int[u_*(a_. + b_.*ArcCsc[c_.*x_]), x_Symbol] := With[{v = IntHide[u, x]}, Dist[(a + b*ArcCsc[c*x]), v, x] + b/c* Int[SimplifyIntegrand[v/(x^2*Sqrt[1 - 1/(c^2*x^2)]), x], x] /; InverseFunctionFreeQ[v, x]] /; FreeQ[{a, b, c}, x]
Int[u_.*(a_. + b_.*ArcSec[c_.*x_])^n_., x_Symbol] := Unintegrable[u*(a + b*ArcSec[c*x])^n, x] /; FreeQ[{a, b, c, n}, x]
Int[u_.*(a_. + b_.*ArcCsc[c_.*x_])^n_., x_Symbol] := Unintegrable[u*(a + b*ArcCsc[c*x])^n, x] /; FreeQ[{a, b, c, n}, x]
