(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(g_+h_.*x_)^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-g)/h]},
  1/h \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,g+h*x] /;
 BinomialQ[Px,x]] /;
FreeQ[{g,h,m,p},x] && PolyQ[Pn,x]


(* ::Code:: *)
Int[u_^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]]},
  1/Coeff[u,x,1] \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,u] /;
 BinomialQ[Px,x]] /;
FreeQ[{m,p},x] && LinearQ[u,x] && PolyQ[Pn,x] && NeQ[Coeff[u,x,0],0]


(* ::Code:: *)
Int[(g_+h_.*x_)^m_.*Pn_^p_.*Qn_^q_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-g)/h], Qx=ReplaceAll[Qn,x->(x-g)/h]},
  1/h \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p*ExpandToSum[Qx,x]^q,x],x,g+h*x] /;
 BinomialQ[Px,x] && BinomialQ[Qx,x]] /;
FreeQ[{g,h,m,p,q},x] && PolyQ[Pn,x] && PolyQ[Qn,x] && EqQ[Expon[Pn,x],Expon[Qn,x]]


(* ::Code:: *)
Int[u_^m_.*Pn_^p_.*Qn_^q_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]], Qx=ReplaceAll[Qn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]]},
  1/Coeff[u,x,1] \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p*ExpandToSum[Qx,x]^q,x],x,u] /;
 BinomialQ[Px,x] && BinomialQ[Qx,x]] /;
FreeQ[{m,p,q},x] && LinearQ[u,x] && PolyQ[Pn,x] && PolyQ[Qn,x] && EqQ[Expon[Pn,x],Expon[Qn,x]] && NeQ[Coeff[u,x,0],0]


(* ::Code:: *)
Int[(g_+h_.*x_)^m_.*Pn_^p_.*Qn_^q_.*Rn_^r_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-g)/h], Qx=ReplaceAll[Qn,x->(x-g)/h], Rx=ReplaceAll[Rn,x->(x-g)/h]},
  1/h \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p*ExpandToSum[Qx,x]^q*ExpandToSum[Rx,x]^r,x],x,g+h*x] /;
 BinomialQ[Px,x] && BinomialQ[Qx,x] && BinomialQ[Rx,x]] /;
FreeQ[{g,h,m,p,q,r},x] && PolyQ[Pn,x] && PolyQ[Qn,x] && PolyQ[Rn,x] && 
  EqQ[Expon[Pn,x],Expon[Qn,x]] && EqQ[Expon[Pn,x],Expon[Rn,x]]


(* ::Code:: *)
Int[u_^m_.*Pn_^p_.*Qn_^q_.*Rn_^r_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]], Qx=ReplaceAll[Qn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]], 
    Rx=ReplaceAll[Rn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]]},
  1/Coeff[u,x,1] \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p*ExpandToSum[Qx,x]^q*ExpandToSum[Rx,x]^r,x],x,u] /;
 BinomialQ[Px,x] && BinomialQ[Qx,x] && BinomialQ[Rx,x]] /;
FreeQ[{m,p,q,r},x] && LinearQ[u,x] && PolyQ[Pn,x] && PolyQ[Qn,x] && PolyQ[Rn,x] && 
  EqQ[Expon[Pn,x],Expon[Qn,x]] && EqQ[Expon[Pn,x],Expon[Rn,x]] && NeQ[Coeff[u,x,0],0]


(* ::Code:: *)
Int[(g_+h_.*x_)^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-g)/h]},
  1/h \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,g+h*x] /;
 BinomialQ[Px,x]] /;
FreeQ[{g,h,m,p},x] && PolyQ[Pn,x]


(* ::Code:: *)
Int[u_^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]]},
  1/Coeff[u,x,1] \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,u] /;
 BinomialQ[Px,x]] /;
FreeQ[{m,p},x] && LinearQ[u,x] && PolyQ[Pn,x] && NeQ[Coeff[u,x,0],0]


(* ::Code:: *)
Int[(g_+h_.*x_)^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-g)/h]},
  1/h \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,g+h*x] /;
 TrinomialQ[Px,x]] /;
FreeQ[{g,h,m,p},x] && PolyQ[Pn,x]


(* ::Code:: *)
Int[u_^m_.*Pn_^p_.,x_Symbol] :=
  With[{Px=ReplaceAll[Pn,x->(x-Coeff[u,x,0])/Coeff[u,x,1]]},
  1/Coeff[u,x,1] \[Star] Subst[Int[x^m*ExpandToSum[Px,x]^p,x],x,u] /;
 TrinomialQ[Px,x]] /;
FreeQ[{m,p},x] && LinearQ[u,x] && PolyQ[Pn,x] && NeQ[Coeff[u,x,0],0]


(* ::Code:: *)
Int[Sqrt[v_]/(d_+e_.*x_^4),x_Symbol] :=
  With[{a=Coeff[v,x,0],b=Coeff[v,x,2],c=Coeff[v,x,4]},
  a/d \[Star] Subst[Int[1/(1-2*b*x^2+(b^2-4*a*c)*x^4),x],x,x/Sqrt[v]] /;
 EqQ[c*d+a*e,0] && PosQ[a*c]] /;
FreeQ[{d,e},x] && PolyQ[v,x^2,2]


(* ::Code:: *)
Int[Sqrt[a_+b_.*x_^2+c_.*x_^4]/(d_+e_.*x_^4),x_Symbol] :=
  With[{q=Sqrt[b^2-4*a*c]},
  -a*Sqrt[b+q]/(2*Sqrt[2]*Rt[-a*c,2]*d)*ArcTan[Sqrt[b+q]*x*(b-q+2*c*x^2)/(2*Sqrt[2]*Rt[-a*c,2]*Sqrt[a+b*x^2+c*x^4])] + 
  a*Sqrt[-b+q]/(2*Sqrt[2]*Rt[-a*c,2]*d)*ArcTanh[Sqrt[-b+q]*x*(b+q+2*c*x^2)/(2*Sqrt[2]*Rt[-a*c,2]*Sqrt[a+b*x^2+c*x^4])]] /;
FreeQ[{a,b,c,d,e},x] && EqQ[c*d+a*e,0] && NegQ[a*c]


(* ::Code:: *)
Int[(A_+B_.*x_^n_)/(a_+b_.*x_^2+c_.*x_^n_+d_.*x_^n2_), x_Symbol] :=
  A^2*(n-1) \[Star] Subst[Int[1/(a+A^2*b*(n-1)^2*x^2),x],x,x/(A*(n-1)-B*x^n)] /;
FreeQ[{a,b,c,d,A,B,n},x] && EqQ[n2,2*n] && NeQ[n,2] && EqQ[a*B^2-A^2*d*(n-1)^2,0] && EqQ[B*c+2*A*d*(n-1),0]


(* ::Code:: *)
Int[x_^m_.*(A_+B_.*x_^n_.)/(a_+b_.*x_^k_.+c_.*x_^n_.+d_.*x_^n2_), x_Symbol] :=
  A^2*(m-n+1)/(m+1) \[Star] Subst[Int[1/(a+A^2*b*(m-n+1)^2*x^2),x],x,x^(m+1)/(A*(m-n+1)+B*(m+1)*x^n)] /;
FreeQ[{a,b,c,d,A,B,m,n},x] && EqQ[n2,2*n] && EqQ[k,2*(m+1)] && EqQ[a*B^2*(m+1)^2-A^2*d*(m-n+1)^2,0] && EqQ[B*c*(m+1)-2*A*d*(m-n+1),0]


(* ::Code:: *)
Int[(a_+b_.*x_^2+c_.*x_^4)/(d_+e_.*x_^2+f_.*x_^4+g_.*x_^6),x_Symbol] :=
  With[{q=Rt[(-a*c*f^2+12*a^2*g^2+f*(3*c^2*d-2*a*b*g))/(c*g*(3*c*d-a*f)),2],
        r=Rt[(a*c*f^2+4*g*(b*c*d+a^2*g)-f*(3*c^2*d+2*a*b*g))/(c*g*(3*c*d-a*f)),2]},
  c/(g*q)*ArcTan[(r+2*x)/q] - 
  c/(g*q)*ArcTan[(r-2*x)/q] - 
  c/(g*q)*ArcTan[(3*c*d-a*f)*x/(g*q*(b*c*d-2*a^2*g)*(b*c*d-a*b*f+4*a^2*g))*
    (b*c^2*d*f-a*b^2*f*g-2*a^2*c*f*g+6*a^2*b*g^2+c*(3*c^2*d*f-a*c*f^2-b*c*d*g+2*a^2*g^2)*x^2+c^2*g*(3*c*d-a*f)*x^4)]] /;
FreeQ[{a,b,c,d,e,f,g},x] && EqQ[9*c^3*d^2-c*(b^2+6*a*c)*d*f+a^2*c*f^2+2*a*b*(3*c*d+a*f)*g-12*a^3*g^2,0] && 
  EqQ[3*c^4*d^2*e-3*a^2*c^2*d*f*g+a^3*c*f^2*g+2*a^3*g^2*(b*f-6*a*g)-c^3*d*(2*b*d*f+a*e*f-12*a*d*g),0] && 
  NeQ[3*c*d-a*f,0] && NeQ[b*c*d-2*a^2*g,0] && NeQ[b*c*d-a*b*f+4*a^2*g,0] && 
  PosQ[(-a*c*f^2+12*a^2*g^2+f*(3*c^2*d-2*a*b*g))/(c*g*(3*c*d-a*f))]


(* ::Code:: *)
Int[(a_+c_.*x_^4)/(d_+e_.*x_^2+f_.*x_^4+g_.*x_^6),x_Symbol] :=
  With[{q=Rt[(-a*c*f^2+12*a^2*g^2+3*f*c^2*d)/(c*g*(3*c*d-a*f)),2],
        r=Rt[(a*c*f^2+4*a^2*g^2-3*c^2*d*f)/(c*g*(3*c*d-a*f)),2]},
  c/(g*q)*ArcTan[(r+2*x)/q] - 
  c/(g*q)*ArcTan[(r-2*x)/q] - 
  c/(g*q)*ArcTan[(c*(3*c*d-a*f)*x*(2*a^2*f*g-(3*c^2*d*f-a*c*f^2+2*a^2*g^2)*x^2-c*(3*c*d-a*f)*g*x^4))/(8*a^4*g^3*q)]] /;
FreeQ[{a,c,d,e,f,g},x] && EqQ[9*c^3*d^2-6*a*c^2*d*f+a^2*c*f^2-12*a^3*g^2,0] && 
  EqQ[3*c^4*d^2*e-3*a^2*c^2*d*f*g+a^3*c*f^2*g-12*a^4*g^3-a*c^3*d*(e*f-12*d*g),0] && 
  NeQ[3*c*d-a*f,0] && PosQ[(-a*c*f^2+12*a^2*g^2+3*c^2*d*f)/(c*g*(3*c*d-a*f))]


(* ::Code:: *)
Int[Pm_/Qn_,x_Symbol] :=
  With[{m=Expon[Pm,x],n=Expon[Qn,x]},
  Coeff[Pm,x,m]*Log[Qn]/(n*Coeff[Qn,x,n]) + Simplify[Pm-Coeff[Pm,x,m]*D[Qn,x]/(n*Coeff[Qn,x,n])] \[Star] Int[1/Qn,x]/;
 EqQ[m,n-1] && EqQ[D[Simplify[Pm-Coeff[Pm,x,m]/(n*Coeff[Qn,x,n])*D[Qn,x]],x],0]] /;
PolyQ[Pm,x] && PolyQ[Qn,x]


(* ::Code:: *)
Int[Pm_*Qn_^p_,x_Symbol] :=
  With[{m=Expon[Pm,x],n=Expon[Qn,x]},
  Coeff[Pm,x,m]*Qn^(p+1)/(n*(p+1)*Coeff[Qn,x,n]) + Simplify[Pm-Coeff[Pm,x,m]*D[Qn,x]/(n*Coeff[Qn,x,n])] \[Star] Int[Qn^p,x]/;
 EqQ[m,n-1] && EqQ[D[Simplify[Pm-Coeff[Pm,x,m]/(n*Coeff[Qn,x,n])*D[Qn,x]],x],0]] /;
FreeQ[p,x] && PolyQ[Pm,x] && PolyQ[Qn,x] && NeQ[p,-1]


(* ::Code:: *)
Int[Pm_/Qn_,x_Symbol] :=
  With[{m=Expon[Pm,x],n=Expon[Qn,x]},
  Coeff[Pm,x,m]*Log[Qn]/(n*Coeff[Qn,x,n]) + 
  1/(n*Coeff[Qn,x,n]) \[Star] Int[ExpandToSum[n*Coeff[Qn,x,n]*Pm-Coeff[Pm,x,m]*D[Qn,x],x]/Qn,x]/;
 EqQ[m,n-1]] /;
PolyQ[Pm,x] && PolyQ[Qn,x]


(* ::Code:: *)
Int[Pm_*Qn_^p_,x_Symbol] :=
  With[{m=Expon[Pm,x],n=Expon[Qn,x]},
  Coeff[Pm,x,m]*Qn^(p+1)/(n*(p+1)*Coeff[Qn,x,n]) + 
  1/(n*Coeff[Qn,x,n]) \[Star] Int[ExpandToSum[n*Coeff[Qn,x,n]*Pm-Coeff[Pm,x,m]*D[Qn,x],x]*Qn^p,x]/;
 EqQ[m,n-1]] /;
FreeQ[p,x] && PolyQ[Pm,x] && PolyQ[Qn,x] && NeQ[p,-1]


(* ::Code:: *)
Int[Pm_*Qn_^p_.,x_Symbol] :=
  With[{m=Expon[Pm,x],n=Expon[Qn,x]},
  Coeff[Pm,x,m]*x^(m-n+1)*Qn^(p+1)/((m+n*p+1)*Coeff[Qn,x,n]) + 
  1/((m+n*p+1)*Coeff[Qn,x,n]) \[Star] 
    Int[ExpandToSum[(m+n*p+1)*Coeff[Qn,x,n]*Pm-Coeff[Pm,x,m]*x^(m-n)*((m-n+1)*Qn+(p+1)*x*D[Qn,x]),x]*Qn^p,x] /;
 LtQ[1,n,m+1] && m+n*p+1<0] /;
FreeQ[p,x] && PolyQ[Pm,x] && PolyQ[Qn,x] && LtQ[p,-1]



