(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[u_.*Px_^p_,x_Symbol] :=
  With[{b=Coeff[Px,x,1],c=Coeff[Px,x,2],d=Coeff[Px,x,3],e=Coeff[Px,x,4]},
  Px^FracPart[p]/(x^FracPart[p]*(b+c*x+d*x^2+e*x^3)^FracPart[p]) \[Star] Int[u*x^p*(b+c*x+d*x^2+e*x^3)^p,x]] /;
FreeQ[p,x] && PolyQ[Px,x,4] && EqQ[Coeff[Px,x,0],0] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[Px_.*(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  e^p \[Star] Int[ExpandIntegrand[Px*(b/d+(d+Sqrt[e*(b^2-4*a*c)/a+8*a*d*e/b])/(2*e)*x+x^2)^p*(b/d+(d-Sqrt[e*(b^2-4*a*c)/a+8*a*d*e/b])/(2*e)*x+x^2)^p,x],x] /;
FreeQ[{a,b,c,d,e},x] && PolyQ[Px,x] && ILtQ[p,0] && EqQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[Px_.*(a_+b_.*x_+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  e^p \[Star] Int[ExpandIntegrand[Px*(b/d+(d+Sqrt[d^2+8*a*d*e/b])/(2*e)*x+x^2)^p*(b/d+(d-Sqrt[d^2+8*a*d*e/b])/(2*e)*x+x^2)^p,x],x] /;
FreeQ[{a,b,d,e},x] && PolyQ[Px,x] && ILtQ[p,0] && EqQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[Px_.*(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  With[{S=Root[a*d^2-b^2*e+(b*d^2-4*b*c*e+8*a*d*e)*x+(c*d^2-4*c^2*e+2*b*d*e+16*a*e^2)*x^2+(d^3-4*c*d*e+8*b*e^2)*x^3,3]},
  Subst[Int[ReplaceAll[Px,x->x+S]*ExpandToSum[a+b*(x+S)+c*(x+S)^2+d*(x+S)^3+e*(x+S)^4,x]^p,x],x,x-S] /;
 RationalQ[S]] /;
FreeQ[{a,b,c,d,e},x] && PolyQ[Px,x] && ILtQ[p,0] && RationalQ[a,b,c,d,e] && NeQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[Px_.*(a_+b_.*x_+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  With[{S=Root[a*d^2-b^2*e+(b*d^2+8*a*d*e)*x+(2*b*d*e+16*a*e^2)*x^2+(d^3+8*b*e^2)*x^3,3]},
  Subst[Int[ReplaceAll[Px,x->x+S]*ExpandToSum[a+b*(x+S)+d*(x+S)^3+e*(x+S)^4,x]^p,x],x,x-S] /;
 RationalQ[S]] /;
FreeQ[{a,b,d,e},x] && PolyQ[Px,x] && ILtQ[p,0] && RationalQ[a,b,d,e] && NeQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[x_^m_.*Px_.*(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  e^p \[Star] Int[ExpandIntegrand[x^m*Px*(b/d+(d+Sqrt[e*(b^2-4*a*c)/a+8*a*d*e/b])/(2*e)*x+x^2)^p*(b/d+(d-Sqrt[e*(b^2-4*a*c)/a+8*a*d*e/b])/(2*e)*x+x^2)^p,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && PolyQ[Px,x] && ILtQ[p,0] && EqQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[x_^m_.*Px_.*(a_+b_.*x_+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  e^p \[Star] Int[ExpandIntegrand[x^m*Px*(b/d+(d+Sqrt[d^2+8*a*d*e/b])/(2*e)*x+x^2)^p*(b/d+(d-Sqrt[d^2+8*a*d*e/b])/(2*e)*x+x^2)^p,x],x] /;
FreeQ[{a,b,d,e,m},x] && PolyQ[Px,x] && ILtQ[p,0] && EqQ[a*d^2-b^2*e,0]


(* ::Code:: *)
Int[Px_.*(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  1/a^(3*p) \[Star] Int[ExpandIntegrand[Px*(a^5-b^5*x^5)^p/(a-b*x)^p,x],x] /;
FreeQ[{a,b,c,d,e},x] && PolyQ[Px,x] && ILtQ[p,0] && NeQ[a,0] && EqQ[c,b^2/a] && EqQ[d,b^3/a^2] && EqQ[e,b^4/a^3]


(* ::Code:: *)
Int[x_^m_.*Px_.*(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4)^p_,x_Symbol] :=
  1/a^(3*p) \[Star] Int[ExpandIntegrand[x^m*Px*(a^5-b^5*x^5)^p/(a-b*x)^p,x],x] /;
FreeQ[{a,b,c,d,e,m},x] && PolyQ[Px,x] && ILtQ[p,0] && NeQ[a,0] && EqQ[c,b^2/a] && EqQ[d,b^3/a^2] && EqQ[e,b^4/a^3]


(* ::Code:: *)
Int[(A_.+B_.*x_+C_.*x_^2)/(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4),x_Symbol] :=
  With[{q=Rt[C*(2*e*(B*d-4*A*e)+C*(d^2-4*c*e)),2]},
  -2*C^2/q*ArcTanh[(C*d-B*e+2*C*e*x)/q] + 
  2*C^2/q*ArcTanh[C*(4*B*c*C-3*B^2*d-4*A*C*d+12*A*B*e+4*C*(2*c*C-B*d+2*A*e)*x+4*C*(2*C*d-B*e)*x^2+8*C^2*e*x^3)/(q*(B^2-4*A*C))]] /;
FreeQ[{a,b,c,d,e,A,B,C},x] && EqQ[B^2*d+2*C*(b*C+A*d)-2*B*(c*C+2*A*e),0] && 
  EqQ[2*B^2*c*C-8*a*C^3-B^3*d-4*A*B*C*d+4*A*(B^2+2*A*C)*e,0] && PosQ[C*(2*e*(B*d-4*A*e)+C*(d^2-4*c*e))]


(* ::Code:: *)
Int[(A_.+C_.*x_^2)/(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4),x_Symbol] :=
  With[{q=Rt[C*(-8*A*e^2+C*(d^2-4*c*e)),2]},
  -2*C^2/q*ArcTanh[C*(d+2*e*x)/q] + 2*C^2/q*ArcTanh[C*(A*d-2*(c*C+A*e)*x-2*C*d*x^2-2*C*e*x^3)/(A*q)]] /;
FreeQ[{a,b,c,d,e,A,C},x] && EqQ[b*C+A*d,0] && EqQ[a*C^2-A^2*e,0] && PosQ[C*(-8*A*e^2+C*(d^2-4*c*e))]


(* ::Code:: *)
Int[(A_.+B_.*x_+C_.*x_^2)/(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4),x_Symbol] :=
  With[{q=Rt[-C*(2*e*(B*d-4*A*e)+C*(d^2-4*c*e)),2]},
  2*C^2/q*ArcTan[(C*d-B*e+2*C*e*x)/q] - 
  2*C^2/q*ArcTan[C*(4*B*c*C-3*B^2*d-4*A*C*d+12*A*B*e+4*C*(2*c*C-B*d+2*A*e)*x+4*C*(2*C*d-B*e)*x^2+8*C^2*e*x^3)/(q*(B^2-4*A*C))]] /;
FreeQ[{a,b,c,d,e,A,B,C},x] && EqQ[B^2*d+2*C*(b*C+A*d)-2*B*(c*C+2*A*e),0] && 
  EqQ[2*B^2*c*C-8*a*C^3-B^3*d-4*A*B*C*d+4*A*(B^2+2*A*C)*e,0] && NegQ[C*(2*e*(B*d-4*A*e)+C*(d^2-4*c*e))]


(* ::Code:: *)
Int[(A_.+C_.*x_^2)/(a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4),x_Symbol] :=
  With[{q=Rt[-C*(-8*A*e^2+C*(d^2-4*c*e)),2]},
  2*C^2/q*ArcTan[(C*d+2*C*e*x)/q] - 2*C^2/q*ArcTan[-C*(-A*d+2*(c*C+A*e)*x+2*C*d*x^2+2*C*e*x^3)/(A*q)]] /;
FreeQ[{a,b,c,d,e,A,C},x] && EqQ[b*C+A*d,0] && EqQ[a*C^2-A^2*e,0] && NegQ[C*(-8*A*e^2+C*(d^2-4*c*e))]


(* ::Code:: *)
Int[P4_^p_,x_Symbol] :=
  With[{a=Coeff[P4,x,0],b=Coeff[P4,x,1],c=Coeff[P4,x,2],d=Coeff[P4,x,3],e=Coeff[P4,x,4]},
  -16*a^2 \[Star] Subst[
    Int[1/(b-4*a*x)^2*(a*(-3*b^4+16*a*b^2*c-64*a^2*b*d+256*a^3*e-32*a^2*(3*b^2-8*a*c)*x^2+256*a^4*x^4)/(b-4*a*x)^4)^p,x],
    x,b/(4*a)+1/x] /;
 NeQ[a,0] && NeQ[b,0] && EqQ[b^3-4*a*b*c+8*a^2*d,0]] /;
FreeQ[p,x] && PolyQ[P4,x,4] && IntegerQ[2*p] && Not[IGtQ[p,0]]


(* ::Code:: *)
Int[x_/Sqrt[a_+b_.*x_+c_.*x_^2+e_.*x_^4],x_Symbol] :=
  With[{Px=1/320*(33*b^2*c+6*a*c^2+40*a^2*e)-22/5*a*c*e*x^2+22/15*b*c*e*x^3+1/4*e*(5*c^2+4*a*e)*x^4+
    4/3*b*e^2*x^5+2*c*e^2*x^6+e^3*x^8},
  1/(8*Rt[e,2])*Log[Px + (1/(8*Rt[e,2]*x) \[Star] D[Px,x])*Sqrt[a+b*x+c*x^2+e*x^4]]] /;
FreeQ[{a,b,c,e},x] && EqQ[71*c^2+100*a*e,0] && EqQ[1152*c^3-125*b^2*e,0]


(* ::Code:: *)
Int[(A_+B_.*x_)/Sqrt[a_+b_.*x_+c_.*x_^2+d_.*x_^3+e_.*x_^4],x_Symbol] :=
  B \[Star] Subst[Int[x/Sqrt[(-3*d^4+16*c*d^2*e-64*b*d*e^2+256*a*e^3)/(256*e^3)+(d^3-4*c*d*e+8*b*e^2)*x/(8*e^2)-
    (3*d^2-8*c*e)*x^2/(8*e)+e*x^4],x],x,d/(4*e)+x] /;
FreeQ[{a,b,c,d,e,A,B},x] && EqQ[B*d-4*A*e,0] && 
  EqQ[d*(141*d^3-752*c*d*e-400*b*e^2)+16*e^2*(71*c^2+100*a*e),0] && 
  EqQ[144*(3*d^2-8*c*e)^3+125*(d^3-4*c*d*e+8*b*e^2)^2,0]


(* ::Code:: *)
Int[(f_+g_.*x_^2)/((d_+e_.*x_+d_.*x_^2)*Sqrt[a_+b_.*x_+c_.*x_^2+b_.*x_^3+a_.*x_^4]),x_Symbol] :=
  a*f/(d*Rt[a^2*(2*a-c),2])*ArcTan[(a*b+(4*a^2+b^2-2*a*c)*x+a*b*x^2)/(2*Rt[a^2*(2*a-c),2]*Sqrt[a+b*x+c*x^2+b*x^3+a*x^4])] /;
FreeQ[{a,b,c,d,e,f,g},x] && EqQ[b*d-a*e,0] && EqQ[f+g,0] && PosQ[a^2*(2*a-c)]


(* ::Code:: *)
Int[(f_+g_.*x_^2)/((d_+e_.*x_+d_.*x_^2)*Sqrt[a_+b_.*x_+c_.*x_^2+b_.*x_^3+a_.*x_^4]),x_Symbol] :=
  -a*f/(d*Rt[-a^2*(2*a-c),2])*ArcTanh[(a*b+(4*a^2+b^2-2*a*c)*x+a*b*x^2)/(2*Rt[-a^2*(2*a-c),2]*Sqrt[a+b*x+c*x^2+b*x^3+a*x^4])] /;
FreeQ[{a,b,c,d,e,f,g},x] && EqQ[b*d-a*e,0] && EqQ[f+g,0] && NegQ[a^2*(2*a-c)]



