(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Sin[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcCot[x]]+b*Cos[n*ArcCot[x]]]]^p/(1+x^2),x],x,Cot[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Sin[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcTan[x]]+b*Cos[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcCos[x]]+b*Sin[n*ArcCos[x]]]]^p/Sqrt[1-x^2],x],x,Cos[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcSin[x]]+b*Cos[n*ArcSin[x]]]]^p/Sqrt[1-x^2],x],x,Sin[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[2*m*ArcTan[x]]+b*Sin[2*n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[2*m*ArcCot[x]]+b*Cos[2*n*ArcCot[x]]]]^p/(1+x^2),x],x,Cot[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Cos[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcSin[x]]+b*Cos[n*ArcSin[x]]]]^p/Sqrt[1-x^2],x],x,Sin[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[2*m*ArcTan[x]]+b*Cos[2*n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m] && IntegerQ[n]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Sin[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcCot[x]]+b*Cos[n*ArcCot[x]]]]^p/(1+x^2),x],x,Cot[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Sin[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcTan[x]]+b*Cos[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcCos[x]]+b*Sin[n*ArcCos[x]]]]^p/Sqrt[1-x^2],x],x,Cos[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[m*ArcSin[x]]+b*Cos[n*ArcSin[x]]]]^p/Sqrt[1-x^2],x],x,Sin[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[(m-1)/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*sin[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[2*m*ArcTan[x]]+b*Sin[2*n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*cos[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  -2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Cos[2*m*ArcCot[x]]+b*Cos[2*n*ArcCot[x]]]]^p/(1+x^2),x],x,Cot[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcTan[x]]+b*Cos[n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m/2] && IntegerQ[n/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  1/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[m*ArcSin[x]]+b*Cos[n*ArcSin[x]]]]^p/Sqrt[1-x^2],x],x,Sin[c+d*x]] /;
FreeQ[{a,b,c,d},x] && ILtQ[(p-1)/2,0] && IntegerQ[m/2] && IntegerQ[(n-1)/2]


(* ::Code:: *)
Int[(a_.*sin[m_.*(c_.+d_.*x_)]+b_.*cos[n_.*(c_.+d_.*x_)])^p_,x_Symbol] :=
  2/d \[Star] Subst[Int[Simplify[TrigExpand[a*Sin[2*m*ArcTan[x]]+b*Cos[2*n*ArcTan[x]]]]^p/(1+x^2),x],x,Tan[1/2*(c+d*x)]] /;
FreeQ[{a,b,c,d},x] && ILtQ[p,0] && IntegerQ[m] && IntegerQ[n]



