
(* ::Subsection::Closed:: *)
(* 4.7.5 Inert trig functions *)
Int[(a_.*F_[c_. + d_.*x_]^p_)^n_, x_Symbol, _:RubiNotebookReference["f75e94e1"]] := With[{v = ActivateTrig[F[c + d*x]]}, a^IntPart[n]*(v/NonfreeFactors[v, x])^(p*IntPart[n])*(a*v^p)^ FracPart[n]/NonfreeFactors[v, x]^(p*FracPart[n])* Int[NonfreeFactors[v, x]^(n*p), x]] /; FreeQ[{a, c, d, n, p}, x] && InertTrigQ[F] && Not[IntegerQ[n]] && IntegerQ[p]
Int[(a_.*(b_.*F_[c_. + d_.*x_])^p_)^n_., x_Symbol, _:RubiNotebookReference["f5182ab8"]] := With[{v = ActivateTrig[F[c + d*x]]}, a^IntPart[n]*(a*(b*v)^p)^FracPart[n]/(b*v)^(p*FracPart[n])* Int[(b*v)^(n*p), x]] /; FreeQ[{a, b, c, d, n, p}, x] && InertTrigQ[F] && Not[IntegerQ[n]] && Not[IntegerQ[p]]
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f4da408f"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Cos] || EqQ[F, cos])
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f195560a"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[SubstFor[1, Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Sin] || EqQ[F, sin])
Int[u_*Cosh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f0573c3d"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x]
Int[u_*Sinh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f2118264"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x]
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f3d3e853"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Cot] || EqQ[F, cot])
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f88faf6e"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -1/(b*c)* Subst[Int[SubstFor[1/x, Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Tan] || EqQ[F, tan])
Int[u_*Coth[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f94dc559"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x]
Int[u_*Tanh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["502d16cd"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x]
Int[u_*F_[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["51ef7cfa"]] := With[{d = FreeFactors[Tan[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Tan[c*(a + b*x)]/d, u, x], x], x, Tan[c*(a + b*x)]/d] /; FunctionOfQ[Tan[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u] && (EqQ[F, Sec] || EqQ[F, sec])
Int[u_/cos[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["53a9c2a3"]] := With[{d = FreeFactors[Tan[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Tan[c*(a + b*x)]/d, u, x], x], x, Tan[c*(a + b*x)]/d] /; FunctionOfQ[Tan[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u]
Int[u_*F_[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["526ba894"]] := With[{d = FreeFactors[Cot[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[SubstFor[1, Cot[c*(a + b*x)]/d, u, x], x], x, Cot[c*(a + b*x)]/d] /; FunctionOfQ[Cot[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u] && (EqQ[F, Csc] || EqQ[F, csc])
Int[u_/sin[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["5724be11"]] := With[{d = FreeFactors[Cot[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[SubstFor[1, Cot[c*(a + b*x)]/d, u, x], x], x, Cot[c*(a + b*x)]/d] /; FunctionOfQ[Cot[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u]
Int[u_*Sech[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["56e6d426"]] := With[{d = FreeFactors[Tanh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Tanh[c*(a + b*x)]/d, u, x], x], x, Tanh[c*(a + b*x)]/d] /; FunctionOfQ[Tanh[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u]
Int[u_*Csch[c_.*(a_. + b_.*x_)]^2, x_Symbol, _:RubiNotebookReference["54a06a7f"]] := With[{d = FreeFactors[Coth[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[SubstFor[1, Coth[c*(a + b*x)]/d, u, x], x], x, Coth[c*(a + b*x)]/d] /; FunctionOfQ[Coth[c*(a + b*x)]/d, u, x, True]] /; FreeQ[{a, b, c}, x] && NonsumQ[u]
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_., x_Symbol, _:RubiNotebookReference["55620048"]] := With[{d = FreeFactors[Tan[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[1/(x^n*(1 + d^2*x^2)), Tan[c*(a + b*x)]/d, u, x], x], x, Tan[c*(a + b*x)]/d] /; FunctionOfQ[Tan[c*(a + b*x)]/d, u, x, True] && TryPureTanSubst[ActivateTrig[u]*Cot[c*(a + b*x)]^n, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n] && (EqQ[F, Cot] || EqQ[F, cot])
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_., x_Symbol, _:RubiNotebookReference["5e3e4775"]] := With[{d = FreeFactors[Cot[c*(a + b*x)], x]}, -1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[1/(x^n*(1 + d^2*x^2)), Cot[c*(a + b*x)]/d, u, x], x], x, Cot[c*(a + b*x)]/d] /; FunctionOfQ[Cot[c*(a + b*x)]/d, u, x, True] && TryPureTanSubst[ActivateTrig[u]*Tan[c*(a + b*x)]^n, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n] && (EqQ[F, Tan] || EqQ[F, tan])
Int[u_*Coth[c_.*(a_. + b_.*x_)]^n_., x_Symbol, _:RubiNotebookReference["5ffc2d42"]] := With[{d = FreeFactors[Tanh[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[1/(x^n*(1 - d^2*x^2)), Tanh[c*(a + b*x)]/d, u, x], x], x, Tanh[c*(a + b*x)]/d] /; FunctionOfQ[Tanh[c*(a + b*x)]/d, u, x, True] && TryPureTanSubst[ActivateTrig[u]*Coth[c*(a + b*x)]^n, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n]
Int[u_*Tanh[c_.*(a_. + b_.*x_)]^n_., x_Symbol, _:RubiNotebookReference["4298b923"]] := With[{d = FreeFactors[Coth[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[1/(x^n*(1 - d^2*x^2)), Coth[c*(a + b*x)]/d, u, x], x], x, Coth[c*(a + b*x)]/d] /; FunctionOfQ[Coth[c*(a + b*x)]/d, u, x, True] && TryPureTanSubst[ActivateTrig[u]*Tanh[c*(a + b*x)]^n, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[n]
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{v = FunctionOfTrig[u, x]}, ShowStep["", "Int[F[Cot[a+b*x]],x]", "-1/b*Subst[Int[F[x]/(1+x^2),x],x,Cot[a+b*x]]", Hold[ With[{d = FreeFactors[Cot[v], x]}, Dist[-d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Cot[v]/d, u, x], x], x, Cot[v]/d], x]]]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Cot[v], x], u, x, True] && TryPureTanSubst[ActivateTrig[u], x]] /; SimplifyFlag, Int[u_, x_Symbol, _:RubiNotebookReference["435ad314"]] := With[{v = FunctionOfTrig[u, x]}, With[{d = FreeFactors[Cot[v], x]}, Dist[-d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Cot[v]/d, u, x], x], x, Cot[v]/d], x]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Cot[v], x], u, x, True] && TryPureTanSubst[ActivateTrig[u], x]]]
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{v = FunctionOfTrig[u, x]}, ShowStep["", "Int[F[Tan[a+b*x]],x]", "1/b*Subst[Int[F[x]/(1+x^2),x],x,Tan[a+b*x]]", Hold[ With[{d = FreeFactors[Tan[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v]/d, u, x], x], x, Tan[v]/d], x]]]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Tan[v], x], u, x, True] && TryPureTanSubst[ActivateTrig[u], x]] /; SimplifyFlag, Int[u_, x_Symbol, _:RubiNotebookReference["411c6d4d"]] := With[{v = FunctionOfTrig[u, x]}, With[{d = FreeFactors[Tan[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v]/d, u, x], x], x, Tan[v]/d], x]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Tan[v], x], u, x, True] && TryPureTanSubst[ActivateTrig[u], x]]]
Int[F_[a_. + b_.*x_]^p_.*G_[c_. + d_.*x_]^q_., x_Symbol, _:RubiNotebookReference["40de077a"]] := Int[ExpandTrigReduce[ActivateTrig[F[a + b*x]^p*G[c + d*x]^q], x], x] /; FreeQ[{a, b, c, d}, x] && (EqQ[F, sin] || EqQ[F, cos]) && (EqQ[G, sin] || EqQ[G, cos]) && IGtQ[p, 0] && IGtQ[q, 0]
Int[F_[a_. + b_.*x_]^p_.*G_[c_. + d_.*x_]^q_.*H_[e_. + f_.*x_]^r_., x_Symbol, _:RubiNotebookReference["459111ff"]] := Int[ExpandTrigReduce[ ActivateTrig[F[a + b*x]^p*G[c + d*x]^q*H[e + f*x]^r], x], x] /; FreeQ[{a, b, c, d, e, f}, x] && (EqQ[F, sin] || EqQ[F, cos]) && (EqQ[G, sin] || EqQ[G, cos]) && (EqQ[H, sin] || EqQ[H, cos]) && IGtQ[p, 0] && IGtQ[q, 0] && IGtQ[r, 0]
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["44537bc8"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Cos] || EqQ[F, cos])
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["4615c591"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[SubstFor[1, Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Sin] || EqQ[F, sin])
Int[u_*Cosh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["47d7afa6"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x]
Int[u_*Sinh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["4c8be89b"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[SubstFor[1, Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x]
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["4d4982ac"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Cot] || EqQ[F, cot])
Int[u_*F_[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["fa24de46"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -1/(b*c)* Subst[Int[SubstFor[1/x, Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && (EqQ[F, Tan] || EqQ[F, tan])
Int[u_*Coth[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["fbe6b471"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x]
Int[u_*Tanh[c_.*(a_. + b_.*x_)], x_Symbol, _:RubiNotebookReference["f9a00a28"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, 1/(b*c)* Subst[Int[SubstFor[1/x, Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x]
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["f862601f"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(1 - d^2*x^2)^((n - 1)/2), Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Cos] || EqQ[F, cos])
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["fd2d769a"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(1 - d^2*x^2)^((-n - 1)/2), Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Sec] || EqQ[F, sec])
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["fcef1cad"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[ SubstFor[(1 - d^2*x^2)^((n - 1)/2), Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Sin] || EqQ[F, sin])
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["fea9a2f4"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -d/(b*c)* Subst[Int[ SubstFor[(1 - d^2*x^2)^((-n - 1)/2), Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Csc] || EqQ[F, csc])
Int[u_*Cosh[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["ff6bc8c3"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(1 + d^2*x^2)^((n - 1)/2), Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*Sech[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["f4378ffe"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(1 + d^2*x^2)^((-n - 1)/2), Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*Sinh[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["f5f5e5c9"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(-1 + d^2*x^2)^((n - 1)/2), Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*Csch[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["67f3e6ff"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, d/(b*c)* Subst[Int[ SubstFor[(-1 + d^2*x^2)^((-n - 1)/2), Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["66318cc8"]] := With[{d = FreeFactors[Sin[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[(1 - d^2*x^2)^((n - 1)/2)/x^n, Sin[c*(a + b*x)]/d, u, x], x], x, Sin[c*(a + b*x)]/d] /; FunctionOfQ[Sin[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Cot] || EqQ[F, cot])
Int[u_*F_[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["64773291"]] := With[{d = FreeFactors[Cos[c*(a + b*x)], x]}, -1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[(1 - d^2*x^2)^((n - 1)/2)/x^n, Cos[c*(a + b*x)]/d, u, x], x], x, Cos[c*(a + b*x)]/d] /; FunctionOfQ[Cos[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Tan] || EqQ[F, tan])
Int[u_*Coth[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["65b558a6"]] := With[{d = FreeFactors[Sinh[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[(1 + d^2*x^2)^((n - 1)/2)/x^n, Sinh[c*(a + b*x)]/d, u, x], x], x, Sinh[c*(a + b*x)]/d] /; FunctionOfQ[Sinh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*Tanh[c_.*(a_. + b_.*x_)]^n_, x_Symbol, _:RubiNotebookReference["60fa4e23"]] := With[{d = FreeFactors[Cosh[c*(a + b*x)], x]}, 1/(b*c*d^(n - 1))* Subst[Int[ SubstFor[(-1 + d^2*x^2)^((n - 1)/2)/x^n, Cosh[c*(a + b*x)]/d, u, x], x], x, Cosh[c*(a + b*x)]/d] /; FunctionOfQ[Cosh[c*(a + b*x)]/d, u, x]] /; FreeQ[{a, b, c}, x] && IntegerQ[(n - 1)/2] && NonsumQ[u]
Int[u_*(v_ + d_.*F_[c_.*(a_. + b_.*x_)]^n_.), x_Symbol, _:RubiNotebookReference["61382414"]] := With[{e = FreeFactors[Sin[c*(a + b*x)], x]}, Int[ActivateTrig[u*v], x] + d*Int[ActivateTrig[u]*Cos[c*(a + b*x)]^n, x] /; FunctionOfQ[Sin[c*(a + b*x)]/e, u, x]] /; FreeQ[{a, b, c, d}, x] && Not[FreeQ[v, x]] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Cos] || EqQ[F, cos])
Int[u_*(v_ + d_.*F_[c_.*(a_. + b_.*x_)]^n_.), x_Symbol, _:RubiNotebookReference["637e9a4d"]] := With[{e = FreeFactors[Cos[c*(a + b*x)], x]}, Int[ActivateTrig[u*v], x] + d*Int[ActivateTrig[u]*Sin[c*(a + b*x)]^n, x] /; FunctionOfQ[Cos[c*(a + b*x)]/e, u, x]] /; FreeQ[{a, b, c, d}, x] && Not[FreeQ[v, x]] && IntegerQ[(n - 1)/2] && NonsumQ[u] && (EqQ[F, Sin] || EqQ[F, sin])
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{v = FunctionOfTrig[u, x]}, ShowStep["", "Int[F[Sin[a+b*x]]*Cos[a+b*x],x]", "Subst[Int[F[x],x],x,Sin[a+b*x]]/b", Hold[ With[{d = FreeFactors[Sin[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1, Sin[v]/d, u/Cos[v], x], x], x, Sin[v]/d], x]]]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Sin[v], x], u/Cos[v], x]] /; SimplifyFlag, Int[u_, x_Symbol, _:RubiNotebookReference["62bcf07a"]] := With[{v = FunctionOfTrig[u, x]}, With[{d = FreeFactors[Sin[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1, Sin[v]/d, u/Cos[v], x], x], x, Sin[v]/d], x]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Sin[v], x], u/Cos[v], x]]]
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{v = FunctionOfTrig[u, x]}, ShowStep["", "Int[F[Cos[a+b*x]]*Sin[a+b*x],x]", "-Subst[Int[F[x],x],x,Cos[a+b*x]]/b", Hold[ With[{d = FreeFactors[Cos[v], x]}, Dist[-d/Coefficient[v, x, 1], Subst[Int[SubstFor[1, Cos[v]/d, u/Sin[v], x], x], x, Cos[v]/d], x]]]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Cos[v], x], u/Sin[v], x]] /; SimplifyFlag, Int[u_, x_Symbol, _:RubiNotebookReference["69e0b747"]] := With[{v = FunctionOfTrig[u, x]}, With[{d = FreeFactors[Cos[v], x]}, Dist[-d/Coefficient[v, x, 1], Subst[Int[SubstFor[1, Cos[v]/d, u/Sin[v], x], x], x, Cos[v]/d], x]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Cos[v], x], u/Sin[v], x]]]
Int[u_.*(a_. + b_.*cos[d_. + e_.*x_]^2 + c_.*sin[d_. + e_.*x_]^2)^p_., x_Symbol, _:RubiNotebookReference["6822dd70"]] := (a + c)^p*Int[ActivateTrig[u], x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[b - c, 0]
Int[u_.*(a_. + b_.*tan[d_. + e_.*x_]^2 + c_.*sec[d_. + e_.*x_]^2)^p_., x_Symbol, _:RubiNotebookReference["df4f819a"]] := (a + c)^p*Int[ActivateTrig[u], x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[b + c, 0]
Int[u_.*(a_. + b_.*cot[d_. + e_.*x_]^2 + c_.*csc[d_. + e_.*x_]^2)^p_., x_Symbol, _:RubiNotebookReference["de8debad"]] := (a + c)^p*Int[ActivateTrig[u], x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[b + c, 0]
Int[u_/y_, x_Symbol, _:RubiNotebookReference["dccb55f4"]] := With[{q = DerivativeDivides[ActivateTrig[y], ActivateTrig[u], x]}, q*Log[RemoveContent[ActivateTrig[y], x]] /; Not[FalseQ[q]]] /; Not[InertTrigFreeQ[u]]
Int[u_/(y_*w_), x_Symbol, _:RubiNotebookReference["dd093fc3"]] := With[{q = DerivativeDivides[ActivateTrig[y*w], ActivateTrig[u], x]}, q*Log[RemoveContent[ActivateTrig[y*w], x]] /; Not[FalseQ[q]]] /; Not[InertTrigFreeQ[u]]
Int[u_*y_^m_., x_Symbol, _:RubiNotebookReference["d8462946"]] := With[{q = DerivativeDivides[ActivateTrig[y], ActivateTrig[u], x]}, q*ActivateTrig[y^(m + 1)]/(m + 1) /; Not[FalseQ[q]]] /; FreeQ[m, x] && NeQ[m, -1] && Not[InertTrigFreeQ[u]]
Int[u_*y_^m_.*z_^n_., x_Symbol, _:RubiNotebookReference["d9844371"]] := With[{q = DerivativeDivides[ActivateTrig[y*z], ActivateTrig[u*z^(n - m)], x]}, q*ActivateTrig[y^(m + 1)*z^(m + 1)]/(m + 1) /; Not[FalseQ[q]]] /; FreeQ[{m, n}, x] && NeQ[m, -1] && Not[InertTrigFreeQ[u]]
Int[u_.*(a_.*F_[c_. + d_.*x_]^p_)^n_, x_Symbol, _:RubiNotebookReference["dbc2fd28"]] := With[{v = ActivateTrig[F[c + d*x]]}, a^IntPart[n]*(v/NonfreeFactors[v, x])^(p*IntPart[n])*(a*v^p)^ FracPart[n]/NonfreeFactors[v, x]^(p*FracPart[n])* Int[ActivateTrig[u]*NonfreeFactors[v, x]^(n*p), x]] /; FreeQ[{a, c, d, n, p}, x] && InertTrigQ[F] && Not[IntegerQ[n]] && IntegerQ[p]
Int[u_.*(a_.*(b_.*F_[c_. + d_.*x_])^p_)^n_., x_Symbol, _:RubiNotebookReference["da00971f"]] := With[{v = ActivateTrig[F[c + d*x]]}, a^IntPart[n]*(a*(b*v)^p)^FracPart[n]/(b*v)^(p*FracPart[n])* Int[ActivateTrig[u]*(b*v)^(n*p), x]] /; FreeQ[{a, b, c, d, n, p}, x] && InertTrigQ[F] && Not[IntegerQ[n]] && Not[IntegerQ[p]]
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{v = FunctionOfTrig[u, x]}, ShowStep["", "Int[F[Tan[a+b*x]],x]", "1/b*Subst[Int[F[x]/(1+x^2),x],x,Tan[a+b*x]]", Hold[ With[{d = FreeFactors[Tan[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v]/d, u, x], x], x, Tan[v]/d], x]]]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Tan[v], x], u, x]] /; SimplifyFlag && InverseFunctionFreeQ[u, x] && Not[ MatchQ[u, v_.*(c_.*tan[w_]^n_.*tan[z_]^n_.)^p_. /; FreeQ[{c, p}, x] && IntegerQ[n] && LinearQ[w, x] && EqQ[z, 2*w]]], Int[u_, x_Symbol, _:RubiNotebookReference["d15cd022"]] := With[{v = FunctionOfTrig[u, x]}, With[{d = FreeFactors[Tan[v], x]}, Dist[d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v]/d, u, x], x], x, Tan[v]/d], x]] /; Not[FalseQ[v]] && FunctionOfQ[NonfreeFactors[Tan[v], x], u, x]] /; InverseFunctionFreeQ[u, x] && Not[ MatchQ[u, v_.*(c_.*tan[w_]^n_.*tan[z_]^n_.)^p_. /; FreeQ[{c, p}, x] && IntegerQ[n] && LinearQ[w, x] && EqQ[z, 2*w]]]]
Int[u_*(c_.*sin[v_])^m_, x_Symbol, _:RubiNotebookReference["d09eba15"]] := With[{w = FunctionOfTrig[u*Sin[v/2]^(2*m)/(c*Tan[v/2])^m, x]}, (c*Sin[v])^m*(c*Tan[v/2])^m/Sin[v/2]^(2*m)* Int[u*Sin[v/2]^(2*m)/(c*Tan[v/2])^m, x] /; Not[FalseQ[w]] && FunctionOfQ[NonfreeFactors[Tan[w], x], u*Sin[v/2]^(2*m)/(c*Tan[v/2])^m, x]] /; FreeQ[c, x] && LinearQ[v, x] && IntegerQ[m + 1/2] && Not[SumQ[u]] && InverseFunctionFreeQ[u, x]
Int[u_.*(a_.*tan[c_. + d_.*x_]^n_. + b_.*sec[c_. + d_.*x_]^n_.)^p_, x_Symbol, _:RubiNotebookReference["cdfa2e74"]] := Int[ActivateTrig[u]*Sec[c + d*x]^(n*p)*(b + a*Sin[c + d*x]^n)^p, x] /; FreeQ[{a, b, c, d}, x] && IntegersQ[n, p]
Int[u_.*(a_.*cot[c_. + d_.*x_]^n_. + b_.*csc[c_. + d_.*x_]^n_.)^p_, x_Symbol, _:RubiNotebookReference["cc384443"]] := Int[ActivateTrig[u]*Csc[c + d*x]^(n*p)*(b + a*Cos[c + d*x]^n)^p, x] /; FreeQ[{a, b, c, d}, x] && IntegersQ[n, p]
Int[u_*(a_*F_[c_. + d_.*x_]^p_. + b_.*F_[c_. + d_.*x_]^q_.)^n_., x_Symbol, _:RubiNotebookReference["ce7efa1a"]] := Int[ActivateTrig[u*F[c + d*x]^(n*p)*(a + b*F[c + d*x]^(q - p))^n], x] /; FreeQ[{a, b, c, d, p, q}, x] && InertTrigQ[F] && IntegerQ[n] && PosQ[q - p]
Int[u_*(a_*F_[d_. + e_.*x_]^p_. + b_.*F_[d_. + e_.*x_]^q_. + c_.*F_[d_. + e_.*x_]^r_.)^n_., x_Symbol, _:RubiNotebookReference["cfbc902d"]] := Int[ActivateTrig[ u*F[d + e*x]^(n*p)*(a + b*F[d + e*x]^(q - p) + c*F[d + e*x]^(r - p))^n], x] /; FreeQ[{a, b, c, d, e, p, q, r}, x] && InertTrigQ[F] && IntegerQ[n] && PosQ[q - p] && PosQ[r - p]
Int[u_*(a_ + b_.*F_[d_. + e_.*x_]^p_. + c_.*F_[d_. + e_.*x_]^q_.)^n_., x_Symbol, _:RubiNotebookReference["caf386a8"]] := Int[ActivateTrig[ u*F[d + e*x]^(n*p)*(b + a*F[d + e*x]^(-p) + c*F[d + e*x]^(q - p))^ n], x] /; FreeQ[{a, b, c, d, e, p, q}, x] && InertTrigQ[F] && IntegerQ[n] && NegQ[p]
Int[u_.*(a_.*cos[c_. + d_.*x_] + b_.*sin[c_. + d_.*x_])^n_., x_Symbol, _:RubiNotebookReference["cb31ec9f"]] := Int[ActivateTrig[u]*(a*E^(-a/b*(c + d*x)))^n, x] /; FreeQ[{a, b, c, d, n}, x] && EqQ[a^2 + b^2, 0]
Int[u_, x_Symbol, _:RubiNotebookReference["c97752c6"]] := Int[TrigSimplify[u], x] /; TrigSimplifyQ[u]
Int[u_.*(a_*v_)^p_, x_Symbol, _:RubiNotebookReference["c8b538f1"]] := With[{uu = ActivateTrig[u], vv = ActivateTrig[v]}, a^IntPart[p]*(a*vv)^FracPart[p]/(vv^FracPart[p])* Int[uu*vv^p, x]] /; FreeQ[{a, p}, x] && Not[IntegerQ[p]] && Not[InertTrigFreeQ[v]]
Int[u_.*(v_^m_)^p_, x_Symbol, _:RubiNotebookReference["c3e97fcc"]] := With[{uu = ActivateTrig[u], vv = ActivateTrig[v]}, (vv^m)^FracPart[p]/(vv^(m*FracPart[p]))*Int[uu*vv^(m*p), x]] /; FreeQ[{m, p}, x] && Not[IntegerQ[p]] && Not[InertTrigFreeQ[v]]
Int[u_.*(v_^m_.*w_^n_.)^p_, x_Symbol, _:RubiNotebookReference["c22b15fb"]] := With[{uu = ActivateTrig[u], vv = ActivateTrig[v], ww = ActivateTrig[w]}, (vv^m*ww^n)^FracPart[p]/(vv^(m*FracPart[p])*ww^(n*FracPart[p]))* Int[uu*vv^(m*p)*ww^(n*p), x]] /; FreeQ[{m, n, p}, x] && Not[IntegerQ[p]] && (Not[InertTrigFreeQ[v]] || Not[InertTrigFreeQ[w]])
Int[u_, x_Symbol, _:RubiNotebookReference["75464911"]] := With[{v = ExpandTrig[u, x]}, Int[v, x] /; SumQ[v]] /; Not[InertTrigFreeQ[u]]
If[TrueQ[$LoadShowSteps], Int[u_, x_Symbol] := With[{w = Block[{$ShowSteps = False, $StepCounter = Null}, Int[SubstFor[ 1/(1 + FreeFactors[Tan[FunctionOfTrig[u, x]/2], x]^2*x^2), Tan[FunctionOfTrig[u, x]/2]/ FreeFactors[Tan[FunctionOfTrig[u, x]/2], x], u, x], x]]}, ShowStep["", "Int[F[Sin[a+b*x],Cos[a+b*x]],x]", "2/b*Subst[Int[1/(1+x^2)*F[2*x/(1+x^2),(1-x^2)/(1+x^2)],x],x, Tan[(a+b*x)/2]]", Hold[ Module[{v = FunctionOfTrig[u, x], d}, d = FreeFactors[Tan[v/2], x]; Dist[2*d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v/2]/d, u, x], x], x, Tan[v/2]/d], x]]]] /; CalculusFreeQ[w, x]] /; SimplifyFlag && InverseFunctionFreeQ[u, x] && Not[FalseQ[FunctionOfTrig[u, x]]], Int[u_, x_Symbol, _:RubiNotebookReference["74842326"]] := With[{w = Block[{$ShowSteps = False, $StepCounter = Null}, Int[SubstFor[ 1/(1 + FreeFactors[Tan[FunctionOfTrig[u, x]/2], x]^2*x^2), Tan[FunctionOfTrig[u, x]/2]/ FreeFactors[Tan[FunctionOfTrig[u, x]/2], x], u, x], x]]}, Module[{v = FunctionOfTrig[u, x], d}, d = FreeFactors[Tan[v/2], x]; Dist[2*d/Coefficient[v, x, 1], Subst[Int[SubstFor[1/(1 + d^2*x^2), Tan[v/2]/d, u, x], x], x, Tan[v/2]/d], x]] /; CalculusFreeQ[w, x]] /; InverseFunctionFreeQ[u, x] && Not[FalseQ[FunctionOfTrig[u, x]]]]
(* If[TrueQ[$LoadShowSteps], Int[u_,x_Symbol] := With[{v=FunctionOfTrig[u,x]}, ShowStep["","Int[F[Sin[a+b*x],Cos[a+b*x]],x]","2/b*Subst[Int[1/(1+x^ 2)*F[2*x/(1+x^2),(1-x^2)/(1+x^2)],x],x,Tan[(a+b*x)/2]]",Hold[ With[{d=FreeFactors[Tan[v/2],x]}, Dist[2*d/Coefficient[v,x,1],Subst[Int[SubstFor[1/(1+d^2*x^2),Tan[v/ 2]/d,u,x],x],x,Tan[v/2]/d],x]]]] /; Not[FalseQ[v]]] /; SimplifyFlag &&  InverseFunctionFreeQ[u,x], Int[u_,x_Symbol] := With[{v=FunctionOfTrig[u,x]}, With[{d=FreeFactors[Tan[v/2],x]}, Dist[2*d/Coefficient[v,x,1],Subst[Int[SubstFor[1/(1+d^2*x^2),Tan[v/ 2]/d,u,x],x],x,Tan[v/2]/d],x]] /; Not[FalseQ[v]]] /;  InverseFunctionFreeQ[u,x]] *)
Int[u_, x_Symbol, _:RubiNotebookReference["7700f748"]] := With[{v = ActivateTrig[u]}, CannotIntegrate[v, x]] /; Not[InertTrigFreeQ[u]]
