
(* ::Subsection::Closed:: *)
(* 4.5.11 (e x)^m (a+b sec(c+d x^n))^p *)
Int[(a_. + b_.*Sec[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6794406"]] := 1/n*Subst[Int[x^(1/n - 1)*(a + b*Sec[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, p}, x] && IGtQ[1/n, 0] && IntegerQ[p]
Int[(a_. + b_.*Csc[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["43ffa5f"]] := 1/n*Subst[Int[x^(1/n - 1)*(a + b*Csc[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, p}, x] && IGtQ[1/n, 0] && IntegerQ[p]
Int[(a_. + b_.*Sec[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["5fd9068"]] := Unintegrable[(a + b*Sec[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_. + b_.*Csc[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["b286ed"]] := Unintegrable[(a + b*Csc[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_. + b_.*Sec[c_. + d_.*u_^n_])^p_., x_Symbol, _:RubiNotebookReference["170ecda"]] := 1/Coefficient[u, x, 1]* Subst[Int[(a + b*Sec[c + d*x^n])^p, x], x, u] /; FreeQ[{a, b, c, d, n, p}, x] && LinearQ[u, x] && NeQ[u, x]
Int[(a_. + b_.*Csc[c_. + d_.*u_^n_])^p_., x_Symbol, _:RubiNotebookReference["3365283"]] := 1/Coefficient[u, x, 1]* Subst[Int[(a + b*Csc[c + d*x^n])^p, x], x, u] /; FreeQ[{a, b, c, d, n, p}, x] && LinearQ[u, x] && NeQ[u, x]
Int[(a_. + b_.*Sec[u_])^p_., x_Symbol, _:RubiNotebookReference["2f438b4"]] := Int[(a + b*Sec[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[(a_. + b_.*Csc[u_])^p_., x_Symbol, _:RubiNotebookReference["9a87f89"]] := Int[(a + b*Csc[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[x_^m_.*(a_. + b_.*Sec[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["86a15be"]] := 1/n*Subst[Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*Sec[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, m, n, p}, x] && IGtQ[Simplify[(m + 1)/n], 0] && IntegerQ[p]
Int[x_^m_.*(a_. + b_.*Csc[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6eb246c6"]] := 1/n*Subst[Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*Csc[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, m, n, p}, x] && IGtQ[Simplify[(m + 1)/n], 0] && IntegerQ[p]
Int[x_^m_.*(a_. + b_.*Sec[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6f702cf1"]] := Unintegrable[x^m*(a + b*Sec[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
Int[x_^m_.*(a_. + b_.*Csc[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6d3692a8"]] := Unintegrable[x^m*(a + b*Csc[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Sec[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6cf4f89f"]] := e^IntPart[m]*(e*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*Sec[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Csc[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["69bbee1a"]] := e^IntPart[m]*(e*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*Csc[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Sec[u_])^p_., x_Symbol, _:RubiNotebookReference["6879842d"]] := Int[(e*x)^m*(a + b*Sec[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, e, m, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[(e_*x_)^m_.*(a_. + b_.*Csc[u_])^p_., x_Symbol, _:RubiNotebookReference["6a3f3a74"]] := Int[(e*x)^m*(a + b*Csc[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, e, m, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[x_^m_.*Sec[a_. + b_.*x_^n_.]^p_*Sin[a_. + b_.*x_^n_.], x_Symbol, _:RubiNotebookReference["6bfd5043"]] := x^(m - n + 1)*Sec[a + b*x^n]^(p - 1)/(b*n*(p - 1)) - (m - n + 1)/(b*n*(p - 1))* Int[x^(m - n)*Sec[a + b*x^n]^(p - 1), x] /; FreeQ[{a, b, p}, x] && IntegerQ[n] && GeQ[m - n, 0] && NeQ[p, 1]
Int[x_^m_.*Csc[a_. + b_.*x_^n_.]^p_*Cos[a_. + b_.*x_^n_.], x_Symbol, _:RubiNotebookReference["60a1177e"]] := -x^(m - n + 1)*Csc[a + b*x^n]^(p - 1)/(b*n*(p - 1)) + (m - n + 1)/(b*n*(p - 1))* Int[x^(m - n)*Csc[a + b*x^n]^(p - 1), x] /; FreeQ[{a, b, p}, x] && IntegerQ[n] && GeQ[m - n, 0] && NeQ[p, 1]
