(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_.,x_Symbol] :=
  Int[ExpandIntegrand[Px*(a+b*x^2+c*x^4)^p,x],x] /;
FreeQ[{a,b,c},x] && PolyQ[Px,x] && IGtQ[p,0]


(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  With[{m=Expon[Px,x,Min]},
  Int[x^m*ExpandToSum[Px/x^m,x]*(a+b*x^2+c*x^4)^p,x] /;
 GtQ[m,0] && Not[MatchQ[Px,x^m*u_.]]] /;
FreeQ[{a,b,c,p},x] && PolyQ[Px,x]


(* ::Code:: *)
Int[Pn_*(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  Module[{n=Expon[Pn,x],k},
  Int[Sum[Coeff[Pn,x,2*k]*x^(2*k),{k,0,n/2}]*(a+b*x^2+c*x^4)^p,x] + 
  Int[x*Sum[Coeff[Pn,x,2*k+1]*x^(2*k),{k,0,(n-1)/2}]*(a+b*x^2+c*x^4)^p,x]] /;
FreeQ[{a,b,c,p},x] && PolyQ[Pn,x] && Not[PolyQ[Pn,x^2]]


(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_.,x_Symbol] :=
  With[{d=Coeff[Px,x,0],e=Coeff[Px,x,2],f=Coeff[Px,x,4]},
  d*x*(a+b*x^2+c*x^4)^(p+1)/a /;
 EqQ[a*e-b*d*(2*p+3),0] && EqQ[a*f-c*d*(4*p+5),0]] /;
FreeQ[{a,b,c,p},x] && PolyQ[Px,x^2] && EqQ[Expon[Px,x],4]


(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_.,x_Symbol] :=
  With[{d=Coeff[Px,x,0],e=Coeff[Px,x,2],f=Coeff[Px,x,4],g=Coeff[Px,x,6]},
  x*(3*a*d+(a*e-b*d*(2*p+3))*x^2)*(a+b*x^2+c*x^4)^(p+1)/(3*a^2) /;
 EqQ[3*a^2*g-c*(4*p+7)*(a*e-b*d*(2*p+3)),0] && EqQ[3*a^2*f-3*a*c*d*(4*p+5)-b*(2*p+5)*(a*e-b*d*(2*p+3)),0]] /;
FreeQ[{a,b,c,p},x] && PolyQ[Px,x^2] && EqQ[Expon[Px,x],6]


(* ::Code:: *)
Int[Px_/(a_+b_.*x_^2+c_.*x_^4),x_Symbol] :=
  Int[ExpandIntegrand[Px/(a+b*x^2+c*x^4),x],x] /;
FreeQ[{a,b,c},x] && PolyQ[Px,x^2] && Expon[Px,x^2]>1


(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  With[{d=Coeff[PolynomialRemainder[Px,a+b*x^2+c*x^4,x],x,0],
        e=Coeff[PolynomialRemainder[Px,a+b*x^2+c*x^4,x],x,2]},
  x*(a+b*x^2+c*x^4)^(p+1)*(a*b*e-d*(b^2-2*a*c)-c*(b*d-2*a*e)*x^2)/(2*a*(p+1)*(b^2-4*a*c)) + 
  1/(2*a*(p+1)*(b^2-4*a*c)) \[Star] Int[(a+b*x^2+c*x^4)^(p+1)*
    ExpandToSum[2*a*(p+1)*(b^2-4*a*c)*PolynomialQuotient[Px,a+b*x^2+c*x^4,x]+
      b^2*d*(2*p+3)-2*a*c*d*(4*p+5)-a*b*e+c*(4*p+7)*(b*d-2*a*e)*x^2,x],x]] /;
FreeQ[{a,b,c},x] && PolyQ[Px,x^2] && Expon[Px,x^2]>1 && NeQ[b^2-4*a*c,0] && LtQ[p,-1]


(* ::Code:: *)
Int[Px_*(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  With[{n=Expon[Px,x^2],e=Coeff[Px,x^2,Expon[Px,x^2]]},
  e*x^(2*n-3)*(a+b*x^2+c*x^4)^(p+1)/(c*(2*n+4*p+1)) + 
  1/(c*(2*n+4*p+1)) \[Star] Int[(a+b*x^2+c*x^4)^p*
    ExpandToSum[c*(2*n+4*p+1)*Px-a*e*(2*n-3)*x^(2*n-4)-b*e*(2*n+2*p-1)*x^(2*n-2)-c*e*(2*n+4*p+1)*x^(2*n),x],x]] /;
FreeQ[{a,b,c,p},x] && PolyQ[Px,x^2] && Expon[Px,x^2]>1 && NeQ[b^2-4*a*c,0] && Not[LtQ[p,-1]]



