
(* ::Subsection::Closed:: *)
(* 1.2.2.4 (f x)^m (d+e x^2)^q (a+b x^2+c x^4)^p *)
(* Int[(f_.*x_)^m_.*(e_.*x_^2)^q_.*(a_+b_.*x_^2+c_.*x_^4)^p_.,x_ Symbol] := e^q/f^(2*q)*Int[(f*x)^(m+2*q)*(a+b*x^2+c*x^4)^p,x] /;  FreeQ[{a,b,c,e,f,m,p},x] && IntegerQ[q] *)
(* Int[(f_.*x_)^m_.*(e_.*x_^2)^q_.*(a_+c_.*x_^4)^p_.,x_Symbol] :=  e^q/f^(2*q)*Int[(f*x)^(m+2*q)*(a+c*x^4)^p,x] /;  FreeQ[{a,c,e,f,m,p},x] && IntegerQ[q] *)
Int[x_^m_.*(e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["795556f7"]] := 1/(2*e^((m - 1)/2))* Subst[Int[(e*x)^(q + (m - 1)/2)*(a + b*x + c*x^2)^p, x], x, x^2] /; FreeQ[{a, b, c, e, p, q}, x] && Not[IntegerQ[q]] && IntegerQ[(m - 1)/2]
Int[x_^m_.*(e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7c1a4072"]] := 1/(2*e^((m - 1)/2))* Subst[Int[(e*x)^(q + (m - 1)/2)*(a + c*x^2)^p, x], x, x^2] /; FreeQ[{a, c, e, p, q}, x] && Not[IntegerQ[q]] && IntegerQ[(m - 1)/2]
Int[(f_.*x_)^m_.*(e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7dd82a45"]] := e^IntPart[q]*(e*x^2)^ FracPart[q]/(f^(2*IntPart[q])*(f*x)^(2*FracPart[q]))* Int[(f*x)^(m + 2*q)*(a + b*x^2 + c*x^4)^p, x] /; FreeQ[{a, b, c, e, f, m, p, q}, x] && Not[IntegerQ[q]]
Int[(f_.*x_)^m_.*(e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7f9e941c"]] := e^IntPart[q]*(e*x^2)^ FracPart[q]/(f^(2*IntPart[q])*(f*x)^(2*FracPart[q]))* Int[(f*x)^(m + 2*q)*(a + c*x^4)^p, x] /; FreeQ[{a, c, e, f, m, p, q}, x] && Not[IntegerQ[q]]
Int[x_*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7e5cfe2b"]] := 1/2*Subst[Int[(d + e*x)^q*(a + b*x + c*x^2)^p, x], x, x^2] /; FreeQ[{a, b, c, d, e, p, q}, x]
Int[x_*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7500b916"]] := 1/2*Subst[Int[(d + e*x)^q*(a + c*x^2)^p, x], x, x^2] /; FreeQ[{a, c, d, e, p, q}, x]
(* Int[(f_.*x_)^m_.*(d_+e_.*x_^2)^q_.*(a_+b_.*x_^2+c_.*x_^4)^p_.,x_ Symbol] := 1/c^p*Int[(f*x)^m*(d+e*x^2)^q*(b/2+c*x^2)^(2*p),x] /;  FreeQ[{a,b,c,d,e,f,m,p,q},x] && EqQ[b^2-4*a*c,0] && IntegerQ[p] *)
Int[x_^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["e7e60d5"]] := 1/2*Subst[Int[x^((m - 1)/2)*(d + e*x)^q*(a + b*x + c*x^2)^p, x], x, x^2] /; FreeQ[{a, b, c, d, e, p, q}, x] && EqQ[b^2 - 4*a*c, 0] && Not[IntegerQ[p]] && IGtQ[(m + 1)/2, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["fbc0ae2"]] := (a + b*x^2 + c*x^4)^ FracPart[p]/(c^IntPart[p]*(b/2 + c*x^2)^(2*FracPart[p]))* Int[(f*x)^m*(d + e*x^2)^q*(b/2 + c*x^2)^(2*p), x] /; FreeQ[{a, b, c, d, e, f, m, p, q}, x] && EqQ[b^2 - 4*a*c, 0] && Not[IntegerQ[p]]
Int[x_^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["dfab4bb"]] := 1/2*Subst[Int[x^((m - 1)/2)*(d + e*x)^q*(a + b*x + c*x^2)^p, x], x, x^2] /; FreeQ[{a, b, c, d, e, p, q}, x] && IntegerQ[(m - 1)/2]
Int[x_^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["c38de8c"]] := 1/2*Subst[Int[x^((m - 1)/2)*(d + e*x)^q*(a + c*x^2)^p, x], x, x^2] /; FreeQ[{a, c, d, e, p, q}, x] && IntegerQ[(m + 1)/2]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["977c809"]] := Int[(f*x)^m*(d + e*x^2)^(q + p)*(a/d + c/e*x^2)^p, x] /; FreeQ[{a, b, c, d, e, f, m, q}, x] && NeQ[b^2 - 4*a*c, 0] && EqQ[c*d^2 - b*d*e + a*e^2, 0] && IntegerQ[p]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["8b5a23e"]] := Int[(f*x)^m*(d + e*x^2)^(q + p)*(a/d + c/e*x^2)^p, x] /; FreeQ[{a, c, d, e, f, q, m, q}, x] && EqQ[c*d^2 + a*e^2, 0] && IntegerQ[p]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["af31c67"]] := (a + b*x^2 + c*x^4)^ FracPart[ p]/((d + e*x^2)^FracPart[p]*(a/d + (c*x^2)/e)^FracPart[p])* Int[(f*x)^m*(d + e*x^2)^(q + p)*(a/d + c/e*x^2)^p, x] /; FreeQ[{a, b, c, d, e, f, m, p, q}, x] && NeQ[b^2 - 4*a*c, 0] && EqQ[c*d^2 - b*d*e + a*e^2, 0] && Not[IntegerQ[p]]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["b317650"]] := (a + c*x^4)^ FracPart[ p]/((d + e*x^2)^FracPart[p]*(a/d + (c*x^2)/e)^FracPart[p])* Int[(f*x)^m*(d + e*x^2)^(q + p)*(a/d + c/e*x^2)^p, x] /; FreeQ[{a, c, d, e, f, m, p, q}, x] && EqQ[c*d^2 + a*e^2, 0] && Not[IntegerQ[p]]
Int[x_^m_.*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["6d316d"]] := (-d)^(m/2 - 1)*(c*d^2 - b*d*e + a*e^2)^p* x*(d + e*x^2)^(q + 1)/(2*e^(2*p + m/2)*(q + 1)) + 1/(2*e^(2*p + m/2)*(q + 1))*Int[(d + e*x^2)^(q + 1)* ExpandToSum[ Together[ 1/(d + e*x^2)*(2*e^(2*p + m/2)*(q + 1)* x^m*(a + b*x^2 + c*x^4)^p - (-d)^(m/2 - 1)*(c*d^2 - b*d*e + a*e^2)^ p*(d + e*(2*q + 3)*x^2))], x], x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && ILtQ[q, -1] && IGtQ[m/2, 0]
Int[x_^m_.*(d_ + e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1af5b5a"]] := (-d)^(m/2 - 1)*(c*d^2 + a*e^2)^p* x*(d + e*x^2)^(q + 1)/(2*e^(2*p + m/2)*(q + 1)) + 1/(2*e^(2*p + m/2)*(q + 1))*Int[(d + e*x^2)^(q + 1)* ExpandToSum[ Together[ 1/(d + e*x^2)*(2*e^(2*p + m/2)*(q + 1)*x^m*(a + c*x^4)^p - (-d)^(m/2 - 1)*(c*d^2 + a*e^2)^ p*(d + e*(2*q + 3)*x^2))], x], x] /; FreeQ[{a, c, d, e}, x] && IGtQ[p, 0] && ILtQ[q, -1] && IGtQ[m/2, 0]
Int[x_^m_*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1ccbcf3b"]] := (-d)^(m/2 - 1)*(c*d^2 - b*d*e + a*e^2)^p* x*(d + e*x^2)^(q + 1)/(2*e^(2*p + m/2)*(q + 1)) + (-d)^(m/2 - 1)/(2*e^(2*p)*(q + 1))*Int[x^m*(d + e*x^2)^(q + 1)* ExpandToSum[ Together[ 1/(d + e*x^2)*(2*(-d)^(-m/2 + 1)* e^(2*p)*(q + 1)*(a + b*x^2 + c*x^4)^p - (e^(-m/2)*(c*d^2 - b*d*e + a*e^2)^p*x^(-m))*(d + e*(2*q + 3)*x^2))], x], x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && ILtQ[q, -1] && ILtQ[m/2, 0]
Int[x_^m_*(d_ + e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1d09a50c"]] := (-d)^(m/2 - 1)*(c*d^2 + a*e^2)^p* x*(d + e*x^2)^(q + 1)/(2*e^(2*p + m/2)*(q + 1)) + (-d)^(m/2 - 1)/(2*e^(2*p)*(q + 1))*Int[x^m*(d + e*x^2)^(q + 1)* ExpandToSum[ Together[ 1/(d + e*x^2)*(2*(-d)^(-m/2 + 1)* e^(2*p)*(q + 1)*(a + c*x^4)^p - (e^(-m/2)*(c*d^2 + a*e^2)^p*x^(-m))*(d + e*(2*q + 3)*x^2))], x], x] /; FreeQ[{a, c, d, e}, x] && IGtQ[p, 0] && ILtQ[q, -1] && ILtQ[m/2, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1f4f1b55"]] := Int[ExpandIntegrand[(f*x)^m (d + e*x^2)^q*(a + b*x^2 + c*x^4)^p, x], x] /; FreeQ[{a, b, c, d, e, f, m, q}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && IGtQ[q, -2]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1e8d7162"]] := Int[ExpandIntegrand[(f*x)^m (d + e*x^2)^q*(a + c*x^4)^p, x], x] /; FreeQ[{a, c, d, e, f, m, q}, x] && IGtQ[p, 0] && IGtQ[q, -2]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1bc267e7"]] := With[{Qx = PolynomialQuotient[(a + b*x^2 + c*x^4)^p, d + e*x^2, x], R = Coeff[ PolynomialRemainder[(a + b*x^2 + c*x^4)^p, d + e*x^2, x], x, 0]}, -R*(f*x)^(m + 1)*(d + e*x^2)^(q + 1)/(2*d*f*(q + 1)) + f/(2*d*(q + 1))* Int[(f*x)^(m - 1)*(d + e*x^2)^(q + 1)* ExpandToSum[2*d*(q + 1)*x*Qx + R*(m + 2*q + 3)*x, x], x]] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && LtQ[q, -1] && GtQ[m, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1a000dd0"]] := With[{Qx = PolynomialQuotient[(a + c*x^4)^p, d + e*x^2, x], R = Coeff[PolynomialRemainder[(a + c*x^4)^p, d + e*x^2, x], x, 0]}, -R*(f*x)^(m + 1)*(d + e*x^2)^(q + 1)/(2*d*f*(q + 1)) + f/(2*d*(q + 1))* Int[(f*x)^(m - 1)*(d + e*x^2)^(q + 1)* ExpandToSum[2*d*(q + 1)*x*Qx + R*(m + 2*q + 3)*x, x], x]] /; FreeQ[{a, c, d, e, f}, x] && IGtQ[p, 0] && LtQ[q, -1] && GtQ[m, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1846b389"]] := With[{Qx = PolynomialQuotient[(a + b*x^2 + c*x^4)^p, f*x, x], R = PolynomialRemainder[(a + b*x^2 + c*x^4)^p, f*x, x]}, R*(f*x)^(m + 1)*(d + e*x^2)^(q + 1)/(d*f*(m + 1)) + 1/(d*f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^q* ExpandToSum[d*f*(m + 1)*Qx/x - e*R*(m + 2*q + 3), x], x]] /; FreeQ[{a, b, c, d, e, f, q}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["1984d9be"]] := With[{Qx = PolynomialQuotient[(a + c*x^4)^p, f*x, x], R = PolynomialRemainder[(a + c*x^4)^p, f*x, x]}, R*(f*x)^(m + 1)*(d + e*x^2)^(q + 1)/(d*f*(m + 1)) + 1/(d*f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^q* ExpandToSum[d*f*(m + 1)*Qx/x - e*R*(m + 2*q + 3), x], x]] /; FreeQ[{a, c, d, e, f, q}, x] && IGtQ[p, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["12d89e83"]] := c^p*(f*x)^(m + 4*p - 1)*(d + e*x^2)^(q + 1)/(e* f^(4*p - 1)*(m + 4*p + 2*q + 1)) + 1/(e*(m + 4*p + 2*q + 1))*Int[(f*x)^m*(d + e*x^2)^q* ExpandToSum[ e*(m + 4*p + 2*q + 1)*((a + b*x^2 + c*x^4)^p - c^p*x^(4*p)) - d*c^p*(m + 4*p - 1)*x^(4*p - 2), x], x] /; FreeQ[{a, b, c, d, e, f, m, q}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[p, 0] && Not[IntegerQ[q]] && NeQ[m + 4*p + 2*q + 1, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["131af4b4"]] := c^p*(f*x)^(m + 4*p - 1)*(d + e*x^2)^(q + 1)/(e* f^(4*p - 1)*(m + 4*p + 2*q + 1)) + 1/(e*(m + 4*p + 2*q + 1))*Int[(f*x)^m*(d + e*x^2)^q* ExpandToSum[ e*(m + 4*p + 2*q + 1)*((a + c*x^4)^p - c^p*x^(4*p)) - d*c^p*(m + 4*p - 1)*x^(4*p - 2), x], x] /; FreeQ[{a, c, d, e, f, m, q}, x] && IGtQ[p, 0] && Not[IntegerQ[q]] && NeQ[m + 4*p + 2*q + 1, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["a477a85e"]] := With[{k = Denominator[m]}, k/f*Subst[ Int[x^(k*(m + 1) - 1)*(d + e*x^(2*k)/f^2)^ q*(a + b*x^(2*k)/f^k + c*x^(4*k)/f^4)^p, x], x, (f*x)^(1/k)]] /; FreeQ[{a, b, c, d, e, f, p, q}, x] && NeQ[b^2 - 4*a*c, 0] && FractionQ[m] && IntegerQ[p]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["a5b5c269"]] := With[{k = Denominator[m]}, k/f*Subst[ Int[x^(k*(m + 1) - 1)*(d + e*x^(2*k)/f)^q*(a + c*x^(4*k)/f)^p, x], x, (f*x)^(1/k)]] /; FreeQ[{a, c, d, e, f, p, q}, x] && FractionQ[m] && IntegerQ[p]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a7f37c30"]] := (f*x)^(m + 1)*(a + b*x^2 + c*x^4)^ p*(d*(m + 4*p + 3) + e*(m + 1)*x^2)/(f*(m + 1)*(m + 4*p + 3)) + 2*p/(f^2*(m + 1)*(m + 4*p + 3))* Int[(f*x)^(m + 2)*(a + b*x^2 + c*x^4)^(p - 1)* Simp[2*a*e*(m + 1) - b*d*(m + 4*p + 3) + (b*e*(m + 1) - 2*c*d*(m + 4*p + 3))*x^2, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && GtQ[p, 0] && LtQ[m, -1] && m + 4*p + 3 != 0 && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a6311607"]] := (f*x)^(m + 1)*(a + c*x^4)^ p*(d*(m + 4*p + 3) + e*(m + 1)*x^2)/(f*(m + 1)*(m + 4*p + 3)) + 4*p/(f^2*(m + 1)*(m + 4*p + 3))* Int[(f*x)^(m + 2)*(a + c*x^4)^(p - 1)*(a*e*(m + 1) - c*d*(m + 4*p + 3)*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && GtQ[p, 0] && LtQ[m, -1] && m + 4*p + 3 != 0 && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a37e0082"]] := (f*x)^(m + 1)*(a + b*x^2 + c*x^4)^ p*(b*e*2*p + c*d*(m + 4*p + 3) + c*e*(4*p + m + 1)*x^2)/ (c*f*(4*p + m + 1)*(m + 4*p + 3)) + 2*p/(c*(4*p + m + 1)*(m + 4*p + 3))* Int[(f*x)^m*(a + b*x^2 + c*x^4)^(p - 1)* Simp[2*a*c*d*(m + 4*p + 3) - a*b*e*(m + 1) + (2*a*c*e*(4*p + m + 1) + b*c*d*(m + 4*p + 3) - b^2*e*(m + 2*p + 1))*x^2, x], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && GtQ[p, 0] && NeQ[4*p + m + 1, 0] && NeQ[m + 4*p + 3, 0] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a2bc6ab5"]] := (f*x)^(m + 1)*(a + c*x^4)^ p*(c*d*(m + 4*p + 3) + c*e*(4*p + m + 1)*x^2)/(c* f*(4*p + m + 1)*(m + 4*p + 3)) + 4*a*p/((4*p + m + 1)*(m + 4*p + 3))* Int[(f*x)^m*(a + c*x^4)^(p - 1)* Simp[d*(m + 4*p + 3) + e*(4*p + m + 1)*x^2, x], x] /; FreeQ[{a, c, d, e, f, m}, x] && GtQ[p, 0] && NeQ[4*p + m + 1, 0] && NeQ[m + 4*p + 3, 0] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a0fad4ec"]] := f*(f*x)^(m - 1)*(a + b*x^2 + c*x^4)^(p + 1)*(b*d - 2*a*e - (b*e - 2*c*d)*x^2)/(2*(p + 1)*(b^2 - 4*a*c)) - f^2/(2*(p + 1)*(b^2 - 4*a*c))* Int[(f*x)^(m - 2)*(a + b*x^2 + c*x^4)^(p + 1)* Simp[(m - 1)*(b*d - 2*a*e) - (4*p + 4 + m + 1)*(b*e - 2*c*d)* x^2, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && GtQ[m, 1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["a138bedb"]] := f*(f*x)^(m - 1)*(a + c*x^4)^(p + 1)*(a*e - c*d*x^2)/(4*a*c*(p + 1)) - f^2/(4*a*c*(p + 1))* Int[(f*x)^(m - 2)*(a + c*x^4)^(p + 1)*(a*e*(m - 1) - c*d*(4*p + 4 + m + 1)*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && LtQ[p, -1] && GtQ[m, 1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["aa64f9e6"]] := -(f*x)^(m + 1)*(a + b*x^2 + c*x^4)^(p + 1)*(d*(b^2 - 2*a*c) - a*b*e + (b*d - 2*a*e)*c*x^2)/(2*a* f*(p + 1)*(b^2 - 4*a*c)) + 1/(2*a*(p + 1)*(b^2 - 4*a*c))* Int[(f*x)^m*(a + b*x^2 + c*x^4)^(p + 1)* Simp[d*(b^2*(m + 2*(p + 1) + 1) - 2*a*c*(m + 4*(p + 1) + 1)) - a*b*e*(m + 1) + c*(m + 2*(2*p + 3) + 1)*(b*d - 2*a*e)*x^2, x], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["aba693d1"]] := -(f*x)^(m + 1)*(a + c*x^4)^(p + 1)*(d + e*x^2)/(4*a* f*(p + 1)) + 1/(4*a*(p + 1))* Int[(f*x)^m*(a + c*x^4)^(p + 1)* Simp[d*(m + 4*(p + 1) + 1) + e*(m + 2*(2*p + 3) + 1)*x^2, x], x] /; FreeQ[{a, c, d, e, f, m}, x] && LtQ[p, -1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["39a090e7"]] := e*f*(f*x)^(m - 1)*(a + b*x^2 + c*x^4)^(p + 1)/(c*(m + 4*p + 3)) - f^2/(c*(m + 4*p + 3))* Int[(f*x)^(m - 2)*(a + b*x^2 + c*x^4)^p* Simp[a*e*(m - 1) + (b*e*(m + 2*p + 1) - c*d*(m + 4*p + 3))*x^2, x], x] /; FreeQ[{a, b, c, d, e, f, p}, x] && NeQ[b^2 - 4*a*c, 0] && GtQ[m, 1] && NeQ[m + 4*p + 3, 0] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["3862fad0"]] := e*f*(f*x)^(m - 1)*(a + c*x^4)^(p + 1)/(c*(m + 4*p + 3)) - f^2/(c*(m + 4*p + 3))* Int[(f*x)^(m - 2)*(a + c*x^4)^ p*(a*e*(m - 1) - c*d*(m + 4*p + 3)*x^2), x] /; FreeQ[{a, c, d, e, f, p}, x] && GtQ[m, 1] && NeQ[m + 4*p + 3, 0] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["3a244489"]] := d*(f*x)^(m + 1)*(a + b*x^2 + c*x^4)^(p + 1)/(a*f*(m + 1)) + 1/(a*f^2*(m + 1))* Int[(f*x)^(m + 2)*(a + b*x^2 + c*x^4)^p* Simp[a*e*(m + 1) - b*d*(m + 2*p + 3) - c*d*(m + 4*p + 5)*x^2, x], x] /; FreeQ[{a, b, c, d, e, f, p}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[m, -1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["3be62ebe"]] := d*(f*x)^(m + 1)*(a + c*x^4)^(p + 1)/(a*f*(m + 1)) + 1/(a*f^2*(m + 1))* Int[(f*x)^(m + 2)*(a + c*x^4)^ p*(a*e*(m + 1) - c*d*(m + 4*p + 5)*x^2), x] /; FreeQ[{a, c, d, e, f, p}, x] && LtQ[m, -1] && IntegerQ[2*p] && (IntegerQ[p] || IntegerQ[m])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["3ea9383b"]] := With[{r = Rt[c/e*(2*c*d - b*e), 2]}, e/2*Int[(f*x)^m/(c*d/e - r*x + c*x^2), x] + e/2*Int[(f*x)^m/(c*d/e + r*x + c*x^2), x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && EqQ[c*d^2 - a*e^2, 0] && GtQ[d/e, 0] && PosQ[c/e*(2*c*d - b*e)]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["3f6b520c"]] := With[{r = Rt[2*c^2*d/e, 2]}, e/2*Int[(f*x)^m/(c*d/e - r*x + c*x^2), x] + e/2*Int[(f*x)^m/(c*d/e + r*x + c*x^2), x]] /; FreeQ[{a, c, d, e, f, m}, x] && EqQ[c*d^2 - a*e^2, 0] && GtQ[d/e, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["3d2dec55"]] := With[{q = Rt[b^2 - 4*a*c, 2]}, (e/2 + (2*c*d - b*e)/(2*q))* Int[(f*x)^m/(b/2 - q/2 + c*x^2), x] + (e/2 - (2*c*d - b*e)/(2*q))* Int[(f*x)^m/(b/2 + q/2 + c*x^2), x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["3cef8662"]] := With[{q = Rt[-a*c, 2]}, -(e/2 + c*d/(2*q))* Int[(f*x)^m/(q - c*x^2), x] + (e/2 - c*d/(2*q))* Int[(f*x)^m/(q + c*x^2), x]] /; FreeQ[{a, c, d, e, f, m}, x]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_./(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["37b3c15f"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q/(a + b*x^2 + c*x^4), x], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && IntegerQ[q] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_./(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["3671ab68"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q/(a + c*x^4), x], x] /; FreeQ[{a, c, d, e, f, m}, x] && IntegerQ[q] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_./(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["811cf782"]] := Int[ExpandIntegrand[(f*x)^m, (d + e*x^2)^q/(a + b*x^2 + c*x^4), x], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && IntegerQ[q] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_./(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["80de9db5"]] := Int[ExpandIntegrand[(f*x)^m, (d + e*x^2)^q/(a + c*x^4), x], x] /; FreeQ[{a, c, d, e, f, m}, x] && IntegerQ[q] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["829823ec"]] := f^4/c^2*Int[(f*x)^(m - 4)*(c*d - b*e + c*e*x^2)*(d + e*x^2)^(q - 1), x] - f^4/c^2* Int[(f*x)^(m - 4)*(d + e*x^2)^(q - 1)* Simp[a*(c*d - b*e) + (b*c*d - b^2*e + a*c*e)*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && GtQ[q, 0] && GtQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["835a49db"]] := f^4/c*Int[(f*x)^(m - 4)*(d + e*x^2)^q, x] - a*f^4/c*Int[(f*x)^(m - 4)*(d + e*x^2)^q/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f, q}, x] && Not[IntegerQ[q]] && GtQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["86155f5e"]] := e*f^2/c*Int[(f*x)^(m - 2)*(d + e*x^2)^(q - 1), x] - f^2/c* Int[(f*x)^(m - 2)*(d + e*x^2)^(q - 1)* Simp[a*e - (c*d - b*e)*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && GtQ[q, 0] && GtQ[m, 1] && LeQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["87d73569"]] := e*f^2/c*Int[(f*x)^(m - 2)*(d + e*x^2)^(q - 1), x] - f^2/c* Int[(f*x)^(m - 2)*(d + e*x^2)^(q - 1)* Simp[a*e - c*d*x^2, x]/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f}, x] && Not[IntegerQ[q]] && GtQ[q, 0] && GtQ[m, 1] && LeQ[m, 3]
Int[(f_.*x_)^m_*(d_. + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["85918b30"]] := d/a*Int[(f*x)^m*(d + e*x^2)^(q - 1), x] - 1/(a*f^2)* Int[(f*x)^(m + 2)*(d + e*x^2)^(q - 1)* Simp[b*d - a*e + c*d*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && GtQ[q, 0] && LtQ[m, 0]
Int[(f_.*x_)^m_*(d_. + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["8453e107"]] := d/a*Int[(f*x)^m*(d + e*x^2)^(q - 1), x] + 1/(a*f^2)* Int[(f*x)^(m + 2)*(d + e*x^2)^(q - 1)* Simp[a*e - c*d*x^2, x]/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f}, x] && Not[IntegerQ[q]] && GtQ[q, 0] && LtQ[m, 0]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["8f0fa63a"]] := d^2*f^4/(c*d^2 - b*d*e + a*e^2)*Int[(f*x)^(m - 4)*(d + e*x^2)^q, x] - f^4/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 4)*(d + e*x^2)^(q + 1)* Simp[a*d + (b*d - a*e)*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && LtQ[q, -1] && GtQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["8ecdcc0d"]] := d^2*f^4/(c*d^2 + a*e^2)*Int[(f*x)^(m - 4)*(d + e*x^2)^q, x] - a*f^4/(c*d^2 + a*e^2)* Int[(f*x)^(m - 4)*(d + e*x^2)^(q + 1)*(d - e*x^2)/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f}, x] && Not[IntegerQ[q]] && LtQ[q, -1] && GtQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["93a9586c"]] := -d*e*f^2/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 2)*(d + e*x^2)^q, x] + f^2/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 2)*(d + e*x^2)^(q + 1)* Simp[a*e + c*d*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && LtQ[q, -1] && GtQ[m, 1] && LeQ[m, 3]
Int[(f_.*x_)^m_.*(d_. + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["926b325b"]] := -d*e*f^2/(c*d^2 + a*e^2)* Int[(f*x)^(m - 2)*(d + e*x^2)^q, x] + f^2/(c*d^2 + a*e^2)* Int[(f*x)^(m - 2)*(d + e*x^2)^(q + 1)* Simp[a*e + c*d*x^2, x]/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f}, x] && Not[IntegerQ[q]] && LtQ[q, -1] && GtQ[m, 1] && LeQ[m, 3]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["902d8c02"]] := e^2/(c*d^2 - b*d*e + a*e^2)*Int[(f*x)^m*(d + e*x^2)^q, x] + 1/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^m*(d + e*x^2)^(q + 1)* Simp[c*d - b*e - c*e*x^2, x]/(a + b*x^2 + c*x^4), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && LtQ[q, -1]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["91efe635"]] := e^2/(c*d^2 + a*e^2)*Int[(f*x)^m*(d + e*x^2)^q, x] + c/(c*d^2 + a*e^2)* Int[(f*x)^m*(d + e*x^2)^(q + 1)*(d - e*x^2)/(a + c*x^4), x] /; FreeQ[{a, c, d, e, f, m}, x] && Not[IntegerQ[q]] && LtQ[q, -1]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["94a0f0b0"]] := Int[ExpandIntegrand[(d + e*x^2)^q, (f*x)^m/(a + b*x^2 + c*x^4), x], x] /; FreeQ[{a, b, c, d, e, f, q}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["95629a87"]] := Int[ExpandIntegrand[(d + e*x^2)^q, (f*x)^m/(a + c*x^4), x], x] /; FreeQ[{a, c, d, e, f, q}, x] && Not[IntegerQ[q]] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["972424de"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q, 1/(a + b*x^2 + c*x^4), x], x] /; FreeQ[{a, b, c, d, e, f, m, q}, x] && NeQ[b^2 - 4*a*c, 0] && Not[IntegerQ[q]] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["96e64ee9"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q, 1/(a + c*x^4), x], x] /; FreeQ[{a, c, d, e, f, m, q}, x] && Not[IntegerQ[q]] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + b_.*x_^2 + c_.*x_^4), x_Symbol, _:RubiNotebookReference["9dba09d4"]] := With[{r = Rt[b^2 - 4*a*c, 2]}, 2*c/r*Int[(f*x)^m*(d + e*x^2)^q/(b - r + 2*c*x^2), x] - 2*c/r*Int[(f*x)^m*(d + e*x^2)^q/(b + r + 2*c*x^2), x]] /; FreeQ[{a, b, c, d, e, f, m, q}, x] && NeQ[b^2 - 4*a*c, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_/(a_ + c_.*x_^4), x_Symbol, _:RubiNotebookReference["9c7863e3"]] := With[{r = Rt[-a*c, 2]}, -c/(2*r)*Int[(f*x)^m*(d + e*x^2)^q/(r - c*x^2), x] - c/(2*r)*Int[(f*x)^m*(d + e*x^2)^q/(r + c*x^2), x]] /; FreeQ[{a, c, d, e, f, m, q}, x]
Int[(f_.*x_)^m_*(a_. + b_.*x_^2 + c_.*x_^4)^p_./(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2b153f09"]] := 1/d^2*Int[(f*x)^ m*(a*d + (b*d - a*e)*x^2)*(a + b*x^2 + c*x^4)^(p - 1), x] + (c*d^2 - b*d*e + a*e^2)/(d^2*f^4)* Int[(f*x)^(m + 4)*(a + b*x^2 + c*x^4)^(p - 1)/(d + e*x^2), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && GtQ[p, 0] && LtQ[m, -2]
Int[(f_.*x_)^m_*(a_ + c_.*x_^4)^p_./(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2ad7553e"]] := a/d^2*Int[(f*x)^m*(d - e*x^2)*(a + c*x^4)^(p - 1), x] + (c*d^2 + a*e^2)/(d^2*f^4)* Int[(f*x)^(m + 4)*(a + c*x^4)^(p - 1)/(d + e*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && GtQ[p, 0] && LtQ[m, -2]
Int[(f_.*x_)^m_*(a_. + b_.*x_^2 + c_.*x_^4)^p_./(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2891eb67"]] := 1/(d*e)*Int[(f*x)^m*(a*e + c*d*x^2)*(a + b*x^2 + c*x^4)^(p - 1), x] - (c*d^2 - b*d*e + a*e^2)/(d*e*f^2)* Int[(f*x)^(m + 2)*(a + b*x^2 + c*x^4)^(p - 1)/(d + e*x^2), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && GtQ[p, 0] && LtQ[m, 0]
Int[(f_.*x_)^m_*(a_ + c_.*x_^4)^p_./(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["29538150"]] := 1/(d*e)*Int[(f*x)^m*(a*e + c*d*x^2)*(a + c*x^4)^(p - 1), x] - (c*d^2 + a*e^2)/(d*e*f^2)* Int[(f*x)^(m + 2)*(a + c*x^4)^(p - 1)/(d + e*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && GtQ[p, 0] && LtQ[m, 0]
Int[(f_.*x_)^m_.*(a_. + b_.*x_^2 + c_.*x_^4)^p_/(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2c1c97d5"]] := -f^4/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 4)*(a*d + (b*d - a*e)*x^2)*(a + b*x^2 + c*x^4)^p, x] + d^2*f^4/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 4)*(a + b*x^2 + c*x^4)^(p + 1)/(d + e*x^2), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && GtQ[m, 2]
Int[(f_.*x_)^m_.*(a_ + c_.*x_^4)^p_/(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2ddefde2"]] := -a*f^4/(c*d^2 + a*e^2)* Int[(f*x)^(m - 4)*(d - e*x^2)*(a + c*x^4)^p, x] + d^2*f^4/(c*d^2 + a*e^2)* Int[(f*x)^(m - 4)*(a + c*x^4)^(p + 1)/(d + e*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && LtQ[p, -1] && GtQ[m, 2]
Int[(f_.*x_)^m_.*(a_. + b_.*x_^2 + c_.*x_^4)^p_/(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2f9843bb"]] := f^2/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 2)*(a*e + c*d*x^2)*(a + b*x^2 + c*x^4)^p, x] - d*e*f^2/(c*d^2 - b*d*e + a*e^2)* Int[(f*x)^(m - 2)*(a + b*x^2 + c*x^4)^(p + 1)/(d + e*x^2), x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && GtQ[m, 0]
Int[(f_.*x_)^m_.*(a_ + c_.*x_^4)^p_/(d_. + e_.*x_^2), x_Symbol, _:RubiNotebookReference["2e5a298c"]] := f^2/(c*d^2 + a*e^2)* Int[(f*x)^(m - 2)*(a*e + c*d*x^2)*(a + c*x^4)^p, x] - d*e*f^2/(c*d^2 + a*e^2)* Int[(f*x)^(m - 2)*(a + c*x^4)^(p + 1)/(d + e*x^2), x] /; FreeQ[{a, c, d, e, f}, x] && LtQ[p, -1] && GtQ[m, 0]
Int[x_^2/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["25066eb1"]] := d/(2*d*e)*Int[1/Sqrt[a + b*x^2 + c*x^4], x] - d/(2*d*e)* Int[(d - e*x^2)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4]), x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && NeQ[c*d^2 - b*d*e + a*e^2, 0] && PosQ[c/a] && EqQ[c*d^2 - a*e^2, 0]
Int[x_^2/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["24c40486"]] := d/(2*d*e)*Int[1/Sqrt[a + c*x^4], x] - d/(2*d*e)*Int[(d - e*x^2)/((d + e*x^2)*Sqrt[a + c*x^4]), x] /; FreeQ[{a, c, d, e}, x] && NeQ[c*d^2 + a*e^2, 0] && PosQ[c/a] && EqQ[c*d^2 - a*e^2, 0]
Int[x_^2/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["73762f5f"]] := With[{q = Rt[c/a, 2]}, -a*(e + d*q)/(c*d^2 - a*e^2)* Int[1/Sqrt[a + b*x^2 + c*x^4], x] + a*d*(e + d*q)/(c*d^2 - a*e^2)* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4]), x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && NeQ[c*d^2 - b*d*e + a*e^2, 0] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^2/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["72b44568"]] := With[{q = Rt[c/a, 2]}, -a*(e + d*q)/(c*d^2 - a*e^2)*Int[1/Sqrt[a + c*x^4], x] + a*d*(e + d*q)/(c*d^2 - a*e^2)* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + c*x^4]), x]] /; FreeQ[{a, c, d, e}, x] && NeQ[c*d^2 + a*e^2, 0] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["70f2fb31"]] := -1/e^2* Int[(d - e*x^2)/Sqrt[a + b*x^2 + c*x^4], x] + d^2/e^2*Int[1/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4]), x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && PosQ[c/a] && EqQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["71309106"]] := -1/e^2*Int[(d - e*x^2)/Sqrt[a + c*x^4], x] + d^2/e^2*Int[1/((d + e*x^2)*Sqrt[a + c*x^4]), x] /; FreeQ[{a, c, d, e}, x] && PosQ[c/a] && EqQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["747f8783"]] := With[{q = Rt[c/a, 2]}, -1/(e*q)*Int[(1 - q*x^2)/Sqrt[a + b*x^2 + c*x^4], x] + d^2/(e*(e - d*q))* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4]), x] /; EqQ[2*c*d - a*e*q, 0]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["75bdedb4"]] := With[{q = Rt[c/a, 2]}, -1/(e*q)*Int[(1 - q*x^2)/Sqrt[a + c*x^4], x] + d^2/(e*(e - d*q))* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + c*x^4]), x] /; EqQ[2*c*d - a*e*q, 0]] /; FreeQ[{a, c, d, e}, x] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["77fb53ed"]] := With[{q = Rt[c/a, 2]}, -(2*c*d - a*e*q)/(c*e*(e - d*q))* Int[1/Sqrt[a + b*x^2 + c*x^4], x] - 1/(e*q)*Int[(1 - q*x^2)/Sqrt[a + b*x^2 + c*x^4], x] + d^2/(e*(e - d*q))* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4]), x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^4/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["763939da"]] := With[{q = Rt[c/a, 2]}, -(2*c*d - a*e*q)/(c*e*(e - d*q))*Int[1/Sqrt[a + c*x^4], x] - 1/(e*q)*Int[(1 - q*x^2)/Sqrt[a + c*x^4], x] + d^2/(e*(e - d*q))* Int[(1 + q*x^2)/((d + e*x^2)*Sqrt[a + c*x^4]), x]] /; FreeQ[{a, c, d, e}, x] && PosQ[c/a] && NeQ[c*d^2 - a*e^2, 0]
Int[x_^m_/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["7d657ee7"]] := x^(m - 5)*Sqrt[a + b*x^2 + c*x^4]/(c*e*(m - 3)) - 1/(c*e*(m - 3))* Int[x^(m - 6)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4])* Simp[a*d*(m - 5) + (a*e*(m - 5) + b*d*(m - 4))* x^2 + (b*e*(m - 4) + c*d*(m - 3))*x^4, x], x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && IGtQ[m/2, 2]
Int[x_^m_/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["7ca714d0"]] := x^(m - 5)*Sqrt[a + c*x^4]/(c*e*(m - 3)) - 1/(c*e*(m - 3))* Int[x^(m - 6)/((d + e*x^2)*Sqrt[a + c*x^4])* Simp[a*d*(m - 5) + a*e*(m - 5)*x^2 + c*d*(m - 3)*x^4, x], x] /; FreeQ[{a, c, d, e}, x] && IGtQ[m/2, 2]
Int[x_^m_/((d_ + e_.*x_^2)*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["cbca483a"]] := x^(m + 1)*Sqrt[a + b*x^2 + c*x^4]/(a*d*(m + 1)) - 1/(a*d*(m + 1))* Int[x^(m + 2)/((d + e*x^2)*Sqrt[a + b*x^2 + c*x^4])* Simp[a*e*(m + 1) + b*d*(m + 2) + (b*e*(m + 2) + c*d*(m + 3))*x^2 + c*e*(m + 3)*x^4, x], x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && ILtQ[m/2, 0]
Int[x_^m_/((d_ + e_.*x_^2)*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["ca08220d"]] := x^(m + 1)*Sqrt[a + c*x^4]/(a*d*(m + 1)) - 1/(a*d*(m + 1))* Int[x^(m + 2)/((d + e*x^2)*Sqrt[a + c*x^4])* Simp[a*e*(m + 1) + c*d*(m + 3)*x^2 + c*e*(m + 3)*x^4, x], x] /; FreeQ[{a, c, d, e}, x] && ILtQ[m/2, 0]
Int[x_^m_/(Sqrt[d_ + e_.*x_^2]*Sqrt[a_ + b_.*x_^2 + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["c84e9c54"]] := x^3*Sqrt[e + d/x^2]* Sqrt[c + b/x^2 + a/x^4]/(Sqrt[d + e*x^2]*Sqrt[a + b*x^2 + c*x^4])* Int[x^(m - 3)/(Sqrt[e + d/x^2]*Sqrt[c + b/x^2 + a/x^4]), x] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && IntegerQ[m/2]
Int[x_^m_/(Sqrt[d_ + e_.*x_^2]*Sqrt[a_ + c_.*x_^4]), x_Symbol, _:RubiNotebookReference["c98cf663"]] := x^3*Sqrt[e + d/x^2]*Sqrt[c + a/x^4]/(Sqrt[d + e*x^2]*Sqrt[a + c*x^4])* Int[x^(m - 3)/(Sqrt[e + d/x^2]*Sqrt[c + a/x^4]), x] /; FreeQ[{a, c, d, e}, x] && IntegerQ[m/2]
Int[x_^m_*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["ccc3e0e6"]] := With[{f = Coeff[PolynomialRemainder[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x], x, 0], g = Coeff[ PolynomialRemainder[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x], x, 2]}, x*(a + b*x^2 + c*x^4)^(p + 1)*(a*b*g - f*(b^2 - 2*a*c) - c*(b*f - 2*a*g)*x^2)/(2*a*(p + 1)*(b^2 - 4*a*c)) + 1/(2*a*(p + 1)*(b^2 - 4*a*c))*Int[(a + b*x^2 + c*x^4)^(p + 1)* Simp[ExpandToSum[ 2*a*(p + 1)*(b^2 - 4*a*c)* PolynomialQuotient[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x] + b^2*f*(2*p + 3) - 2*a*c*f*(4*p + 5) - a*b*g + c*(4*p + 7)*(b*f - 2*a*g)*x^2, x], x], x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && IGtQ[q, 1] && IGtQ[m/2, 0]
Int[x_^m_*(d_ + e_.*x_^2)^q_*(a_ + b_.*x_^2 + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["cd018ad1"]] := With[{f = Coeff[PolynomialRemainder[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x], x, 0], g = Coeff[ PolynomialRemainder[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x], x, 2]}, x*(a + b*x^2 + c*x^4)^(p + 1)*(a*b*g - f*(b^2 - 2*a*c) - c*(b*f - 2*a*g)*x^2)/(2*a*(p + 1)*(b^2 - 4*a*c)) + 1/(2*a*(p + 1)*(b^2 - 4*a*c))* Int[x^m*(a + b*x^2 + c*x^4)^(p + 1)* Simp[ExpandToSum[ 2*a*(p + 1)*(b^2 - 4*a*c)*x^(-m)* PolynomialQuotient[x^m*(d + e*x^2)^q, a + b*x^2 + c*x^4, x] + (b^2*f*(2*p + 3) - 2*a*c*f*(4*p + 5) - a*b*g)*x^(-m) + c*(4*p + 7)*(b*f - 2*a*g)*x^(2 - m), x], x], x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1] && IGtQ[q, 1] && ILtQ[m/2, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["cf473488"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q*(a + b*x^2 + c*x^4)^p, x], x] /; FreeQ[{a, b, c, d, e, f, m, p, q}, x] && NeQ[b^2 - 4*a*c, 0] && (IGtQ[p, 0] || IGtQ[q, 0] || IntegersQ[m, q])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["ce855ebf"]] := Int[ExpandIntegrand[(f*x)^m*(d + e*x^2)^q*(a + c*x^4)^p, x], x] /; FreeQ[{a, c, d, e, f, m, p, q}, x] && (IGtQ[p, 0] || IGtQ[q, 0] || IntegersQ[m, q])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_*(a_ + c_.*x_^4)^p_, x_Symbol, _:RubiNotebookReference["c5d91982"]] := (f*x)^m/x^m* Int[ExpandIntegrand[ x^m*(a + c*x^4)^ p, (d/(d^2 - e^2*x^4) - e*x^2/(d^2 - e^2*x^4))^(-q), x], x] /; FreeQ[{a, c, d, e, f, m, p}, x] && Not[IntegerQ[p]] && ILtQ[q, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + b_.*x_^2 + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["c41b73b5"]] := Unintegrable[(f*x)^m*(d + e*x^2)^q*(a + b*x^2 + c*x^4)^p, x] /; FreeQ[{a, b, c, d, e, f, m, p, q}, x]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^q_.*(a_ + c_.*x_^4)^p_., x_Symbol, _:RubiNotebookReference["7160c28c"]] := Unintegrable[(f*x)^m*(d + e*x^2)^q*(a + c*x^4)^p, x] /; FreeQ[{a, c, d, e, f, m, p, q}, x]
