(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
(* Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  c^p/e^(2*p) \[Star] Int[u*(d+e*x^n)^(q+2*p),x] /;
FreeQ[{a,b,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && IntegerQ[p] && EqQ[2*c*d-b*e,0] *)


(* ::Code:: *)
Int[(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  1/c^p \[Star] Int[(b/2+c*x^n)^(2*p),x] /;
FreeQ[{a,b,c,n,p},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && IntegerQ[p] && NeQ[p,1]


(* ::Code:: *)
Int[u_*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  1/c^p \[Star] Int[u*(b/2+c*x^n)^(2*p),x] /;
FreeQ[{a,b,c,n,p},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && IntegerQ[p]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  e^q/c^(q/2) \[Star] Int[u*(a+b*x^n+c*x^(2*n))^(p+q/2),x] /;
FreeQ[{a,b,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && EqQ[2*c*d-b*e,0] && Not[IntegerQ[p]] && IntegerQ[q/2]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  e^(q-1)/c^((q-1)/2) \[Star] Int[u*(d+e*x^n)*(a+b*x^n+c*x^(2*n))^(p+(q-1)/2),x] /;
FreeQ[{a,b,c,d,e,p},x] && EqQ[b^2-4*a*c,0] && EqQ[2*c*d-b*e,0] && Not[IntegerQ[p]] && IntegerQ[(q-1)/2]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  (a+b*x^n+c*x^(2*n))^p/(d+e*x^n)^(2*p) \[Star] Int[u (d+e*x^n)^(q+2*p),x] /;
FreeQ[{a,b,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && EqQ[2*c*d-b*e,0] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[u_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  (a+b*x^n+c*x^(2*n))^FracPart[p]/(c^IntPart[p]*(b/2+c*x^n)^(2*FracPart[p])) \[Star] Int[u*(b/2+c*x^n)^(2*p),x] /;
FreeQ[{a,b,c,n,p},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && IntegerQ[p-1/2] && NeQ[u,x^(n-1)] && NeQ[u,x^(2*n-1)] && Not[EqQ[p,1/2] && EqQ[u,x^(-2*n-1)]]


(* ::Code:: *)
Int[u_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  a^IntPart[p]*(a+b*x^n+c*x^(2*n))^FracPart[p]/(1+2*c*x^n/b)^(2*FracPart[p]) \[Star] Int[u*(1+2*c*x^n/b)^(2*p),x] /;
FreeQ[{a,b,c,n,p},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && Not[IntegerQ[2*p]] && NeQ[u,x^(n-1)] && NeQ[u,x^(2*n-1)]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  (-e^2/c)^q \[Star] Int[u*(d-e*x^n)^p,x] /;
FreeQ[{a,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[c*d^2+a*e^2,0] && EqQ[p+q,0] && GtQ[d,0] && LtQ[c,0] && GtQ[e^2,0]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  Int[u*(d+e*x^n)^(p+q)*(a/d+c/e*x^n)^p,x] /;
FreeQ[{a,b,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[c*d^2-b*d*e+a*e^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[d,0] && LtQ[c,0])


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  Int[u*(d+e*x^n)^(p+q)*(a/d+c/e*x^n)^p,x] /;
FreeQ[{a,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[c*d^2+a*e^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[d,0])


(* ::Code:: *)
Int[(d_+e_.*x_^2)/Sqrt[a_+c_.*x_^4],x_Symbol] :=
  d/Sqrt[a] \[Star] Int[Sqrt[1+e*x^2/d]/Sqrt[1-e*x^2/d],x] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && NegQ[c/a] && GtQ[a,0]


(* ::Code:: *)
Int[(d_+e_.*x_^2)/Sqrt[a_+c_.*x_^4],x_Symbol] :=
  Sqrt[1+c*x^4/a]/Sqrt[a+c*x^4] \[Star] Int[(d+e*x^2)/Sqrt[1+c*x^4/a],x] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && NegQ[c/a] && Not[GtQ[a,0]] && Not[LtQ[a,0] && GtQ[c,0]]


(* ::Code:: *)
Int[1/((d_+e_.*x_^2)*Sqrt[a_+c_.*x_^4]),x_Symbol] :=
  x/(d*Sqrt[a+c*x^4]) - 
  (Sqrt[-1+e/d*x^2]*Sqrt[1+e/d*x^2]*EllipticE[ArcSin[(Sqrt[2]*Rt[e/d,2]*x)/Sqrt[-1+e/d*x^2]],1/2])/(Sqrt[2]*d*Rt[e/d,2]*Sqrt[a+c*x^4]) + 
  (Sqrt[-1+e/d*x^2]*Sqrt[1+e/d*x^2]*EllipticF[ArcSin[(Sqrt[2]*Rt[e/d,2]*x)/Sqrt[-1+e/d*x^2]],1/2])/(Sqrt[2]*d*Rt[e/d,2]*Sqrt[a+c*x^4]) /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && LtQ[a,0] && GtQ[c,0] && PosQ[e/d]


(* ::Code:: *)
(* Int[1/((d_+e_.*x_^2)*Sqrt[a_+c_.*x_^4]),x_Symbol] :=
  -(d-e*x^2)/(2*d*e*x*Sqrt[a+c*x^4]) + 
  Sqrt[d/e+x^2]/(Sqrt[2]*d*Sqrt[1/(1-e*x^2/d)]*Sqrt[a+c*x^4])*EllipticE[ArcSin[Sqrt[d/e+x^2]/x],1/2] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && LtQ[a,0] && GtQ[c,0] && NegQ[e/d] *)


(* ::Code:: *)
Int[1/((d_+e_.*x_^2)*Sqrt[a_+c_.*x_^4]),x_Symbol] :=
  x/(d*Sqrt[a+c*x^4]) - 
  x/(d*Sqrt[-2*a]*Sqrt[-e/d*x^2])*EllipticE[ArcSin[Sqrt[-2*a]*Sqrt[-1-e/d*x^2]/Sqrt[a+c*x^4]],1/2] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && LtQ[a,0] && GtQ[c,0] && NegQ[e/d]


(* ::Code:: *)
Int[x_^2/((d_+e_.*x_^2)*Sqrt[a_+c_.*x_^4]),x_Symbol] :=
  -x/(e*Sqrt[a+c*x^4]) + 
  (Sqrt[-1+e/d*x^2]*Sqrt[1+e/d*x^2]*EllipticE[ArcSin[(Sqrt[2]*Rt[e/d,2]*x)/Sqrt[-1+e/d*x^2]],1/2])/(Sqrt[2]*e*Rt[e/d,2]*Sqrt[a+c*x^4]) /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && LtQ[a,0] && GtQ[c,0] && PosQ[e/d]


(* ::Code:: *)
Int[x_^2/((d_+e_.*x_^2)*Sqrt[a_+c_.*x_^4]),x_Symbol] :=
  -x/(e*Sqrt[a+c*x^4]) + 
  x/(e*Sqrt[-2*a]*Sqrt[-e/d*x^2])*EllipticE[ArcSin[(Sqrt[-2*a]*Sqrt[-1-e/d*x^2])/Sqrt[a+c*x^4]],1/2] - 
  x/(e*Sqrt[-2*a]*Sqrt[-e/d*x^2])*EllipticF[ArcSin[(Sqrt[-2*a]*Sqrt[-1-e/d*x^2])/Sqrt[a+c*x^4]],1/2] /;
FreeQ[{a,c,d,e},x] && EqQ[c*d^2+a*e^2,0] && LtQ[a,0] && GtQ[c,0] && NegQ[e/d]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  (a+b*x^n+c*x^(2*n))^FracPart[p]/((d+e*x^n)^FracPart[p]*(a/d+c*x^n/e)^FracPart[p]) \[Star] Int[u*(d+e*x^n)^(p+q)*(a/d+c/e*x^n)^p,x] /;
FreeQ[{a,b,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[c*d^2-b*d*e+a*e^2,0] && Not[IntegerQ[p]] && Not[EqQ[q,1] && EqQ[n,2]]


(* ::Code:: *)
Int[u_.*(d_+e_.*x_^n_)^q_.*(a_+c_.*x_^n2_.)^p_,x_Symbol] :=
  (a+c*x^(2*n))^FracPart[p]/((d+e*x^n)^FracPart[p]*(a/d+c*x^n/e)^FracPart[p]) \[Star] Int[u*(d+e*x^n)^(p+q)*(a/d+c/e*x^n)^p,x] /;
FreeQ[{a,c,d,e,n,p,q},x] && EqQ[n2,2*n] && EqQ[c*d^2+a*e^2,0] && Not[IntegerQ[p]] && Not[EqQ[q,1] && EqQ[n,2]]


(* ::Code:: *)
Int[(b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  Int[x^(2*p)*(b+c*x^2)^p,x] /;
FreeQ[{b,c},x] && IntegerQ[p]


(* ::Code:: *)
Int[Sqrt[b_.*x_^2+c_.*x_^4],x_Symbol] :=
  (b*x^2+c*x^4)^(3/2)/(3*c*x^3) /;
FreeQ[{b,c},x]


(* ::Code:: *)
Int[(b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  (b*x^2+c*x^4)^(p+1)/(c*(4*p+1)*x^3) - 
  b*(2*p-1)/(c*(4*p+1)) \[Star] Int[(b*x^2+c*x^4)^p/x^2,x] /;
FreeQ[{b,c,p},x] && IGtQ[p-1/2,0]


(* ::Code:: *)
Int[1/Sqrt[b_.*x_^2+c_.*x_^4],x_Symbol] :=
  -Subst[Int[1/(1-b*x^2),x],x,x/Sqrt[b*x^2+c*x^4]] /;
FreeQ[{b,c},x]


(* ::Code:: *)
(* Int[(b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  (b*x^2+c*x^4)^(p+1)/(b*(2*p+1)*x) - 
  c*(4*p+3)/(b*(2*p+1)) \[Star] Int[x^2*(b*x^2+c*x^4)^p,x] /;
FreeQ[{b,c,p},x] && Not[IntegerQ[p]] && ILtQ[2*p+3/2,0] *)


(* ::Code:: *)
Int[(b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  -(b*x^2+c*x^4)^(p+1)/(2*b*(p+1)*x) + 
  (4*p+3)/(2*b*(p+1)) \[Star] Int[(b*x^2+c*x^4)^(p+1)/x^2,x] /;
FreeQ[{b,c},x] && Not[IntegerQ[p]] && LtQ[p,-1]


(* ::Code:: *)
Int[(b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  (b*x^2+c*x^4)^p/(x^(2*p)*(b+c*x^2)^p) \[Star] Int[x^(2*p)*(b+c*x^2)^p,x] /;
FreeQ[{b,c,p},x] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[(a_.+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  Int[ExpandIntegrand[(a+b*x^2+c*x^4)^p,x],x] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && IGtQ[p,0]


(* ::Code:: *)
Int[(a_.+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  x*(a+b*x^2+c*x^4)^p/(4*p+1) + 
  2*p/(4*p+1) \[Star] Int[(2*a+b*x^2)*(a+b*x^2+c*x^4)^(p-1),x] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && GtQ[p,0] && IntegerQ[2*p]


(* ::Code:: *)
Int[(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  -x*(b^2-2*a*c+b*c*x^2)*(a+b*x^2+c*x^4)^(p+1)/(2*a*(p+1)*(b^2-4*a*c)) +
  1/(2*a*(p+1)*(b^2-4*a*c)) \[Star] Int[(b^2-2*a*c+2*(p+1)*(b^2-4*a*c)+b*c*(4*p+7)*x^2)*(a+b*x^2+c*x^4)^(p+1),x] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && LtQ[p,-1] && IntegerQ[2*p]


(* ::Code:: *)
Int[1/(a_+b_.*x_^2+c_.*x_^4),x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  c/q \[Star] Int[1/(b/2-q/2+c*x^2),x] - c/q \[Star] Int[1/(b/2+q/2+c*x^2),x]] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && PosQ[b^2-4*a*c]


(* ::Code:: *)
Int[1/(a_+b_.*x_^2+c_.*x_^4),x_Symbol] :=
  With[{q=Rt[a/c,2]},
  With[{r=Rt[2*q-b/c,2]},
  1/(2*c*q*r) \[Star] Int[(r-x)/(q-r*x+x^2),x] + 1/(2*c*q*r) \[Star] Int[(r+x)/(q+r*x+x^2),x]]] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && NegQ[b^2-4*a*c]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  2*Sqrt[-c] \[Star] Int[1/(Sqrt[b+q+2*c*x^2]*Sqrt[-b+q-2*c*x^2]),x]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0] && LtQ[c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[c/a,4]},
  (1+q^2*x^2)*Sqrt[(a+b*x^2+c*x^4)/(a*(1+q^2*x^2)^2)]/(2*q*Sqrt[a+b*x^2+c*x^4])*EllipticF[2*ArcTan[q*x],1/2-b*q^2/(4*c)]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0] && GtQ[c/a,0] && LtQ[b/a,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  Sqrt[-2*a-(b-q)*x^2]*Sqrt[(2*a+(b+q)*x^2)/q]/(2*Sqrt[-a]*Sqrt[a+b*x^2+c*x^4])*
    EllipticF[ArcSin[x/Sqrt[(2*a+(b+q)*x^2)/(2*q)]],(b+q)/(2*q)] /;
  IntegerQ[q]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0] && LtQ[a,0] && GtQ[c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  Sqrt[(2*a+(b-q)*x^2)/(2*a+(b+q)*x^2)]*Sqrt[(2*a+(b+q)*x^2)/q]/(2*Sqrt[a+b*x^2+c*x^4]*Sqrt[a/(2*a+(b+q)*x^2)])*
    EllipticF[ArcSin[x/Sqrt[(2*a+(b+q)*x^2)/(2*q)]],(b+q)/(2*q)]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0] && LtQ[a,0] && GtQ[c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  (2*a+(b+q)*x^2)*Sqrt[(2*a+(b-q)*x^2)/(2*a+(b+q)*x^2)]/(2*a*Rt[(b+q)/(2*a),2]*Sqrt[a+b*x^2+c*x^4])*
    EllipticF[ArcTan[Rt[(b+q)/(2*a),2]*x],2*q/(b+q)] /;
 PosQ[(b+q)/a] && Not[PosQ[(b-q)/a] && SimplerSqrtQ[(b-q)/(2*a),(b+q)/(2*a)]]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  (2*a+(b-q)*x^2)*Sqrt[(2*a+(b+q)*x^2)/(2*a+(b-q)*x^2)]/(2*a*Rt[(b-q)/(2*a),2]*Sqrt[a+b*x^2+c*x^4])*
    EllipticF[ArcTan[Rt[(b-q)/(2*a),2]*x],-2*q/(b-q)] /;
 PosQ[(b-q)/a]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  Sqrt[1+(b+q)*x^2/(2*a)]*Sqrt[1+(b-q)*x^2/(2*a)]/(Rt[-(b+q)/(2*a),2]*Sqrt[a+b*x^2+c*x^4])*
    EllipticF[ArcSin[Rt[-(b+q)/(2*a),2]*x],(b-q)/(b+q)] /;
 NegQ[(b+q)/a] && Not[NegQ[(b-q)/a] && SimplerSqrtQ[-(b-q)/(2*a),-(b+q)/(2*a)]]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  Sqrt[1+(b-q)*x^2/(2*a)]*Sqrt[1+(b+q)*x^2/(2*a)]/(Rt[-(b-q)/(2*a),2]*Sqrt[a+b*x^2+c*x^4])*
    EllipticF[ArcSin[Rt[-(b-q)/(2*a),2]*x],(b+q)/(b-q)] /;
 NegQ[(b-q)/a]] /;
FreeQ[{a,b,c},x] && GtQ[b^2-4*a*c,0]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[c/a,4]},
  (1+q^2*x^2)*Sqrt[(a+b*x^2+c*x^4)/(a*(1+q^2*x^2)^2)]/(2*q*Sqrt[a+b*x^2+c*x^4])*EllipticF[2*ArcTan[q*x],1/2-b*q^2/(4*c)]] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && PosQ[c/a]


(* ::Code:: *)
Int[1/Sqrt[a_+b_.*x_^2+c_.*x_^4],x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  Sqrt[1+2*c*x^2/(b-q)]*Sqrt[1+2*c*x^2/(b+q)]/Sqrt[a+b*x^2+c*x^4] \[Star] 
    Int[1/(Sqrt[1+2*c*x^2/(b-q)]*Sqrt[1+2*c*x^2/(b+q)]),x]] /;
FreeQ[{a,b,c},x] && NeQ[b^2-4*a*c,0] && NegQ[c/a]


(* ::Code:: *)
Int[(a_+b_.*x_^2+c_.*x_^4)^p_,x_Symbol] :=
  With[{q=Rt[b^2-4*a*c,2]},
  a^IntPart[p]*(a+b*x^2+c*x^4)^FracPart[p]/((1+2*c*x^2/(b+q))^FracPart[p]*(1+2*c*x^2/(b-q))^FracPart[p]) \[Star] 
    Int[(1+2*c*x^2/(b+q))^p*(1+2*c*x^2/(b-q))^p,x]] /;
FreeQ[{a,b,c,p},x] && NeQ[b^2-4*a*c,0]



