
(* ::Section:: *)
(* 1.2.4.3 (d+e x^(n-q)) (a x^q+b x^n+c x^(2 n-q))^p *)

(* ::Subsection::Closed:: *)
(* 1.2.4.3 (d+e x^(n-q)) (a x^q+b x^n+c x^(2 n-q))^p *)
Int[((A_) + (B_.)*(x_)^(r_.))*((a_.)*(x_)^(q_.) + (b_.)*(x_)^(n_.) + (c_.)*(x_)^(j_.))^(p_.), x_Symbol] := Int[x^(p*q)*(A + B*x^(n - q))*(a + b*x^(n - q) + c*x^(2*(n - q)))^p, x] /; FreeQ[{a, b, c, A, B, n, q}, x] && EqQ[r, n - q] && EqQ[j, 2*n - q] && IntegerQ[p] && PosQ[n - q]
Int[((A_) + (B_.)*(x_)^(j_.))/Sqrt[(a_.)*(x_)^(q_.) + (b_.)*(x_)^(n_.) + (c_.)*(x_)^(r_.)], x_Symbol] := x^(q/2)*(Sqrt[a + b*x^(n - q) + c*x^(2*(n - q))]/Sqrt[a*x^q + b*x^n + c*x^(2*n - q)])*Int[(A + B*x^(n - q))/(x^(q/2)*Sqrt[a + b*x^(n - q) + c*x^(2*(n - q))]), x] /; FreeQ[{a, b, c, A, B, n, q}, x] && EqQ[j, n - q] && EqQ[r, 2*n - q] && PosQ[n - q] && EqQ[n, 3] && EqQ[q, 2]
Int[((A_) + (B_.)*(x_)^(r_.))*((a_.)*(x_)^(q_.) + (b_.)*(x_)^(n_.) + (c_.)*(x_)^(j_.))^(p_), x_Symbol] := x*(b*B*(n - q)*p + A*c*(p*q + (n - q)*(2*p + 1) + 1) + B*c*(p*(2*n - q) + 1)*x^(n - q))*((a*x^q + b*x^n + c*x^(2*n - q))^p/(c*(p*(2*n - q) + 1)*(p*q + (n - q)*(2*p + 1) + 1))) + (n - q)*(p/(c*(p*(2*n - q) + 1)*(p*q + (n - q)*(2*p + 1) + 1)))*Int[x^q*(2*a*A*c*(p*q + (n - q)*(2*p + 1) + 1) - a*b*B*(p*q + 1) + (2*a*B*c*(p*(2*n - q) + 1) + A*b*c*(p*q + (n - q)*(2*p + 1) + 1) - b^2*B*(p*q + (n - q)*p + 1))*x^(n - q))*(a*x^q + b*x^n + c*x^(2*n - q))^(p - 1), x] /; FreeQ[{a, b, c, A, B, n, q}, x] && EqQ[r, n - q] && EqQ[j, 2*n - q] &&  !IntegerQ[p] && NeQ[b^2 - 4*a*c, 0] && GtQ[p, 0] && NeQ[p*(2*n - q) + 1, 0] && NeQ[p*q + (n - q)*(2*p + 1) + 1, 0]
Int[((A_) + (B_.)*(x_)^(r_.))*((a_.)*(x_)^(q_.) + (c_.)*(x_)^(j_.))^(p_), x_Symbol] := With[{n = q + r}, x*(A*(p*q + (n - q)*(2*p + 1) + 1) + B*(p*(2*n - q) + 1)*x^(n - q))*((a*x^q + c*x^(2*n - q))^p/((p*(2*n - q) + 1)*(p*q + (n - q)*(2*p + 1) + 1))) + (n - q)*(p/((p*(2*n - q) + 1)*(p*q + (n - q)*(2*p + 1) + 1)))*Int[x^q*(2*a*A*(p*q + (n - q)*(2*p + 1) + 1) + (2*a*B*(p*(2*n - q) + 1))*x^(n - q))*(a*x^q + c*x^(2*n - q))^(p - 1), x] /; EqQ[j, 2*n - q] && NeQ[p*(2*n - q) + 1, 0] && NeQ[p*q + (n - q)*(2*p + 1) + 1, 0]] /; FreeQ[{a, c, A, B, q}, x] &&  !IntegerQ[p] && GtQ[p, 0]
Int[((A_) + (B_.)*(x_)^(r_.))*((a_.)*(x_)^(q_.) + (b_.)*(x_)^(n_.) + (c_.)*(x_)^(j_.))^(p_), x_Symbol] := (-x^(-q + 1))*(A*b^2 - a*b*B - 2*a*A*c + (A*b - 2*a*B)*c*x^(n - q))*((a*x^q + b*x^n + c*x^(2*n - q))^(p + 1)/(a*(n - q)*(p + 1)*(b^2 - 4*a*c))) + (1/(a*(n - q)*(p + 1)*(b^2 - 4*a*c)))*Int[((A*b^2*(p*q + (n - q)*(p + 1) + 1) - a*b*B*(p*q + 1) - 2*a*A*c*(p*q + 2*(n - q)*(p + 1) + 1) + (p*q + (n - q)*(2*p + 3) + 1)*(A*b - 2*a*B)*c*x^(n - q))*(a*x^q + b*x^n + c*x^(2*n - q))^(p + 1))/x^q, x] /; FreeQ[{a, b, c, A, B, n, q}, x] && EqQ[r, n - q] && EqQ[j, 2*n - q] &&  !IntegerQ[p] && NeQ[b^2 - 4*a*c, 0] && LtQ[p, -1]
Int[((A_) + (B_.)*(x_)^(r_.))*((a_.)*(x_)^(q_.) + (c_.)*(x_)^(j_.))^(p_), x_Symbol] := With[{n = q + r}, (-x^(-q + 1))*(a*A*c + a*B*c*x^(n - q))*((a*x^q + c*x^(2*n - q))^(p + 1)/(a*(n - q)*(p + 1)*(2*a*c))) + (1/(a*(n - q)*(p + 1)*(2*a*c)))*Int[((a*A*c*(p*q + 2*(n - q)*(p + 1) + 1) + a*B*c*(p*q + (n - q)*(2*p + 3) + 1)*x^(n - q))*(a*x^q + c*x^(2*n - q))^(p + 1))/x^q, x] /; EqQ[j, 2*n - q]] /; FreeQ[{a, c, A, B, q}, x] &&  !IntegerQ[p] && LtQ[p, -1]
Int[((A_) + (B_.)*(x_)^(j_.))*((a_.)*(x_)^(q_.) + (b_.)*(x_)^(n_.) + (c_.)*(x_)^(r_.))^(p_.), x_Symbol] := Unintegrable[(A + B*x^(n - q))*(a*x^q + b*x^n + c*x^(2*n - q))^p, x] /; FreeQ[{a, b, c, A, B, n, p, q}, x] && EqQ[j, n - q] && EqQ[r, 2*n - q]
Int[((A_) + (B_.)*(u_)^(j_.))*((a_.)*(u_)^(q_.) + (b_.)*(u_)^(n_.) + (c_.)*(u_)^(r_.))^(p_.), x_Symbol] := (1/Coefficient[u, x, 1])*Subst[Int[(A + B*x^(n - q))*(a*x^q + b*x^n + c*x^(2*n - q))^p, x], x, u] /; FreeQ[{a, b, c, A, B, n, p, q}, x] && EqQ[j, n - q] && EqQ[r, 2*n - q] && LinearQ[u, x] && NeQ[u, x]