
(* ::Subsection::Closed:: *)
(* 7.1.4 (f x)^m (d+e x^2)^p (a+b arcsinh(c x))^n *)
Int[x_*(a_. + b_.*ArcSinh[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol] := 1/e*Subst[Int[(a + b*x)^n*Tanh[x], x], x, ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[n, 0]
Int[x_*(a_. + b_.*ArcCosh[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol] := 1/e*Subst[Int[(a + b*x)^n*Coth[x], x], x, ArcCosh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
(* Int[x_*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_Symbol] :=   (d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(2*e*(p+1)) - b*n*d^p/(2*c*(p+1))*Int[(1+c^2*x^2)^(p+1/2)*(a+b*ArcSinh[c*x])^(n-1) ,x] /; FreeQ[{a,b,c,d,e,p},x] && EqQ[e,c^2*d] && GtQ[n,0] &&  NeQ[p,-1] && (IntegerQ[p] || GtQ[d,0]) *)
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^ n/(2*e*(p + 1)) - b*n*(-d)^p/(2*c*(p + 1))* Int[(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && NeQ[p, -1] && IntegerQ[p]
(* Int[x_*(d1_+e1_.*x_)^p_.*(d2_+e2_.*x_)^p_.*(a_.+b_.*ArcCosh[c_.*x_] )^n_.,x_Symbol] :=  (d1+e1*x)^(p+1)*(d2+e2*x)^(p+1)*(a+b*ArcCosh[c*x])^n/(2*e1*e2*(p+1)) - b*n*(-d1*d2)^(p-1/2)/(2*c*(p+1))*Int[(-1+c^2*x^2)^(p+1/2)*(a+b* ArcCosh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d1,e1,d2,e2,p},x] &&  EqQ[e1-c*d1,0] && EqQ[e2+c*d2,0] && GtQ[n,0] && IntegerQ[p+1/2] &&  (GtQ[d1,0] && LtQ[d2,0]) *)
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^ n/(2*e*(p + 1)) - b*n*d^ IntPart[p]*(d + e*x^2)^ FracPart[p]/(2*c*(p + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && NeQ[p, -1]
Int[x_*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*e1*e2*(p + 1)) - b*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* c*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && NeQ[p, -1] && IntegerQ[p + 1/2]
Int[x_*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*e1*e2*(p + 1)) - b*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* c*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && NeQ[p, -1]
Int[(a_. + b_.*ArcSinh[c_.*x_])^n_./(x_*(d_ + e_.*x_^2)), x_Symbol] := 1/d*Subst[Int[(a + b*x)^n/(Cosh[x]*Sinh[x]), x], x, ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[n, 0]
Int[(a_. + b_.*ArcCosh[c_.*x_])^n_./(x_*(d_ + e_.*x_^2)), x_Symbol] := -1/d* Subst[Int[(a + b*x)^n/(Cosh[x]*Sinh[x]), x], x, ArcCosh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[n, 0]
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  (f*x)^(m+1)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(d*f*(m+1)) - b*c*n*d^p/(f*(m+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p+1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f,m,p},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && EqQ[m+2*p+3,0] && NeQ[m,-1] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d*f*(m + 1)) + b*c*n*(-d)^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1] && IntegerQ[p]
(* Int[(f_.*x_)^m_*(d1_+e1_.*x_)^p_.*(d2_+e2_.*x_)^p_.*(a_.+b_.* ArcCosh[c_.*x_])^n_.,x_Symbol] :=  (f*x)^(m+1)*(d1+e1*x)^(p+1)*(d2+e2*x)^(p+1)*(a+b*ArcCosh[c*x])^n/(d1* d2*f*(m+1)) + b*c*n*(-d1*d2)^p/(f*(m+1))*Int[(f*x)^(m+1)*(-1+c^2*x^2)^(p+1/2)*(a+ b*ArcCosh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d1,e1,d2,e2,f,m,p},x] &&  EqQ[e1-c*d1,0] && EqQ[e2+c*d2,0] && GtQ[n,0] && EqQ[m+2*p+3,0] && NeQ[m,-1] && IntegerQ[p+1/2] && (GtQ[d1,0] && LtQ[d2,0]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n/(d*f*(m + 1)) - b*c*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(f*(m + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d1*d2*f*(m + 1)) + b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(f*(m + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1] && IntegerQ[p + 1/2]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d1*d2*f*(m + 1)) + b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(f*(m + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && EqQ[m + 2*p + 3, 0] && NeQ[m, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])/x_, x_Symbol] := (d + e*x^2)^p*(a + b*ArcSinh[c*x])/(2*p) - b*c*d^p/(2*p)*Int[(1 + c^2*x^2)^(p - 1/2), x] + d*Int[(d + e*x^2)^(p - 1)*(a + b*ArcSinh[c*x])/x, x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])/x_, x_Symbol] := (d + e*x^2)^p*(a + b*ArcCosh[c*x])/(2*p) - b*c*(-d)^p/(2*p)* Int[(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2), x] + d*Int[(d + e*x^2)^(p - 1)*(a + b*ArcCosh[c*x])/x, x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSinh[c*x])/(f*(m + 1)) - b*c*d^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p - 1/2), x] - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcSinh[c*x]), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && IGtQ[p, 0] && ILtQ[(m + 1)/2, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCosh[c*x])/(f*(m + 1)) - b*c*(-d)^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2), x] - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcCosh[c*x]), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0] && ILtQ[(m + 1)/2, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcSinh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && IGtQ[p, 0]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcCosh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0]
Int[x_^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := With[{u = IntHide[x^m*(1 + c^2*x^2)^p, x]}, Dist[d^p*(a + b*ArcSinh[c*x]), u, x] - b*c*d^p*Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IntegerQ[ p - 1/2] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0]) && NeQ[p, -1/2] && GtQ[d, 0]
Int[x_^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := With[{u = IntHide[x^m*(1 + c*x)^p*(-1 + c*x)^p, x]}, Dist[(-d1*d2)^p*(a + b*ArcCosh[c*x]), u, x] - b*c*(-d1*d2)^p* Int[SimplifyIntegrand[u/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x], x]] /; FreeQ[{a, b, c, d1, e1, d2, e2}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && IntegerQ[p - 1/2] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0]) && NeQ[p, -1/2] && GtQ[d1, 0] && LtQ[d2, 0]
Int[x_^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := With[{u = IntHide[x^m*(1 + c^2*x^2)^p, x]}, (a + b*ArcSinh[c*x])*Int[x^m*(d + e*x^2)^p, x] - b*c*d^(p - 1/2)*Sqrt[d + e*x^2]/Sqrt[1 + c^2*x^2]* Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[p + 1/2, 0] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0])
Int[x_^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := With[{u = IntHide[x^m*(1 + c*x)^p*(-1 + c*x)^p, x]}, (a + b*ArcCosh[c*x])*Int[x^m*(d1 + e1*x)^p*(d2 + e2*x)^p, x] - b*c*(-d1*d2)^(p - 1/2)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[SimplifyIntegrand[u/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x], x]] /; FreeQ[{a, b, c, d1, e1, d2, e2}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && IGtQ[p + 1/2, 0] && (IGtQ[(m + 1)/2, 0] || ILtQ[(m + 2*p + 3)/2, 0])
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] := (f*x)^(m+1)*(d+e*x^2)^p*(a+b*ArcSinh[c*x])^n/(f*(m+1)) -   2*e*p/(f^2*(m+1))*Int[(f*x)^(m+2)*(d+e*x^2)^(p-1)*(a+b*ArcSinh[c*x]) ^n,x] - b*c*n*d^p/(f*(m+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p-1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && GtQ[p,0] && LtQ[m,-1] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCosh[c*x])^n/(f*(m + 1)) - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcCosh[c*x])^n, x] - b*c*n*(-d)^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && LtQ[m, -1] && IntegerQ[p]
(* Int[(f_.*x_)^m_*(d1_+e1_.*x_)^p_*(d2_+e2_.*x_)^p_*(a_.+b_.*ArcCosh[ c_.*x_])^n_.,x_Symbol] :=  (f*x)^(m+1)*(d1+e1*x)^p*(d2+e2*x)^p*(a+b*ArcCosh[c*x])^n/(f*(m+1)) - 2*e1*e2*p/(f^2*(m+1))*Int[(f*x)^(m+2)*(d1+e1*x)^(p-1)*(d2+e2*x)^(p- 1)*(a+b*ArcCosh[c*x])^n,x] - b*c*n*(-d1*d2)^p/(f*(m+1))*Int[(f*x)^(m+1)*(-1+c^2*x^2)^(p-1/2)*(a+ b*ArcCosh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d1,e1,d2,e2,f},x] &&  EqQ[e1-c*d1,0] && EqQ[e2+c*d2,0] && GtQ[n,0] && GtQ[p,0] && LtQ[m,-1]  && IntegerQ[p-1/2] && (GtQ[d1,0] && LtQ[d2,0]) *)
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcSinh[c*x])^n/(f*(m + 1)) - b*c*n*Sqrt[d + e*x^2]/(f*(m + 1)*Sqrt[1 + c^2*x^2])* Int[(f*x)^(m + 1)*(a + b*ArcSinh[c*x])^(n - 1), x] - c^2*Sqrt[d + e*x^2]/(f^2*(m + 1)*Sqrt[1 + c^2*x^2])* Int[(f*x)^(m + 2)*(a + b*ArcSinh[c*x])^n/Sqrt[1 + c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*Sqrt[d1_ + e1_.*x_]* Sqrt[d2_ + e2_.*x_]*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]*(a + b*ArcCosh[c*x])^n/(f*(m + 1)) - b*c*n*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(f*(m + 1)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^(m + 1)*(a + b*ArcCosh[c*x])^(n - 1), x] - c^2*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(f^2*(m + 1)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[((f*x)^(m + 2)*(a + b*ArcCosh[c*x])^n)/(Sqrt[1 + c*x]* Sqrt[-1 + c*x]), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSinh[c*x])^n/(f*(m + 1)) - 2*e*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^(p - 1)*(a + b*ArcSinh[c*x])^n, x] - b*c*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(f*(m + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && GtQ[p, 0] && LtQ[m, -1]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n/(f*(m + 1)) - 2*e1*e2*p/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d1 + e1*x)^(p - 1)*(d2 + e2*x)^(p - 1)*(a + b*ArcCosh[c*x])^n, x] - b*c*n*(-d1*d2)^(p - 1/2)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(f*(m + 1)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && GtQ[p, 0] && LtQ[m, -1] && IntegerQ[p - 1/2]
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  (f*x)^(m+1)*(d+e*x^2)^p*(a+b*ArcSinh[c*x])^n/(f*(m+2*p+1)) + 2*d*p/(m+2*p+1)*Int[(f*x)^m*(d+e*x^2)^(p-1)*(a+b*ArcSinh[c*x])^n,x]  - b*c*n*d^p/(f*(m+2*p+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p-1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f,m},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && GtQ[p,0] && Not[LtQ[m,-1]] && (IntegerQ[p] || GtQ[d,0]) &&  (RationalQ[m] || EqQ[n,1]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcCosh[c*x])^n/(f*(m + 2*p + 1)) + 2*d*p/(m + 2*p + 1)* Int[(f*x)^m*(d + e*x^2)^(p - 1)*(a + b*ArcCosh[c*x])^n, x] - b*c*n*(-d)^p/(f*(m + 2*p + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[p, 0] && Not[LtQ[m, -1]] && IntegerQ[p] && (RationalQ[m] || EqQ[n, 1])
Int[(f_.*x_)^m_*Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)* Sqrt[d + e*x^2]*(a + b*ArcSinh[c*x])^n/(f*(m + 2)) - b*c*n*Sqrt[d + e*x^2]/(f*(m + 2)*Sqrt[1 + c^2*x^2])* Int[(f*x)^(m + 1)*(a + b*ArcSinh[c*x])^(n - 1), x] + Sqrt[d + e*x^2]/((m + 2)*Sqrt[1 + c^2*x^2])* Int[(f*x)^m*(a + b*ArcSinh[c*x])^n/Sqrt[1 + c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && Not[LtQ[m, -1]] && (RationalQ[m] || EqQ[n, 1])
Int[(f_.*x_)^m_*Sqrt[d1_ + e1_.*x_]* Sqrt[d2_ + e2_.*x_]*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]*(a + b*ArcCosh[c*x])^n/(f*(m + 2)) - b*c*n*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(f*(m + 2)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^(m + 1)*(a + b*ArcCosh[c*x])^(n - 1), x] - Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/((m + 2)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^m*(a + b*ArcCosh[c*x])^n/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && Not[LtQ[m, -1]] && (RationalQ[m] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^ p*(a + b*ArcSinh[c*x])^n/(f*(m + 2*p + 1)) + 2*d*p/(m + 2*p + 1)* Int[(f*x)^m*(d + e*x^2)^(p - 1)*(a + b*ArcSinh[c*x])^n, x] - b*c*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(f*(m + 2*p + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && GtQ[p, 0] && Not[LtQ[m, -1]] && (RationalQ[m] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n/(f*(m + 2*p + 1)) + 2*d1*d2*p/(m + 2*p + 1)* Int[(f*x)^ m*(d1 + e1*x)^(p - 1)*(d2 + e2*x)^(p - 1)*(a + b*ArcCosh[c*x])^ n, x] - b*c*n*(-d1*d2)^(p - 1/2)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(f*(m + 2*p + 1)*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && GtQ[p, 0] && Not[LtQ[m, -1]] && IntegerQ[p - 1/2] && (RationalQ[m] || EqQ[n, 1])
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  (f*x)^(m+1)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(d*f*(m+1)) - c^2*(m+2*p+3)/(f^2*(m+1))*Int[(f*x)^(m+2)*(d+e*x^2)^p*(a+b*ArcSinh[ c*x])^n,x] - b*c*n*d^p/(f*(m+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p+1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f,p},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && LtQ[m,-1] && IntegerQ[m] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d*f*(m + 1)) + c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^p*(a + b*ArcCosh[c*x])^n, x] + b*c*n*(-d)^p/(f*(m + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[m, -1] && IntegerQ[m] && IntegerQ[p]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n/(d*f*(m + 1)) - c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d + e*x^2)^p*(a + b*ArcSinh[c*x])^n, x] - b*c*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(f*(m + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && LtQ[m, -1] && IntegerQ[m]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d1*d2*f*(m + 1)) + c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n, x] + b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(f*(m + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[m, -1] && IntegerQ[m] && IntegerQ[p + 1/2]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(d1*d2*f*(m + 1)) + c^2*(m + 2*p + 3)/(f^2*(m + 1))* Int[(f*x)^(m + 2)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n, x] + b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(f*(m + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[m, -1] && IntegerQ[m]
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  f*(f*x)^(m-1)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(2*e*(p+1)) - f^2*(m-1)/(2*e*(p+1))*Int[(f*x)^(m-2)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[ c*x])^n,x] - b*f*n*d^p/(2*c*(p+1))*Int[(f*x)^(m-1)*(1+c^2*x^2)^(p+1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && LtQ[p,-1] && GtQ[m,1] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^ n/(2*e*(p + 1)) - f^2*(m - 1)/(2*e*(p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d)^p/(2*c*(p + 1))* Int[(f*x)^(m - 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && GtQ[m, 1] && IntegerQ[p]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^ n/(2*e*(p + 1)) - f^2*(m - 1)/(2*e*(p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n, x] - b*f*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(2*c*(p + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && LtQ[p, -1] && GtQ[m, 1]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*e1*e2*(p + 1)) - f^2*(m - 1)/(2*e1*e2*(p + 1))* Int[(f*x)^(m - 2)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* c*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m - 1)*(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[p, -1] && GtQ[m, 1] && IntegerQ[p + 1/2]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*e1*e2*(p + 1)) - f^2*(m - 1)/(2*e1*e2*(p + 1))* Int[(f*x)^(m - 2)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* c*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[IntegerQ[p]] && GtQ[m, 1]
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  -(f*x)^(m+1)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(2*d*f*(p+1)) + (m+2*p+3)/(2*d*(p+1))*Int[(f*x)^m*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x]) ^n,x] + b*c*n*d^p/(2*f*(p+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p+1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f,m},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && LtQ[p,-1] && Not[GtQ[m,1]] && (IntegerQ[p] || GtQ[d,0]) &&   (IntegerQ[m] || IntegerQ[p] || EqQ[n,1]) *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := -(f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*d*f*(p + 1)) + (m + 2*p + 3)/(2*d*(p + 1))* Int[(f*x)^m*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^n, x] - b*c*n*(-d)^p/(2*f*(p + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && IntegerQ[p]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := -(f*x)^(m + 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n/(2*d*f*(p + 1)) + (m + 2*p + 3)/(2*d*(p + 1))* Int[(f*x)^m*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n, x] + b*c*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(2*f*(p + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && (IntegerQ[m] || IntegerQ[p] || EqQ[n, 1])
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := -(f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*d1*d2*f*(p + 1)) + (m + 2*p + 3)/(2*d1*d2*(p + 1))* Int[(f*x)^ m*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^ n, x] - b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* f*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && (IntegerQ[m] || EqQ[n, 1]) && IntegerQ[p + 1/2]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := -(f*x)^(m + 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(2*d1*d2*f*(p + 1)) + (m + 2*p + 3)/(2*d1*d2*(p + 1))* Int[(f*x)^ m*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^ n, x] - b*c*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(2* f*(p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && LtQ[p, -1] && Not[GtQ[m, 1]] && (IntegerQ[m] || IntegerQ[p] || EqQ[n, 1])
(* Int[(f_.*x_)^m_*(a_.+b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_+e_.*x_^2],x_ Symbol] := f*(f*x)^(m-1)*Sqrt[d+e*x^2]*(a+b*ArcSinh[c*x])^n/(e*m) -   b*f*n*Sqrt[1+c^2*x^2]/(c*m*Sqrt[d+e*x^2])*Int[(f*x)^(m-1)*(a+b* ArcSinh[c*x])^(n-1),x] - f^2*(m-1)/(c^2*m)*Int[((f*x)^(m-2)*(a+b*ArcSinh[c*x])^n)/Sqrt[d+e*x^ 2],x] /; FreeQ[{a,b,c,d,e,f},x] && EqQ[e,c^2*d] && GtQ[n,0] &&  GtQ[m,1] && GtQ[d,0] && IntegerQ[m] *)
(* Int[(f_.*x_)^m_*(a_.+b_.*ArcCosh[c_.*x_])^n_./(Sqrt[d1_+e1_.*x_]* Sqrt[d2_+e2_.*x_]),x_Symbol] :=  f*(f*x)^(m-1)*Sqrt[d1+e1*x]*Sqrt[d2+e2*x]*(a+b*ArcCosh[c*x])^n/(e1*e2* m) + b*f*n*Sqrt[d1+e1*x]*Sqrt[d2+e2*x]/(c*d1*d2*m*Sqrt[1+c*x]*Sqrt[-1+c* x])*Int[(f*x)^(m-1)*(a+b*ArcCosh[c*x])^(n-1),x] + f^2*(m-1)/(c^2*m)*Int[(f*x)^(m-2)*(a+b*ArcCosh[c*x])^n/(Sqrt[d1+e1* x]*Sqrt[d2+e2*x]),x] /; FreeQ[{a,b,c,d1,e1,d2,e2,f},x] &&  EqQ[e1-c*d1,0] && EqQ[e2+c*d2,0] && GtQ[n,0] && GtQ[m,1] &&  IntegerQ[m] *)
Int[(f_.*x_)^m_*(a_. + b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol] := f*(f*x)^(m - 1)*Sqrt[d + e*x^2]*(a + b*ArcSinh[c*x])^n/(e*m) - b*f*n*Sqrt[1 + c^2*x^2]/(c*m*Sqrt[d + e*x^2])* Int[(f*x)^(m - 1)*(a + b*ArcSinh[c*x])^(n - 1), x] - f^2*(m - 1)/(c^2*m)* Int[((f*x)^(m - 2)*(a + b*ArcSinh[c*x])^n)/Sqrt[d + e*x^2], x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && GtQ[m, 1] && IntegerQ[m]
Int[(f_.*x_)^ m_*(a_. + b_.*ArcCosh[c_.*x_])^ n_./(Sqrt[d1_ + e1_.*x_]*Sqrt[d2_ + e2_.*x_]), x_Symbol] := f*(f*x)^(m - 1)*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]*(a + b*ArcCosh[c*x])^n/(e1*e2*m) + b*f*n*Sqrt[d1 + e1*x]* Sqrt[d2 + e2*x]/(c*d1*d2*m*Sqrt[1 + c*x]*Sqrt[-1 + c*x])* Int[(f*x)^(m - 1)*(a + b*ArcCosh[c*x])^(n - 1), x] + f^2*(m - 1)/(c^2*m)* Int[(f*x)^(m - 2)*(a + b*ArcCosh[c*x])^ n/(Sqrt[d1 + e1*x]*Sqrt[d2 + e2*x]), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && GtQ[m, 1] && IntegerQ[m]
Int[x_^m_*(a_. + b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol] := 1/(c^(m + 1)*Sqrt[d])* Subst[Int[(a + b*x)^n*Sinh[x]^m, x], x, ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && GtQ[d, 0] && IGtQ[n, 0] && IntegerQ[m]
Int[x_^m_*(a_. + b_.*ArcCosh[c_.*x_])^ n_./(Sqrt[d1_ + e1_.*x_]*Sqrt[d2_ + e2_.*x_]), x_Symbol] := 1/(c^(m + 1)*Sqrt[-d1*d2])* Subst[Int[(a + b*x)^n*Cosh[x]^m, x], x, ArcCosh[c*x]] /; FreeQ[{a, b, c, d1, e1, d2, e2}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && IGtQ[n, 0] && GtQ[d1, 0] && LtQ[d2, 0] && IntegerQ[m]
Int[(f_.*x_)^m_*(a_. + b_.*ArcSinh[c_.*x_])/Sqrt[d_ + e_.*x_^2], x_Symbol] := (f*x)^(m + 1)*(a + b*ArcSinh[c*x])* Hypergeometric2F1[ 1/2, (1 + m)/2, (3 + m)/2, -c^2*x^2]/(Sqrt[d]*f*(m + 1)) - b*c*(f*x)^(m + 2)* HypergeometricPFQ[{1, 1 + m/2, 1 + m/2}, {3/2 + m/2, 2 + m/2}, -c^2*x^2]/(Sqrt[d]*f^2*(m + 1)*(m + 2)) /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && GtQ[d, 0] && Not[IntegerQ[m]]
Int[(f_.*x_)^ m_*(a_. + b_.*ArcCosh[c_.*x_])/(Sqrt[d1_ + e1_.*x_]* Sqrt[d2_ + e2_.*x_]), x_Symbol] := (f*x)^(m + 1)* Sqrt[1 - c^2*x^2]*(a + b*ArcCosh[c*x])* Hypergeometric2F1[1/2, (1 + m)/2, (3 + m)/2, c^2*x^2]/ (f*(m + 1)*Sqrt[d1 + e1*x]*Sqrt[d2 + e2*x]) + b*c*(f*x)^(m + 2)* HypergeometricPFQ[{1, 1 + m/2, 1 + m/2}, {3/2 + m/2, 2 + m/2}, c^2*x^2]/(Sqrt[-d1*d2]*f^2*(m + 1)*(m + 2)) /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[d1, 0] && LtQ[d2, 0] && Not[IntegerQ[m]]
Int[(f_.*x_)^m_*(a_. + b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol] := Sqrt[1 + c^2*x^2]/Sqrt[d + e*x^2]* Int[(f*x)^m*(a + b*ArcSinh[c*x])^n/Sqrt[1 + c^2*x^2], x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && Not[GtQ[d, 0]] && (IntegerQ[m] || EqQ[n, 1])
Int[(f_.*x_)^ m_*(a_. + b_.*ArcCosh[c_.*x_])^ n_./(Sqrt[d1_ + e1_.*x_]*Sqrt[d2_ + e2_.*x_]), x_Symbol] := Sqrt[1 + c*x]*Sqrt[-1 + c*x]/(Sqrt[d1 + e1*x]*Sqrt[d2 + e2*x])* Int[(f*x)^m*(a + b*ArcCosh[c*x])^n/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && Not[GtQ[d1, 0] && LtQ[d2, 0]] && (IntegerQ[m] || EqQ[n, 1])
(* Int[(f_.*x_)^m_*(d_+e_.*x_^2)^p_*(a_.+b_.*ArcSinh[c_.*x_])^n_.,x_ Symbol] :=  f*(f*x)^(m-1)*(d+e*x^2)^(p+1)*(a+b*ArcSinh[c*x])^n/(e*(m+2*p+1)) - f^2*(m-1)/(c^2*(m+2*p+1))*Int[(f*x)^(m-2)*(d+e*x^2)^p*(a+b*ArcSinh[ c*x])^n,x] - b*f*n*d^p/(c*(m+2*p+1))*Int[(f*x)^(m-1)*(1+c^2*x^2)^(p+1/2)*(a+b* ArcSinh[c*x])^(n-1),x] /; FreeQ[{a,b,c,d,e,f,p},x] && EqQ[e,c^2*d] &&  GtQ[n,0] && GtQ[m,1] && NeQ[m+2*p+1,0] && (IntegerQ[p] || GtQ[d,0]) &&  IntegerQ[m] *)
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])^ n/(e*(m + 2*p + 1)) + f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^p*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d)^p/(c*(m + 2*p + 1))* Int[(f*x)^(m - 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[c^2*d + e, 0] && GtQ[n, 0] && GtQ[m, 1] && NeQ[m + 2*p + 1, 0] && IntegerQ[p] && IntegerQ[m]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^ n/(e*(m + 2*p + 1)) - f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d + e*x^2)^p*(a + b*ArcSinh[c*x])^n, x] - b*f*n* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(c*(m + 2*p + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e, f, p}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && GtQ[m, 1] && NeQ[m + 2*p + 1, 0] && IntegerQ[m]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(e1*e2*(m + 2*p + 1)) + f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(c*(m + 2*p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^ FracPart[p])* Int[(f*x)^(m - 1)*(-1 + c^2*x^2)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && GtQ[m, 1] && NeQ[m + 2*p + 1, 0] && IntegerQ[m] && IntegerQ[p + 1/2]
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := f*(f*x)^(m - 1)*(d1 + e1*x)^(p + 1)*(d2 + e2*x)^(p + 1)*(a + b*ArcCosh[c*x])^n/(e1*e2*(m + 2*p + 1)) + f^2*(m - 1)/(c^2*(m + 2*p + 1))* Int[(f*x)^(m - 2)*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n, x] - b*f*n*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[ p]/(c*(m + 2*p + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^ FracPart[p])* Int[(f*x)^(m - 1)*(1 + c*x)^(p + 1/2)*(-1 + c*x)^(p + 1/2)*(a + b*ArcCosh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[n, 0] && GtQ[m, 1] && NeQ[m + 2*p + 1, 0] && IntegerQ[m]
(* Int[(f_.*x_)^m_.*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_,x_ Symbol] :=  d^p*(f*x)^m*(1+c^2*x^2)^(p+1/2)*(a+b*ArcSinh[c*x])^(n+1)/(b*c*(n+1)) - f*m*d^p/(b*c*(n+1))*Int[(f*x)^(m-1)*(1+c^2*x^2)^(p-1/2)*(a+b* ArcSinh[c*x])^(n+1),x] /; FreeQ[{a,b,c,d,e,f,m,p},x] && EqQ[e,c^2*d] &&  LtQ[n,-1] && EqQ[m+2*p+1,0] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_, x_Symbol] := (f*x)^m*Sqrt[1 + c*x]* Sqrt[-1 + c*x]*(d + e*x^2)^ p*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*(n + 1)) + f*m*(-d)^p/(b*c*(n + 1))* Int[(f*x)^(m - 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0] && IntegerQ[p]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_, x_Symbol] := (f*x)^m* Sqrt[1 + c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcSinh[c*x])^(n + 1)/(b*c*(n + 1)) - f*m*d^ IntPart[p]*(d + e*x^2)^ FracPart[p]/(b*c*(n + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m, p}, x] && EqQ[e, c^2*d] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_, x_Symbol] := (f*x)^m*Sqrt[1 + c*x]* Sqrt[-1 + c*x]*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*(n + 1)) + f*m*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(b* c*(n + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m - 1)*(-1 + c^2*x^2)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0] && IntegerQ[p - 1/2]
Int[(f_.*x_)^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_, x_Symbol] := (f*x)^m*Sqrt[1 + c*x]* Sqrt[-1 + c*x]*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*(n + 1)) + f*m*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(b* c*(n + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, p}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && LtQ[n, -1] && EqQ[m + 2*p + 1, 0]
Int[(f_.*x_)^m_.*(a_. + b_.*ArcSinh[c_.*x_])^n_/Sqrt[d_ + e_.*x_^2], x_Symbol] := (f*x)^ m*(a + b*ArcSinh[c*x])^(n + 1)/(b*c*Sqrt[d]*(n + 1)) - f*m/(b*c*Sqrt[d]*(n + 1))* Int[(f*x)^(m - 1)*(a + b*ArcSinh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && EqQ[e, c^2*d] && LtQ[n, -1] && GtQ[d, 0]
Int[(f_.*x_)^ m_.*(a_. + b_.*ArcCosh[c_.*x_])^ n_/(Sqrt[d1_ + e1_.*x_]*Sqrt[d2_ + e2_.*x_]), x_Symbol] := (f*x)^ m*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*Sqrt[-d1*d2]*(n + 1)) - (f*m)/(b*c*Sqrt[-d1*d2]*(n + 1))* Int[(f*x)^(m - 1)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && LtQ[n, -1] && GtQ[d1, 0] && LtQ[d2, 0]
(* Int[(f_.*x_)^m_.*(a_.+b_.*ArcSinh[c_.*x_])^n_/Sqrt[d_+e_.*x_^2],x_ Symbol] :=  Sqrt[1+c^2*x^2]/Sqrt[d+e*x^2]*Int[(f*x)^m*(a+b*ArcSinh[c*x])^n/Sqrt[1+ c^2*x^2],x] /; FreeQ[{a,b,c,d,e,f,m},x] && EqQ[e,c^2*d] && LtQ[n,-1] &&  Not[GtQ[d,0]] *)
(* Int[(f_.*x_)^m_.*(a_.+b_.*ArcCosh[c_.*x_])^n_/(Sqrt[d1_+e1_.*x_]* Sqrt[d2_+e2_.*x_]),x_Symbol] :=  Sqrt[1+c*x]*Sqrt[-1+c*x]/(Sqrt[d1+e1*x]*Sqrt[d2+e2*x])*Int[(f*x)^m*(a+ b*ArcCosh[c*x])^n/(Sqrt[1+c*x]*Sqrt[-1+c*x]),x] /;  FreeQ[{a,b,c,d1,e1,d2,e2,f,m},x] && EqQ[e1-c*d1,0] && EqQ[e2+c*d2,0] &&  LtQ[n,-1] && Not[GtQ[d1,0] && LtQ[d2,0]] *)
(* Int[(f_.*x_)^m_.*(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_,x_ Symbol] :=  d^p*(f*x)^m*(1+c^2*x^2)^(p+1/2)*(a+b*ArcSinh[c*x])^(n+1)/(b*c*(n+1)) - f*m*d^p/(b*c*(n+1))*Int[(f*x)^(m-1)*(1+c^2*x^2)^(p-1/2)*(a+b* ArcSinh[c*x])^(n+1),x] - c*d^p*(m+2*p+1)/(b*f*(n+1))*Int[(f*x)^(m+1)*(1+c^2*x^2)^(p-1/2)*(a+ b*ArcSinh[c*x])^(n+1),x] /; FreeQ[{a,b,c,d,e,f},x] && EqQ[e,c^2*d] &&  LtQ[n,-1] && IGtQ[m,-3] && IGtQ[2*p,0] && (IntegerQ[p] || GtQ[d,0]) *)
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_, x_Symbol] := (f*x)^m*Sqrt[1 + c*x]* Sqrt[-1 + c*x]*(d + e*x^2)^ p*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*(n + 1)) + f*m*(-d)^p/(b*c*(n + 1))* Int[(f*x)^(m - 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] - c*(-d)^p*(m + 2*p + 1)/(b*f*(n + 1))* Int[(f*x)^(m + 1)*(1 + c*x)^(p - 1/2)*(-1 + c*x)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[c^2*d + e, 0] && LtQ[n, -1] && IGtQ[m, -3] && IGtQ[p, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_, x_Symbol] := (f*x)^m* Sqrt[1 + c^2*x^2]*(d + e*x^2)^ p*(a + b*ArcSinh[c*x])^(n + 1)/(b*c*(n + 1)) - f*m*d^ IntPart[p]*(d + e*x^2)^ FracPart[p]/(b*c*(n + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m - 1)*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n + 1), x] - c*(m + 2*p + 1)* d^IntPart[p]*(d + e*x^2)^ FracPart[p]/(b*f*(n + 1)*(1 + c^2*x^2)^FracPart[p])* Int[(f*x)^(m + 1)*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, f}, x] && EqQ[e, c^2*d] && LtQ[n, -1] && IGtQ[m, -3] && IGtQ[2*p, 0]
Int[(f_.*x_)^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_, x_Symbol] := (f*x)^m*Sqrt[1 + c*x]* Sqrt[-1 + c*x]*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^(n + 1)/(b*c*(n + 1)) + f*m*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(b* c*(n + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m - 1)*(-1 + c^2*x^2)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] - c*(m + 2*p + 1)*(-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/(b* f*(n + 1)*(1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^(m + 1)*(-1 + c^2*x^2)^(p - 1/2)*(a + b*ArcCosh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && LtQ[n, -1] && IGtQ[m, -3] && IGtQ[p + 1/2, 0]
Int[x_^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := d^p/c^(m + 1)* Subst[Int[(a + b*x)^n*Sinh[x]^m*Cosh[x]^(2*p + 1), x], x, ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[e, c^2*d] && IntegerQ[2*p] && GtQ[p, -1] && IGtQ[m, 0] && (IntegerQ[p] || GtQ[d, 0])
Int[x_^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (-d)^p/c^(m + 1)* Subst[Int[(a + b*x)^n*Cosh[x]^m*Sinh[x]^(2*p + 1), x], x, ArcCosh[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[c^2*d + e, 0] && IGtQ[p, 0] && IGtQ[m, 0]
Int[x_^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (-d1*d2)^p/c^(m + 1)* Subst[Int[(a + b*x)^n*Cosh[x]^m*Sinh[x]^(2*p + 1), x], x, ArcCosh[c*x]] /; FreeQ[{a, b, c, d1, e1, d2, e2, n}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && IntegerQ[p + 1/2] && GtQ[p, -1] && IGtQ[m, 0] && (GtQ[d1, 0] && LtQ[d2, 0])
Int[x_^m_.*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_, x_Symbol] := d^IntPart[p]*(d + e*x^2)^FracPart[p]/(1 + c^2*x^2)^FracPart[p]* Int[x^m*(1 + c^2*x^2)^p*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[e, c^2*d] && IntegerQ[2*p] && GtQ[p, -1] && IGtQ[m, 0] && Not[(IntegerQ[p] || GtQ[d, 0])]
Int[x_^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (-d1*d2)^IntPart[p]*(d1 + e1*x)^ FracPart[p]*(d2 + e2*x)^ FracPart[p]/((1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[x^m*(1 + c*x)^p*(-1 + c*x)^p*(a + b*ArcCosh[c*x])^n, x] /; FreeQ[{a, b, c, d1, e1, d2, e2, n}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && IntegerQ[2*p] && GtQ[p, -1] && IGtQ[m, 0] && Not[IntegerQ[p] || GtQ[d1, 0] && LtQ[d2, 0]]
Int[(f_.*x_)^m_*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcSinh[c*x])^n/ Sqrt[d + e*x^2], (f*x)^m*(d + e*x^2)^(p + 1/2), x], x] /; FreeQ[{a, b, c, d, e, f, m, n}, x] && EqQ[e, c^2*d] && GtQ[d, 0] && IGtQ[p + 1/2, 0] && Not[IGtQ[(m + 1)/2, 0]] && (EqQ[m, -1] || EqQ[m, -2])
Int[(f_.*x_)^m_*(d1_ + e1_.*x_)^p_*(d2_ + e2_.*x_)^ p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcCosh[c*x])^ n/(Sqrt[d1 + e1*x]*Sqrt[d2 + e2*x]), (f*x)^ m*(d1 + e1*x)^(p + 1/2)*(d2 + e2*x)^(p + 1/2), x], x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, n}, x] && EqQ[e1 - c*d1, 0] && EqQ[e2 + c*d2, 0] && GtQ[d1, 0] && LtQ[d2, 0] && IGtQ[p + 1/2, 0] && Not[IGtQ[(m + 1)/2, 0]] && (EqQ[m, -1] || EqQ[m, -2])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := d*(f*x)^(m + 1)*(a + b*ArcCosh[c*x])/(f*(m + 1)) + e*(f*x)^(m + 3)*(a + b*ArcCosh[c*x])/(f^3*(m + 3)) - b*c/(f*(m + 1)*(m + 3))* Int[(f*x)^(m + 1)*(d*(m + 3) + e*(m + 1)*x^2)/(Sqrt[1 + c*x]* Sqrt[-1 + c*x]), x] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[c^2*d + e, 0] && NeQ[m, -1] && NeQ[m, -3]
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])/(2* e*(p + 1)) - b*c/(2*e*(p + 1))*Int[(d + e*x^2)^(p + 1)/Sqrt[1 + c^2*x^2], x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[e, c^2*d] && NeQ[p, -1]
Int[x_*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := (d + e*x^2)^(p + 1)*(a + b*ArcCosh[c*x])/(2* e*(p + 1)) - b*c/(2*e*(p + 1))* Int[(d + e*x^2)^(p + 1)/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x] /; FreeQ[{a, b, c, d, e, p}, x] && NeQ[c^2*d + e, 0] && NeQ[p, -1]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcSinh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[e, c^2*d] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[(m - 1)/2, 0] && LeQ[m + p, 0])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_]), x_Symbol] := With[{u = IntHide[(f*x)^m*(d + e*x^2)^p, x]}, Dist[a + b*ArcCosh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/(Sqrt[1 + c*x]*Sqrt[-1 + c*x]), x], x]] /; FreeQ[{a, b, c, d, e, f, m}, x] && NeQ[c^2*d + e, 0] && IntegerQ[p] && (GtQ[p, 0] || IGtQ[(m - 1)/2, 0] && LeQ[m + p, 0])
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcSinh[c*x])^n, (f*x)^m*(d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[e, c^2*d] && IGtQ[n, 0] && IntegerQ[p] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := Int[ExpandIntegrand[(a + b*ArcCosh[c*x])^n, (f*x)^m*(d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, f}, x] && NeQ[c^2*d + e, 0] && IGtQ[n, 0] && IntegerQ[p] && IntegerQ[m]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := Unintegrable[(f*x)^m*(d + e*x^2)^p*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := Unintegrable[(f*x)^m*(d + e*x^2)^p*(a + b*ArcCosh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && IntegerQ[p]
Int[(f_.*x_)^m_.*(d1_ + e1_.*x_)^p_.*(d2_ + e2_.*x_)^ p_.*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := Unintegrable[(f*x)^m*(d1 + e1*x)^p*(d2 + e2*x)^ p*(a + b*ArcCosh[c*x])^n, x] /; FreeQ[{a, b, c, d1, e1, d2, e2, f, m, n, p}, x]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (-d^2*g/e)^q* Int[(h*x)^m*(d + e*x)^(p - q)*(1 + c^2*x^2)^q*(a + b*ArcSinh[c*x])^ n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 + e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(h_.*x_)^m_.*(d_ + e_.*x_)^p_*(f_ + g_.*x_)^ q_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol] := (-d^2*g/e)^IntPart[q]*(d + e*x)^ FracPart[q]*(f + g*x)^FracPart[q]/(1 + c^2*x^2)^FracPart[q]* Int[(h*x)^m*(d + e*x)^(p - q)*(1 + c^2*x^2)^ q*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, h, m, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 + e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
Int[(f_.*x_)^m_.*(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcCosh[c_.*x_])^n_., x_Symbol] := (-d)^ IntPart[p]*(d + e*x^2)^ FracPart[p]/((1 + c*x)^FracPart[p]*(-1 + c*x)^FracPart[p])* Int[(f*x)^m*(1 + c*x)^p*(-1 + c*x)^p*(a + b*ArcCosh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, m, n, p}, x] && EqQ[c^2*d + e, 0] && Not[IntegerQ[p]]
