
(* ::Subsection::Closed:: *)
(* 7.1.3 (d+e x^2)^p (a+b arcsinh(c x))^n *)
(* Int[(a_.+b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_+e_.*x_^2],x_Symbol] :=  1/c*Simp[Sqrt[1+c^2*x^2]/Sqrt[d+e*x^2]]*Subst[Int[(a+b*x)^n,x],x, ArcSinh[c*x]] /; FreeQ[{a,b,c,d,e,n},x] && EqQ[e,c^2*d] *)
Int[1/(Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSinh[c_.*x_])), x_Symbol, _:RubiNotebookReference["adbd9972"]] := 1/(b*c)*Simp[Sqrt[1 + c^2*x^2]/Sqrt[d + e*x^2]]* Log[a + b*ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d]
Int[(a_. + b_.*ArcSinh[c_.*x_])^n_./Sqrt[d_ + e_.*x_^2], x_Symbol, _:RubiNotebookReference["ac7ff345"]] := 1/(b*c*(n + 1))* Simp[Sqrt[1 + c^2*x^2]/ Sqrt[d + e*x^2]]*(a + b*ArcSinh[c*x])^(n + 1) /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[e, c^2*d] && NeQ[n, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol, _:RubiNotebookReference["a930e5c0"]] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcSinh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[p, 0]
Int[Sqrt[d_ + e_.*x_^2]*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["a8f28ff7"]] := x*Sqrt[d + e*x^2]*(a + b*ArcSinh[c*x])^n/2 - b*c*n/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 + c^2*x^2]]* Int[x*(a + b*ArcSinh[c*x])^(n - 1), x] + 1/2*Simp[Sqrt[d + e*x^2]/Sqrt[1 + c^2*x^2]]* Int[(a + b*ArcSinh[c*x])^n/Sqrt[1 + c^2*x^2], x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && GtQ[n, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["aab431ae"]] := x*(d + e*x^2)^p*(a + b*ArcSinh[c*x])^n/(2*p + 1) + 2*d*p/(2*p + 1)* Int[(d + e*x^2)^(p - 1)*(a + b*ArcSinh[c*x])^n, x] - b*c*n/(2*p + 1)*Simp[(d + e*x^2)^p/(1 + c^2*x^2)^p]* Int[x*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && GtQ[p, 0]
Int[(a_. + b_.*ArcSinh[c_.*x_])^n_./(d_ + e_.*x_^2)^(3/2), x_Symbol, _:RubiNotebookReference["ab765b99"]] := x*(a + b*ArcSinh[c*x])^n/(d*Sqrt[d + e*x^2]) - b*c*n/d*Simp[Sqrt[1 + c^2*x^2]/Sqrt[d + e*x^2]]* Int[x*(a + b*ArcSinh[c*x])^(n - 1)/(1 + c^2*x^2), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && GtQ[n, 0]
Int[(d_ + e_.*x_^2)^p_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["a02a1ca4"]] := -x*(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^ n/(2*d*(p + 1)) + (2*p + 3)/(2*d*(p + 1))* Int[(d + e*x^2)^(p + 1)*(a + b*ArcSinh[c*x])^n, x] + b*c*n/(2*(p + 1))*Simp[(d + e*x^2)^p/(1 + c^2*x^2)^p]* Int[x*(1 + c^2*x^2)^(p + 1/2)*(a + b*ArcSinh[c*x])^(n - 1), x] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && GtQ[n, 0] && LtQ[p, -1] && NeQ[p, -3/2]
Int[(a_. + b_.*ArcSinh[c_.*x_])^n_./(d_ + e_.*x_^2), x_Symbol, _:RubiNotebookReference["a1e87693"]] := 1/(c*d)*Subst[Int[(a + b*x)^n*Sech[x], x], x, ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e}, x] && EqQ[e, c^2*d] && IGtQ[n, 0]
(* Int[(d_+e_.*x_^2)^p_.*(a_.+b_.*ArcSinh[c_.*x_])^n_,x_Symbol] :=  d^p*(1+c^2*x^2)^(p+1/2)*(a+b*ArcSinh[c*x])^(n+1)/(b*c*(n+1)) - c*d^p*(2*p+1)/(b*(n+1))*Int[x*(1+c^2*x^2)^(p-1/2)*(a+b*ArcSinh[c*x]) ^(n+1),x] /; FreeQ[{a,b,c,d,e,p},x] && EqQ[e,c^2*d] && LtQ[n,-1] &&  (IntegerQ[p] || GtQ[d,0]) *)
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_, x_Symbol, _:RubiNotebookReference["2a06f2e7"]] := Simp[Sqrt[1 + c^2*x^2]*(d + e*x^2)^ p]*(a + b*ArcSinh[c*x])^(n + 1)/(b*c*(n + 1)) - c*(2*p + 1)/(b*(n + 1))*Simp[(d + e*x^2)^p/(1 + c^2*x^2)^p]* Int[x*(1 + c^2*x^2)^(p - 1/2)*(a + b*ArcSinh[c*x])^(n + 1), x] /; FreeQ[{a, b, c, d, e, p}, x] && EqQ[e, c^2*d] && LtQ[n, -1]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["28404cbe"]] := 1/(b*c)*Simp[(d + e*x^2)^p/(1 + c^2*x^2)^p]* Subst[Int[x^n*Cosh[-a/b + x/b]^(2*p + 1), x], x, a + b*ArcSinh[c*x]] /; FreeQ[{a, b, c, d, e, n}, x] && EqQ[e, c^2*d] && IGtQ[2*p, 0]
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_]), x_Symbol, _:RubiNotebookReference["29822689"]] := With[{u = IntHide[(d + e*x^2)^p, x]}, Dist[a + b*ArcSinh[c*x], u, x] - b*c*Int[SimplifyIntegrand[u/Sqrt[1 + c^2*x^2], x], x]] /; FreeQ[{a, b, c, d, e}, x] && NeQ[e, c^2*d] && (IGtQ[p, 0] || ILtQ[p + 1/2, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["2ccd300c"]] := Int[ExpandIntegrand[(a + b*ArcSinh[c*x])^n, (d + e*x^2)^p, x], x] /; FreeQ[{a, b, c, d, e, n}, x] && NeQ[e, c^2*d] && IntegerQ[p] && (p > 0 || IGtQ[n, 0])
Int[(d_ + e_.*x_^2)^p_.*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["2d0f5a3b"]] := Unintegrable[(d + e*x^2)^p*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, n, p}, x]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["2f49e462"]] := (-d^2*g/e)^q* Int[(d + e*x)^(p - q)*(1 + c^2*x^2)^q*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 + e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0] && GtQ[d, 0] && LtQ[g/e, 0]
Int[(d_ + e_.*x_)^p_*(f_ + g_.*x_)^q_*(a_. + b_.*ArcSinh[c_.*x_])^n_., x_Symbol, _:RubiNotebookReference["2e8b8e55"]] := (d + e*x)^q*(f + g*x)^q/(1 + c^2*x^2)^q* Int[(d + e*x)^(p - q)*(1 + c^2*x^2)^q*(a + b*ArcSinh[c*x])^n, x] /; FreeQ[{a, b, c, d, e, f, g, n}, x] && EqQ[e*f + d*g, 0] && EqQ[c^2*d^2 + e^2, 0] && HalfIntegerQ[p, q] && GeQ[p - q, 0]
