
(* ::Subsection::Closed:: *)
(* 4.1.8 trig^m (a+b cos^p+c sin^q)^n *)
Int[sin[d_. + e_.*x_]^ m_*(a_ + b_.*cos[d_. + e_.*x_]^p_ + c_.*sin[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Cot[d + e*x], x]}, -f/e* Subst[Int[ ExpandToSum[ c + b*(1 + f^2*x^2)^(q/2 - p/2) + a*(1 + f^2*x^2)^(q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*q/2 + 1), x], x, Cot[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && GtQ[p, 0] && LeQ[p, q]
Int[cos[d_. + e_.*x_]^ m_*(a_ + b_.*sin[d_. + e_.*x_]^p_ + c_.*cos[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Tan[d + e*x], x]}, f/e*Subst[ Int[ExpandToSum[ c + b*(1 + f^2*x^2)^(q/2 - p/2) + a*(1 + f^2*x^2)^(q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*q/2 + 1), x], x, Tan[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && GtQ[p, 0] && LeQ[p, q]
Int[sin[d_. + e_.*x_]^ m_*(a_ + b_.*cos[d_. + e_.*x_]^p_ + c_.*sin[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Cot[d + e*x], x]}, -f/e* Subst[Int[ ExpandToSum[ a*(1 + f^2*x^2)^(p/2) + b*f^p*x^p + c*(1 + f^2*x^2)^(p/2 - q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*p/2 + 1), x], x, Cot[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && LtQ[0, q, p]
Int[cos[d_. + e_.*x_]^ m_*(a_ + b_.*sin[d_. + e_.*x_]^p_ + c_.*cos[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Tan[d + e*x], x]}, f/e*Subst[ Int[ExpandToSum[ a*(1 + f^2*x^2)^(p/2) + b*f^p*x^p + c*(1 + f^2*x^2)^(p/2 - q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*p/2 + 1), x], x, Tan[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && LtQ[0, q, p]
Int[sin[d_. + e_.*x_]^ m_*(a_ + b_.*cos[d_. + e_.*x_]^p_ + c_.*sin[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Cot[d + e*x], x]}, -f/e* Subst[Int[ ExpandToSum[ c + b*(1 + f^2*x^2)^(q/2 - p/2) + a*(1 + f^2*x^2)^(q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*q/2 + 1), x], x, Cot[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && GtQ[p, 0] && LeQ[p, q]
Int[cos[d_. + e_.*x_]^ m_*(a_ + b_.*sin[d_. + e_.*x_]^p_ + c_.*cos[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Tan[d + e*x], x]}, f/e*Subst[ Int[ExpandToSum[ c + b*(1 + f^2*x^2)^(q/2 - p/2) + a*(1 + f^2*x^2)^(q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*q/2 + 1), x], x, Tan[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && GtQ[p, 0] && LeQ[p, q]
Int[sin[d_. + e_.*x_]^ m_*(a_ + b_.*cos[d_. + e_.*x_]^p_ + c_.*sin[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Cot[d + e*x], x]}, -f/e* Subst[Int[ ExpandToSum[ a*(1 + f^2*x^2)^(p/2) + b*f^p*x^p + c*(1 + f^2*x^2)^(p/2 - q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*p/2 + 1), x], x, Cot[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && LtQ[0, q, p]
Int[cos[d_. + e_.*x_]^ m_*(a_ + b_.*sin[d_. + e_.*x_]^p_ + c_.*cos[d_. + e_.*x_]^q_)^n_, x_Symbol] := Module[{f = FreeFactors[Tan[d + e*x], x]}, f/e*Subst[ Int[ExpandToSum[ a*(1 + f^2*x^2)^(p/2) + b*f^p*x^p + c*(1 + f^2*x^2)^(p/2 - q/2), x]^ n/(1 + f^2*x^2)^(m/2 + n*p/2 + 1), x], x, Tan[d + e*x]/f]] /; FreeQ[{a, b, c, d, e}, x] && IntegerQ[m/2] && IntegerQ[p/2] && IntegerQ[q/2] && IntegerQ[n] && LtQ[0, q, p]
