
(* ::Subsection::Closed:: *)
(* 4.1.11 (e x)^m (a+b x^n)^p sin *)
Int[(a_ + b_.*x_^n_)^p_.*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["58fa7ab6"]] := Int[ExpandIntegrand[Sin[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, n}, x] && IGtQ[p, 0]
Int[(a_ + b_.*x_^n_)^p_.*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5abcc4ef"]] := Int[ExpandIntegrand[Cos[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, n}, x] && IGtQ[p, 0]
Int[(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5b7eaed8"]] := x^(-n + 1)*(a + b*x^n)^(p + 1)*Sin[c + d*x]/(b*n*(p + 1)) - (-n + 1)/(b*n*(p + 1))* Int[x^(-n)*(a + b*x^n)^(p + 1)*Sin[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(-n + 1)*(a + b*x^n)^(p + 1)*Cos[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, -1] && IGtQ[n, 2]
Int[(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5e31b85d"]] := x^(-n + 1)*(a + b*x^n)^(p + 1)*Cos[c + d*x]/(b*n*(p + 1)) - (-n + 1)/(b*n*(p + 1))* Int[x^(-n)*(a + b*x^n)^(p + 1)*Cos[c + d*x], x] + d/(b*n*(p + 1))* Int[x^(-n + 1)*(a + b*x^n)^(p + 1)*Sin[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, -1] && IGtQ[n, 2]
Int[(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5ff3d26a"]] := Int[ExpandIntegrand[Sin[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5db56c33"]] := Int[ExpandIntegrand[Cos[c + d*x], (a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1])
Int[(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["5c770604"]] := Int[x^(n*p)*(b + a*x^(-n))^p*Sin[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["572b4139"]] := Int[x^(n*p)*(b + a*x^(-n))^p*Cos[c + d*x], x] /; FreeQ[{a, b, c, d}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["56e92b0e"]] := Unintegrable[(a + b*x^n)^p*Sin[c + d*x], x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a58d7674"]] := Unintegrable[(a + b*x^n)^p*Cos[c + d*x], x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a44f1c43"]] := Int[ExpandIntegrand[Sin[c + d*x], (e*x)^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IGtQ[p, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a609a21a"]] := Int[ExpandIntegrand[Cos[c + d*x], (e*x)^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && IGtQ[p, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a7cbc82d"]] := e^m*(a + b*x^n)^(p + 1)*Sin[c + d*x]/(b*n*(p + 1)) - d*e^m/(b*n*(p + 1))*Int[(a + b*x^n)^(p + 1)*Cos[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && ILtQ[p, -1] && EqQ[m, n - 1] && (IntegerQ[n] || GtQ[e, 0])
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a284dea8"]] := e^m*(a + b*x^n)^(p + 1)*Cos[c + d*x]/(b*n*(p + 1)) + d*e^m/(b*n*(p + 1))*Int[(a + b*x^n)^(p + 1)*Sin[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n}, x] && ILtQ[p, -1] && EqQ[m, n - 1] && (IntegerQ[n] || GtQ[e, 0])
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a346b49f"]] := x^(m - n + 1)*(a + b*x^n)^(p + 1)*Sin[c + d*x]/(b*n*(p + 1)) - (m - n + 1)/(b*n*(p + 1))* Int[x^(m - n)*(a + b*x^n)^(p + 1)*Sin[c + d*x], x] - d/(b*n*(p + 1))* Int[x^(m - n + 1)*(a + b*x^n)^(p + 1)*Cos[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, -1] && IGtQ[n, 0] && (GtQ[m - n + 1, 0] || GtQ[n, 2]) && RationalQ[m]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a1000ac6"]] := x^(m - n + 1)*(a + b*x^n)^(p + 1)*Cos[c + d*x]/(b*n*(p + 1)) - (m - n + 1)/(b*n*(p + 1))* Int[x^(m - n)*(a + b*x^n)^(p + 1)*Cos[c + d*x], x] + d/(b*n*(p + 1))* Int[x^(m - n + 1)*(a + b*x^n)^(p + 1)*Sin[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, -1] && IGtQ[n, 0] && (GtQ[m - n + 1, 0] || GtQ[n, 2]) && RationalQ[m]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["a0c260f1"]] := Int[ExpandIntegrand[Sin[c + d*x], x^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1]) && IntegerQ[m]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["ab9e27cc"]] := Int[ExpandIntegrand[Cos[c + d*x], x^m*(a + b*x^n)^p, x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && IGtQ[n, 0] && (EqQ[n, 2] || EqQ[p, -1]) && IntegerQ[m]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["aa5c4dfb"]] := Int[x^(m + n*p)*(b + a*x^(-n))^p*Sin[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[x_^m_.*(a_ + b_.*x_^n_)^p_*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["b738d99a"]] := Int[x^(m + n*p)*(b + a*x^(-n))^p*Cos[c + d*x], x] /; FreeQ[{a, b, c, d, m}, x] && ILtQ[p, 0] && ILtQ[n, 0]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Sin[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["b6fab3ad"]] := Unintegrable[(e*x)^m*(a + b*x^n)^p*Sin[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_.*x_)^m_.*(a_ + b_.*x_^n_)^p_.*Cos[c_. + d_.*x_], x_Symbol, _:RubiNotebookReference["b4bc0df4"]] := Unintegrable[(e*x)^m*(a + b*x^n)^p*Cos[c + d*x], x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
