
(* ::Subsection::Closed:: *)
(* 6.3.11 (e x)^m (a+b tanh(c+d x^n))^p *)
Int[(a_. + b_.*Tanh[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6ed76124"]] := 1/n*Subst[Int[x^(1/n - 1)*(a + b*Tanh[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, p}, x] && IGtQ[1/n, 0] && IntegerQ[p]
Int[(a_. + b_.*Coth[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6c91df7d"]] := 1/n*Subst[Int[x^(1/n - 1)*(a + b*Coth[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, p}, x] && IGtQ[1/n, 0] && IntegerQ[p]
Int[(a_. + b_.*Tanh[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["6d53b54a"]] := Integral[(a + b*Tanh[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_. + b_.*Coth[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["681ca3cf"]] := Integral[(a + b*Coth[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, n, p}, x]
Int[(a_. + b_.*Tanh[c_. + d_.*u_^n_])^p_., x_Symbol, _:RubiNotebookReference["69dec9f8"]] := 1/Coefficient[u, x, 1]* Subst[Int[(a + b*Tanh[c + d*x^n])^p, x], x, u] /; FreeQ[{a, b, c, d, n, p}, x] && LinearQ[u, x] && NeQ[u, x]
Int[(a_. + b_.*Coth[c_. + d_.*u_^n_])^p_., x_Symbol, _:RubiNotebookReference["6b9877a1"]] := 1/Coefficient[u, x, 1]* Subst[Int[(a + b*Coth[c + d*x^n])^p, x], x, u] /; FreeQ[{a, b, c, d, n, p}, x] && LinearQ[u, x] && NeQ[u, x]
Int[(a_. + b_.*Tanh[u_])^p_., x_Symbol, _:RubiNotebookReference["6a5a1d96"]] := Int[(a + b*Tanh[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[(a_. + b_.*Coth[u_])^p_., x_Symbol, _:RubiNotebookReference["61065aab"]] := Int[(a + b*Coth[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[x_^m_.*(a_. + b_.*Tanh[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["60c4309c"]] := 1/n*Subst[ Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*Tanh[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, m, n, p}, x] && IGtQ[Simplify[(m + 1)/n], 0] && IntegerQ[p]
Int[x_^m_.*(a_. + b_.*Coth[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["bbbaa907"]] := 1/n*Subst[ Int[x^(Simplify[(m + 1)/n] - 1)*(a + b*Coth[c + d*x])^p, x], x, x^n] /; FreeQ[{a, b, c, d, m, n, p}, x] && IGtQ[Simplify[(m + 1)/n], 0] && IntegerQ[p]
Int[x_^m_.*Tanh[c_. + d_.*x_^n_]^2, x_Symbol, _:RubiNotebookReference["ba78c330"]] := -x^(m - n + 1)*Tanh[c + d*x^n]/(d*n) + Int[x^m, x] + (m - n + 1)/(d*n)*Int[x^(m - n)*Tanh[c + d*x^n], x] /; FreeQ[{c, d, m, n}, x]
Int[x_^m_.*Coth[c_. + d_.*x_^n_]^2, x_Symbol, _:RubiNotebookReference["b83e7d69"]] := -x^(m - n + 1)*Coth[c + d*x^n]/(d*n) + Int[x^m, x] + (m - n + 1)/(d*n)*Int[x^(m - n)*Coth[c + d*x^n], x] /; FreeQ[{c, d, m, n}, x]
Int[x_^m_.*(a_. + b_.*Tanh[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["b9fc175e"]] := Integral[x^m*(a + b*Tanh[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
Int[x_^m_.*(a_. + b_.*Coth[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["bcb301db"]] := Integral[x^m*(a + b*Coth[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Tanh[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["bd716bec"]] := e^IntPart[m]*(e*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*Tanh[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Coth[c_. + d_.*x_^n_])^p_., x_Symbol, _:RubiNotebookReference["bf37d5b5"]] := e^IntPart[m]*(e*x)^FracPart[m]/x^FracPart[m]* Int[x^m*(a + b*Coth[c + d*x^n])^p, x] /; FreeQ[{a, b, c, d, e, m, n, p}, x]
Int[(e_*x_)^m_.*(a_. + b_.*Tanh[u_])^p_., x_Symbol, _:RubiNotebookReference["bef5bf82"]] := Int[(e*x)^m*(a + b*Tanh[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, e, m, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[(e_*x_)^m_.*(a_. + b_.*Coth[u_])^p_., x_Symbol, _:RubiNotebookReference["b5a9f8bf"]] := Int[(e*x)^m*(a + b*Coth[ExpandToSum[u, x]])^p, x] /; FreeQ[{a, b, e, m, p}, x] && BinomialQ[u, x] && Not[BinomialMatchQ[u, x]]
Int[x_^m_.*Sech[a_. + b_.*x_^n_.]^p_.*Tanh[a_. + b_.*x_^n_.]^q_., x_Symbol, _:RubiNotebookReference["b46b9288"]] := -x^(m - n + 1)*Sech[a + b*x^n]^p/(b*n*p) + (m - n + 1)/(b*n*p)*Int[x^(m - n)*Sech[a + b*x^n]^p, x] /; FreeQ[{a, b, p}, x] && RationalQ[m] && IntegerQ[n] && GeQ[m - n, 0] && EqQ[q, 1]
Int[x_^m_.*Csch[a_. + b_.*x_^n_.]^p_.*Coth[a_. + b_.*x_^n_.]^q_., x_Symbol, _:RubiNotebookReference["a90f06e9"]] := -x^(m - n + 1)*Csch[a + b*x^n]^p/(b*n*p) + (m - n + 1)/(b*n*p)*Int[x^(m - n)*Csch[a + b*x^n]^p, x] /; FreeQ[{a, b, p}, x] && RationalQ[m] && IntegerQ[n] && GeQ[m - n, 0] && EqQ[q, 1]
